### PR TITLE
Publicar lição "De HTML para Lista de Palavras (parte 2)"

### PR DESCRIPTION
**Pull request by DanielAlvesLABDH**
Publicar lição "De HTML para Lista de Palavras (parte 2)"

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
- [x] Add the appropriate "Label"
- [ ] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by DanielAlvesLABDH** [comment]
O erro gerado no PR deve-se ao facto da parte 1 desta lição ainda não estar publicada

**Comment by anisa-hawes** [comment]
> O erro gerado no PR deve-se ao facto da parte 1 desta lição ainda não estar publicada

Yes, you are right! This build will fail until part 1 is published, because the links to it do not yet exist.

**Comment by anisa-hawes** [comment]
Hello @ericbrasiln!

I hope you're well?

Because these lessons link to one another, we need to publish them one at a time as Daniel notes above. Until part 1 is published, our build checking system finds links in part 2 that do not exist yet! 

I can re-base the branches as we go along 🙂

**Comment by ericbrasiln** [comment]
Ok, @anisa-hawes I'll review the first lesson today.

**Review by ericbrasiln — COMMENTED** [review]
Tudo certo com a lição!
Aprovado.

**Review by ericbrasiln — APPROVED** [review]
Agora sim marquei aprovado. 😄

**Comment by DanielAlvesLABDH** [comment]
😃🥳🥳

**Pull request merged**
