### PR TITLE
Upload bulletin banner

### LINKED ISSUE #3092: Upload Bulletin banner to /images/blog
I am uploading an `.svg` and a `.png` version of the new Bulletin banner to the [blog](https://github.com/programminghistorian/jekyll/tree/gh-pages/images/blog) image directory.

### PR DESCRIPTION
**Pull request by charlottejmc**
I have uploaded two versions of the bulletin banner, one in `.svg` and the other in `.png` format.

Closes #3092 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Add the appropriate "Label"
- [x] If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above
- [x] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Assistant @anisa-hawes 
- [x] Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines), then assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR.

### CODE REVIEW

**Comment by charlottejmc** [comment]
Hello @jenniferisasi, @DanielAlvesLABDH and @marie-flesch,

Anisa and I have been working on consolidating a quarterly newsletter with updates  on our project milestones, new lessons, and recent research, to post on our blog and circulate via our social media channels.

We brainstormed a couple names for this newsletter and came up with `Bulletin`, which we would translate as:
- `Boletín` in Spanish
- `Boletim` in Portuguese
- `Bulletin` in French

You can see from the files I have uploaded how this name integrates into the proposed Bulletin banner.

I wonder whether you could give us some feedback on how well that name works in your language? In English, it conveys the sense of "a short official statement or broadcast summary of news", or "a regular newsletter or report issued by an organisation" (from Google).

Thank you very much :sparkles:

(I've just noticed a small issue with the Pt logo, but I'm working to fix that ASAP.) **FIXED**

**Comment by jenniferisasi** [comment]
Happy to read that we are going to have "newsletters" again :) The word "boletín" for Spanish is good, and we have used it before (ie [Segundo boletín informativo del 2020](http://programminghistorian.org/posts/boletin-informativo-junio20))

**Comment by DanielAlvesLABDH** [comment]
Hi @charlottejmc, for me Boletim is fine, but I would like to know the opinion of my colleagues from Brazil. @programminghistorian/portuguese-team o que vos parece? Boletim no Brasil é usado neste sentido?

**Comment by josircg** [comment]
> Hi @charlottejmc, for me Boletim is fine, but I would like to know the opinion of my colleagues from Brazil. @programminghistorian/portuguese-team o que vos parece? Boletim no Brasil é usado neste sentido?

Faz sentido sim Daniel. Boletim é um bom nome.

**Review by anisa-hawes — APPROVED** [review]
Super! Many thanks to all!

We are looking forward to sharing the newsletter with you ☺️

**Pull request merged**
