### PR TITLE
Update editorial workflow

### PR DESCRIPTION
**Pull request by drjwbaker**
Implement suggested changes at https://github.com/programminghistorian/jekyll/issues/1318

PR opened to make to easier to see proposed changes in context.

### CODE REVIEW

**Comment by acrymble** [comment]
@drjwbaker can you fix the travis warnings so we can see the preview link?

**Comment by drjwbaker** [comment]
Done.

**Comment by drjwbaker** [comment]
This PR needs @programminghistorian/french-team & @programminghistorian/spanish-team to approve changes to editor and reviewer guidelines. Is anyone able to pick it up?

**Comment by arojascastro** [comment]
I would review the changes, but I cannot review so many pages... it is impossible to know what is good and what is bad... I need context and maybe to take a day off... (joking)

**Review by arojascastro — APPROVED** [review]
I think it is ok from the Spanish side... i think there are some translation missing from the french side, but I cannot be 100% sure... 

Edit: there are some pages that were edited in English but arent updated in Spanish or French because they werent translated. so it should be ok. 

i think we should have splitted this pull request into different requests... but i guess there is a hidden reason for not doing so. thank you anyway for working a lot.

**Pull request merged**
