### PR TITLE
Display ORCiD

### LINKED ISSUE #1208: ORCID for contributors
Branching this off from #1205

### PR DESCRIPTION
**Pull request by mdlincoln**
This will display ORCiD links for any contributors cross the site if they have an `orcid` id entered in `ph_authors.yml`. This will display for not only authors, but also for editors, reviewers, translators etc. if they have a name match in `ph_authors.yml`. This also displays on the author bios at the bottom of lessons and blog posts, and displays on the editorial team page.

I've updated the english editor guidelines to encourage adding an orcid ID to new author bios if the author has provided one.

- [x] @programminghistorian/spanish-team needs a translation
- [x] @programminghistorian/french-team needs a translation

I will also email the listserv requesting editorial team members to add their orcid IDs to `ph_authors.yml` if they would like to.

Closes #1208

### CODE REVIEW

**Comment by spapastamkou** [comment]
In case a translator or a reviewer has an orcid id but is not in `ph_authors.yml` , should we ask for them to communicate the id anyway?

**Comment by acrymble** [comment]
@spapastamkou if an author isn't listed in the authors file when you are publishing a lesson, then they are added at that time. We do not keep details on reviewers' personal information apart from their name. So I don't think we will be able to add their ORCIDs.

**Comment by mdlincoln** [comment]
You can add them in `ph_authors.yml` if you want to display their ID. You won't need to add a bio since we don't display translator or reviewer bios yet, but it won't break the system if you add their ORCIDs.

**Comment by spapastamkou** [comment]
ok, thank you very much, this helps for the lessons I am currently editing.

**Comment by mdlincoln** [comment]
@spapastamkou thank you for making the change to the FR editor guidelines. Can you please click the "Add your review" button on this PR and approve it just so that we know the FR part is done?

**Comment by arojascastro** [comment]
Done for the Spanish guidelines as well.

**Comment by mdlincoln** [comment]
Thank you @arojascastro !

**Review by spapastamkou — APPROVED** [review]

**Pull request merged**
