### PR TITLE
translate snippet and fix equipo text 

### PR DESCRIPTION
**Pull request by arojascastro**
sorry for creating a new branch for this... may you approve this please?

### CODE REVIEW

**Comment by mdlincoln** [comment]
It's ok! Once a PR is merged, we have to create a new branch anyway - and this time, it looks like it's just the changes we need. Thanks :)

**Review by mdlincoln — APPROVED** [review]

**Comment by arojascastro** [comment]
Yes, but I should use an already existing branch, right? like *translation-es* rather than creating new branches every time I make a change, right?

**Comment by mdlincoln** [comment]
If changed English text is part of a PR (like #612) then you should add the commits to the branch of that PR. You can see the name of a PR's branch right underneath its header. The PR #612 is on the `archiving-policy` branch:

screen shot 2018-01-29 at 8 46 24 am

If you are changing text that is already in `gh-pages`, then you need to create a new branch. There is no special `translation-es` branch that we keep updating, though.

**Comment by arojascastro** [comment]
Ok, yes, the problem is that I am using SourceTree and sometimes I am not in the *right* branch, and I committ changes from the wrong branch... 

I have a *translation-es* branch... but maybe I should not?

captura de pantalla 2018-01-29 a las 17 52 39

**Comment by mdlincoln** [comment]
Branches are temporary things - so we create new ones for changes that need to go together. The archiving policy changes should all be on the same branch for testing and review - but once they're merged, then we can delete that branch. The only branch that is really permanent is `gh-pages` which is the published version of the site.

**Pull request merged**
