### PR TITLE
Httr tutorial

### PR DESCRIPTION
**Pull request by petercarrjones**
Added a tutorial on using an API in R. Specifically, the DPLA API. It might not make sense in the absence of a basic R tutorial right now, but hopefully still useful to some.

### CODE REVIEW

**Comment by wcaleb** [comment]
Thanks! This looks great, but will need to go through the review process all our submissions undergo. Would you be interested in doing the "basic R tutorial" you describe? Or perhaps something @lmullen has done could be adapted for Programming Historian for this purpose?

**Comment by petercarrjones** [comment]
I'm sure @lmullen has a good idea on a basic R tutorial. I'm happy to help with it.

**Comment by wcaleb** [comment]
Perhaps we could just include a link to Lincoln's [Digital History 
Methods in R](http://lincolnmullen.com/projects/dh-r/) at the beginning 
of your lesson?

**Comment by petercarrjones** [comment]
That makes a lot of sense. I'm also happy for any other changes that occur through the editing process.

**Comment by lmullen** [comment]
@petercarrjones @wcaleb You all are of course welcome to point to the DH in R work in progress. The basics of R chapter isn't written yet, and probably won't be for a while. There are dozens of introductions to R, but none of them very compelling. You could do worse than the one on CRAN: Torfs and Brauer, [A Very Short Introduction to R](http://cran.r-project.org/doc/contrib/Torfs+Brauer-Short-R-Intro.pdf).

**Comment by wcaleb** [comment]
This has been added to the [Lesson Pipeline](https://github.com/programminghistorian/jekyll/wiki/Lesson-Pipeline) wiki.

**Comment by ianmilligan1** [comment]
@petercarrjones I've merged this commit to begin the review process. Peter, I've made a few tiny edits - which you can see in [this commit](https://github.com/programminghistorian/jekyll/commit/b8b12e2a60fb96eaca32576ba113173a3e53a928). Feel free to revert/comment on them.

I think the only thing that I might suggest adding before sending out for review is a brief conclusion: any next steps? Any further readings? Anything that you think they should explore? This might help wrap it up. Let me know and I will contact reviewers and open up a ticket for that. 

Apologies for the delay on this. I promise as speedy a review process as possible!

**Comment by wcaleb** [comment]
Thanks, Ian! But note that our new workflow for future lessons is to do all the review before merging, and have reviewers leave comments on the pull request. 

Sent from my iPhone

W. Caleb McDaniel
Associate Professor of History
Duncan College Master
Rice University

http://wcm1.web.rice.edu/
http://www.duncancollege.net/

**Comment by ianmilligan1** [comment]
Ah, I see. So should pre-submission reviews be done outside of GitHub via e-mail until the final stage then? Still getting my head around our new workflow!

And especially apologies to @petercarrjones.

**Comment by wcaleb** [comment]
I think the ultimate goal is for all review to happen on the Pull Request page in comments. That could still occur in this case even though you've merged. Alternatively, if it's not too much trouble for Peter, I could revert the merge commit and he could re-submit a new Pull Request. In that case I could generate a preview of the lesson that you could send to reviewers. 

Sent from my iPhone

W. Caleb McDaniel
Associate Professor of History
Duncan College Master
Rice University

http://wcm1.web.rice.edu/
http://www.duncancollege.net/

**Comment by ianmilligan1** [comment]
Why don't we revert, Peter can review my suggested edits above, and then re-submit a new Request. And then we'd generate preview, send to reviewers?

**Comment by fredgibbs** [comment]
yesterday i updated the reviewer-guidelines page to reflect the new
"comment on pull request' system that we're moving to, in case reviewers
will be looking for directions there. but probably they can figure out what
to do in either case as long as they know to look for either a pull request
or a ticket to post their review on.

On Fri, Aug 21, 2015 at 2:26 PM, W. Caleb McDaniel <notifications@github.com

> wrote:
> 
> I think the ultimate goal is for all review to happen on the Pull Request
> page in comments. That could still occur in this case even though you've
> merged. Alternatively, if it's not too much trouble for Peter, I could
> revert the merge commit and he could re-submit a new Pull Request. In that
> case I could generate a preview of the lesson that you could send to
> reviewers.
> 
> Sent from my iPhone
> 
> W. Caleb McDaniel
> Associate Professor of History
> Duncan College Master
> Rice University
> 
> http://wcm1.web.rice.edu/
> http://www.duncancollege.net/
> 
> > On Aug 21, 2015, at 3:18 PM, Ian Milligan notifications@github.com
> > wrote:
> > 
> > Ah, I see. So should pre-submission reviews be done outside of GitHub
> > via e-mail until the final stage then? Still getting my head around our new
> > workflow!
> > 
> > And especially apologies to @petercarrjones.
> > 
> > On August 21, 2015 at 4:16:34 PM, W. Caleb McDaniel (
> > notifications@github.com) wrote:
> > 
> > Thanks, Ian! But note that our new workflow for future lessons is to do
> > all the review before merging, and have reviewers leave comments on the
> > pull request.
> > 
> > Sent from my iPhone
> > 
> > W. Caleb McDaniel
> > Associate Professor of History
> > Duncan College Master
> > Rice University
> > 
> > http://wcm1.web.rice.edu/
> > http://www.duncancollege.net/
> > 
> > > On Aug 21, 2015, at 3:10 PM, Ian Milligan notifications@github.com
> > > wrote:
> > > 
> > > @petercarrjones I've merged this commit to begin the review process.
> > > Peter, I've made a few tiny edits - which you can see in this commit.
> > > 
> > > I think the only thing that I might suggest adding before sending out
> > > for review is a brief conclusion: any next steps? Any further readings?
> > > Anything that you think they should explore? This might help wrap it up.
> > > Let me know and I will contact reviewers and open up a ticket for that.
> > > 
> > > Apologies for the delay on this. I promise as speedy a review process
> > > as possible!
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub.
> > 
> > ## 
> > 
> > Ian Milligan, PhD
> > Assistant Professor
> > Department of History, Faculty of Arts
> > University of Waterloo
> > 200 University Avenue West, Waterloo, ON, N2L 3G1
> > P 519-888-4567, ext. 32775
> > C 519-807-7279
> > ianmilligan.ca/
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/programminghistorian/jekyll/pull/77#issuecomment-133550863
> .

## 

frederick w gibbs | assistant professor of history | univ. of new mexico
fredgibbs.net | @fredgibbs
http://www.twitter.com/fredgibbs

**Comment by petercarrjones** [comment]
Sounds great. I'm happy to resubmit (after a few more final edits).

**Comment by wcaleb** [comment]
Thanks @petercarrjones. I've deleted the merged lesson. It would be best if you could sync your fork so that it is up to date with our repo (or delete your fork and fork again), and then create a new branch and new pull request. Since you created the pull request before we had made some changes necessary to this new workflow, that's probably the best way forward. Let me know if that doesn't make sense, or if that's inconvenient for you. Appreciate your flexibility as we work out this system!

**Comment by wcaleb** [comment]
FYI @ianmilligan1 here's [the information](http://programminghistorian.org/reviewer-guidelines#how-to-submit-your-review) @fredgibbs was referring to. Apologies for the confusion!

**Comment by petercarrjones** [comment]
That should be easy enough to refork it, then create a new pull request.
Thanks all.

**Comment by ianmilligan1** [comment]
Thanks, @petercarrjones - and if you have any questions, I'm happy to help either here or [by e-mail](mailto:i2millig@uwaterloo.ca)!

**Comment by ianmilligan1** [comment]
Hi @petercarrjones - just pinging again, do you want to create a new pull request and then we'll get started on the peer review process? Looking forward to working with you on this in the new year!

**Pull request merged**
