### PR TITLE
Refactor translation link generation

### PR DESCRIPTION
**Pull request by mdlincoln**
This PR significantly simplifies the translation link generation logic, which results in a decent build time speedup.

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
~if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description~
- [x] Add the appropriate "Label"
- [x] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
~- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above~

Other to-dos before this can be merged:

- [x] Remove variable inspection displays (I want them up there for the technical team to get an understanding of what's happening behind the scenes)
- [x] Check for any current translation link problems like pages missing `original` or multiple pages in same language pointing to same original

### CODE REVIEW

**Comment by mdlincoln** [comment]
@programminghistorian/technical-team we'll take a look through this during our call

**Comment by mdlincoln** [comment]
@programminghistorian/french-team while I was working on this, I saw two nearly identical files:

- fr/votre-avis.md
- fr/reaction.md

reaction.md is currently the file that is linked in the menu. I deleted votre-avis.md - it seems to be the out-of-date version of the content. Please let me know if there are objections, or if you would like to update the text used in the menu.

**Comment by mdlincoln** [comment]
A draft walkthrough for @programminghistorian/technical-team : https://github.com/programminghistorian/jekyll/wiki/Technical-Tutorial-on-Translation-Links

**Comment by mdlincoln** [comment]
Reminder to @programminghistorian/technical-team to look over the wiki documentation in conjunction with this PR preview, and let me know how I can better clarify the walkthrough and/or the comments in the code.

I'll finish and merge this PR next Monday March 2.

**Comment by walshbr** [comment]
Look good to me! I think it all makes sense. Thanks for putting this together.

**Comment by mdlincoln** [comment]
This is ready for a @programminghistorian/technical-team member to approve and then I can merge.

**Comment by walshbr** [comment]
@mdlincoln - On this page - https://deploy-preview-1673--ph-preview.netlify.com/es/

It looks like one of the links is getting incorrectly generated for the "contribute" dropdown and resulting in an empty box for the dropdown link.

Screen Shot 2020-03-02 at 11 59 06 AM

**Comment by mdlincoln** [comment]
oh good catch - we've had that for a while. I seem to remember there's a reason for it - can look more into it tomorrow to remind myself what's going on...

**Comment by mdlincoln** [comment]
So the Spanish team does not have a separate "translation guide" page. They have a combined ["Guía para autores y traductores" page](https://programminghistorian.org/es/guia-para-autores). 

I can add logic to the menu to keep that blank from showing up. @programminghistorian/spanish-team FYI you may want to consider if you want to separate out your author & translator guide - it would be nice from the technical standpoint because it's the only exception to the patterns we have set up across the rest of the core pages. But that's a bigger task than this one PR.

**Comment by spapastamkou** [comment]
> @programminghistorian/french-team while I was working on this, I saw two nearly identical files:
> 
> * fr/votre-avis.md
> * fr/reaction.md
> 
> reaction.md is currently the file that is linked in the menu. I deleted votre-avis.md - it seems to be the out-of-date version of the content. Please let me know if there are objections, or if you would like to update the text used in the menu.

@mdlincoln I am sorry, I just saw this. I think it was by mistake at the very beginning that we (or should I say quite probably I!) had created 2 files with the same content and different name for the same page. Then it was forgotten and thank you very much for cleaning this.

**Comment by jenniferisasi** [comment]
> I can add logic to the menu to keep that blank from showing up. @programminghistorian/spanish-team FYI you may want to consider if you want to separate out your author & translator guide - it would be nice from the technical standpoint because it's the only exception to the patterns we have set up across the rest of the core pages. But that's a bigger task than this one PR.

First, just getting to this (and my email). Thanks @mdlincoln for all this you have done (and announced on Twitter). I think we were going to separate guides for translators but I don't recall what happened to the idea... I'll let @rivaquiroga if we want to proceed. If the FR and EN and eventually PR team have them separate, we should have them separate too.

**Comment by spapastamkou** [comment]
@jenniferisasi the discussion on this is now in issue #1695; I copy there the link for your comment and add the relevant issues that led to the creation of a separate page for translation guidelines.

**Comment by mdlincoln** [comment]
@programminghistorian/technical-team please review...

**Review by walshbr — APPROVED** [review]

**Comment by walshbr** [comment]
Sorry - missed that you had made the change.

**Pull request merged**
