### PR TITLE
Update funding declaration

### LINKED ISSUE #833: Change to funding declarations
The current funding declaration on the about page is no longer up to date given our upcoming workshp funded by the British Academy. Propose:

## Funding & Ownership

The project is grateful for the following support:

* Seed funding and project management support from the Network in Canadian History & Environment (NiCHE) [2011-2013].
* Ongoing hosting support from the Roy Rosenzweig Center for New Media (RRCHNM) [2011-Present].
* Funding for a writing workshop in Bogota, Colombia, supported by the British Academy [2018].

The Programming Historian is a volunteer-driven project. It is published by the Editorial Board of the Programming Historian.

### PR DESCRIPTION
**Pull request by acrymble**
Our current funding declaration is out of date because of recent funding. This needs to be reflected on the website.

This update needs to be translated into Spanish. @mariajoafana can you please take care of that, since this is our event that received funding? Closes #833

### CODE REVIEW

**Comment by mdlincoln** [comment]
I rebased this against `gh-pages` so that it can be easily merged back into the published site. That means a lot of extra commits appear on the PR right now, but they'll be seamlessly merged in later.

@mariajoafana note that you can still see the specific changes to the about pages here: <https://github.com/programminghistorian/jekyll/pull/834/files#diff-28d6582603c439a42e4b9c584f336308R31>

**Comment by mdlincoln** [comment]
@mariajoafana what is the status of this?

**Comment by acrymble** [comment]
@mariajoafana I don't think you were receiving these email requests. Can you please take a look at this?

**Comment by acrymble** [comment]
I think there's some confusion @mdlincoln about what needs translating. Can we simplify this any way so it's more obvious? @mariajoafana

**Comment by arojascastro** [comment]
I think the required change has been made here: https://github.com/programminghistorian/jekyll/pull/888

**Comment by mariajoafana** [comment]
Yes, sorry I found something else that needed an updated translation in the Readme section, but I also updated the funding declaration as Antonio noted.

**Review by mdlincoln — APPROVED** [review]

**Pull request merged**
