### PR TITLE
Collaborative blog with jekyll GitHub

### PR DESCRIPTION
**Pull request by svmelton**
Creating Collaborative Blog with Jekyll & GitHub lesson

### Checklist

- [X] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [X] Add the appropriate "Label"
- [x] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by svmelton** [comment]
Hi @programminghistorian/technical-team! I'm getting the following error:
```
jekyll 3.8.5 | Error:  undefined method `[]' for nil:NilClass
build.command failed
```
Any ideas what might be causing the issue?

**Comment by walshbr** [comment]
Just checked - it has two issues that I saw. The "Scholars' Lab community" from the metadata is causing an error, i think, because they don't have a bio in the author bio file. I could just give a sentence for the purposes of the lesson if you want. Something like "The original version of this lesson drew from internal documentation created by the Scholars' Lab community at the University of Virginia Library" as the "bio."

It needs a DOI field in the metadata, which I think also needs to be added to the template - https://programminghistorian.org/en/editor-guidelines#3-add-yaml-metadata-to-the-lesson-file.

**Comment by svmelton** [comment]
Thanks, @walshbr! I've just added the DOI. If you could add that bio, that would be great. I'll open a PR to update the template.

**Comment by drjwbaker** [comment]
@svmelton Quick question. Can I just check that we feel that the DOI process is running smoothly?

**Comment by svmelton** [comment]
@drjwbaker Yes! Sussex has been great to work with.

**Comment by walshbr** [comment]
Check that out @svmelton? It still needs translation on the bios, I believe, though I can't remember if we translate those outright or wait until the lesson itself gets translated.

**Comment by svmelton** [comment]
Thanks @walshbr! Looks good to me. I think we can wait on translation until the lesson itself gets translated.

**Comment by svmelton** [comment]
Just pinging @programminghistorian/technical-team for final review whenever you get a chance!

**Comment by walshbr** [comment]
(I should probably not do the approval since it is my lesson :) )

**Review by ZoeLeBlanc — APPROVED** [review]
Looks good to me! Merge away 👍

**Pull request merged**
