### PR TITLE
Adds references in research pages

### PR DESCRIPTION
**Pull request by spapastamkou**
*Adds 3 references in research page in EN, FR, ES, PT*

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [ ] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Review by DanielAlvesLABDH — DISMISSED** [review]

**Comment by spapastamkou** [comment]
@rivaquiroga The build fails because of a dead link in ```/es/lecciones/topic-modeling-y-mallet.html``` It is(was!)  a dataset on figshare: 

 ``` *  External link http://figshare.com/articles/looted_heritage_reports_txt.zip/91828 failed: 404 No error```
Cc @svmelton as the lesson is a translation of ```/en/lessons/topic-modeling-and-mallet```

**Review by rivaquiroga — APPROVED** [review]

**Comment by rivaquiroga** [comment]
@spapastamkou, I fixed the link in the ES translation and in the original EN lesson :wrench:

**Comment by spapastamkou** [comment]
Thank you @rivaquiroga ! 
Otherwise, if I am not mistaken, the data file is not in the ```assets``` directory. Do you think we should add them? (for the Mallet lesson I mean).

**Comment by rivaquiroga** [comment]
@spapastamkou that dataset is suggested in the "Further Reading" section, in case readers want to se another example. Is not a key resource of the lesson itself, so I don't think is necesary to add it to the `assets` directory.

**Comment by spapastamkou** [comment]
@rivaquiroga Got it (had not seen it was not the main dataset). Thanks!

**Pull request merged**
