### PR TITLE
Issue 2932

### LINKED ISSUE #2932: Updates to our Events pages
I am updating the following pages of our website to reflect new and forthcoming events:

/en/events
/es/eventos
/fr/manifestations
/pt/eventos

(I am aware that the layout of this page lacks interest, and will need some energy to activate. For now, it is the basic minimum).

### PR DESCRIPTION
**Pull request by anisa-hawes**
I am updating the following pages of our website to reflect new and forthcoming events:

/en/events
/es/eventos
/fr/manifestations
/pt/eventos

Closes #2932 

(I am aware that the layout of this page lacks interest, and will need some energy to activate. For now, it is the basic minimum).

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Add the appropriate "Label"
- [x] If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above
- [x] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Assistant @anisa-hawes 
- [x] Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines), then assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR.

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Ah! Thank you, @rivaquiroga ! I could have done these !

**Comment by rivaquiroga** [comment]
(This is just a very productive way to avoid doing other tasks I need to be doing 🤣 )

**Comment by rivaquiroga** [comment]
I missed an `*` so the second event is not well formated 😅. I'll fix it

**Comment by jenniferisasi** [comment]
> (This is just a very productive way to avoid doing other tasks I need to be doing 🤣 )

Productive procrastination FTW

**Review by rivaquiroga — APPROVED** [review]

**Pull request merged**
