### PR TITLE
menu link to technical contributions wiki

### LINKED ISSUE #847: Make Tech Install Instructions More Visible
I attempted to add instructions to running site locally with this PR [https://github.com/programminghistorian/jekyll/pull/844](https://github.com/programminghistorian/jekyll/pull/844) since technical instructions weren't explicitly provided in the README. However, I now see that there is a guide in the Wiki on making technical contributions [https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions).

Can I update the README to link to the current guide to making technical contributions and/or update the [contribute page](https://programminghistorian.org/contribute) to include a description and link to the wiki article on making technical contributions? Currently, the contribute page seems to focus on editorial contributions and reporting issues and the README doesn't link to the Wiki.

Goal: Update the site and/or readme to make the current wiki on getting started with technical instructions more visible for first-time contributors.

### PR DESCRIPTION
**Pull request by mdlincoln**
Closes #847

Is "Contribuciones técnicas" a satisfactory label for "Technical Contributions" @programminghistorian/spanish-team ?

### CODE REVIEW

**Comment by acrymble** [comment]
should it say (ingles) after it on the Spanish site?

**Review by arojascastro — APPROVED** [review]
Yes, "Contribuciones técnicas" is fine. Thanks ou

**Comment by arojascastro** [comment]
I think this comitt 12556780154dcda19493ae980cb788148b875635 should fix the translation -- unless I overlooked more changes. Let me know @mdlincoln

**Comment by acrymble** [comment]
Thanks to @M0nica for suggesting we make this information more visible

**Pull request merged**
