### PR TITLE
Add Antoine Henry

### PR DESCRIPTION
**Pull request by icolab**
Add Antoine Henry as part of the team

*add the reason for your pull request here*

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by spapastamkou** [comment]
@icolab La photo de profil doit être en noir et blanc (carrée 300 px) (plus d'infos [ici](https://github.com/programminghistorian/jekyll/wiki/Onboarding-Process-for-New-Editors#your-first-month) au dernier paragraphe). Peux-tu la modifier dans ce pull request-ci en utilsant cette branche? (j'ai approuvé l'autre sans faire attention que la photo était en couleurs). Merci!

**Comment by icolab** [comment]
@spapastamkou désolé pour ce raté, c'est corrigé normalement

**Review by spapastamkou — CHANGES_REQUESTED** [review]
@icolab Dans le champ ```sortname``` il faut plutôt mettre ton nom de famille

**Comment by spapastamkou** [comment]
@icolab je me suis permise de bidouiller un peu ta photo:-) tu veux me dire ce que tu en penses? tu peux la voir dans la [prévisualisation ](https://deploy-preview-2066--ph-preview.netlify.app/en/project-team)de netlify

**Comment by icolab** [comment]
@spapastamkou très bien pour ma photo :-)

**Review by spapastamkou — APPROVED** [review]

**Pull request merged**
