### PR TITLE
Update research pages

### LINKED ISSUE #3007: Collating recent research activities and outputs for the en/research, es/investigacion, fr/recherche and pt/pesquisa pages
Hello all

@programminghistorian/english-team 
@programminghistorian/spanish-team 
@programminghistorian/french-team 
@programminghistorian/portuguese-team 

**Have you done research that connects to your work with the _Programming Historian_ recently?**

I'm preparing an update of the en/research, es/investigacion, fr/recherche and pt/pesquisa pages of our website, and would be keen to hear about any recent articles / chapters / reports / posters / papers.

Please write a comment here, ideally including:

- Name(s)
- Title of your article / chapter / report / workshop / poster / paper
- Organising institution or group
- Location, date
- Link (if applicable)

I'll prepare an update.

Please note that if your recent research activity was a workshop or event that we posted on our events pages it will already be included 🙂

### PR DESCRIPTION
**Pull request by charlottejmc**
Update research page
Closes #3007

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Add the appropriate "Label"
- [x] If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above
- [x] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Assistant @anisa-hawes 
- [x] Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)
- [x] Assign at least one individual or team to "Reviewers"
  - ~[ ] if the text needs to be translated, please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines), then assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR.~

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Thank you for preparing this @charlottejmc! One very small edit to make: FR Septembre > septembre (lowercase s).

You can make this edit directly [within the Files Changed tab](https://github.com/programminghistorian/jekyll/pull/3041/files) here in the Pull Request: 

Screenshot 2023-10-11 at 15 54 59

Alternatively, you can opt to [navigate back to your branch](https://github.com/programminghistorian/jekyll/tree/update-research-pages), then tap into `/fr/recherche.md` to make the adjustment ☺️

**Comment by anisa-hawes** [comment]
Hello @charlottejmc,

Also we have an addition from Josir (@josircg) who has left [a comment in the Issue](https://github.com/programminghistorian/jekyll/issues/3007#issuecomment-1757902944) 🙂 

Update: this is forthcoming, so we can add this to the Events pages instead. Let's do this with a separate PR via Issue #3006.

**Comment by charlottejmc** [comment]
Thank you @anisa-hawes! I have made the edit to Septembre (>septembre). I can start the new PR for the Events page as well.

**Review by anisa-hawes — APPROVED** [review]

**Comment by anisa-hawes** [comment]
Perfect, @charlottejmc! This is ready for you to merge in.

**Pull request merged**
