### PR TITLE
Update guia-para-autores per issue #1040

### PR DESCRIPTION
**Pull request by jenniferisasi**
At least one member of the @programminghistorian/spanish-team needs to check these changes and approve them.

### CODE REVIEW

**Review by vgayolrs — DISMISSED** [review]
Great @jenniferisasi !
It seems to me that all the changes are correct, follow the new guidelines in English and also corrects errors. I just think that on line 224 you should leave "hola mundo" in Spanish. Thoughts?

**Comment by jenniferisasi** [comment]
Gracias @vgayolrs. Line 224 changed, ¡se me había escapado!

**Review by vgayolrs — APPROVED** [review]
¡Genial @jenniferisasi !

**Comment by mariajoafana** [comment]
Se ve bien, voy a darle merge

**Pull request merged**
