### PR TITLE
Issue 2489 and 2442

### LINKED ISSUE #2442: New section to display awards in About page
Programming Historian was the recipient of an Open Content category award in the Open Publishing Award 2021 https://openpublishingawards.org/results/2021/index.html 

This has prompted a conversation about displaying our awards somewhere in our website. The simple addition can happen in the About page in a new section that we can create; if we want to display logos for each award I believe it will work best if we place them at the end of the page. But open to other suggestions.

### LINKED ISSUE #2489: Adding a link to History of the Project section of en/about, es/acerca-de, fr/apropos, pt/sobre
Following an idea @nabsiddiqui raised on our "general" Slack channel recently –that William J. Turkel's original blog post about his intention to create _Programming Historian_ would be of interest our team and broader community– @drjwbaker suggested we add the following link [<http://digitalhistoryhacks.blogspot.com/2008/01/programming-historian.html>] to the [History of the Project](https://programminghistorian.org/en/about#history-of-the-project) section of en/about, es/acerca-de, fr/apropos, pt/sobre

I think it could be woven into the first sentences as follows:

"The _Programming Historian_ was founded in 2008 by William J. Turkel and Alan MacEachern. Turkel published [a blog post](http://digitalhistoryhacks.blogspot.com/2008/01/programming-historian.html) at the time, setting out their intentions for the project. Initially it focused heavily on the Python programming language and was published open access as a Network in Canadian History & Environment (NiCHE) ‘Digital Infrastructure’ project."

### PR DESCRIPTION
**Pull request by anisa-hawes**
We are making some adjustments to the en/about, es/acerca-de, fr/apropos, pt/sobre pages of our website.

1. Replacing "Gold" with "Diamond" in relation to our publishing model and updating the accompanying link to <https://doi.org/10.6084/m9.figshare.6900566.v1>
2. Creating an Awards section
3. Adapting the History of the Project section to include a link to Turkel's blog post

Closes #2442 
Closes #2489 

I would like to ask if anyone from the @programminghistorian/french-team and @programminghistorian/portuguese-team have time to translate the following?

(Thank you to @jenniferisasi for the Spanish translations which have been applied to the branch already)

--

## Diamond Open Access
This adheres to a '[Diamond](https://doi.org/10.6084/m9.figshare.6900566.v1)' open access model of publishing. 

## Awards
The _Programming Historian_ has won multiple awards which recognise and celebrate our achievements in the spheres of open access publishing and digital scholarship. In 2016 our English-language journal was the winner of the [Digital Humanities Awards](http://dhawards.org/dhawards2016/results/) in the Best Series of Posts category, then in the following year, 2017, _Programming Historian en español_ [won that very same accolade](http://dhawards.org/dhawards2017/results/). In 2018, The _Programming Historian en español_ was the winner of 'Mejor iniciativa formativa desarrollada durante el año 2018', [Humanidades Digitales Hispánicas Association](http://humanidadesdigitaleshispanicas.es/). We won the [Canadian Social Knowledge Institute's Open Scholarship Award](https://etcl.uvic.ca/events-activities/open-scholarship-awards/) 2020 and in 2021 we were awarded [Coko Foundation's Open Publishing Award](https://openpublishingawards.org/results/2021/index.html) in their Open Content category.

## History of the Project
Turkel published [a blog post](http://digitalhistoryhacks.blogspot.com/2008/01/programming-historian.html) at the time, setting out their intentions for the project. Initially it focused heavily on the Python programming language […]

--

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by InesSalome** [comment]
Hello @anisa-hawes ! I can take charge of the french translation next week.

**Comment by anisa-hawes** [comment]
Thank you, Gwenaëlle @InesSalome! I'll be working on this again on Wednesday.

**Comment by InesSalome** [comment]
Done ! I have just a doubt about the translation of "digital scholarship" in Awards' part : does it mean "lessons, tutoriels online" or as Spanish translation suggests "transmission of methods in digital humanities" ?

**Comment by jenniferisasi** [comment]
> Done ! I have just a doubt about the translation of "digital scholarship" in Awards' part : does it mean "lessons, tutoriels online" or as Spanish translation suggests "transmission of methods in digital humanities" ?

Hi @InesSalome! I translated it with those words because we don't have a direct translation for digital scholarship; so we usually expand it to methods/research/pedagogy in DH - hope that makes sense.

**Comment by spapastamkou** [comment]
How about "domaine de la publication en libre accès et des humanités numériques" to keep it simple? (I suggest "libre accès" ou accès libre instead of "accès ouvert" bcz ouvert is mostly about access, and libre covers the whole range of reuse etc).

**Comment by spapastamkou** [comment]
@InesSalome merci beaucoup:-)

**Comment by anisa-hawes** [comment]
Thank you @InesSalome! + thank you @jenniferisasi & @spapastamkou! Much appreciated!

**Comment by anisa-hawes** [comment]
Hello @programminghistorian/portuguese-team. I wonder if anyone has time to translate the following new paragraph for our pt/sobre page:

## Awards
The _Programming Historian_ has won multiple awards which recognise and celebrate our achievements in the spheres of open access publishing and digital scholarship. In 2016 our English-language journal was the winner of the [Digital Humanities Awards](http://dhawards.org/dhawards2016/results/) in the Best Series of Posts category, then in the following year, 2017, _Programming Historian en español_ [won that very same accolade](http://dhawards.org/dhawards2017/results/). In 2018, The _Programming Historian en español_ was the winner of 'Mejor iniciativa formativa desarrollada durante el año 2018', [Humanidades Digitales Hispánicas Association](http://humanidadesdigitaleshispanicas.es/). We won the [Canadian Social Knowledge Institute's Open Scholarship Award](https://etcl.uvic.ca/events-activities/open-scholarship-awards/) 2020 and in 2021 we were awarded [Coko Foundation's Open Publishing Award](https://openpublishingawards.org/results/2021/index.html) in their Open Content category.

& these two sentences which have also been adjusted:

## Diamond Open Access
This adheres to a '[Diamond](https://doi.org/10.6084/m9.figshare.6900566.v1)' open access model of publishing. 

## History of the Project
Turkel published [a blog post](http://digitalhistoryhacks.blogspot.com/2008/01/programming-historian.html) at the time, setting out their intentions for the project. Initially it focused heavily on the Python programming language […]

I can slot the text into the .md file for you, if you'd prefer to Comment here with the translation. Thank you.

**Comment by joanacvp** [comment]
Hello @anisa-hawes. Here follow the translations into PT.

**Awards**
O _Programming Historian_ ganhou vários prémios que reconhecem as suas conquistas nas esferas das publicações em acesso aberto e da pesquisa digital. Em 2016 a nossa versão em inglês ganhou o [Digital Humanities Awards](http://dhawards.org/dhawards2016/results/) na categoria de _Best Series of Posts_. No ano seguinte, em 2017, o _Programming Historian en español_ ganhou o mesmo louvor e, no ano seguinte, venceu a 'Mejor iniciativa formativa desarrollada durante el año 2018', [Humanidades Digitales Hispánicas Association](http://humanidadesdigitaleshispanicas.es/). Ganhámos o Canadian Social Knowledge Institute's Open Scholarship Award em 2020 e, em 2021, foi-nos atribuído o Coko Foundation's Open Publishing Award na categoria _Open Content_.


**_Open Access_ [Diamante]**(https://doi.org/10.6084/m9.figshare.6900566.v1)
Tal adere a um modelo de publicação de acesso aberto [Diamante](https://figshare.com/articles/dataset/Diamond_open_access_venn/6900566/1).

**História do Projeto**
Na altura, Turkel publicou uma entrada no [blog](http://digitalhistoryhacks.blogspot.com/2008/01/programming-historian.html), definindo as suas intenções para o projeto. Inicialmente, focava-se fortemente na linguagem de programação Python.

**Comment by anisa-hawes** [comment]
Thank you so much @joanacvp! ✨

**Review by acrymble — APPROVED** [review]

**Pull request merged**
