### PR TITLE
change name on files

### PR DESCRIPTION
**Pull request by jenniferisasi**
Upon tweeting about the Newsletter I realize there was a mistake on the slurs, which was making the past newsletter and the current newsletter the same one. This was caused by me using the same characters/name after the date on the markdown file names. Lesson learned: Always use different names on the files regardless of the date being different.  

to address duplicate slurs on blogposts that is causing an issue of dissapearing blogposts

*add the reason for your pull request here*

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by jenniferisasi** [comment]
Ok, gonna try to fix the errors: 

- ./_site/es/lecciones/topic-modeling-y-mallet.html
467  *  External link https://web.archive.org/web/20180831100043/http://www.dlsi.ua.es/~borja/NavarroTomas_PosterSEPLN2015.pdf failed: 404 No error
468- ./_site/posts/PH-espanol-in-DH2018.html
469  *  External link http://web.archive.org/web/20190410194847/https://dh2018.adho.org/en/ failed: 404 No error
470- ./_site/posts/boletin-informativo-march20.html
471  *  External link https://software.ac.uk/blog/2020-01-10-announcing-2020-software-sustainability-institute-fellow failed: 404 No error

**Comment by walshbr** [comment]
I'm around this morning if you run into issues @jenniferisasi!

**Comment by jenniferisasi** [comment]
> I'm around this morning if you run into issues @jenniferisasi!

Thanks @walshbr! Two broken links are from the Wayback Machine... but one link (on topic modeling lesson) is on the regular web... weird. Let's see if it passes now

**Review by walshbr — APPROVED** [review]
Seems to work to me!

**Pull request merged**
