### PR TITLE
add new translation on R and network analysis

### PR DESCRIPTION
**Pull request by arojascastro**
First attempt to publish this lesson translated by Jennifer. Reviewed in https://github.com/programminghistorian/ph-submissions/issues/218

### CODE REVIEW

**Comment by arojascastro** [comment]
We got some errors that affect other pages or tutorials:

./_site/en/lessons/understanding-regular-expressions.html
  *  External link http://regex.learncodethehardway.org/book/ failed: 404 No error
- ./_site/es/lecciones/escritura-sostenible-usando-pandoc-y-markdown.html
  *  External link http://cli.learncodethehardway.org/book/ failed: 404 No error
- ./_site/posts/PH-espanol-in-DH2018.html
  *  External link https://dh2018.adho.org/en/ failed: 404 No error

**Comment by jenniferisasi** [comment]
Those same errors were preventing me from publishing something yesterday too. Now I know for sure it's that! I created an issue #1289 and I will get to them as soon as I can.

**Comment by arojascastro** [comment]
¡Gracias!

**Comment by mdlincoln** [comment]
Alright, those broken links should be fixed for you now @arojascastro

**Comment by arojascastro** [comment]
thank you! waiting for @mariajoafana 's approval now

**Comment by mdlincoln** [comment]
Hello @mariajoafana, have you had a chance to review this?

**Review by mariajoafana — APPROVED** [review]

**Comment by mariajoafana** [comment]
This have been merged

**Pull request merged**
