### PR TITLE
Sentiment analysis.md

### PR DESCRIPTION
**Pull request by acrymble**
Publishing "Sentiment Analysis" by @zoews. Should include all files.

### CODE REVIEW

**Comment by acrymble** [comment]
I'm getting some Travis errors here. I think they're because of the accents in Zoe's name. Is there a fix for that?

**Comment by ianmilligan1** [comment]
Let me take a look! (working on it now)

**Comment by ianmilligan1** [comment]
I changed it up and it's building locally now - Travis should be fine too (fingers crossed).

**Review by ianmilligan1 — APPROVED** [review]
This is good to merge, btw. Do you want me to make it live, Adam?

**Comment by acrymble** [comment]
Yes please!

**Comment by ianmilligan1** [comment]
Done and done!

**Pull request merged**
