### PR TITLE
Issue 3175

### LINKED ISSUE #3175: Replace 'Gold' with 'Diamond' on our /en/ipp, /es/pia, /fr/pi and /pt/ppi pages
I've recently noticed that the text on our /en/ipp, /es/pia, and /fr/pi and pages mentions we publish 'gold open access scholarship' rather than 'diamond open access'. This is a very important distinction because Gold Open Access will usually incur costs to the authors, whereas we are entirely free for readers and authors alike.

I believe /pt/ppi does not specify whether we are gold or diamond open access, but I will take this opportunity to add it in nonetheless.

### PR DESCRIPTION
**Pull request by anisa-hawes**
We've opened this Issue to correct our /en/ipp, /es/pia, /fr/pi and /pt/ppi pages which describe our publishing model as 'gold open access' where it should be 'diamond open access'.

I've also taken the opportunity to rephrase the description of our Gold Tier membership offer (making it a more general and open opportunity to collaborate, rather than a specific offer of workshops), and remove an accompanying footnote which isn't any longer needed. 

Closes #3175 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Add the appropriate "Label"
- [x] If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above
- [x] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Manager @anisa-hawes 
- [x] Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines), then assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR.

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Hello @jenniferisasi and @ericbrasiln,

I hope you're well?

I'd like to ask for your (or a member of your teams') support to check my translations of a rephrased sentence about our Gold Tier membership offer. 

I'm happy for you to make any corrections/adjustments directly [in this branch](https://github.com/programminghistorian/jekyll/pull/3183/files), or to add a comment here so I can make the changes you recommend.

Thank you!

& Thank you @charlottejmc for checking the FR already ✨

**Comment by jenniferisasi** [comment]
Running this AM but wanted to leave a small correction here (inserts in italics)

Las tarifas para nuestros colaboradores en nivel Gold son de £3.000 GBP, $4.200 USD, €3.600 EUR, $5.100 CAD. Como parte de la membresía, se les ofrece la oportunidad de trabajar con nosotros *para* mejorar el uso que hacen sus comunidades de las herramientas y métodos de las humanidades digitales.

**Comment by anisa-hawes** [comment]
Many thanks, @jenniferisasi. I've made that adjustment: https://github.com/programminghistorian/jekyll/pull/3183/commits/96e17326f6559d07c46b8836e19bf6e1a70d02fc.

**Comment by ericbrasiln** [comment]
Hello, 

This week and next I'm at an academic event in Rio de Janeiro.  I won't be able to work on the proghist until next Friday.  I apologize for the inconvenience.

**Comment by anisa-hawes** [comment]
Thank you to @joanacvp for sending me corrections for my PT translation by email 🙂

**Comment by joanacvp** [comment]
> Thank you to @joanacvp for sending me corrections for my PT translation by email 🙂

I am glad to be able to help :)

**Review by spapastamkou — APPROVED** [review]

**Pull request merged**
