### PR TITLE
Upgrade MALLET Lesson from 2.0.7 to 2.0.8

### PR DESCRIPTION
**Pull request by ianmilligan1**
Picking up on #393, this PR upgrades the lesson from 2.0.7 to 2.0.8. The major change in this release for our purposes is one of the output files, which can be seen in the new lines 524-532 below.

Putting here just to have it one place before merging. Any comments or thoughts are greatly appreciated.

### CODE REVIEW

**Comment by shawngraham** [comment]
Given that 2.0.8 makes the output a bit less useable (from our standpoint), maybe just point the download to 2.0.7 & make a note that if the user grabs 2.0.8, the output is in this other format...?

**Comment by ianmilligan1** [comment]
Re: keeping it at 2.0.7, that was our original plan, but it's leading to a lot of feedback... I think a lot of people download MALLET, get it started, and then turn to us. And one of the only places to find 2.0.7 is to dig into the link in our lesson.

We're trying to avoid lessons on outdated versions, which I think is probably a good policy.

**Comment by acrymble** [comment]
You're both authors on this (as is Scott Weingart). This strikes me as the type of scenario we've been discussing a lot lately. @shawngraham it would be good to get your candid view on how you'd like this type of updating managed (assuming you have a candid view).

**Comment by ianmilligan1** [comment]
Yes, we've also been discussing off this ticket.

**Comment by mdlincoln** [comment]
No rush at all on this @ianmilligan1 - but do you have some target timeline for completing this? Just so I know when to check in 👍

**Comment by ianmilligan1** [comment]
Just waiting on folks - my guess and hope is within two weeks of DH 2017 wrapping up. 😀

**Comment by ianmilligan1** [comment]
Just to update re: this, I pinged @shawngraham and @scottbot.

**Pull request merged**
