### PR TITLE
Add markdown file for lesson

### PR DESCRIPTION
**Pull request by svmelton**
Adding md for Beginner's Guide to Twitter Data

### CODE REVIEW

**Comment by jenniferisasi** [comment]
Hmm looks like there is some issue between the lesson file and the authors file. I'm going to try to find out what it is.

**Comment by jenniferisasi** [comment]
@svmelton did any of you add the authors of this lesson to the `ph_authors.yml` file yet? I can't find them so I guess not, and then I believe that is a huge red flag for Travis.

**Comment by svmelton** [comment]
Hi @jenniferisasi— @spapastamkou mentioned that she did:
https://github.com/programminghistorian/ph-submissions/issues/248#issuecomment-544293189 

(Also, I might be a bit confused with the process. I'm wondering if we're hitting an issue because I'm committing to @spapastamkou's branch, which is probably behind the master branch. I haven't pushed to a branch other than the default before, so I might be missing some steps!)

**Comment by walshbr** [comment]
Hmm…FWIW, if you're just merging things directly into @spapastamkou's branch and she has already given you permission to do so, I think you can go ahead and do it. The workflow and tests we have set up is really set up for merging into the main gh-pages timeline. Particularly since it seems like the resultant branch with your changes in it will have the fixes you need for those tests, it might make sense to go ahead and merge these two branches together then make a pull request for the combined set of changes with everything related to the lesson. Am I understanding that correctly @svmelton? I think you're right that the parenthetical you mentioned might be the issue. Because I do see that the branch has the file you're looking for.

**Comment by svmelton** [comment]
Thanks, @walshbr—that makes sense. I'll go ahead and merge.

**Comment by spapastamkou** [comment]
Yes, the file ```ph-authors.yml``` in the branch was updated with the authors' names. I'll update the branch as well.

**Comment by walshbr** [comment]
I think if you make a fresh PR with all the stuff on one branch that will help clarify things.

**Comment by spapastamkou** [comment]
created the #1536 PR

**Pull request merged**
