### PR TITLE
Add alert bar to wget lesson re: Nat Arch. Australia

### LINKED ISSUE #909: Applied Archival Downloading with Wget
- Mac
- GNU Wget 1.19.1 built on darwin16.6.0.
- Python 3.6.3 :: Anaconda, Inc.
- The [The National Archives of Australia](https://programminghistorian.org/en/lessons/applied-archival-downloading-with-wget#a-second-example-the-national-archives-of-australia) section appears to no longer work. View doesn't allow for `right click -> view image` bit of the lesson. Script downloads html files. Wget calls seem to be not finding what they should (see below).

`--2018-06-14 16:31:29--  http://www.nla.gov.au/apps/cdview/?pi=nla.ms-ms5393-1-s1-v.jpg`
`Resolving www.nla.gov.au... 192.102.239.53`
`Connecting to www.nla.gov.au|192.102.239.53|:80... connected.`
`HTTP request sent, awaiting response... 302 Moved Temporarily`
`Location: http://nla.gov.au/nla.ms-ms5393-1-s1-v.jpg [following]`
`--2018-06-14 16:31:32--  http://nla.gov.au/nla.ms-ms5393-1-s1-v.jpg`
`Resolving nla.gov.au... 192.102.239.32`
`Connecting to nla.gov.au|192.102.239.32|:80... connected.`
`HTTP request sent, awaiting response... 200 OK`
`Length: unspecified [text/html]`
`Saving to: ‘index.html?pi=nla.ms-ms5393-1-s1-v.jpg.2’`
` `
`index.html?pi=nla.ms-ms5     [ <=>                            ]  11.81K  --.-KB/s    in 0.001s  `
` `
`2018-06-14 16:31:34 (11.6 MB/s) - ‘index.html?pi=nla.ms-ms5393-1-s1-v.jpg.2’ saved [12090]`
` `
`--2018-06-14 16:31:36--  http://www.nla.gov.au/apps/cdview/?pi=nla.ms-ms5393-1-s2-v.jpg`
`Reusing existing connection to www.nla.gov.au:80.`
`HTTP request sent, awaiting response... 302 Moved Temporarily`
`Location: http://nla.gov.au/nla.ms-ms5393-1-s2-v.jpg [following]`

### PR DESCRIPTION
**Pull request by mdlincoln**
Closes #909

### CODE REVIEW

**Comment by arojascastro** [comment]
I am not sure but I think @vgayolrs has just uploaded a translation of this lesson. Are we aware of this little change?

**Comment by mdlincoln** [comment]
Thanks for noting that @arojascastro, I'll add a note in the review ticket at https://github.com/programminghistorian/ph-submissions/issues/181

**Comment by vgayolrs** [comment]
@arojascastro @mdlincoln : This problem does not affect the [translation](https://github.com/programminghistorian/ph-submissions/issues/201) I did since it's from the first lesson of the series:  It works with the site http://activehistory.ca, which is operating correctly.

**Review by vgayolrs — APPROVED** [review]

**Comment by mdlincoln** [comment]
No @vgayolrs, there are 2 wget lessons, and this translation http://programminghistorian.github.io/ph-submissions/es/traducciones/descarga-archivos-wget#segundo-ejemplo-archivos-nacionales-de-australia does contain the problem section

**Comment by vgayolrs** [comment]
yes, @mdlincoln ,  I'd noticed. We shall request the translator to add the alert bar... Actually, I already left the notice on the ticket.

**Comment by mariajoafana** [comment]
So I guess this is ready to merge, we'll create a new pull request for updating the Spanish translation

**Pull request merged**
