### PR TITLE
Publicar Análise de sentimento para exploração de dados

### PR DESCRIPTION
**Pull request by DanielAlvesLABDH**
*Publicar a tradução da lição "Sentiment Analysis for Exploratory Data Analysis"*

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by DanielAlvesLABDH** [comment]
Hi @programminghistorian/technical-team! Am I doing something wrong here or this is an internal error from the build?

 jekyll 3.8.5 | Error:  undefined method `[]' for nil:NilClass
Error: Process completed with exit code 1.

Thanks in advance for the help!

**Review by ericbrasiln — DISMISSED** [review]
Boa noite, @DanielAlvesLABDH 
Executei todo o código da lição e funcionaou perfeitamente.
Aprovo a publicação.

**Comment by ZoeLeBlanc** [comment]
Looking into this error now @DanielAlvesLABDH ! I'll hopefully report back soon with a fix 👍🏽

**Comment by DanielAlvesLABDH** [comment]
Thank you @ZoeLeBlanc

**Comment by ZoeLeBlanc** [comment]
Ok looks like the issue is solved! Seems like it was just a small error with the original Author's name (need to write in the actual unicode for the diacritical marks). 

I also included formatting for the code blocks but that's just for rendering purposes. Just as an FYI, when you use the ``` syntax in Markdown, it will only properly render if you write the code language next to it (most programming languages are accepted though!). In this case, I assumed all of them were Python but definitely be worth double checking in case I missed something.

Let me know if there's still issues and once it's done building, I'll add my review 😊

**Comment by ZoeLeBlanc** [comment]
Looks like the current error is that you're missing an image for your figure @DanielAlvesLABDH. I tried to look in the Ph-Submissions folder but looked like the figure was never rendering there either 🤔 .

I'm pretty sure you should be set once you get that figure image but feel free to ping me or tech team if you have any additional errors!

**Comment by DanielAlvesLABDH** [comment]
Hi @ZoeLeBlanc, many thanks for all the work on this. I will probably never guess that one of the errors was on those letters in the name of the author. Thanks also for the tip about the code blocks. Made another review, change only a couple of things. Now things look fine. Best

**Comment by DanielAlvesLABDH** [comment]
Just asked the colleagues that translated and edited the lesson for the new image. Thanks again @ZoeLeBlanc

**Review by ericbrasiln — APPROVED** [review]
Boa tarde, @DanielAlvesLABDH
Em relação à lição traduzida para o português, o código está funcionando e não encontrei problemas. Aprovo a publicação.

**Pull request merged**
