### PR TITLE
Added search corpus generation files and created a new version of thi…

### PR DESCRIPTION
**Pull request by ZoeLeBlanc**
…s branch

Adding search generation to create initial search corpus files for each language.

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [ ] Add the appropriate "Label"
- [ ] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by mdlincoln** [comment]
oh dammit, I ended up merging the bad commits from your old branch b/c they were named the same 🤦‍♂

**Comment by mdlincoln** [comment]
I'm going to close this and re-push JUST the json modifications (I'm going to DRY them up a bit anyway)

**Comment by ZoeLeBlanc** [comment]
@mdlincoln sorry for the confusion!! I deleted the earlier remote branch, so curious how the bad commits remained 🤔?? But regardless thanks for fixing 🙏

**Comment by mdlincoln** [comment]
It was not your fault entirely - I still had the local tracking branch named `issue-1018` so when it pulled the latest, it didn't treat your new branch as "new".

**Pull request closed without merging**
