### PR TITLE
Publicar Reutilização de código e modularidade em Python

### PR DESCRIPTION
**Pull request by DanielAlvesLABDH**
*Publicar tradução da lição "Code Reuse and Modularity in Python"*

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by DanielAlvesLABDH** [comment]
O DOI já foi solicitado. A aguardar...

**Comment by DanielAlvesLABDH** [comment]
DOI introduzido. Falta apenas uma verificação geral da @aracele (a quem agradeço, desde já) para publicar

**Review by aracele — COMMENTED** [review]
Verificado! Parece tudo certo pra mim!

**Review by aracele — APPROVED** [review]

**Comment by DanielAlvesLABDH** [comment]
Muito obrigado @aracele

**Pull request merged**
