### PR TITLE
Revert "Update research.md"

### PR DESCRIPTION
**Pull request by walshbr**
This reverts commit 442137844360f771d5ea5312b593b55bc99c8699.

*add the reason for your pull request here*

### Checklist

- [ ] Assign yourself in the "Assignees" menu
- [ ] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [ ] Add the appropriate "Label"
- [ ] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by walshbr** [comment]
@drjwbaker  - I don't know how you committed directly to gh-pages, because I couldn't do so to revert your commit. I think the only way to do so is to pull request my revert commit so that the thing is back to the previous state so that you can then open your PR properly.

**Review by drjwbaker — DISMISSED** [review]
ta :)

**Comment by drjwbaker** [comment]
> @drjwbaker - I don't know how you committed directly to gh-pages, because I couldn't do so to revert your commit. I think the only way to do so is to pull request my revert commit so that the thing is back to the previous state so that you can then open your PR properly.

For some reason I have those admin privileges. @mdlincoln knows. And has told me off more than once for direct committing :)

**Comment by drjwbaker** [comment]
@walshbr Will you merge?

**Comment by mdlincoln** [comment]
More than one person needed admin privileges, and @drjwbaker had been doing lots of other admin-y work. That's why. Perhaps someone else can take on this? You'll want at least 2-3 folks with it, and I'll be leaving soon.

**Comment by drjwbaker** [comment]
> More than one person needed admin privileges, and @drjwbaker had been doing lots of other admin-y work. That's why. Perhaps someone else can take on this? You'll want at least 2-3 folks with it, and I'll be leaving soon.

Yeah, I can't be trusted. Can't the whole @programminghistorian/technical-team be admins?

**Comment by walshbr** [comment]
Put me in, coach @mdlincoln.
@drjwbaker - had to fix a dead link. Can you review again?

**Review by drjwbaker — APPROVED** [review]

**Comment by drjwbaker** [comment]
@walshbr @mdlincoln Can someone make me an admin again please? Sorry to ask. Specifically, I can no longer push to https://github.com/programminghistorian/project-and-business-archive and I think that is because my access has been changed. I didn't realise that would be a knock-on effect of changing my status!

**Comment by mdlincoln** [comment]
I thought all that was moved to an outside repo now?

**Comment by drjwbaker** [comment]
Yes, a private repo at https://github.com/programminghistorian/project-and-business-archive

**Comment by drjwbaker** [comment]
I just need to be able to push to that repo from the terminal.

**Comment by mdlincoln** [comment]
I've now made you an owner of that specific repo, rather than an owner of the whole ProgHist org

**Comment by drjwbaker** [comment]
That worked. Ta.

**Pull request merged**
