### PR TITLE
Proposal for Code of Conduct file

### LINKED ISSUE #2362: Possibility to a Code of Conduct (to take advantage of new GitHub feature)
In the same way that a `license.md` file is highlighted on the right side of a repo page, GitHub [now highights](https://twitter.com/github/status/1456635470339788803) `code_of_conduct.md`.

We have a few CoC-like docs scattered around - e.g. https://github.com/programminghistorian/jekyll/wiki#social-guidance and https://programminghistorian.org/en/author-guidelines#holding-us-to-account - so I wondered if we had the will to highlight them in a central CoC md file.

If there is no will - of suggestions otherwise - I will happily close the ticket.

### PR DESCRIPTION
**Pull request by drjwbaker**
create proposed CoC per https://github.com/programminghistorian/jekyll/issues/2362#issuecomment-962987906

Closes #2362

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Hello @drjwbaker. I've made one small adjustment, just removing an extra pair of brackets at line 7. 
Where is this .md file found on Jekyll?

Is this CoC to appear on the live site? Whereabouts? Trying to find it to check the Netlify Preview...

**Comment by drjwbaker** [comment]
It won't appear on jekkyl, just on the repo: like this https://twitter.com/github/status/1456635470339788803

**Review by anisa-hawes — APPROVED** [review]

**Comment by drjwbaker** [comment]
Per https://github.com/programminghistorian/jekyll/issues/2362 we had been waiting on translation of this (or at least @rivaquiroga expressed an interest in adding ES).

**Comment by drjwbaker** [comment]
So maybe that can be a new PR?

**Comment by anisa-hawes** [comment]
Apologies! Shall I re-open this?

**Comment by drjwbaker** [comment]
Nah. Leave it now that it is done :)

**Pull request merged**
