### PR TITLE
removed leading whitespace from custom TOC headers

### PR DESCRIPTION
**Pull request by jjon**
I think removing the leading whitespace from the TOC headers will fix it, but I'm pretty unfamiliar with all the various flavors of MD, so I'll proof the result as carefully as I can.
J

### CODE REVIEW

**Comment by mdlincoln** [comment]
You know what, we actually need to remove all the `<a name=...>` tags from the headers. The ToC include will do all the linking work for us.

**Comment by mdlincoln** [comment]
Closes #557

**Review by mdlincoln — CHANGES_REQUESTED** [review]
Remove every `<a name="..."></a>` tag

**Comment by jjon** [comment]
Such that all TOC headers in the MD read like:
```
#Creating the Dictionary
##Create a skeleton dictionary.

```
with no leading whitespace, yes?

**Comment by mdlincoln** [comment]
One space is fine: https://programminghistorian.org/lessons/getting-started-with-markdown#headings

**Comment by jjon** [comment]
Got it. Working...

**Review by mdlincoln — APPROVED** [review]

**Comment by mdlincoln** [comment]
Awesome, thanks @jjon

**Comment by jjon** [comment]
Looks like that did the trick. Thanks for your help @mdlincoln. As ever, I stand ready to help the PM project in any way I can. Don't hesitate to call on me.

**Pull request merged**
