### PR TITLE
Publish fr/lecons/demarrer-avec-omeka-classic

### LINKED ISSUE #3210: Preparing to publish a new FR translation demarrer-avec-omeka-classic
I am opening this Issue to prepare a new FR translation for publication.

### PR DESCRIPTION
**Pull request by anisa-hawes**
Preparing files for publication.

Closes #3210 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Add the appropriate "Label"
- [x] If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above
- [x] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Manager @anisa-hawes 
- [x] Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)
- [x] Assign at least one individual or team to "Reviewers"
  - ~~[ ] if the text needs to be translated, please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines), then assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR.~~

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Bonjour Marie, @marie-flesch.

I’ve staged demarrer-avec-omeka-classic for publication. You can [read it through in Preview](https://deploy-preview-3211--ph-preview.netlify.app/) and let me know if you note anything which you'd like to adjust.

If you're happy, we can publish this lesson next week when our colleagues at Sussex will be around to activate our DOI, and then we can launch the promotions on social media.

--

Thank you,
A.

**Review by marie-flesch — DISMISSED** [review]
It looks great to me!

**Comment by davvalent** [comment]
Hi @anisa-hawes and @marie-flesch,

There is a problem with Figure 11: it's the wrong one. We are supposed to see [Bertie the dog](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/images/up-and-running-with-omeka/en-or-up-and-running-11.png)!

Please have a look at the draft website: http://programminghistorian.github.io/ph-submissions/fr/en-cours/traductions/demarrer-avec-omeka-classic#une-question-%C3%A9pineuse

Regards,

David

**Comment by anisa-hawes** [comment]
Many thanks for spotting our error here, @davvalent! Sincere apologies. We made a small mistake with the image numbering where the sequence of original images and translated images overlapped. 

I've corrected this now, and have double-checked the Preview here in Jekyll against the Preview in ph-submissions.

**Review by marie-flesch — APPROVED** [review]
It looks good!

**Comment by anisa-hawes** [comment]
Thank you, @marie-flesch and @davvalent! 

Now published. I will update you both as soon as the DOI is live, then launch our social media announcements. I appreciate your patience.

**Pull request merged**
