### PR TITLE
Add archivist role to teamroles and snippets

### PR DESCRIPTION
**Pull request by drjwbaker**
add archivist role. Is this the right wording Adam?

needs translation

### CODE REVIEW

**Review by vgayolrs — COMMENTED** [review]
For the translation I opted for the unusual term of "archivista" instead of the common "archivero" looking for gender inclusion.

**Review by mdlincoln — CHANGES_REQUESTED** [review]
Fix the indentation so it matches the rest of the file. Without this, Jekyll can't understand this file.

**Comment by drjwbaker** [comment]
@mdlincoln okay. done (forgot how stupidly fussy yml can be!)

**Comment by drjwbaker** [comment]
@mdlincoln And I *think* this PR now contains the changes I'd originally made at https://github.com/programminghistorian/jekyll/pull/664 ..

**Review by mdlincoln — APPROVED** [review]

**Pull request merged**
