### PR TITLE
Update research.md

### PR DESCRIPTION
**Pull request by drjwbaker**
Added recent talk at University of Sussex. Spanish review required.

### CODE REVIEW

**Comment by acrymble** [comment]
I've also added this to /investigacion, along with some other updates to the page that had been forgotten in syncing.

**Review by arojascastro — APPROVED** [review]
It looks good to me. Thank you fro adding yourself!

**Comment by arojascastro** [comment]
Why is Travis failing at this?

**Comment by ianmilligan1** [comment]
If you click "Details" above you can see the errors. In this case it's

```
- ./_site/lessons/geoparsing-text-with-edinburgh.html
  *  External link http://englishplacenames.cerch.kcl.ac.uk failed: 404 No error
- ./_site/lessons/intro-to-augmented-reality-with-unity.html
  *  External link http://trace.english.ufl.edu/projects/arcs failed: 404 No error
- ./_site/lessons/transliterating.html
  *  External link http://www.codecademy.com/courses/css-coding-with-style failed: 404 No error
```

I think these were broken links that @mdlincoln fixed in another pull request so I think we ignore them for now.

**Comment by mdlincoln** [comment]
Correct, those links were fixed in #740.

**Pull request merged**
