### PR TITLE
Add line on Impact Manager funding

### PR DESCRIPTION
**Pull request by drjwbaker**
@spapastamkou @rivaquiroga this requires translation of the line:

> Funding to support the project "The Programming Historian: developing and sustaining impact in the Global South" provided by the [ESRC Impact Accelerator Account, University of Sussex](http://www.sussex.ac.uk/staff/research/rqi/rqi_information_and_support/rqi_impact_funding/if-esrciaa/) [2019].

### CODE REVIEW

**Comment by spapastamkou** [comment]
@mdlincoln I have a travis build fail after the FR commit bcz of a link that claims to be in a lesson ([Extracting illustrated pages](https://programminghistorian.org/en/lessons/extracting-illustrated-pages)) but that I DID replace yesterday in PR #1599 with archived link. I checked the web site and the archived link is in the lesson. 
pr-5259-travisfail

**Comment by spapastamkou** [comment]
@mdlincoln I update the branch:-)

**Review by spapastamkou — DISMISSED** [review]

**Review by rivaquiroga — APPROVED** [review]

**Comment by drjwbaker** [comment]
Thanks all for your efforts. Is this good to go? (I've not got confirmed reviews yet but it looks it..)

**Comment by drjwbaker** [comment]
I'm not totally sure why this is still open. So I'm going to merge. Shout at me if everything breaks.

**Pull request merged**
