### PR TITLE
New patrons added

### PR DESCRIPTION
**Pull request by acrymble**
We have 2 new patrons to add to the support pages, and a new 'Educator' tier at $10 per month, which I've added to each of the 4 language pages. I haven't translated that new tier name but suggest the following:

ES: "educador(a)"
FR: "éducateur/éducatrice"
PT: "educador(a)"

If the teams want to suggest alternatives, I can update the pages.

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Review by DanielAlvesLABDH — DISMISSED** [review]
Sounds good!

**Comment by jenniferisasi** [comment]
@acrymble the proposed title in ES is correct! I can approve but I think you want to make the changes in the three languages, right?

**Comment by acrymble** [comment]
@jenniferisasi yes. I have updated them now. It's a bit awkward because it means we have to guess about gendering people with these new gendered names. Not ideal long term.

**Comment by jenniferisasi** [comment]
> @jenniferisasi yes. I have updated them now. It's a bit awkward because it means we have to guess about gendering people with these new gendered names. Not ideal long term.

Yes, that will be the case, so if you want to avoid doing that I propose the following two options: 

1) Use only the terms in the sentence "En particular, agradecemos la contribución de los siguientes suscriptores de Patreon de nivel 'Mecenas' y 'Educador(a)':" and thus the genders are in the word as two options and then not put in parenthesis what each are or if in parenthesis keep the same word with both genders. 

2) Change the wording a bit (like we do when writting/translating lessons to avoid gender) and go with the noun for type not people: 
EN: "education" "subscription" "apprenticeship" "patronage" 
ES: "educación" "suscripción" "aprendizaje" "patrocinio"
FR: "éducation" "abonnement" "apprentissage" "patronage"
PT: "educação" "inscrição" "aprendizagem" "patrocínio" 

What do you think?

**Comment by acrymble** [comment]
Yes that will be better. I'll try to do that tomorrow.

**Comment by acrymble** [comment]
Thanks @jenniferisasi I've gone with your second option. Hopefully I've got it right.

**Review by DanielAlvesLABDH — CHANGES_REQUESTED** [review]
@acrymble I suggest the following translation: "Subscrição" "Aprendizagem" "Educação" "Patrocínio"

**Review by DanielAlvesLABDH — APPROVED** [review]

**Pull request merged**
