### PR TITLE
Create 2017-03-02-launch-PH-Spanish

### PR DESCRIPTION
**Pull request by mariajoafana**
Hi all, I just translated the announcement to launch the Spanish site from Spanish to English. It needs proofreading, so if anyone could take a look and suggest some edits that would be great. Thanks!

### CODE REVIEW

**Comment by acrymble** [comment]
Thanks @mariajoafana . Sorry I'm crap at Git (embarrassing really). I'll have to comment by line number because I don't know how to fix on the file itself:

line 2: "¡" is not used in English, unless you're doing that for effect, which is fine.
line 9: same as above.
line 10: for consistency, "*Programming Historian*" should be italicized.
line 10: need period after the link to the new site.
line 10: 'inaugurate' should probably be 'launch'.
line 10: cut "among others" from the end of the line.
line 12: there are more than fifty tutorials (but who's counting!)
line 12: two spaces between "English" and "PH"
line 12: you might add links to some of the lessons you mention.
line 14: "trasnlation" should be 'translation'.

Also if someone can tell me how I could have submitted suggestions to the file itself I can stop being embarrassingly inept.

**Comment by mariajoafana** [comment]
thanks a lot @acrymble ! Below my first message there's a link "Create 2017-03-02-launch-PH-Spanish ", there's how to access the file, but I'm not sure if you can see it or if only I can see it. Anyway, the feedback this way is perfect. I'll make the corrections later today. 
I think we are aiming to do the launch early next week. What do guys think? @vgayolrs @arojascastro 
I've finished the last details for the network analysis lesson today but I think we can wait before posting it in the webpage. I think is a good idea to launch the site with the Python lessons first, and then start announcing new translated lessons every once in a while.

**Comment by acrymble** [comment]
you could post the blog posts now and just not mention them until next
week. Might be interesting to see how many people notice.

**Comment by mariajoafana** [comment]
Sounds good!

**Review by mariajoafana — COMMENTED** [review]
Last changes

**Pull request merged**
