### PR TITLE
Create getting_started_with_palladio

### PR DESCRIPTION
**Pull request by wcaleb**
@miriamposner originally wrote this as a workshop, but Adam thought maybe we should publish it on PH.

### CODE REVIEW

**Comment by fredgibbs** [comment]
On the Lessons page, we should be sure to group this with the other Intro to Palladio tutorial we have, http://programminghistorian.org/lessons/creating-network-diagrams-from-historical-sources, and possibly highlight key differences at the beginnings of each lesson so readers can choose appropriately.

**Comment by miriamposner** [comment]
Yeah. The other lesson is really about network analysis for historical
research. It does use Palladio, but only for its NA capabilities. This
lesson is really about Palladio in general, and how to use it to get to
know and understand a dataset.

**Comment by acrymble** [comment]
Thanks @miriamposner I will take on the role of editor for this. In the first instance, I'll have a read through and try the lesson, and then I'll find a couple of reviewers to try it as well and I will facilitate that conversation to ensure that it remains productive and timely. I'll also make sure we've got a clear delineation between this and the other Palladio tutorial, but it sounds like you've already considered that.

It's end of term here, but I'll do my best to get on this quickly.

As you know, you can always turn to @ianmilligan1 if you feel there's a need for an ombudsperson to step in.

Looking forward to working with you.

**Comment by miriamposner** [comment]
Thanks, @acrymble! Do you want the images as well? They might help to
show what's going on, but I wasn't sure how to get them uploaded at this
stage.

**Comment by acrymble** [comment]
I can look at them on your blog for now, I presume?

If not, then yes that would be helpful.

Adam

**Comment by acrymble** [comment]
@wcaleb do we get a preview automatically, or do I have to do something to generate it on Heroku?

**Comment by acrymble** [comment]
Thanks for this submission @miriamposner. This looks like an excellent workshop-style lesson, which I think will be very useful, and I hope to try it out with my own students. I've had a read through and tried it out, and I've got a few points I'd like to suggest/discuss before I send it to some reviwers for testing.

Starting with the easy bits.

You have a typo: 'Description from Slide Note' should read 'Description from Slide Mount'

Minor bug: The timeline feature doesn't work in Firefox on Mac. Nothing we can do about that, but if you could flag that for people that would be helpful.

Not sure if bug: When you load the gallery feature, if you havn't set your categories to load the image, clicking on the spot where the image should have been sent me back to the Palladio homepage, and I lost my work. A warning there might be a good idea.

Usability point: You mention a lot of tools, especially in the intro. Can you link out to these please? Likewise, there are a couple of relevant PH lessons that it would be good to point out to readers. Especially:
- http://programminghistorian.org/lessons/cleaning-data-with-openrefine
- http://programminghistorian.org/lessons/creating-network-diagrams-from-historical-sources

Thinking about potential problems: can you make a comment on data types and cleaning data before Palladio? I imagine some people won't know that a computer requires 'dates' in a certain format, or that 'text' or 'georeferences' also have to follow certain rules. For example, if one of your dates was formatted incorrectly, what would happen to Palladio? How do I know if my data is ready?

---

1) More generally, I think it would be really helpful for students and historians if the lesson emphasised the way that this tool lets you get to know your sets of structured, digital, historical sources (as you note in the comment above), and maybe learn something about those sources that's difficult to do when staring at a spreadsheet. A paragraph to start off along the lines of 'who is this useful for?' that thinks of the audience as a historian who works with 'sources' rather than a DHer who thinks in terms of 'data' would be a good way to increase the accessibility of the lesson and to broaden the audience. A change in the title would probably help with that shift in emphasis. Maybe something like: getting to know geo-temporal datasets using Palladio? Open to ideas, of course.

2) You've given us a really rich dataset here, which is a fantastic choice for this tool. But we don't really take the time to get to know it, or to know what a tool like this might help us discover. What do you think about spoiling the lesson and showing us what we're going to find right away, to hook the reader into finding out how to make that discovery?

3) It might also be helpful to give us a pared-down version of the data (which we should store with the lesson in case the dropbox version disappears). You've got a lot of columns that don't come into the lesson, some of which have fairly ambiguous column titles that aren't immediately obvious to a person who hasn't used this dataset before. Would it be easier for a new user if they were just removed before we got going? That way you could send them into the csv file before jumping into Palladio. That way they act as a historian: getting to see what they can understand, before moving to the digital tool to see how that makes things easier/different. That might help them know if their own data is a good fit and therefore if they want to keep reading.

4) The sections are great and your examples are awesome. I think I would have found it helpful for you to have your historians' hat on a bit more throughout, telling us WHY we're choosing certain facets or choices for the various categories so that I understand them well enough to use them on my own data. But also interpreting what we're finding with this that makes this experience worthwhile. Can you help us discover something within the data that we wouldn't otherwise find? Give us that eureka! moment? I'm thinking of a group of students here, but I think it would be really awesome to send them in to explore the dataset in Excel, ask them what they can find, and then have a series of meaningful historical discoveries that emerge as if by magic through each of the various tools (map, timeline, facets, gallery, etc). That might be tricky, but let me know what you think.

I hope that's helpful as a starting point for a conversation. This looks like a great tool that I hadn't used before, and I plan to try this lesson out with my students. So please let me know your thoughts on these areas. From what I see, it looks like a bit of flushing out rather than major changes, are what would make this a really fantastic piece.

**Comment by wcaleb** [comment]
@acrymble I'm going to have to look into this further. Heroku is saying we only get five free preview apps, and we're using all of our free allotment right now ...

**Comment by miriamposner** [comment]
Hi @acrymble! These are all fantastic suggestions and I think they would
strengthen the tutorial a lot. I am going to get as much as I can done
tonight, as Dora seems pretty happy jumping around pretending to be a
chicken.

On Sat, Dec 5, 2015 at 11:18 AM, W. Caleb McDaniel <notifications@github.com

**Comment by acrymble** [comment]
Will reopen if I hear from author.

**Pull request closed without merging**
