### PR TITLE
Add table-wrapper to style CSS

### PR DESCRIPTION
**Pull request by jenniferisasi**
inside Tables section to add a scroll thingy for wide tables that are "cut"

Following @spapastamkou issue on #2503 while formatting a new lesson that has a wide table (long to the side) and was not displaying without a scroll. 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] ~~if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description~~
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by jenniferisasi** [comment]
🤔 now how do I check if it worked...

**Comment by spapastamkou** [comment]
@jenniferisasi I will check if it works by reinserting in the lesson the html div that I took away after I had seen it did not work (without at the time the intervention in the the CSS you just did). Once this pull request is ok, but I see it is this link that provokes the fail: https://joedicastro.com/pages/markdown.html 
By the way, I see the other links in the build fail are very explicit on Ukraine!

**Comment by spapastamkou** [comment]
of course, you are already fixing the broken link:-)

**Comment by jenniferisasi** [comment]
> By the way, I see the other links in the build fail are very explicit on Ukraine!

:O what. I had not gotten to those links yet... Hmm I am going to consult on what to do about them; moving the link temporarily [here](https://leafletjs.com/SlavaUkraini/) is an option.

**Comment by spapastamkou** [comment]
it might be fixed after a while without doing anything. maybe it is a gentle reminder:-)

**Comment by ZoeLeBlanc** [comment]
I think we should just update the links since it seems that this invasion won't be over soon and we'll likely have other PRs in the next few weeks 

this is the two links and I'm happy to do the changes or if someone already has this branch locally, feel free to take the lead
https://leafletjs.com/SlavaUkraini/plugins.html
https://leafletjs.com/SlavaUkraini/reference.html

let me know if there's anything else I can help with, and thanks for all your hard work 👏🏽

**Comment by anisa-hawes** [comment]
Hello @jenniferisasi and @spapastamkou. 

Do you think we should temporarily update the links in /en/lessons/mapping-with-python-leaflet

from http://leafletjs.com/plugins.html -> https://leafletjs.com/SlavaUkraini/plugins.html
from http://leafletjs.com/reference.html -> https://leafletjs.com/SlavaUkraini/reference.html

?

**Comment by anisa-hawes** [comment]
Ah! Just seeing your comment, @ZoeLeBlanc! I can update the links!

**Review by anisa-hawes — APPROVED** [review]

**Pull request merged**
