### PR TITLE
Display multiple ISSN on footer

### LINKED ISSUE #555: ISSN in footer
Our ISSN is no longer present on the home page. This is strongly recommended by the ISSN guidelines (http://www.issn.org/understanding-the-issn/assignment-rules/the-issn-for-electronic-media/). I suggest the most useful and least obtrusive place to put that is in the footer.

To avoid any design issues, I propose we just swap out the 'Hosted by Github' bit. I don't think we need to advertise for a private company.

### PR DESCRIPTION
**Pull request by mdlincoln**
Closes #555 

@programminghistorian/spanish-team now that there is a distinct ISSN for The Programming Historian en español, `es/acerca-de.md` should be updated to include the new ISSN using the snippets. Take a look at the change I made to `en/about.md`. Also, @drjwbaker can you confirm that the Spanish about page points to the right page in DOAJ re: #897 ?

### CODE REVIEW

**Review by arojascastro — DISMISSED** [review]
Many thanks

**Review by drjwbaker — DISMISSED** [review]
Correct :)

**Comment by acrymble** [comment]
@mdlincoln can you clarify what exactly needs updating on /es/acerca.md so that someone can be confident about the change?

**Comment by mdlincoln** [comment]
I fixed it myself. This just needs a passing review now.

**Review by acrymble — APPROVED** [review]
This looks fine.

**Pull request merged**
