### PR TITLE
Moving files for Working with Batches of PDFs

### PR DESCRIPTION
**Pull request by svmelton**

### CODE REVIEW

**Comment by svmelton** [comment]
Hey @programminghistorian/technical-team! I got this error on the build and I'm not sure what went wrong: `comparison of Array with Array failed in feed.xml`

**Comment by mdlincoln** [comment]
Just a guess, but try setting your date format to YYYY-MM-DD

**Comment by jenniferisasi** [comment]
The first link in this sentence in Extracting Illustrated Pages is broken

> requests (Install docs) [creator recommends pipenv installation; for pip install see PyPI]
https://2.python-requests.org//en/master/user/install/

Could [this](https://pypi.org/project/requests/) be the correct dependency now? Unfortunately I don't know Python to help with it. 

I think the error can be overrode (??) until the link is fixed, but I don't have the permission to do it.

**Comment by walshbr** [comment]
That's correct @jenniferisasi! Pushed the change and it should be good for merging now.

**Review by mdlincoln — APPROVED** [review]

**Pull request merged**
