### PR TITLE
Adjust IPP offer

### LINKED ISSUE #1732: Institutional Partner Programme in a time of crisis
This ticket is breaking off from a discussion on a gdoc @jenniferisasi kindly put together that will form the basis of our comms to libraries/institutions 'advertising' our IPP.

@walshbr & @svmelton are of the opinion that we give a little more back in return than what we currently have listed at https://programminghistorian.org/en/support-us#institutional-partner-programme

We previously (though I can't find the tickets) avoided making too many promises in return for Patreon or IPP £, but given this time of crisis, I suspect we might revisit that.

One option which I like, to borrow/adapt from @walshbr, is to have some kind of regular community calls (either themed or as no agenda 'office hours') where one of our team offers support to IPP members: e.g. tips on how to adapt our materials to develop a workshop, advise on OA publishing, gather ideas about articles people need, et cetera.

I suspect there is a way of doing that that is:

- low effort.
- gives something tangible back to IPP members.
- helps us learn from our community.
- develops our offer.
- is creative, enjoyable, and fun without us straying too far into things we don't really want to do right now (troubleshooting articles, giving out loads of free advice, becoming a training provider)

Thoughts?

### PR DESCRIPTION
**Pull request by drjwbaker**
Add l48, per discussion at #1732.

FR @spapastamkou and ES @rivaquiroga translation required for the line..

> Want advice on running an open access publication, implementing multilingual publishing workflows, or adapting _Programming Historian_ articles for a workshop environment? Your IPP membership gives you access to ad hoc advice from our expert team (on request, not including formal consultancy).

..though there is no hurry on this.

Closes #1732

### CODE REVIEW

**Comment by drjwbaker** [comment]
@programminghistorian/technical-team For this PR and https://github.com/programminghistorian/jekyll/pull/1733 I had to manually rerun the Travis check to make the build pass (I didn't change anything, just went in to rerun and it passed). Is this now the normal process (and I missed the memo!) or is something amiss?

**Comment by mdlincoln** [comment]
Not having seen why the first check didn't pass, I can't tell you what changed. If it was a 404 on a link, it may have been that the link was temporarily down but went back up in between builds.

**Comment by walshbr** [comment]
It was a 404 - http://jairomelo.com/tutoriales/ayuda/script-iniciar-xampp-ubuntu - from this page -  https://deploy-preview-1734--ph-preview.netlify.com/es/lecciones/construir-repositorio-de-fuentes.

**Comment by walshbr** [comment]
FWIW that link is also down now, so it's probably going in and out and you happened to re-run the checks when it was up?

**Review by mdlincoln — CHANGES_REQUESTED** [review]
@drjwbaker replace that unreliable link.

**Comment by drjwbaker** [comment]
Sorry, I don't understand how to find that link because I did not add that link, and it isn't on the page I am editing.

**Comment by mdlincoln** [comment]
@drjwbaker here are the lines showing the offending file and link from the old errored build that @walshbr mentioned: https://travis-ci.com/github/programminghistorian/jekyll/builds/159546250#L466-L467

**Comment by rivaquiroga** [comment]
@drjwbaker, I'll contact the author of the lesson with the problematic link (it's from his own webpage). We published that lesson last week and the link was working, so maybe he changed something

**Comment by mdlincoln** [comment]
@rivaquiroga I wouldn't make this complicated - just use the wayback machine and be done with it.

**Comment by drjwbaker** [comment]
> @drjwbaker here are the lines showing the offending file and link from the old errored build that @walshbr mentioned: https://travis-ci.com/github/programminghistorian/jekyll/builds/159546250#L466-L467

For future reference (so I don't have to both y'all) how did you find that errored build? (now the checks of passed, I can't see where I find the one that failed)

And @mdlincoln, sadly, waybackmachine doesn't have a copy of https://jairomelo.github.io/tutoriales/ayuda/script-iniciar-xampp-ubuntu

**Comment by walshbr** [comment]
@drjwbaker - if you click around in travis you can go from the current build to a build history log that will show you previous builds. So I clicked through until I found the one with an X by it for this pull request. Screenshots attached might help.  First I clicked on details next to travis. Then on "the build" link to go to the current build.  Then on "pull requests" because this is a pull request build. Then I clicked on the one with an x. Hope that helps!


=

Screen Shot 2020-04-10 at 11 55 39 AM
=
Screen Shot 2020-04-10 at 11 55 44 AM
=
Screen Shot 2020-04-10 at 11 58 13 AM
=
Screen Shot 2020-04-10 at 11 55 59 AM

**Review by rivaquiroga — DISMISSED** [review]

**Review by spapastamkou — APPROVED** [review]

**Comment by mdlincoln** [comment]
@walshbr thanks very much for providing that documentation, and sorry @drjwbaker that Travis/Github has recently modified their interface just a bit so our docs are slightly out of date. I've opened #1735 to update our wiki to reflect this.

**Review by mdlincoln — APPROVED** [review]

**Comment by mdlincoln** [comment]
Also a reminder @drjwbaker - please do not delete the default text that shows up when you open the PR. This is a useful checklist that would have contained the link to our documentation on how to address this problem.

**Comment by drjwbaker** [comment]
> Also a reminder @drjwbaker - please do not delete the default text that shows up when you open the PR. This is a useful checklist that would have contained the link to our documentation on how to address this problem.

Yeah. Apologies. Bad habit.

**Comment by drjwbaker** [comment]
@rivaquiroga Can I just double check that you are happy before I merge please. Thanks.

**Review by rivaquiroga — APPROVED** [review]

**Comment by rivaquiroga** [comment]
I approved it on Friday, but my approval was dismissed because changes (the FR translation) were made afterwards.

**Comment by drjwbaker** [comment]
> I approved it on Friday, but my approval was dismissed because changes (the FR translation) were made afterwards.

Ah okay. Still getting used to the 'stale review' thing :)

**Pull request merged**
