### PR TITLE
Issue 2986

### LINKED ISSUE #2986: Preparing publication of new EN lesson
I am preparing files for publication of the final original lesson in our Jisc/TNA series.

### PR DESCRIPTION
**Pull request by anisa-hawes**
Preparing files for publication on behalf of AWC who is both ME and Ed. of this lesson.

Closes #2986

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Add the appropriate "Label"
- [x] If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above
- [x] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Assistant @anisa-hawes 
- [x] Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] ~~if the text needs to be translated, please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines), then assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR.~~

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Dear @hawc2,

You will note that I have created a Zenodo deposit of the accompanying dataset. Our brilliant colleagues at University of Sussex Library helped me to generate the necessary XML and have assigned the dataset with a DOI. You will find this at line 245 of the `.md` file: <https://doi.org/10.46430/phen0112>.

If you agree, one final thing I would suggest is that we copy the `.ipynb` linked at line 148 and upload this to our PH Colab repository and save it to /assets here on Jekyll. This will empower us to manage and support future translation or maintenance work which may be required. 

Update: I've done this in ph-submissions [/assets/clustering-visualizing-word-embeddings/clustering-visualizing-word-embeddings.ipynb](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/assets/clustering-visualizing-word-embeddings/clustering-visualizing-word-embeddings.ipynb) and it seems good. If you agree with me that this is a useful step, I can upload the asset here in Jekyll too and adjust the various links to it throughout the lesson.

**Comment by hawc2** [comment]
Thanks @anisa-hawes for setting this all up! Yes that sounds good about the Jupyter Notebook. Once that's ready, I'll review everything.

**Comment by jreades** [comment]
I just clicked on the DOI link for the data: you’ve accidentally hoovered up a bunch of additional teaching data that has nothing to do with the tutorial. 

The only two files associated with this lesson are:
 ph-tutorial-data-cleaned.csv.gz 24.3 MB
 ph-tutorial-data-cleaned.parquet 27.0 MB
 The parquet file is the one used by the notebook, the CSV is there for people who don’t/can’t use the parquet file. 
 
So it’s not a 700MB download. Max should be about 45MB if you combine them both. But you might prefer to have the DOI point directly to the parquet file with the notebook having an additional DOI for a zip containing both or the CSV separately.

**Comment by anisa-hawes** [comment]
Thank you for this clarification, @jreades. Apologies for my misunderstanding. I captured all the files shown here: <http://orca.casa.ucl.ac.uk/~jreades/data/>. I'll remove the files that aren't required and update you later today.

**Comment by jreades** [comment]
Sorry, I had mentioned this in the comments but didn’t think to put those files in their own directory (that’s a drop folder for a bunch of temporary teaching data) so can see how that was confusing in retrospect.

**Comment by anisa-hawes** [comment]
Thank you for your understanding, @jreades. I've edited the deposit on Zenodo, so the contents is now just those two files: https://doi.org/10.46430/phen0112. 

@hawc2, Please see [Jonathan's comment above](https://github.com/programminghistorian/jekyll/pull/2987#issuecomment-1655125861) re: the data. I leave it up to you to decide, but I think it keeps things simple if we have one DOI and both files together in a `.zip`.

**Comment by hawc2** [comment]
It seems like we can keep one DOI for the whole asset package. From what I understand, the Parquet file is the preferred dataset, and the CSV is a backup, but they both connect to the same Jupyter Notebook for the same lesson. As long as that's the case, let's just keep it to one data/notebook DOI per published lesson

**Comment by hawc2** [comment]
@jreades We aim to publish this lesson next week. Please take a look over this preview this week to make sure everything looks fine to you: https://deploy-preview-2987--ph-preview.netlify.app/en/lessons/clustering-visualizing-word-embeddings

**Comment by hawc2** [comment]
One thought @jreades is we could simplify the abstract a bit, if you look at other examples you'll see they're usually pretty brief

**Comment by jreades** [comment]
I will try to look at this tomorrow when j back from holiday — also, I noticed Jennie’s ORCID is missing. I we look it up.

**Comment by jreades** [comment]
On the abstract, how about:

~~~~~~~~~~
This lesson uses word embeddings and clustering to identify groups of similar documents in a corpus of 8,000 academic abstracts.
~~~~~~~~~~

And Jennie’s ORCID is: 0000-0002-0720-9523 and should be added to the tutorial.

I think that’s it!

Jon

**Comment by hawc2** [comment]
That works, I might keep a shortened second sentence from the original as well. We'll publish this lesson by the end of the week at the latest!

**Comment by hawc2** [comment]
@anisa-hawes for linking the Colab notebook, we should either link directly to the Colab notebook itself, or to the Github page where the Jupyter Notebook is hosted. You'll see if you try the link for Colab (linked in two places) it tries to open the actual Jupyter Notebook in the browser, which doesn't render correctly, and doesn't provide a link to Colab. I hope that's clear, for future lessons with Colab notebooks

**Comment by hawc2** [comment]
@anisa-hawes Also I should point out that @jreades does still link to some external assets for this lesson hosted on his github page. They're mentioned in the Required Libraries section, and they relate to a Dockerized version of the lesson, which seems to me divergent enough of a way of following along with this lesson that it's ok we don't host these assets in the ProgHist repo. But if you prefer, we could do that

**Comment by anisa-hawes** [comment]
Hello @hawc2. 

I’ve experimented with adjusting the links at lines 150, 159, 379, 711, 819  in multiple ways but, indeed, the build requires it to be a ‘relative link’ beginning with the path /assets. That is how we usually link to assets. I’m unclear why it doesn’t open the GitHub page where the `.ipynb` is hosted in this case but ~~wonder if it may work as we expect it to once the lesson is published?~~ – I will ask for more advice on this.  [Nope]

You mention that Jon links to notes on using Docker hosted on his GitHub repo. I think you are referring to line 150 which reads:

_A [Docker](https://www.docker.com/) image is also available and instructions for using it can be found [on GitHub](https://perma.cc/3JN9-JZN2)._  I archived this link, so that the instructions remain available. Which asset(s) do you think we could host? I'm unclear on how the Docker image interacts with the Colab notebook, so I welcome your advice.

**Comment by anisa-hawes** [comment]
**Note:** The build  check is failing here due to a broken link elsewhere on our website. That is in the process of being fixed #3000. When it is complete, I'll rebase this PR.

**Comment by hawc2** [comment]
@anisa-hawes it might be worth publishing the lesson and retroactively fixing the asset links if they end up not working right. 

@jreades can you clarify the role of the Docker image here? We could host all those files in the PH repository so you don't need to permanently keep them on your personal Github. Does that seem fine to you?

**Comment by anisa-hawes** [comment]
Hello @hawc2. I have been chatting with Riva and trying to better understand what is happening here. 

After publication we need this link to direct to <https://github.com/programminghistorian/jekyll/blob/gh-pages/assets/clustering-visualizing-word-embeddings/clustering-visualizing-word-embeddings.ipynb>.

When I try formating this as a relative link (following our usual practice /assets/clustering-visualizing-word-embeddings/clustering-visualizing-word-embeddings.ipynb) the file displays as raw data.

When I use the full link, the build checks fail with the error message:

`It looks this page contains a full link to data in one of our GitHub repositories. Do not link to GitHub for data. Instead, please use a relative path starting with /`

Riva suggested (and I agree) that if we are going to host notebooks in this way, we will need to adapt our build check rules about how we link to internal assets. We could stipulate an exception to the rules for any file ending in `.ipynb`.

It will require a small change to our `build.yml` file. 

Opening an Issue to investigate this #3001.

**Comment by hawc2** [comment]
I see that makes sense

**Comment by anisa-hawes** [comment]
Hello @hawc2. 

With Zoe and Riva's help, we've found a good solution (#3001) which doesn't involve updating our `build.yml` or our `validate_yaml.rb`. 

We will host the `.ipynb` in our /assets directory (#3004) but use Jupyter's nbviewer to render the notebook: https://nbviewer.org/github/programminghistorian/jekyll/blob/gh-pages/assets/clustering-visualizing-word-embeddings/clustering-visualizing-word-embeddings.ipynb. I've updated the links in this lesson's Markdown.

Please let me know if any further changes are needed for the Docker instructions/link. Otherwise, I think this is ready to merge.

**Comment by hawc2** [comment]
Great, looks good. Go ahead and merge @anisa-hawes 

We'll deal with the Docker files after publication?

**Comment by anisa-hawes** [comment]
Thank you, @hawc2. 

I remain unclear how the Docker image interacts with the Colab notebook, and [which of the files here](https://github.com/jreades/ph-tutorial-code/tree/main/docker) would be hosted. 

I notice that there is only one sentence within the lesson which mentions Docker, (“A [Docker](https://www.docker.com/) image is also available and instructions for using it can be found [on GitHub](https://perma.cc/3JN9-JZN2)”). I'm afraid I don’t have any knowledge about this approach, or what the benefits would be to working with Docker in this context.

One of the problems I foresee is that it would be challenging for us to assist readers with troubleshooting the steps outlined in the Readme. (Did the reviewers test this Docker workflow?)

I'd like to suggest that we put the sentence (“A [Docker](https://www.docker.com/) image is also available and instructions for using it can be found [on GitHub](https://perma.cc/3JN9-JZN2)”) into parentheses or an endnote. As we are sharing the `.ipynb`, readers will be able to work within whichever environment they wish. The lesson is guiding them through the steps of one approach in detail but not every approach. Parentheses or an endnote would clarify that this secondary resource / alternative approach is supplementary to the lesson we've published (reviewed, tested and copyedited).

**Comment by hawc2** [comment]
@anisa-hawes an endnote seems like a good solution to me.

@jreades it might help to update the Readme of your Github repo with a little more of an explanation of how it is connected to the code introduced in the PH lesson. We're essentially treating the Docker option as a secondary resource, at the moment though neither the lesson or the secondary resource spell out their connection very clearly.

**Comment by anisa-hawes** [comment]
Thank you, @hawc2. I've made that adjustment: https://github.com/programminghistorian/jekyll/pull/2987/commits/36ae2fa513d031d4dae12c4634046ff70329a588

**Comment by hawc2** [comment]
Looks great to me, thanks @anisa-hawes for setting up this new way for PH to host/link Juptyer Notebooks! 

@jreades We're going to go ahead and publish the  lesson and close this pullrequest, we can follow up via email or on the main Github issue if you have any further thoughts or comments.

**Review by hawc2 — DISMISSED** [review]

**Comment by anisa-hawes** [comment]
I've made a final tweak to the abstract and also added Python as one of the `topics:` to help readers find this lesson in our directory.

**Review by hawc2 — APPROVED** [review]

**Comment by jreades** [comment]
Cool. Per @hawc2's request I am just updating the tutorial repo that holds the code to provide a bit more detail on how the parts fit together.

**Comment by hawc2** [comment]
Thanks @jreades, congrats on publishing your lesson!

**Pull request merged**
