### PR TITLE
Added Getting Started with Markdown lesson.

### PR DESCRIPTION
**Pull request by ghost**
First go at beginner Markdown lesson -- suggestions welcomed. Any ideas for wrapping it up better are especially appreciated.

### CODE REVIEW

**Comment by wcaleb** [comment]
Are we ready to add this lesson? Just noticing we never merged the pull request. @williamjturkel @acrymble

**Comment by ssimpkin** [comment]
Close, not quite! I'm having a colleague read through and zest up the content a bit. Still feel it could use some tweaking.

**Comment by ianmilligan1** [comment]
Just pinging as I see this is still outstanding: how are things going, @ssimpkin? I think this'll be a fantastic addition for historians (especially those who want to write for Programming Historian!).

**Comment by jbfink** [comment]
Don't blame @ssimpkin on this one, I've fallen down on looking at the dang thing and she asked me like twenty years ago. Am going to do it today.

**Comment by wcaleb** [comment]
This has been added to the [Lesson Pipeline](https://github.com/programminghistorian/jekyll/wiki/Lesson-Pipeline) wiki.

**Comment by ianmilligan1** [comment]
Just checking in again like the gadfly that I am. How go things?

**Comment by ghost** [comment]
They go! John had a look over [here](https://github.com/jbfink/getting-started-with-markdown/blob/master/getting-started-with-markdown.md) and the biggest change was a switch over to another browser-based md editor. I'm happy with it as a public intro, but feel that the wiki "instructions for authors" page is better suited for teaching people the ropes as lesson contributors.

**Comment by ianmilligan1** [comment]
Thanks @ssimpkin! While there's overlap with the wiki 'instructions for authors' page, I still think there's value to having it as a lesson - there'd be folks who want to write in Markdown who would never think of looking at our contribute page (and it's a great, simple overview). 

Other editorial thoughts?

**Comment by miriamposner** [comment]
Agreed!

**Comment by fredgibbs** [comment]
me too--i think the authors page is about our process and doesn't offer
much in the way of markdown, which we require. so it's super helpful.

a possible addition to the lesson would be a concluding paragraph or so
about the process of writing a markdown file (like a PH lesson) in a basic
text editor, knowing that all the formatting will show up eventually, and
that getting used to the idea of not actually seeing the formatting--but
rather the syntax for it--takes a little time but is super useful. this
makes the files highly portable (not just over time, but across different
platforms and editorial workflows!).

the one other addition i would like, but isn't necessarily essential, is to
have more consistent visualization of the rendering of markdown in the
tutorial itself so that users can skim through the lesson and easily see
what markdown produces when rendered or converted into something else like
HTML. it appears in some places, but not in a standardized way or evenly
across the examples. i think smoothing this out would make the lesson more
useful for those just skimming through to understand what markdown is, and
also even more useful for readers who sit down and go through the whole
thing and want to easily associate the syntax with a typographical style
they are used to. obviously the markdown renderer does this, but i think
there's real value in having it in the lesson itself as well. (the renderer
could be used for other things in the lesson, too, like instructing the
reader to take a raw .md file from the PH repository and paste it into the
renderer to see what happens...)

but it's going to be really great to have this on the lesson page!

On Tue, Aug 25, 2015 at 10:20 AM, Miriam Posner notifications@github.com
wrote:

> Agreed!
> 
> On Tue, Aug 25, 2015 at 11:26 AM, Ian Milligan notifications@github.com
> wrote:
> 
> > Thanks @ssimpkin https://github.com/ssimpkin! While there's overlap
> > with the wiki 'instructions for authors' page, I still think there's
> > value
> > to having it as a lesson - there'd be folks who want to write in Markdown
> > who would never think of looking at our contribute page (and it's a
> > great,
> > simple overview).
> > 
> > Other editorial thoughts?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/programminghistorian/jekyll/pull/61#issuecomment-134625866
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/programminghistorian/jekyll/pull/61#issuecomment-134657651
> .

## 

frederick w gibbs | assistant professor of history | univ. of new mexico
fredgibbs.net | @fredgibbs
http://www.twitter.com/fredgibbs

**Comment by wcaleb** [comment]
This lesson seems to me like it's ready to merge. Unless I'm mistaken, I think it's already been reviewed, and revisions have been made. It all looks good to me!

**Comment by ianmilligan1** [comment]
Ah, I missed the little commit hidden there. I think it looks ready to go! What do you think, @ssimpkin?

**Comment by ghost** [comment]
Sending it off to another colleague for a quick look, then it's just a
matter of adding the reviewers' names. Will wrap it up by the end of the
week. Excited to get it out there!

**Comment by acrymble** [comment]
@ianmilligan1 I don't think anyone is posting this. Can you manage it?

**Comment by ianmilligan1** [comment]
Where do we find our images (i.e. do we have a central repository of our images, or do we just randomly find them on the Web and make sure we've got the rights)? I'm at a conference all week but can probably find some time.

**Comment by acrymble** [comment]
Instructions here: https://github.com/programminghistorian/jekyll/wiki/Lesson-Images

But I can't figure out how to actually upload the image to the site. If you figure that out, let me know.

**Comment by ianmilligan1** [comment]
Sure, I can do that - wanna just shoot me it via e-mail? if you give me a good shortcut to downsize an image to 200 x 200 - any online platform that you use? My Photoshop is borked.

(am at a conference so there's a chance I might disappear until tomorrow at any point)

**Comment by ianmilligan1** [comment]
Nevermind, just found the world's sketchiest photo resizer site and used it. If you shoot me the image, I'll upload them together.

**Comment by ianmilligan1** [comment]
It also occurs to me - what section should this go into? Data Manipulation is the closest current fit, but it's not a great one. Any offhand thoughts, @acrymble?

**Comment by acrymble** [comment]
Data Management, no? But the title is awkward. It's about formats for best
practices.

**Comment by acrymble** [comment]
Maybe we need a new category.

**Comment by ianmilligan1** [comment]
I figure Data Management is OK for now, but we should think about a new category?

In any case, it's LIVE!!! Hurray. Both on http://programminghistorian.org/lessons/ and http://programminghistorian.org/lessons/getting-started-with-markdown. 

Can we start the publicity engine? :grinning:

**Comment by ghost** [comment]
Oh hey, awesome! Looks like it's under "Data Manipulation" instead of "Data
Management", though.

I'll send along a little bio blurb shortly.

Thanks again for all of your patience and suggestions. It was fun!

**Comment by ianmilligan1** [comment]
Sorry @ssimpkin, fixed in the last commit. And yes, please send along a bio - probably easiest is to just [e-mail it to me](mailto:i2millig@uwaterloo.ca).

**Comment by ianmilligan1** [comment]
As per #119, pinging @miriamposner to let her know that this post is up. @acrymble's "Extracting Keywords" is up too. A banner day!

**Comment by miriamposner** [comment]
Gah, somehow I didn't see this! I will tweet up a storm tomorrow. Congrats, @ssimpkin and @acrymble!

**Pull request merged**
