### PR TITLE
Update feedback.md

### LINKED ISSUE #2203: Updating feedback.md
I am updating the options for leaving feedback/reporting bugs, reflecting revisions to our Lesson Maintenance Workflow.

### PR DESCRIPTION
**Pull request by anisa-hawes**
I am updating the options for leaving feedback/reporting bugs, reflecting revisions to our Lesson Maintenance Workflow. Closes #2203. 

I have also suggested minor grammatical adjustments to the existing text.

Dear Es, FR, and PT teams,

May I ask for your help to translate the following paragraph into Spanish, French and Portuguese?:

`en/feedback.md`

## Option 1: Email

Send an email to our [Publishing Assistant](mailto:anisa.hawes@icloud.com).

Please include the following information in your message:

- The full title of the lesson
- The system you are using (Mac, Linux, Windows)
- Version numbers of the relevant software you are using
- The exact steps you took that caused the problem

## Option 2: Open an Issue on GitHub

First, [sign up for a free, personal GitHub account](https://help.github.com/articles/signing-up-for-a-new-github-account) if you don't already have one. Log in if you already have an account.

Then, go to the [issues page](https://github.com/programminghistorian/jekyll/issues?state=open) of our Repository.

Create a new issue with a descriptive title and complete as much information as you can, following the prompts we provide.

For more information about GitHub issues, read the GitHub Guide on [Mastering Issues](https://guides.github.com/features/issues/).

If you believe you know how to fix the problem in the lesson, you may wish to consider forking our repository and making a pull request.

For more information about pull requests, see the GitHub Guide on [Forking Projects](https://guides.github.com/activities/forking/) or Rich Jones's tutorial on [How to GitHub](https://gun.io/blog/how-to-github-fork-branch-and-pull-request/).

## Further Resources on Git and GitHub

Using Git and GitHub can be fairly simple once you get the hang of it.  If you are interested in learning more and contributing, the [GitHub](https://help.github.com/articles/good-resources-for-learning-git-and-github/) website is a great place to start.

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Hello @acrymble. Maybe you could help me with this next week? I'd like to understand what has caused the build check to fail here...

I haven't assigned reviewers yet, as I wanted to make sure everything worked first!

**Comment by acrymble** [comment]
Sure @Anisa-ProgHist. The problem is links in other parts of the site have stopped working.

You can click on the "Details" link next to the failed build to get more information. In this case it's flagging 2 links on pages you weren't working on at all that return 404 errors. Those may be temporary or permanent. There's no way to know.

This is something we may want to raise with the @programminghistorian/technical-team as broken links are increasingly preventing us from merging pull requests. A monthly full-site link check is probably a much better use of everyone's time.

**Comment by walshbr** [comment]
FWIW, we already do that - links are only checked once a month. https://github.com/programminghistorian/jekyll/blob/gh-pages/_build/build.sh. It's set on line 10 of that file. But each individual link has its own 30 day timer for whether or not it needs to be checked - it gets checked and then logged as something that is checked until 30 days pass. I'm not sure if there's a way to globally delay the checker as a whole, but you could expand the range of days a link is cached for beyond 30 days.

**Comment by walshbr** [comment]
You can see the checker looking at the cached links vs active links to check in that same log under "details" - it's this part -
Adding 2549 links to the cache...
Removing 0 links from the cache...
Checking 2549 external links...
Adding 619 links to the cache...
Removing 0 links from the cache...
Found 619 internal links in the cache...
Ran on 453 files!

But I agree it makes sense to expand that length of caching.

**Comment by anisa-hawes** [comment]
Thank you for the info @walshbr. What do you think is the best way to move forwards with closing this Issue?

**Comment by walshbr** [comment]
@Anisa-ProgHist - the things to do for this ticket would be - 

1) Fix the broken links (we usually operate on a "if you find them you fix them" policy) and push the changes to the pull request.

or

2) If we know the links are already fixed elsewhere, but the branch is behind, we need to update this branch. The instructions to do that from the terminal are always (mostly) at the bottom of the pull request - the part that says "You can also open this in GitHub Desktop or view command line instructions." If you click "view command line instructions" you get two steps. You only step one. In this case, that's:

```
git fetch origin
git checkout -b Issue-\#2203 origin/Issue-\#2203
git merge gh-pages
git push
```

The first three lines are automatically put at the bottom of each ticket, and they  check the branch out locally and update it  with the latest changes. The last git push line is the only missing step - that updates your pull request. You don't want to add in step two, because that would actually merge your pull request itself into our main branch. That's what the tech team does when updating the stale branches. Anyone who's used to working with the command line can do it though!

I did it here, so you should be good for merging it. You'll need to mark it "ready for review" in order to get it  reviewed though.

**Comment by DanielAlvesLABDH** [comment]
Dear Anisa, here ia the translation to Portuguese. Best 
"Envie um email para o/a nosso/a Assistente de Publicação.

Inclua as seguintes informações na sua mensagem:

     O título completo da lição
     O sistema que está a usar (Mac, Linux, Windows)
     Números da versão do software relevante que está a usar
     As etapas exatas que executou e que causaram o problema"

**Review by rivaquiroga — DISMISSED** [review]

**Comment by rivaquiroga** [comment]
@Anisa-ProgHist, the ES translation is ready

**Comment by anisa-hawes** [comment]
Thank you, @DanielAlvesLABDH and @rivaquiroga ! 

My sincere apologies, as I made a mistake in my initial translation request. Riva, I see that you noticed my mistake and have already made the extra changes!

Daniel, I have added your translation and made the small additional edits in pt/reportar-um-erro.md. Do you have a moment to glance over this? I have not written any Portuguese, just adjusted the order and the options.

**Review by DanielAlvesLABDH — APPROVED** [review]

**Pull request merged**
