### PR TITLE
Publicar analise-correspondencia-pesquisa-historica-R

### PR DESCRIPTION
**Pull request by DanielAlvesLABDH**
*Publicar tradução da lição "Correspondence Analysis for Historical Research with R"*

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Add the appropriate "Label"
- [ ] If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above
- [x] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Assistant @anisa-hawes 
- [x] Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)
- [x] Assign at least one individual or team to "Reviewers"

### CODE REVIEW

**Comment by DanielAlvesLABDH** [comment]
Hi @anisa-hawes. The build failed because of a broken link in this lesson https://programminghistorian.org/es/lecciones/administracion-de-datos-en-r. This link hhttps://es.r4ds.hadley.nz/visualizaci%C3%B3n-de-datos.html doesn't open. Apparently the Spanish version of this site (https://r4ds.hadley.nz/) is not working.

**Comment by rivaquiroga** [comment]
@DanielAlvesLABDH, @anisa-hawes, you can use this version: https://cienciadedatos.github.io/r4ds/visualizaci%C3%B3n-de-datos.html
We are making some updates on the site, and the official link won't be available for a couple of days.

**Comment by DanielAlvesLABDH** [comment]
Thanks for letting us know @rivaquiroga. If it just for a couple of days we can wait. Maybe @joanacvp can go ahead and make the final revision while we wait. And we still have to include the DOI.

**Comment by anisa-hawes** [comment]
Thank you @DanielAlvesLABDH and @rivaquiroga.

- [x] I'll temporarily update the broken link in /es/lecciones/administracion-de-datos-en-r with the alternative Riva suggests so that this can move forwards. (I can update again when the ES R for Data Science site is live – just let me know when it's ready Riva).

- [x] I've added in the DOI.

**Review by joanacvp — APPROVED** [review]
Está pronta a ser publicada!

**Pull request merged**
