### PR TITLE
Add Communication Team Roles

### PR DESCRIPTION
**Pull request by walshbr**
refs #1327.

@mdlincoln can you take a quick look and make sure I honored the YML setup you have going on? I also wasn't sure if we wanted an overarching label for the teams in addition to the roles themselves. This PR adds creates the roles discussed in #1327 and adds them to @amsichani @jenniferisasi and myself. But it does not also create an overarching "communications team" role. Let me know if we need that. 

Once @mdlincoln approves we can ping the Spanish and French teams to translate the few sentences here.

### CODE REVIEW

**Comment by acrymble** [comment]
Can someone ping me when this is merged so I can do the Project Development Team too?

**Comment by walshbr** [comment]
Can do @acrymble. 

Ah also I just saw #1342 that creates both a generalized role as well as a lead role. I'll update this PR to reflect this structure.

**Comment by acrymble** [comment]
While you're at it can you remove the "Community Engagement" tags, since these are now legacy?

**Comment by walshbr** [comment]
I was just thinking that same thing @acrymble. Removed them in the last commit. This should be ready to glance at @mdlincoln, and then after you get a chance to do that can you request review from the Spanish and French teams to translate it?

**Comment by jenniferisasi** [comment]
May I start translating the changes in the team roles into Spanish?

**Comment by walshbr** [comment]
I think so @jenniferisasi, so long as the descriptions of the roles seem good to you as Communications Boss™

**Comment by walshbr** [comment]
Since @jenniferisasi has translated this into Spanish, I've requested review from the French team. I think any changes @mdlincoln might flag wouldn't affect the translations themselves - just where we put them in the files. So no reason to wait on translating if someone has time.

**Comment by acrymble** [comment]
Can I ask for a timeline from the French team here? This pull request is preventing us from closing further tickets on implementing our new structure.

**Review by mdlincoln — APPROVED** [review]

**Pull request merged**
