### PR TITLE
trying to get htmlproofer working

### PR DESCRIPTION
**Pull request by ZoeLeBlanc**
*add the reason for your pull request here*

### Checklist

- [ ] Assign yourself in the "Assignees" menu
- [ ] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [ ] Add the appropriate "Label"
- [ ] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by ZoeLeBlanc** [comment]
Ok @anisa-hawes think I found a short term solution to our build issue. Essentially htmlproofer has updated to a new version and while I would like us to start using it, I couldn't get the newer version working. So for now, we are using an older version which required me forking a github action and deploying it to docker. So if we merge this in and pull down into the existing PRs we should be good to go.

If this all sounds good to you, I'll go ahead and merge this in. Thanks!

**Comment by anisa-hawes** [comment]
Amazing, @ZoeLeBlanc! ✨ Thank you for your support with this. I'm happy for you to merge this in! 

Next step will be for me to re-base the other PRs in our pipeline so we can move forwards.

**Comment by ZoeLeBlanc** [comment]
Hey @anisa-hawes! Thanks so much for giving me the thumbs up. Would you mind actually approving the PR though since I need that to merge it in?

**Review by anisa-hawes — APPROVED** [review]
Thank you, @ZoeLeBlanc!

**Pull request merged**
