### PR TITLE
Publicar_nocoes-basicas-paginas-web-html

### PR DESCRIPTION
**Pull request by DanielAlvesLABDH**
Publicar a lição traduzida Noções básicas de páginas web e html

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
- [x] Add the appropriate "Label"
- [ ] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by DanielAlvesLABDH** [comment]
Hi @ZoeLeBlanc! After some struggle ;-) I think I manage to edit the file correctly, but it is failing because of missing links on other files. Can you help or show me the way I can solve this? Thanks

**Comment by jenniferisasi** [comment]
Ugh one of those is my translation. I'm going to try to find that missing PDF to update. We are investigating the other broken link, that the build should be ignoring.

**Review by ZoeLeBlanc — APPROVED** [review]
Looks great 🎉 ! Merge it in 👍🏽

**Comment by DanielAlvesLABDH** [comment]
Thank you @ZoeLeBlanc and @jenniferisasi! 🎉🎉🎉

**Pull request merged**
