### PR TITLE
Uploading lesson files

### PR DESCRIPTION
**Pull request by svmelton**
### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by svmelton** [comment]
Would someone from @programminghistorian/technical-team mind taking a look and seeing why the build is failing? (Could it be because the lesson doesn't have any topics associated with it?)

**Comment by jenniferisasi** [comment]
@svmelton "topics" is a required field on all lesson so that is triggering the fail in the build for sure.
Now, I am not 100% the error displayed is exactly that, because I cannot locate in which building/plugin file 'topics' is identified as 'method'.

**Comment by svmelton** [comment]
> @svmelton "topics" is a required field on all lesson so that is triggering the fail in the build for sure. Now, I am not 100% the error displayed is exactly that, because I cannot locate in which building/plugin file 'topics' is identified as 'method'.

Thanks @jenniferisasi! This actually raises a question @anisa-hawes just noted: in the [editorial guidelines](https://programminghistorian.org/en/editor-guidelines#3-add-yaml-metadata-to-the-lesson-file) there's a mention of editing the lessonfilter.js file:
`Edit /js/lessonfilter.js so the filter button to filter the lesson page to that topic works. Search the file for the ten-line chunk of code beginning with $('#filter-api'), copy and paste that chunk of code, and replace the two appearances of “api” with your new topic.`  

But it doesn't appear that the filter-api code is in that file—I'm wondering if it was taken out when we revamped the search functionality. Are we still adding topics, and is this step necessary? (I'm happy to start a separate issue if that's helpful!)

**Comment by jenniferisasi** [comment]
Wow, I have not read the guidelines in so long that I had forgotten about that part. 

Inspecting the [lessonfilter.js](https://github.com/programminghistorian/jekyll/blob/gh-pages/js/lessonfilter.js) file, I believe you might be correct (though I am no expert on JS, more like super novice 😅). I understand that if you add a new topic to the lesson and then to [/_data/topics.yml](https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/topics.yml) it should show on the button options (until you add it to _data I think it will ignore said topic in the lesson metadata). 

Since adding a new topic means translation is needed, let me know if you want to try that out and I'll add languages. [I'm going to be on and off but monitoring regularly today]

**Comment by svmelton** [comment]
Thanks @jenniferisasi! I think we're ok for this lesson, but I'll create an issue for the larger question of topics.

**Review by anisa-hawes — COMMENTED** [review]
Thank you, @svmelton. I have made 3 very small corrections to the .md file. 

Para 128: Deleted additional 'space' 
Para 128: Exchanged hyphen for long dash
Para 367: Added missing closing parenthesis

**Review by anisa-hawes — APPROVED** [review]

**Pull request merged**
