### PR TITLE
Update ph_authors.yml

### PR DESCRIPTION
**Pull request by sferna109**
Included in bio (Sylvia Fernández)

*add the reason for your pull request here*

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [ ] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by acrymble** [comment]
Oh wow, all four languages?!

Thanks for the start on this. The checklist you see in your original comment here is something you have to do yourself. It's a series of steps for making sure the pull request is valid and you've contacted the right people. In this case, you need to assign yourself, request a review (probably from the English team in this case), add a label (English), and check that the pull request passes the checks (it doesn't yet but we can help you figure that out).

You should also add your photo/avatar to this same pull request. You can have more than one file in a single pull request.

Hope that helps!

**Comment by sferna109** [comment]
> Oh wow, all four languages?!
> 
> Thanks for the start on this. The checklist you see in your original comment here is something you have to do yourself. It's a series of steps for making sure the pull request is valid and you've contacted the right people. In this case, you need to assign yourself, request a review (probably from the English team in this case), add a label (English), and check that the pull request passes the checks (it doesn't yet but we can help you figure that out).
> 
> You should also add your photo/avatar to this same pull request. You can have more than one file in a single pull request.
> 
> Hope that helps!

@acrymble, I have worked in this, but I am still the last two requirements that I am not sure how to proceed. Could you help me, please?

**Comment by acrymble** [comment]
@sferna109 the problem we've got here is that other people have since edited these files, so you're working from out of date versions. That means the checks don't pass because the system recognizes them as old files. We can fix that after though.

First we have to put your avatar in this same pull request instead of in 2 separate ones. Please:

1) close your other pull request (https://github.com/programminghistorian/jekyll/pull/1895)
2) use these instructions to go to the branch for THIS pull request (sferna109-patch-1) and then add the avatar to this pull request (https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions)
3) Request a review from either the English team or Technical team.

That should mean we have a pull request with the information we require. Then we can ask the Technical team to help us re-base the outdated file so that we can close it. We've got 6 people currently trying to onboard onto the team and upload their bio, so that's the problem here.

**Comment by spapastamkou** [comment]
Hi @sferna109, just made some changes in the FR part of your bio. Please note that there is really no equivalent for "Public (Digital) Humanities" in FR institutions so I only left your translation of "Digital Humanities" instead.

**Review by rivaquiroga — APPROVED** [review]

**Comment by acrymble** [comment]
@programminghistorian/technical-team why did this end up in the closed pull requests list? This hasn't been merged yet.

**Comment by walshbr** [comment]
Not sure what you mean @acrymble - it looks like it's open and has never been closed? But I might be missing something.

**Comment by acrymble** [comment]
@walshbr sorry this morning it was showing up for me under closed tickets. Just ignore me.

**Comment by acrymble** [comment]
@sferna109 the Portuguese team is going to translate this file, which means we have to wait 30 days for them to do their work. Please just leave this pull request until they are finished and we can then add your bio to the site.

**Comment by acrymble** [comment]
I am going to add this bio in another pull request of various updates to this page. So closing this pull request.

**Pull request closed without merging**
