### PR TITLE
Downloading Multiple Records - warning update

### PR DESCRIPTION
**Pull request by acrymble**
I've updated the intro to the Downloading Multiple Records lesson after speaking to @svmelton to include an acknowledgement of the historic racialised language used in the examples and to suggest readings on teaching or working with material like this in a sensitive manner.

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [ ] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by spapastamkou** [comment]
Just in time as I work on the lesson's translation:-)

**Comment by acrymble** [comment]
@programminghistorian/technical-team I think there's been an interface change. I don't see the actual error when I click on the 'details' link next to the Build Failed, as used to be the case. Am I looking in the wrong place?

**Comment by spapastamkou** [comment]
It is the link you replaced with a former pull request for a FR lesson; but it needs to be replaced in the EN lesson as well. @mdlincoln did it in pull request #1808 which I reviewed but did not merge. I'll do the merge and hopefully there should be no trouble here.

**Comment by spapastamkou** [comment]
@acrymble Done; if you refresh the branch it should work. 

Otherwise, once you click on "Details" for the Travis build fail, you scroll the page and at the top down click on "View more details on Travis CI". Then you have a new page with the error report.

**Comment by mdlincoln** [comment]
I just re-ran the build so that it reflected the latest changes.

**Review by svmelton — APPROVED** [review]

**Pull request merged**
