### PR TITLE
Add two items and correct a third on research page

### LINKED ISSUE #1983: Add Brandon's MLA talk to the research page
Just a note to myself to add my MLA talk, which I just blogged to our research page - http://walshbr.com/blog/the-programming-historian-and-editorial-process-in-digital-publishing/. 

I also noticed just now that we don't have ML's blog post on how we do translation in Jekyll on the research page - https://matthewlincoln.net/2020/03/01/multilingual-jekyll.html. @acrymble - can I go ahead and add that in the same PR? I assume it was just forgotten as opposed to, say, not wanting to mention blog posts. Because it's definitely something folks would be interested in.

### PR DESCRIPTION
**Pull request by walshbr**
Closes #1983. I added my talk and Matt's blog post. I also noticed a third citation wasn't formatted correctly for linking, so I fixed that one. @acrymble since I feel like you have edited this page the most, can you confirm that it was fine for me to go ahead and edit the Es/Fr/Pt pages myself? It looked like the citations themselves were not really translated across the language publications. So if I was correct in doing that I should be good for merging after you approve. 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [ ] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Review by acrymble — CHANGES_REQUESTED** [review]
For consistency, can you put the dates in the respective languages? I think we've done that while leaving the titles in their original language.

**Comment by walshbr** [comment]
Oh  yes  -  sorry I  missed that.

**Comment by walshbr** [comment]
Through a careful use of Google translate and looking at other entries, I think I got them. Could the  @programminghistorian/french-team @programminghistorian/portuguese-team and @programminghistorian/spanish-team confirm by approving your pieces? And @acrymble can you dismiss the stale review, please? Thank you!

**Review by acrymble — DISMISSED** [review]

**Comment by JoshuaGOB** [comment]
The month names in Portuguese should be all in lower case.

**Comment by walshbr** [comment]
@JoshuaGOB the Pt month names were capitalized elsewhere in the document. Did you want to modify those across the board?

**Comment by DanielAlvesLABDH** [comment]
Dear @JoshuaGOB and @walshbr I can't make the changes now, but the months in the PT team should be capitalized in the first letter. In Brazil they are, in Portugal officially they aren't but we adopt here the Brazilian rule... 😉

**Review by DanielAlvesLABDH — DISMISSED** [review]

**Comment by walshbr** [comment]
Ok! We should be good for PT then. I had capitalized them.

**Review by mariechristineb — APPROVED** [review]

**Review by jenniferisasi — APPROVED** [review]

**Pull request merged**
