### PR TITLE
update Getting Started with Markdown lesson

### LINKED ISSUE #2102: Broken link found in getting-started-with-markdown
Our build system found a broken 404 link in "Getting Started with Markdown". 

[https://stackedit.io/editor](https://stackedit.io/editor) no longer exists, and it looks like it has been replaced with [https://stackedit.io/app#](https://stackedit.io/app#)

I was going to do the simple edit, but upon reading the instructions that go with the link, I found that they no longer match with the app in question: 

> click on the # in the upper left corner for a menu. Choose Import from URL, then paste the following URL to display the “Intro to Bash” lesson in the editor

I clicked on the # and only these options are now available for import: 

Screen Shot 2021-03-30 at 6 16 25 PM

Looks like we could remove that step easily and proceed, but the lesson is available in all languages, so the edit needs to be in sync.

### PR DESCRIPTION
**Pull request by spapastamkou**
*Update of Getting Started with Markdown lesson (FR, EN, ES): instructions for v5 of StackEdit. Closes #2102*

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by spapastamkou** [comment]
FYI @DanielAlvesLABDH @joanacvp

**Comment by spapastamkou** [comment]
@jenniferisasi I asked for review but it will be for when changes in ES and EN version are in, it is mostly for you to be informed since the beginning.

**Comment by spapastamkou** [comment]
There is also a broken link in this post: https://programminghistorian.org/posts/promoting-digital-archives.html The [link](https://www.bodleian.ox.ac.uk/__data/assets/$1) has not been archived anywhere from what I see, I propose we only keep the generic link of the Bodleian.

**Comment by jenniferisasi** [comment]
Thanks @spapastamkou! I would swear I had gotten rid of that other broken link... hmmm 

ok, I did, but because I couldn't merge that PR #2101 it is still broken, @walshbr @ZoeLeBlanc would anything happen IF we get rid of the link in this PR when I try to update the one with the newsletter?

**Comment by jenniferisasi** [comment]
And I'm going to try to edit the lesson in ES, then @rivaquiroga only needs to double-check.

**Comment by ZoeLeBlanc** [comment]
@jenniferisasi I would say do whatever is easiest for you! So either remove the link in all languages until we update it (though you might need to add placeholder text so that readers would know about the missing link and not sure if that would need to be translated or not)OR add the link to our list of urls we ignore when we build the site (this is the build.yml file) and then you can merge in this branch

**Comment by spapastamkou** [comment]
@jenniferisasi You can review and merge, if you want, I checked the preview of all three versions and all seems ok.

**Comment by jenniferisasi** [comment]
Thanks @spapastamkou! I am going to ask that some in the @programminghistorian/english-team reviews their version so that someone is away of the change. And then I can merge :)

**Review by svmelton — APPROVED** [review]

**Pull request merged**
