### PR TITLE
Issue 3086

### LINKED ISSUE #3086: Update French translations
I am opening this issue to update several of the French translations on the Programming Historian website:

Instead of [fr/manifestations](https://programminghistorian.org/fr/manifestations), we will use `fr/evenements` (événements) instead. I will make this change for the page name and the headings throughout.

Instead of `"Vous pouvez faire une donation"` at the top of each FR lesson, we will write `"Vous pouvez faire un don"`

These translations have been decided on in collaboration with the  FR Managing Editor.

### PR DESCRIPTION
**Pull request by charlottejmc**
I have made changes to two of the French terms used on the website:

`Manifestations` is now `Événements`.

"Vous pouvez faire un`e donation`" is now "Vous pouvez faire `un don !`".

Closes #3086 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Add the appropriate "Label"
- [x] If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above
- [x] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Assistant @anisa-hawes 
- [x] Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)
- [x] Assign at least one individual or team to "Reviewers"
  - ~[ ] if the text needs to be translated, please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines), then assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR.~

### CODE REVIEW

**Comment by charlottejmc** [comment]
Bonsoir @marie-flesch,

I have made the changes we spoke about by email. I would be very grateful if you could check the Netflify preview on your end, and approve the changes if you are happy with them!

Thank you very much ✨

**Comment by marie-flesch** [comment]
Awesome @charlottejmc! Just a small change : "Évènements" (new spelling)  instead of "Événements" (old spelling), both times it appears. New spelling is consistent with pronunciation while the older one is not :)

**Comment by charlottejmc** [comment]
Thanks @marie-flesch, I've made that change now!

**Review by anisa-hawes — DISMISSED** [review]
Thank you, @charlottejmc! 

As Marie has given her review via a comment (and you've implemented the adjustment she suggested), I'm happy to approve this.

**Review by anisa-hawes — APPROVED** [review]
As @marie-flesch has already reviewed this via a comment (and you've implemented the adjustment she suggested), I'm happy to approve this.

**Pull request merged**
