### PR TITLE
update about (EN) and apropos (FR) pages as per #951

### LINKED ISSUE #951: Link issues on the /about page
The issues are relevant to the [Gold Open Access part of the page](https://programminghistorian.org/en/about#gold-open-access) and were first raised in #940. 

I copy/paste exactly from there: 
- link to RCUK's website has changed. Redirection works (15 secs). Do we keep the same link or replace with new one?
- link to HEFCE web site: works but the web site is "historical and no longer maintained" bcz HEFCE closed in March 2018.
- how about adding a bit of European context (Guidelines to the Rules on Open Access to Scientific Publications and Open Access to Research Data in Horizon 2020)?
http://ec.europa.eu/research/participants/data/ref/h2020/grants_manual/hi/oa_pilot/h2020-hi-oa-pilot-guide_en.pdf  

And @acrymble 's comment: "The HEFCE and RCUK links were mentioned because they have policy implications for any UK-based authors. Essentially, your work will only 'count' in future if it is open access. This statement merely notes that we are compliant. If we need to highlight compliance for other regions then I agree it's worth adding more notes/links. But we should stay focused on that compliance message rather than advocating widely for open access policies around the world (which is important but probably belongs somewhere else)"

I share this point of view as well, give emphasis mainly to the message and be able to provide more links (European and Latin American context maybe?). 

My question is: are we willing to correspondingly modify this part of the page? If so, how do we organise this work?

### PR DESCRIPTION
**Pull request by spapastamkou**
I just updated the EN about and the FR apropos pages following latest comments in #951 issue. This closes #951.  

The ES acerca page should be modified in the same way. Please @programminghistorian/spanish-team take note that in this page https://programminghistorian.org/en/about#gold-open-access 
the following part 

"All submissions to the Programming Historian are published under a Creative Commons ‘CC-BY’ license. This adheres to a ‘Gold’ open access model of publishing, which is fully compliant with the Berlin Declaration on Open Access to Knowledge in the Sciences and Humanities, RCUK funding and HEFCE publishing requirements for scholars in the UK, as well as the Canadian Tri-Agency Open Access Policy. ‘Gold’ open access means that the version of record is made freely available without subscription fee or restrictions on access. Authors are permitted to republish their tutorials anywhere"

**is replaced by** 

"All submissions to the Programming Historian are published under a Creative Commons ‘CC-BY’ license. This adheres to a ‘Gold’ open access model of publishing. The version of record is made freely available without subscription fee or restrictions on access. Authors are permitted to republish their tutorials anywhere."

### CODE REVIEW

**Comment by acrymble** [comment]
looks fine but needs a Spanish translation update.

**Comment by arojascastro** [comment]
done

**Review by arojascastro — DISMISSED** [review]

**Review by fdlaramee — DISMISSED** [review]

**Comment by arojascastro** [comment]
we need @acrymble review to merge this pull request 🙏 and probably to fix this issue first: https://github.com/programminghistorian/jekyll/issues/1207

**Comment by acrymble** [comment]
This needs to have the latest pull request incorporated into it because it's no longer in sync with the lead branch. I'm not sure how to do that.

**Review by arojascastro — APPROVED** [review]

**Comment by arojascastro** [comment]
I faked a change and Travis processed all again. I think it is fine now but we need @fdlaramee review again... sorry

**Review by fdlaramee — APPROVED** [review]

**Pull request merged**
