### PR TITLE
Issue 2462

### LINKED ISSUE #2462: User reported Issue: Building a static website with Jekyll (on Windows)
A user has reported that the command `choco install ruby -y` is not recognised by GitBash on Windows.

They are following the instructions given in the [On Windows](https://programminghistorian.org/en/lessons/building-static-sites-with-jekyll-github-pages#on-windows-) section of en/lessons/building-static-sites-with-jekyll-github-pages.

I note that the [En Windows](es/lecciones/sitios-estaticos-con-jekyll-y-github-pages#en-windows-) section of es/lecciones/sitios-estaticos-con-jekyll-y-github-pages does not use the Chocolatey package manager.

### PR DESCRIPTION
**Pull request by charlottejmc**
I have implemented the changes suggested by a very helpful external contributor (Leonardo Barleta) to adjust the steps under the `### On Windows` section.  

Closes #2462 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Add the appropriate "Label"
- [x] If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above
- [x] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Manager @anisa-hawes 
- [x] Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines), then assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR.

### CODE REVIEW

**Comment by charlottejmc** [comment]
Dear @jenniferisasi and @ericbrasiln,

We've received a very helpful contribution from an external contributor, who's updated the `## On Windows` section (and two extra lines) to fix the problems raised in the Lesson Maintenance issue #2462.

I would be very grateful if you could coordinate a translation of these changes in Spanish and Portuguese!

Please only refer to the changes you can see in the 'rich diff' from [this commit](https://github.com/programminghistorian/jekyll/pull/3239/commits/0d435472b57a48ecfb1d00bc499e9ccc165c4135), as I made some subsequent typesetting changes which you don't need to worry about. (I can implement those later myself, after your translation.) 

Thank you very much for your time.

**Comment by anisa-hawes** [comment]
Thank you for preparing this for us, @charlottejmc!

---

Grateful thanks to Leonardo Barleta @lbarleta for contributing ! ✨

**Comment by ericbrasiln** [comment]
Hello @charlottejmc

This lesson hasn't been published in Portuguese yet, and the translation process is currently on hold.

I'll add a comment to the translation issue to highlight the need for these changes to be incorporated.

**Review by ericbrasiln — APPROVED** [review]
🚀

**Comment by charlottejmc** [comment]
Hi @ericbrasiln, apologies for the confusion!

Thank you very much for linking this PR in the issue thread for the ongoing PT translation.

**Pull request merged**
