### PR TITLE
Added FAQs to JISC/TNA/PH CfP

### LINKED ISSUE #2294: Potential FAQs derived from PH/JISC/TNA author event
Hello everyone,

Following our very successful author event, I came up with a list of possible FAQs to add to the [CfP/Blog post](https://programminghistorian.org/posts/cfp-jisc-ph). These are (in no particular order right now, though I will organise them thematically):

- Can I still publish my lesson in *The Programming Historian* even if it hasn't been selected for this call?
- How will I know you have received my application?
- Will I need to translate (or arrange for the translation) of the lesson myself?
- When will I hear if my lesson has been accepted?
- Can I appeal the decision?
- Do I need a GitHub account or learn Markdown?
- Why is the peer review process open?
- Where can I find guidance for writing my lesson?
- Why does the CfP focuses on large-scale data?
- Who makes up the selection panel?
- What is the selection criteria?
- Does my lesson need to make use of JISC/TNA datasets?
- What should I do if I have more than one idea I would like to submit?
- What should I do if my dataset is too big?
- Can I make use of cloud services for data processing in my lesson?
- Are you able to take personal circumstances into account? (e.g. parental leave)

Some of these issues are already addressed in the CfP (though are also the kinds of things people tend to misunderstand, skim, or need confirmation about), others came from the author event, others still just things I was thinking about.

I'm drafting and making a pull request for this now (we can correct specific wordings there) but, in the meantime, anything you think should not be a part of this list / should be added?

P.S.: I can't seem to find Peter's username -- if he's not here, I can send them a link to the FAQs once they've been published and add any of his corrections/suggestions later, to avoid multiplying channels of conversation

### PR DESCRIPTION
**Pull request by tiagosousagarcia**
Closes #2294

Adding a FAQ list to the PH/JISC/TNA blogpost/CfP

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

Please check the wording of both Qs and As -- and in particular the answers to the questions around selection (criteria, panel) which I am a bit uncertain of. I've put the FAQs at the bottom of the post, let me know if top would be best (or anywhere else for that matter).

I've also added the links to the Portuguese archives @DanielAlvesLABDH suggested (edited their description slightly to fit with the existing links)

### CODE REVIEW

**Comment by tiagosousagarcia** [comment]
There's a link failing in the En lesson ['Working with batches of PDF files'](https://programminghistorian.org/en/lessons/working-with-batches-of-pdf-files) -- I believe the contente of that link is now (somewhere) on this page (https://docs.microsoft.com/en-us/windows/wsl/wsl-config), but maybe someone from @programminghistorian/english-team could confirm it

**Comment by drjwbaker** [comment]
> 
> 
> There's a link failing in the En lesson ['Working with batches of PDF files'](https://programminghistorian.org/en/lessons/working-with-batches-of-pdf-files) -- I believe the contente of that link is now (somewhere) on this page (https://docs.microsoft.com/en-us/windows/wsl/wsl-config), but maybe someone from @programminghistorian/english-team could confirm it

This is fixed in PR https://github.com/programminghistorian/jekyll/pull/2292 but we're waiting on translation there to pull. @anisa-hawes: I'm going to pull https://github.com/programminghistorian/jekyll/pull/2292 to fix the build issue, then we can open a seperate ticket for FR/PT translation of our charitable status.

**Comment by drjwbaker** [comment]
I reckon these checks will pass now.

**Comment by tiagosousagarcia** [comment]
> I reckon these checks will pass now.

Thanks @drjwbaker -- just pulled the new changes into this branch, so should be good to go (once the checks finish)

**Review by drjwbaker — APPROVED** [review]

**Comment by drjwbaker** [comment]
Help @programminghistorian/technical-team - I merged this PR but I'm getting build fail emails https://github.com/programminghistorian/jekyll/actions/runs/1270207464

**Comment by tiagosousagarcia** [comment]
> Help @programminghistorian/technical-team - I merged this PR but I'm getting build fail emails https://github.com/programminghistorian/jekyll/actions/runs/1270207464

I think that build fail is from my forked repository (which, I think, fails because the PH domain name is already taken) -- not sure why these are appearing in the main repo though :s

**Comment by drjwbaker** [comment]
Hmm. I've raised with the tech team on Slack (and invited you to the slack in case it is useful for you to be there, which is to say you don't have to join!)

**Comment by drjwbaker** [comment]
The changes are at least showing on the site. Which is good!

**Comment by ZoeLeBlanc** [comment]
Taking a look now! And feel free to chime in on Slack @tiagosousagarcia !! So just to clarify you were able to merge in @drjwbaker even though the build failed? Or rather the merge seemed to have worked even though the build failed?

**Comment by drjwbaker** [comment]
@ZoeLeBlanc Checks passed, so I merged, then I got emails saying build had failed.

**Comment by tiagosousagarcia** [comment]
> Hmm. I've raised with the tech team on Slack (and invited you to the slack in case it is useful for you to be there, which is to say you don't have to join!)

Thanks! Could you invite me using the email [I have here though](https://rse.ncldata.dev/tiago-sousa-garcia)? that's where all my slack action happens :)

**Comment by ZoeLeBlanc** [comment]
Ya I think the issue is definitely the fork! It seems like this person had a similar issue here https://github.com/actions/toolkit/issues/465. I'm not sure if forks get secret tokens yet or not 🤔 

Is there a reason to do a fork of the repo @tiagosousagarcia ? Or could you just clone locally and make a normal branch? Happy to investigate this issue further but might need to pause for a bit because of a meeting soon

**Comment by tiagosousagarcia** [comment]
> Ya I think the issue is definitely the fork! It seems like this person had a similar issue here [actions/toolkit#465](https://github.com/actions/toolkit/issues/465). I'm not sure if forks get secret tokens yet or not 🤔
> 
> Is there a reason to do a fork of the repo @tiagosousagarcia ? Or could you just clone locally and make a normal branch? Happy to investigate this issue further but might need to pause for a bit because of a meeting soon

Not particularly, no -- other than for keeping any (potentially catastrophic) changes well and truly separate from the repo. I think I did it as a matter of course, but I don't have to do it

**Comment by drjwbaker** [comment]
Thanks @ZoeLeBlanc. I guess my question is, can we leave this and just avoid forking in the future? Or do we need to roll-back this merge, then do it again without forking?

**Pull request merged**
