### PR TITLE
Newsletter 1st trimester of 2020 as per #1706

### PR DESCRIPTION
**Pull request by jenniferisasi**
- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Review by walshbr — DISMISSED** [review]

**Comment by walshbr** [comment]
Looks great!

**Comment by jenniferisasi** [comment]
Thanks everyone for reviewing the newsletter! Gonna merge now and it should publish tomorrow :)

**Review by mdlincoln — CHANGES_REQUESTED** [review]
the push actually has to happen on or after 2020-04-01 in order for it to appear

**Comment by jenniferisasi** [comment]
> the push actually has to happen on or after 2020-04-01 in order for it to appear

Ah! I though it would future-it...so thanks! Will push early tomorrow because I assume I cannot push it in European time... 

I actually now did some changes because I got an update from James.

**Review by mdlincoln — APPROVED** [review]

**Pull request merged**
