### PR TITLE
Portuguese core configuration

### PR DESCRIPTION
**Pull request by mdlincoln**
This PR makes core changes to the site _config.yml, snippets, and creates a `/pt` directory with copies of the core infrastructure files.

1. The changes to _config.yml mark all pages under the `pt` path has having the language `pt`.
2. In snippets, I have added blank entries for Portuguese translations under each item in the list.  Note that I have not yet added `pt` to `language-list` - that should only be done once we are ready for the pages to go live, as this controls what shows up on the front page, the language switching buttons, etc.
3. The `pt` directory contains a copy of the EN core pages, with the correct `original` metadata in place.

Once this is merged, the PT team can begin a new PR to start translating the infrastructure pages. Because the links won't be published until we modify `language-list`, the team could start pushing up individual pages, it wouldn't have to be in one giant PR.

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  ~- [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description~
- [x] Add the appropriate "Label"
- [ ] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
~- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above~

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by mdlincoln** [comment]
n.b. this does technically "publish" pages, so e.g. https://deploy-preview-1755--ph-preview.netlify.app/pt/ shows up. However there's no links to them anywhere until we update `language-list` in the snippets.

**Comment by acrymble** [comment]
@mdlincoln thanks for doing this. It looks like it's a process that we'll need to be able to replicate again in future. Is this something we can collectively document? What might that process need to look like (or forgive me if that's already happening or happened).

**Comment by walshbr** [comment]
@mdlincoln - it looks good to me, except for the one 404 on an English lesson. A larger question before I approve it - do we need to account for the multiple travis errors being thrown by the unpublished PT lessons in some way?

**Comment by mdlincoln** [comment]
Yeah @walshbr about to push another change to the site config that will `exclude` the PT directory from processing right now - I forgot that without having a favicon yet, there would automatically be a broken asset link on every PT page...

**Comment by mdlincoln** [comment]
@acrymble yes this will be in #1737

**Comment by walshbr** [comment]
kk! i'll approve. darned favicons.

**Review by walshbr — DISMISSED** [review]

**Comment by mdlincoln** [comment]
well don't approve it till I push or you'll just have to approve again...

**Comment by walshbr** [comment]
Sorry I just approve everything you do.

**Comment by mdlincoln** [comment]
OK @walshbr I think we're good now :)

**Review by walshbr — APPROVED** [review]

**Pull request merged**
