### PR TITLE
Issue 3226

### LINKED ISSUE #3226: Collating forthcoming events for the /en/events, /es/eventos, /fr/manifestations, /pt/eventos pages
Hello all!

@programminghistorian/english-team
@programminghistorian/spanish-team
@programminghistorian/french-team
@programminghistorian/portuguese-team

The Events pages of our website are now a hub for us to advertise forthcoming Programming Historian-related events.

I'd like to collate information about any confirmed events you will contributing to with a workshop / poster / paper connected to your work with the Programming Historian.

Please let me know in a comment below, ideally including:

Name(s)
Title of your event / workshop / poster / paper
Organising institution or group
Location, date, time, timezone
Link to sign up/further information

And I'll prepare an update :sparkles: 

I'd also like to support the promotion of these events via our social media channels ([Twitter](https://twitter.com/ProgHist) and [Mastodon](https://hcommons.social/@proghist)), so if you want to add a draft promotional post/send it to me by email closer to the time I'd be very happy to share it.

### PR DESCRIPTION
**Pull request by charlottejmc**
I have added multiple upcoming conferences to our Events pages.

Closes #3226 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Add the appropriate "Label"
- [x] If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above
- [x] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Manager @anisa-hawes 
- [x] Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)
- [x] Assign at least one individual or team to "Reviewers"
  - ~[ ] if the text needs to be translated, please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines), then assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR.~

### CODE REVIEW

**Comment by charlottejmc** [comment]
Hello @matgille,

Would you like me to add your upcoming conference in Morocco? 

- Matthias Gille Levenson, [AUTHOR NAMES], '[PRESENTATION TITLE]', [Humanistica 2024](https://humanistica2024.sciencesconf.org/).
Date : 7-9 mai 2024
Lieu : Université Moulay Ismaïl, Meknès, Maroc

**Review by anisa-hawes — DISMISSED** [review]
Thank you for preparing this, @charlottejmc! 

Hello Matthias @matgille, What do you think about us adding your contribution to Humanistica 2024 into this PR? 

If you can share the extra details, we'd love to add it here!

**Comment by matgille** [comment]
> Thank you for preparing this, @charlottejmc!
> 
> Hello Matthias @matgille, What do you think about us adding your contribution to Humanistica 2024 into this PR?
> 
> If you can share the extra details, we'd love to add it here!

Dear Anisa, dear Charlotte, 

You can add our contribution into the PR, but there was a little date change. We will present the paper on may 3, in a hybrid session !

The authors are: Matthias GILLE LEVENSON, Célian RINGWALD, Marie FLESCH, Jennifer ISASI,
Sofia PAPASTAMKOU, Riva QUIROGA6 et David VALENTINE

and the title: 
`Connecter les chapitres linguistiques de Programming Historian ? Vers une
table conceptuelle multilingue constituée semi-automatiquemen`


Best


Matthias

**Comment by matgille** [comment]
Thanks a lot !!

Matthias

**Review by anisa-hawes — APPROVED** [review]

**Pull request merged**
