### PR TITLE
Maj coquilles

### PR DESCRIPTION
**Pull request by icolab**
*Fixes typos in FR editor guidelines*

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by icolab** [comment]
@programminghistorian/technical-team the compilation failed because of:

> Ran on 434 files!
> 
>   *  External link https://programminghistorian.org/es/solicitud-lecciones failed: 404 No error
> 
> - ./_site/posts/bulletin-de-information-juin20.html
> 
>   *  External link https://programminghistorian.org/fr/appel-contributions failed: 404 No error
> - ./_site/posts/newsletter-march20.html
>   *  External link https://programminghistorian.org/en/lesson-requests failed: 404 No error
> 
> HTML-Proofer found 3 failures!

I'm not sure about where to find the broken links and how to fix it sorry

**Comment by spapastamkou** [comment]
@icolab It fails because of broken links in some blog posts, following the recent suppression of lessons request page in each PH version. @jenniferisasi has fixed this in pull request #2084 (that was failing for the same reason!). We'll wait until #2084 is merged; then we'll update this branch and it should be ok. I will review then. 

Thanks for the catch, there were a lot of typos!

**Comment by DanielAlvesLABDH** [comment]
Hi @spapastamkou . The merge on #2084 was done but the problem is still there. We have another PR #2098 for deleting a photo file and the errors are the same. I have checked the files and can't figure out what is the problem

**Comment by acrymble** [comment]
You need to re-base the code to the latest set of files so that the fix is incorporated. I usually do that by saying something like @programminghistorian/technical-team can some one please help me with this? And then I feel guilty about it for a while... :)

**Comment by DanielAlvesLABDH** [comment]
Feeling guilty already Adam. Thanks

**Comment by walshbr** [comment]
there ya go!

**Comment by walshbr** [comment]
Yeah it's really annoying you can't do that rebasing through the online interface :( But not a problem at all - it takes five seconds for one of us who runs things locally! The only annoyance I feel is with GH for not designing a way to do do this online :)

**Comment by DanielAlvesLABDH** [comment]
The same thing happens here (https://github.com/programminghistorian/jekyll/pull/2098) @walshbr ?

**Comment by walshbr** [comment]
@DanielAlvesLABDH - i updated that one too!

**Review by spapastamkou — APPROVED** [review]

**Comment by spapastamkou** [comment]
Glad it works for all of us now @DanielAlvesLABDH !

**Pull request merged**
