### PR TITLE
Add new IPP UCL DH

### PR DESCRIPTION
**Pull request by acrymble**
Add UCL Centre for Digital Humanities as an IPP.

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Review by rivaquiroga — DISMISSED** [review]

**Review by spapastamkou — DISMISSED** [review]
Replace: 
La [UCL Centre for Digital Humanities]
With:
Le [Centre for Digital Humanities de l'University College London]

**Review by DanielAlvesLABDH — DISMISSED** [review]

**Comment by acrymble** [comment]
@spapastamkou we had an email exchange back in September when we agreed to write institution names in their original language to reduce the need for translating on pull requests like this one. Are you suggesting we revisit that?

**Comment by acrymble** [comment]
@jenniferisasi this is ready to be merged and advertised. Can you re-review please?

**Review by jenniferisasi — APPROVED** [review]
@acrymble maybe you did this upon splitting the files in 3 in English and I don't remember, but why is the information in English not showing dates (year-present) as they do in ES, FR and PT? 

I'm approving in case this is something I just don't remember discussing, in which case I apologize.

Ok + in EN we have countries and in the others we don't. Taking note for when we split the file in 3 I make sure all have the same information.

**Comment by acrymble** [comment]
@spapastamkou I can't merge this because of your requested changes. Can you please remove it?

**Comment by acrymble** [comment]
Can someone on the @programminghistorian/technical-team please remove the change request so I can merge this? We need to advertise this support.

**Comment by walshbr** [comment]
You should be good now @acrymble

**Pull request merged**
