### PR TITLE
Contrast mode

### LINKED ISSUE #1524: Lower contrast CSS option
I had a request today at a workshop for an alternate lower contrast css file for people who find white and black too hard on their eyes. If this is relatively easy it would be a good accessibility option.

### PR DESCRIPTION
**Pull request by ZoeLeBlanc**
This PR closes #1524 and finally implements our low contrast mode 🎉 ! I made some tweaks to the UI initially implemented by @walshbr. In the end, decided to go with a small icon button rather than a toggle to both minimize the need for translation and to fit more seamlessly into our current UI.

I also updated the English privacy policy to reflect our use of session storage to save theme preference. 

Happy to have any edits/suggestions on either the UI, functionality, or privacy policy! 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by walshbr** [comment]
Just a note that I have a comment for this PR that I accidentally dropped in the wrong thread - https://github.com/programminghistorian/jekyll/pull/1993#issuecomment-766796846.

**Comment by ZoeLeBlanc** [comment]
Totally agree with your comment @walshbr! I didn't test much of the breakpoints... ideally we would have actually be responsive so might be worth trying to see if we could do that instead

**Comment by walshbr** [comment]
Your call! Personally I would just adjust the breakpoint by 15px or whatever and call it done. I also think the UI choice looks good to me and wouldn't mess with it further.

**Comment by ZoeLeBlanc** [comment]
I love the easy solution but now that we're about to add PT maybe we should wait to see if that fourth language button changes the layout of the menu 🤔. We might want to make the hamburger show up for screens larger than 768 since we have so many buttons now 😅

**Comment by jenniferisasi** [comment]
> I love the easy solution but now that we're about to add PT maybe we should wait to see if that fourth language button changes the layout of the menu 🤔. We might want to make the hamburger show up for screens larger than 768 since we have so many buttons now 😅

Yes, they are very close to launch so I think it is worth it to keep this PR open until after PT launch and do any needed changes rather than re-opening. 

Other than that, it looks fantastic!

**Comment by drjwbaker** [comment]
Agree. I love it.

**Comment by jenniferisasi** [comment]
Screen Shot 2021-01-25 at 10 51 16 AM

After seeing your [comment](https://github.com/programminghistorian/jekyll/issues/1524#issuecomment-766866793) on #1524 I went back to the preview (I had not checked every page) and noticed that this part in particular doesn't comply with accessibility quality. Dark gray on black could be an issue for color blindness.

**Comment by drjwbaker** [comment]
Just noting here that I am red-green, green-brown, blue-purple, and grey-green colour deficient (so, pretty 'bad'). I got on fine with the dark mode as implemented. But also appreciate that I'm not every colour deficient person.

**Comment by walshbr** [comment]
FWIW - that's just the default color contrast I think. I didn't actually test anything. And I had the same thought that the text there should probably be adjusted. IIRC it's not like that across the site, just on certain components.

**Comment by jenniferisasi** [comment]
> FWIW - that's just the default color contrast I think. I didn't actually test anything. And I had the same thought that the text there should probably be adjusted. IIRC it's not like that across the site, just on certain components.

Yes, I only saw that gray/black issue on that particular page. I tried to run the page through a test but it goes back to the published one (doesn't work with the netlify view, I had to check)

**Comment by ZoeLeBlanc** [comment]
@walshbr @hawc2 @jenniferisasi from our discussion last week, I updated to using a toggle and switched when each icon would show for the low contrast mode. If one of you could take a look and give me a 👍🏽 , I'll merge in this PR and we can start more broadly doing an accessibility audit 🙏🏽

**Review by walshbr — APPROVED** [review]

**Comment by jenniferisasi** [comment]
It looks fantastic!

**Pull request merged**
