### PR TITLE
exercise numeric facet in section 'get to know your data' requires op…

### PR DESCRIPTION
**Pull request by felixlohmeier**
fix for some issues in lesson "Cleaning Data with OpenRefine":

-  numeric facet in section 'get to know your data' requires option 'parse cell text into numbers, dates, ...' during import
- number of cells affected in last exercise is 33,008 using OpenRefine 2.7
- typo (wether --> whether)

### CODE REVIEW

**Comment by mdlincoln** [comment]
As you edited this lesson @acrymble I'm putting you in charge of reviewing this PR.

**Comment by acrymble** [comment]
Sorry, but I don't have time to look into this.

**Comment by ianmilligan1** [comment]
Could you loop in the authors @acrymble?

**Comment by acrymble** [comment]
Done.

**Comment by madewild** [comment]
As an author of the lesson, I confirm that the changes proposed by @felixlohmeier are relevant and should be accepted. Thanks for improving this old lesson! :)

**Review by madewild — APPROVED** [review]

**Review by ianmilligan1 — APPROVED** [review]
@madewild (author) has approved, and the additions also look great to me as an editor. Thanks all.

**Pull request merged**
