### PR TITLE
New ES original lesson: Análisis de sentimientos en R

### PR DESCRIPTION
**Pull request by rivaquiroga**
*add the reason for your pull request here*

### Checklist

- [X] Assign yourself in the "Assignees" menu
- [X] Assign at least one individual or team to "Reviewers"
  ~~- [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description~~
- [ ] Add the appropriate "Label"
- [ ] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by jenniferisasi** [comment]
¡Pues sí que respondieron rápido con el DOI! Voy a "leer" para comprobar que todo queda bien por si María José no alcanza a verlo antes, lo apruebo yo.

**Comment by jenniferisasi** [comment]
No aparece esta imagen: 

```
<img src=”/images/analisis-de-sentimientos-r/miau_sentimientos.png alt=”Evolución de las emociones a lo largo del texto”/>
```

Creo que es porque falta la " después de .png? 

[No quiero tocar mi propia lección en este momento por eso del conflicto de intereses]

**Comment by rivaquiroga** [comment]
@jenniferisasi, ahí debería haber quedado resuelto

**Review by jenniferisasi — APPROVED** [review]
Apruebo la carga de la lección (y los otros cambios que venían seguramente de errores en el _build_). ¡Gracias @rivaquiroga!

**Pull request merged**
