### PR TITLE
Update Membership History

### PR DESCRIPTION
**Pull request by walshbr**
Refs #843 - removes Ian and Jeri from the current project membership. @amsichani - can you either push to this branch an update to your section in _data/ph_authors.yml related to your changed institutional affiliation? Or share some copy for me to update with if you'd like. We'll also need to translate that short snippet into Spanish when we have it.

### CODE REVIEW

**Comment by amsichani** [comment]
thanks for the heads up @walshbr ! I ve updated my affiliation on this branch - 'd be great if we could a have a ES translation of it @arojascastro ! Cheers!

**Comment by arojascastro** [comment]
Done! Congrats

**Comment by walshbr** [comment]
@mdlincoln - we're getting some failing tests that I could use a thought on. For links that reference pages on github like so - https://raw.githubusercontent.com/programminghistorian/jekyll/gh-pages/new-lesson-workflow.md - should we just hardcode in the language? or check the language for the current page and add it to the URL that way?

**Review by mdlincoln — APPROVED** [review]
The 404s are fixed by #859 which is still waiting on action by someone on the Spanish team.

**Pull request merged**
