### PR TITLE
Update analisis-voyant-tools.md

### LINKED ISSUE #3042: Replace broken link in /es/lecciones/analisis-voyant-tools
Hello @charlottejmc. Our build checks have identified a broken link in the ES original lesson [Análisis de corpus con Voyant Tools](https://programminghistorian.org/es/lecciones/analisis-voyant-tools). 

The problem link is in the [Buscar textos section of the lesson](https://programminghistorian.org/es/lecciones/analisis-voyant-tools#1-buscar-textos) where you will notice an icon is missing at the end of the paragraph. It appears to be a link directing to a small image of a DOI badge. 

To reiterate, my workflow tends to begin by roughly translating the surrounding paragraph, so that I understand the context well enough to identify a possible alternative link. 

In this case, I navigated to the Zenodo asset which is referenced <https://zenodo.org/records/2547051#.XE9pc1z0mUk>. In the righthand panel headed Details, I can see the DOI badge and I think the replacement link needed will be this one: <https://zenodo.org/badge/DOI/10.5281/zenodo.2547051.svg>. (I must say, I'm a bit confused by the link that's in place, which seems to include a different asset reference 143443132 🤔)

If you have time, do you want to work through the steps of preparing a PR to update this? You're already getting the hang of this brilliantly, but it is good to practice! 🙂 

Technically, broken link fixes count as lesson maintenance tasks, so when it's ready we tag the appropriate Managing Editor(s) for a review. So, in this case, Jenn.

### PR DESCRIPTION
**Pull request by charlottejmc**
Fix broken link to DOI identifier
Closes #3042 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Add the appropriate "Label"
- [x] If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above
- [x] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Assistant @anisa-hawes 
- [x] Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)
- [x] Assign at least one individual or team to "Reviewers"
  - ~[ ] if the text needs to be translated, please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines), then assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR.~

### CODE REVIEW

**Comment by charlottejmc** [comment]
Hola @jenniferisasi,

I have added you as a reviewer so that you could check the change I made (in dialogue with @anisa-hawes). This is a broken-link fix + a small adjustment. We've removed the DOI icon, and added the full citation in a box.

**Comment by anisa-hawes** [comment]
Thank you, @charlottejmc. I'm happy with this, but will wait for @jenniferisasi to confirm she's happy too. ☺️

**Comment by rivaquiroga** [comment]
Hi @charlottejmc! I just realized that my Twitter account is mentioned in this lesson. I'm not very active in Twitter so I'll change the link to my personal website.

**Comment by jenniferisasi** [comment]
Oh, I was about to approve the change :)

**Review by anisa-hawes — APPROVED** [review]

**Pull request merged**
