### PR TITLE
Proposal in workflow

### PR DESCRIPTION
**Pull request by jerielizabeth**
Added paragraph to new lesson workflow to note the proposal ticket in the submissions repository and the 90 days to submission window. Please let me know if the language looks good to everyone.

Also flagging @mariajoafana @arojascastro for changes to the Spanish version of the page.

### CODE REVIEW

**Comment by arojascastro** [comment]
Thanks, I'll take this @jerielizabeth.

**Comment by acrymble** [comment]
Looks fine. Will this be folded into @fredgibbs changes on the new site?

**Comment by jerielizabeth** [comment]
Thanks @arojascastro! Would a separate ticket still be useful?

**Comment by arojascastro** [comment]
As you prefer, if you want to merge we can create a ticket. I will work on this tomorrow though.

**Comment by jerielizabeth** [comment]
@arojascastro If this works for you, I'll let the pull request ticket function as the issue ticket. 

I'll be sure to assign the spanish team on future pull requests to flag translation work more clearly.

**Comment by arojascastro** [comment]
Yes, please @jerielizabeth. I actually was flagged in two more issues, but I cannot find them at the moment. I think one is this precisely. But I cannot find the other one. I always use the "asignee" and "spanish" tag to find out which tasks I need to do - that is good enough.

**Comment by arojascastro** [comment]
Hi @jerielizabeth I have added the paragraph in 503042b. You can merge the request and close this issue. Thanks.

**Pull request merged**
