### PR TITLE
move English pages to /en directory - partial?

### PR DESCRIPTION
**Pull request by acrymble**
related to #826 I've moved all core English pages and lessons EXCEPT index.md to a new /en folder, in line with what we have for spanish. This includes the following pages:

about.md
author-guidelines.md
contribute.md
editor-guidelines.md
feedback.md
lesson-retirement-policy.md
lessons.md
project-team.md
research.md
reviewer-guidelines.md
/lessons..

As requested, I have also added redirect_from: yml tags to all affected files.

This is ALL I have done so if there are other files or processes affected they will not be included in this work to date.

### CODE REVIEW

**Comment by acrymble** [comment]
I suspect that these files will also need to be updated:

https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/snippets.yml
https://github.com/programminghistorian/jekyll/blob/gh-pages/_config.yml

**Comment by walshbr** [comment]
Phew thanks for all this, @acrymble! The [tests](https://travis-ci.org/programminghistorian/jekyll/builds/379567474?utm_source=github_status&utm_medium=notification) show some other places where some links need to be updated. Looks like there are a few places where pages, posts, or lessons linked to pages or assets internally where we'll need to add an 'en' to the path of the link (I assume) -

```
- ./_site/en/author-guidelines.html
  *  internally linking to lessons, which does not exist (line 151)
     <a href="lessons">published lessons</a>
- ./_site/en/editor-guidelines.html
  *  internal image images/editor-guidelines/gh_commits_location_screen.png does not exist (line 517)
- ./_site/en/lessons/dealing-with-big-data-and-network-analysis-using-neo4j.html
  *  internally linking to ../assets/dealing-with-big-data-and-network-analysis-using-neo4j/edges_director_duration.csv, which does not exist (line 477)
     <a href="../assets/dealing-with-big-data-and-network-analysis-using-neo4j/edges_director_duration.csv">edges_director_duration.csv</a>
  *  internally linking to ../assets/dealing-with-big-data-and-network-analysis-using-neo4j/nodes_companies.csv, which does not exist (line 476)
     <a href="../assets/dealing-with-big-data-and-network-analysis-using-neo4j/nodes_companies.csv">nodes_companies.csv</a>
- ./_site/en/lessons/extracting-keywords.html
  *  internally linking to ../assets/extracting-keywords-final-gazetteer.txt, which does not exist (line 701)
     <a href="../assets/extracting-keywords-final-gazetteer.txt">completed list of English and Welsh counties, shortforms, and various other cities (London, Bristol etc) and places (Jersey, Ireland, etc)</a>
- ./_site/en/lessons/generating-an-ordered-data-set-from-an-OCR-text-file.html
  *  internally linking to ../assets/Roman_to_Arabic.txt, which does not exist (line 526)
     <a href="../assets/Roman_to_Arabic.txt">this little script</a>
- ./_site/en/lessons/geocoding-qgis.html
  *  internally linking to ../assets/AlumniCounties.csv, which does not exist (line 372)
     <a href="../assets/AlumniCounties.csv">AlumniCounties.csv</a>
  *  internally linking to ../assets/The_Dataset-Alum-Oxon-Jas1-Placenames.csv, which does not exist (line 371)
     <a href="../assets/The_Dataset-Alum-Oxon-Jas1-Placenames.csv">The_Dataset-Alum-Oxon-Jas1-Placenames.csv</a>
- ./_site/en/lessons/json-and-jq.html
  *  internally linking to ../assets/count_retweets.txt, which does not exist (line 1209)
     <a href="../assets/count_retweets.txt">See my answer.</a>
  *  internally linking to ../assets/filter_retweets.txt, which does not exist (line 1193)
     <a href="../assets/filter_retweets.txt">There are multiple ways to solve this with jq. See my answer here.</a>
  *  internally linking to ../assets/jq_rkm.json, which does not exist (line 439)
     <a href="../assets/jq_rkm.json">rkm.json</a>
  *  internally linking to ../assets/jq_twitter.json, which does not exist (line 734)
     <a href="../assets/jq_twitter.json">Then copy this sample Twitter data</a>
- ./_site/en/lessons/sonification.html
  *  internally linking to ../assets/sonification-diary.csv, which does not exist (line 353)
     <a href="../assets/sonification-diary.csv">Excerpt from the Topic model of John Adams’ Diary</a>
  *  internally linking to ../assets/sonification-diary.csv, which does not exist (line 609)
     <a href="../assets/sonification-diary.csv">This file</a>
  *  internally linking to ../assets/sonification-jesuittopics.csv, which does not exist (line 354)
     <a href="../assets/sonification-jesuittopics.csv">Excerpt from the Topic model of the Jesuit Relations</a>
  *  internally linking to ../assets/sonification-jesuittopics.csv, which does not exist (line 766)
     <a href="../assets/sonification-jesuittopics.csv">sample file</a>
  *  internally linking to ../assets/sonification-roman-data.csv, which does not exist (line 352)
     <a href="../assets/sonification-roman-data.csv">Roman artefact data</a>
  *  internally linking to ../assets/sonification-roman-data.csv, which does not exist (line 445)
     <a href="../assets/sonification-roman-data.csv">sample dataset</a>
  *  internally linking to ../assets/sonification-roman-data.csv, which does not exist (line 448)
     <a href="../assets/sonification-roman-data.csv">sonification-roman-data.csv</a>
  *  internally linking to ../assets/sonification-romancoin-data-music.csv, which does not exist (line 454)
     <a href="../assets/sonification-romancoin-data-music.csv">this</a>
  *  internally linking to ../assets/sonification-romancoin-data-music.csv, which does not exist (line 456)
     <a href="../assets/sonification-romancoin-data-music.csv">demo file for this tutorial</a>
- ./_site/en/lessons/transforming-xml-with-xsl.html
  *  internally linking to ../assets/scissorsandpaste-master.zip, which does not exist (line 446)
     <a href="../assets/scissorsandpaste-master.zip">here</a>
- ./_site/posts/dh-award-2016.html
  *  internally linking to /lessons/text-mining-with-extracted-features, which does not exist (line 189)
     <a href="/lessons/text-mining-with-extracted-features">Text Mining in Python through the HTRC Feature Reader</a>
- ./_site/posts/retirement-and-sustainability-policies.html
  *  internally linking to /lessons/retired/counting-frequencies-from-zotero-items, which does not exist (line 197)
     <a href="/lessons/retired/counting-frequencies-from-zotero-items">Counting Frequencies from Zotero Items</a>
- ./_site/posts/roundup2017a.html
  *  internally linking to /lessons/intro-to-linked-data, which does not exist (line 210)
     <a href="/lessons/intro-to-linked-data">Introduction to the Principles of Linked Open Data</a>
  *  internally linking to /lessons/using-javascript-to-create-maps, which does not exist (line 208)
     <a href="/lessons/using-javascript-to-create-maps">Using JavaScripts to Create Maps of Correspondence</a>
- ./_site/posts/twenty-sixteen-review.html
  *  internally linking to /lessons/text-mining-with-extracted-features, which does not exist (line 178)
     <a href="/lessons/text-mining-with-extracted-features">text mining the HathiTrust collection of 15 million digitised volumes</a>
```

**Comment by acrymble** [comment]
Looks like it's picking up in particular ../ links.

**Comment by walshbr** [comment]
@mdlincoln can correct if I'm wrong, but I think in the cases where we reference assets we want to the paths to begin with '/assets/etc' and not '../assets/etc' unless we are planning to also move the assets folder to be inside 'en', which I don't think we are. The '/assets' bit will look to the root of the project rather than inside the en folder, as the '../assets' will.

**Comment by acrymble** [comment]
So is this an exhaustive list of the links that need fixing? I had been doing that manually and there were a lot more internal links than have been flagged here.

**Comment by walshbr** [comment]
I think so theoretically! Still might be other work remaining that travis isn't catching, but it looks like you got most of them already. Travis is only showing those 27 failed links at the moment. At a glance it looks like the remaining stuff there are blog posts that link to things, references to assets, and the odd standalone page.

**Comment by acrymble** [comment]
Ok, I have fixed the broken links. I also realised I was using the old version of author-guidelines, so I've updated it. Is there anything else to change?

**Comment by mdlincoln** [comment]
Thanks for sending this in @acrymble I really appreciate you taking a stab at it. I will be able to take a close look this weekend.

**Comment by mdlincoln** [comment]
After patching up some of the remaining problems, I think we now have a functioning build.

How do we want to do the landing page at https://programminghistorian.org though?

**Comment by acrymble** [comment]
Maybe leave it for now until new French team has a say? As it stands, we can't really make any other edits while this is open.

**Review by mdlincoln — APPROVED** [review]

**Comment by mdlincoln** [comment]
That's fine with me. Are there any other outstanding problems before we merge?

**Comment by acrymble** [comment]
I don't think so. I guess we'll have to see if we've broken anything!

**Pull request merged**
