### PR TITLE
#2784 insertion of blog post

### LINKED ISSUE #2784: Adding to the blog
@anisa-hawes 

I'd like to ake a blog post containing the end-of-year information I've been sharing on Twitter.

I haven't yet used the blog - can you tell me how to do it?

### PR DESCRIPTION
**Pull request by GeeAlmeida**
New blog post
Closes #2784 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

### CODE REVIEW

**Comment by GeeAlmeida** [comment]
Thanks for finishing this off @anisa-hawes. I think it looks ready to be published!

**Review by anisa-hawes — CHANGES_REQUESTED** [review]
Hello @GeeAlmeida. 

I notice that Picture1.png includes a feint red underline below the word Programme (I think Google Slides is detecting it as a spelling error because it is the British English spelling). The red line will disappear if you add the word 'programme' to your dictionary, or click to ask Google to ignore the spelling. 

I should have included this in the instructions I shared with you in the Issue: Ideally both images should be reduced in size to a maximum of 840px on the longest side, which is important for readers in countries with slower internet speeds. At a glance, I think Picture2.png is about right, but Picture1.png (IPP logos) and Picture3.png (Map Warper) could benefit from being a bit smaller. 

It would be good to delete any images which you didn't use in this post in the end – they will just take up space on our repository!

**Comment by GeeAlmeida** [comment]
> 

Hi Anisa

Thank you for this.

I don't know how to reduce the images. The logos image can't be too small, otherwise the logos will not look good.

**Comment by anisa-hawes** [comment]
Hello @GeeAlmeida.

I'm sending you an email to explain this.

A.

**Comment by GeeAlmeida** [comment]
Hi Anisa

Can you have a look now?

**Comment by anisa-hawes** [comment]
I think it looks good, @GeeAlmeida. 

I liked the images ! I can resize them for you, if you like? (I know it is a bit fiddly and annoying). 

Otherwise, I'm happy to approve.

**Comment by GeeAlmeida** [comment]
Nah, no images...

**Review by anisa-hawes — APPROVED** [review]

**Pull request merged**
