### PR TITLE
Team page update2020

### PR DESCRIPTION
**Pull request by acrymble**
This is a big update to the various role labels people hold for the Project Team page, which was getting quite out of date. It includes adding 2 new members and tweaking a few things so people hopefully have fewer tags next to their names to reflect duplication.

Not ready for review yet.

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by jenniferisasi** [comment]
@acrymble let me know when ready if you want me to take a look. 

Noticing now that only 4 of us in the entire team are institutionally supported, that's too small .

**Comment by acrymble** [comment]
What this pull request does:

1. Updates all team members to their current agreed roles. Removes some duplication (eg ME no longer listed as ME + Editor).
2. Updates bios, photos, and affiliations, etc, as required.
3. Changes the display from bio to affiliation. This means the page can be updated without the need for translation in future, which reduces translation burden and eases burden of new teams.
4. Removes "Impact Manager" role, which was never filled.
5. Removes the long lists of contributors from the project page (I originally tried moving this to the /supporters page but it made it look messy and we just redid that page).
6. Removes the authors_loop.html and collaborators_loop.html includes, which were used in 5.

@jenniferisasi this is ready for your review or for discussion (I can meet on a Friday of your choosing if that's easier).

I think this is a simpler and easier to maintain version of the page.

**Comment by DanielAlvesLABDH** [comment]
@acrymble thanks for all the work with this. One question: is it possible to change my photo using this branch?

**Comment by acrymble** [comment]
@DanielAlvesLABDH yes can you email it to me?

@jenniferisasi I realised this change leaves @JMParr not appearing. We may have to think where she will go on this.

**Comment by acrymble** [comment]
@walshbr @amsichani a query for you both as I try to work out how best to represent the "Publisher" team on the /project-team page.

I've amended this in the pull request to only include the ProgHist Ltd team (since a number of us aren't on individual publication teams) but this leaves out Jess who is only on the Global Team. What I want to avoid is a meaninglessly large "Publisher" team listing. If I were to include the Proghist team and the "team leaders" of Global, Comms, and Tech, would the two of you feel left out or otherwise slighted, since it didn't list you too? The "technical" tag still appears next to your name in your respective publication.

Please be honest. I'm just looking for the most accurate but also least verbose way of representing our project team.

**Comment by walshbr** [comment]
Is that because we're the only non-leaders on the ProgHist LTD group that are also elsewhere in the project? I'm not sure it matters to me too much. I appreciate you asking, but it feels like it's largely an internal bureaucratic question. I'm not sure it matters to me how it gets represented to the public in this instance.

**Comment by jenniferisasi** [comment]
> What this pull request does:
> 
> 1. Updates all team members to their current agreed roles. Removes some duplication (eg ME no longer listed as ME + Editor).
> 2. Updates bios, photos, and affiliations, etc, as required.
> 3. Changes the display from bio to affiliation. This means the page can be updated without the need for translation in future, which reduces translation burden and eases burden of new teams.
> 4. Removes "Impact Manager" role, which was never filled.
> 5. Removes the long lists of contributors from the project page (I originally tried moving this to the /supporters page but it made it look messy and we just redid that page).
> 6. Removes the authors_loop.html and collaborators_loop.html includes, which were used in 5.
> 
> @jenniferisasi this is ready for your review or for discussion (I can meet on a Friday of your choosing if that's easier).
> 
> I think this is a simpler and easier to maintain version of the page.


1, 2 and 3: good idea! I liked to see what each of us work on but it is true that it poses a burden on translation on any updates of the profiles.
4 and 6: fine as well. 
5. Is this going to still be somewhere? 

@acrymble my only recommendation here is that we keep the way we had to go directly to a team or, alternatively, that we create an `if condition` by which teams are moved to the top `depending on the language of the page`. Not the end of the world if we don't have that, but from a user perspective I think it can be frustrating to have to scroll like that, and the list will only but get longer soon (thinking FR team recruitment)

**Comment by acrymble** [comment]
@jenniferisasi I put the table of contents back and I've added in the team leads to the "ProgHist Ltd" team (which is not strinctly accurate but gets the right message across to readers I think). I think this is ready if you're happy with it.

**Comment by jenniferisasi** [comment]
Looking much better now, @acrymble thanks for incorporating the table back. 

I am wondering if we want to already Daniel Alves on the first "Please direct correspondence in the first instance to:" ?

**Comment by acrymble** [comment]
@jenniferisasi the logic for adding Daniel is linked to adding the PT pages officially to the site. So that will automatically happen when the tech team finishes the PT integration.

**Review by jenniferisasi — APPROVED** [review]

**Comment by jenniferisasi** [comment]
> @jenniferisasi the logic for adding Daniel is linked to adding the PT pages officially to the site. So that will automatically happen when the tech team finishes the PT integration.

I see, makes sense. I should have checked the code/page, as I assumed it was just written in there.

**Pull request merged**
