### PR TITLE
Edit Lux IPP name upon request from C2DH

### PR DESCRIPTION
**Pull request by drjwbaker**
Per title. They asked for "Centre for Contemporary and Digital History, Université du Luxembourg, Luxembourg".

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] ~if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description~
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by drjwbaker** [comment]
@jenniferisasi @acrymble before I start looking around for ES/FR/PT equivalent pages and doing the wrong thing, can someone confirm that I still need to edit the 'old' style IPPs pages. Thanks!

**Comment by acrymble** [comment]
/es/colaboradores.md
/fr/nos-soutiens.md
/pt/apoie-nos.md

**Comment by drjwbaker** [comment]
@acrymble thanks. @jenniferisasi this is now ready for review.

**Review by jenniferisasi — APPROVED** [review]
Looks good!

**Pull request merged**
