### PR TITLE
Issue 2523 topic r

### PR DESCRIPTION
**Pull request by jenniferisasi**
As we are receiving more and more lessons that use R as the language to do some research, and after a couple of conversations about it here and there (for example, it is hard to find R with the search option only), the tech-team is going to add "R" as a topic for lessons.

This includes adding a new type in the _data/topics.yml file and then adding R as a topic to existing and new lessons. I am going to start with the lessons in Spanish to make sure the change works.

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
 ~if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description~
- [x] Add the appropriate "Label"
- [ ] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by jenniferisasi** [comment]
It worked! 

image

Ok, so now I'd like to communicate to @rivaquiroga @spapastamkou @DanielAlvesLABDH @svmelton that we can now include "R" as a topic for the lessons. With a bit of patience, I will modify the already published lessons myself, and then @anisa-hawes can approve this. 

and I'll fix the broken link

**Comment by jenniferisasi** [comment]
Hmm @anisa-hawes we have bigger trouble with the broken link. It's a repository that we used to point to in our 4 editorial guidelines, for the editors to search for an image that can serve as thumbnail for the lessons. Looks like the Internet Archive still has a Flickr account but the particular [Internet Archive Book Images](https://www.flickr.com/photos/internetarchivebookimages) account disappeared :/ shall we look for something similar or get rid of the source?

**Comment by ZoeLeBlanc** [comment]
Ya looks like even their IA collection is broken https://archive.org/details/bookimages?tab=collection . Might be worth pointing ppl to either something like unsplash or maybe LOC http://www.loc.gov/pictures/ ... really annoying since these images helped us have a consistent visual for lessons 😭 .

**Comment by spapastamkou** [comment]
thanks for this, @jenniferisasi. We only have one lesson published in French, let me know if/when you want us to do smth.

**Comment by jenniferisasi** [comment]
> Ya looks like even their IA collection is broken https://archive.org/details/bookimages?tab=collection . Might be worth pointing ppl to either something like unsplash or maybe LOC http://www.loc.gov/pictures/ ... really annoying since these images helped us have a consistent visual for lessons 😭 .

The [British Library Flickr](https://www.flickr.com/photos/britishlibrary/) is still working and they have also plenty of images from books in it (that's actually the one I always used). The LoC one seems to have too many pictures and paintings? Not saying it's bad, but it is going to take a lot of browsing, I'm afraid, to get to something similar to our style :/

**Comment by rivaquiroga** [comment]
:broken_heart: Internet Archive Book Images :sob:

**Comment by svmelton** [comment]
Nooooooo not the IA book images! :( :( :(

**Comment by anisa-hawes** [comment]
Oh dear... ! 

I’ve emailed the Internet Archive to ask if the broken link to their Book Images Flickr collection is a temporary glitch, or if it has been permanently removed… Let’s see if they come back with any news…

I’m not certain what the best interim solution is, but I think we have two options:
1. We temporarily replace the link with <https://archive.org/details/bookimages> even though the images there are broken, the URL works.
2. We remove the link to that resource for the time being?

**Comment by anisa-hawes** [comment]
I am going to update the link to <https://archive.org/details/bookimages> for now, even though this is an imperfect solution.  I am confident that it's a temporary problem and the Book Images collection is intended to be made accessible again. I will set myself a reminder to check back on this next week.

**Review by anisa-hawes — APPROVED** [review]

**Pull request merged**
