### PR TITLE
Gold Tier for en/ipp, es/pia, fr/pi, pt/ppi

### LINKED ISSUE #2380: Add Gold Tier IPP membership option
I am adding a Gold Tier IPP membership option to en/ipp, es/pia, fr/pi, pt/ppi.

### PR DESCRIPTION
**Pull request by anisa-hawes**
We are adding a Gold Tier IPP membership option to en/ipp, es/pia, fr/pi, pt/ppi. I've written two sentences to introduce Gold Tier Partnership rates.

If anyone from the @programminghistorian/spanish-team @programminghistorian/french-team and @programminghistorian/portuguese-team have time, the sentences to be translated into ES, FR and PT are: 

_If your institution has resource to offer us even greater support, we also welcome Partnerships at our Gold Tier. Gold Tier Partnership rates are [£3,000 GBP / $4,200 USD / €3,600 EUR / $5,100 CAD*]._

*I note that FR and PT use different currencies. In each currency the Gold Tier rates are x3 the upper rate. 

Closes #2380 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [ ] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [ ] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by DanielAlvesLABDH** [comment]
PT
Se a sua instituição tem recursos para nos oferecer um suporte ainda maior, também damos as boas-vindas a parcerias no nosso nível Gold. As taxas de parceria do nível Gold são €3.600 EUR, $21.000 BRA, £3.000 GBP, $4.200 USD, $5.100 CAD.

**Comment by jenniferisasi** [comment]
ES
Si tu institución tiene recursos para apoyarnos con una cantidad mayor, también agradecemos aportaciones de Instituciones Asociadas en nuestro nivel Gold. Las tarifas de Gold Tier Partnership son £3.000 GBP, $4.200 USD, €3.600 EUR, $5.100 CAD.

Though if someone can double check, please, cos this wording always sounds weird to me (simply cos I am not used to business jargon)

**Comment by anisa-hawes** [comment]
Thank you @DanielAlvesLABDH and @jenniferisasi! If anyone from the @programminghistorian/french-team has time to translate these sentences, I can update the pages across our site.

**Comment by InesSalome** [comment]
FR
Si votre institution a les moyens de nous offrir un plus grand soutien encore, nous accueillons également des partenariats à notre niveau Gold. Les tarifs du partenariat niveau Gold sont d'un montant de 3 600 EUR, 3 600 CHF, 5 100 CAD, 3 000 GBP, 4 200 USD. 

This is a first draft, if anyone of the @programminghistorian/french-team has time to check it will be welcomed :)

**Comment by anisa-hawes** [comment]
Thank you, Gwenaëlle @InesSalome! I will come back to this PR next week when others have had time to check. Wishing you a restful weekend.

**Review by drjwbaker — DISMISSED** [review]

**Pull request closed without merging**
