### PR TITLE
Update editorial guidelines to reflect ph-submissions restructuring

### LINKED ISSUE #1968: Update submission guidelines to reflect reorganization of ph-submissions folder
Breaking off part of #1795. The ph-submissions repo was a bit of a mess, with each team using their own pattern of organizing submitted lessons. I've emailed the managing directors of each language (should have just been a ticket from the go but alas) and gotten approval for this system going forward - 

/fr/lecons/
/es/lecciones/
/en/lessons/
/pt/licoes/

Though the teams are free to make their own subdirectories within their own language folders moving forward, of course. This makes things more consistent. I've already set this up on the ph-submissions side, so we just need to update the URLs in the docs to reflect where new things will be placed.

Note that the fix will apply things for future lessons only - we'll let the old lessons uploaded in weird places under the old system finish and close out rather than trying to move a ton of stuff around. So it should be the case that this will clean up the future and then past will quietly move along until it's up to date as well.

### PR DESCRIPTION
**Pull request by walshbr**
Closes #1968. This clarifies where documents should go in the ph-submissions repository. Note also that since this reflects the URL needed to preview that we paste at the top of the lesson it required small changes in a few places.

### CODE REVIEW

**Comment by walshbr** [comment]
@jenniferisasi since you were the person I talked to most about this restructuring can you check that this makes sense before I tag the  Pt, Fr, and Es teams to translate?

**Comment by jenniferisasi** [comment]
@walshbr it makes sense to me

**Comment by walshbr** [comment]
Ok. @programminghistorian/french-team @programminghistorian/spanish-team and @programminghistorian/portuguese-team - there are some small pieces to translate here to reflect the restructuring of the ph-submissions repository. Let me  know if you have any questions and please approve when you have finished your piece. You can see files changed here -https://github.com/programminghistorian/jekyll/pull/1979/files

Thank you!

**Comment by walshbr** [comment]
Also note that, when looking at the pieces to translate, you should have "fr/es/pt" in place of where the URLs list "en". The abbreviation appropriate to your language. Thanks!

**Review by DanielAlvesLABDH — DISMISSED** [review]

**Comment by DanielAlvesLABDH** [comment]
Done!

**Review by spapastamkou — APPROVED** [review]

**Comment by walshbr** [comment]
@jenniferisasi - I saw you updated the spanish docs. Was that done or did you need more time? No worries if you need more, but wasn't sure if you  just  forgot to approve.

**Review by jenniferisasi — APPROVED** [review]

**Comment by jenniferisasi** [comment]
> @jenniferisasi - I saw you updated the spanish docs. Was that done or did you need more time? No worries if you need more, but wasn't sure if you just forgot to approve.

I kind of didn't want to approve myself, but I re-read it and seems fine.

**Pull request merged**
