### PR TITLE
Publicar Download de Múltiplos Registros usando Query Strings

### PR DESCRIPTION
**Pull request by DanielAlvesLABDH**
Publicar a tradução da lição "Downloading Multiple Records Using Query Strings"

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by DanielAlvesLABDH** [comment]
Dear @anisa-hawes my knowledge of Markdown is limited and although everything seems fine with the preview of this lesson, on line 41 the link and the italics doesn't work correctly inside the div. Can you help, please?
"[Teaching Tolerance](https://www.tolerance.org); Peggy McIntosh, ‘White Privilege: Unpacking the Invisible Knapsack’, _Peace and Freedom Magazine_, (1989), 10-12; Binyavanga Wainaina, ‘How to Write About Africa’, _Granta_ (92): 2006. "

**Review by joanacvp — DISMISSED** [review]
Fiz uma revisão final de ortografia e concordância. Está pronto a ser publicado

**Comment by DanielAlvesLABDH** [comment]
@anisa-hawes I think I have found the solution: https://meta.discourse.org/t/markdown-links-not-working-within-a-div/150145/15
It seems that we must leave an empty line between the div tag and the rest of the markdown

**Comment by DanielAlvesLABDH** [comment]
> @anisa-hawes I think I have found the solution: https://meta.discourse.org/t/markdown-links-not-working-within-a-div/150145/15 It seems that we must leave an empty line between the div tag and the rest of the markdown

Apparently not :-(

**Comment by DanielAlvesLABDH** [comment]
@joanacvp quando puder aprove de novo, por favor

**Review by joanacvp — APPROVED** [review]

**Comment by joanacvp** [comment]
Aprovado

**Comment by anisa-hawes** [comment]
Dear @DanielAlvesLABDH. Apologies, as I did not see this before you merged in. I will correct this now in a separate PR.

**Pull request merged**
