### PR TITLE
Create merci blogpost - closes #1631

### LINKED ISSUE #1631: Say thanks to FR volunteer translators and reviewers
All: the @programminghistorian/french-team will soon be done with the translation editions we had started this fall and so the FR lessons will be integrated in the Twitter bot and will be diffused regularly from the PH twitter account. 

In this occasion, I thought it would be nice to make a blog post (or at least tweet) to thank all volunteers who spontaneously took contact with us and translated lessons from English, as well as the master of the Ecole des chartes (two of these translations come from their students and at least three more are ready for us to edit in the coming months). It is always nice to say thanks but there we were happily surprised of people spontaneously contacting us and I (want to) see it as a community in the making thing that could further encourage people to engage. 

What do you think? The blog post could go out some time in February once these three new lessons are published. All views and ideas welcome, and I ping @jenniferisasi as Communication Manager and @programminghistorian/french-team in particular.

### PR DESCRIPTION
**Pull request by spapastamkou**
*Créer blogpost de remerciements aux contributeurs et contributrices des leçons en français publiées à l'heure actuelle et en cours de préparation*

**Please do not merge, this is a draft!** 

@fdlaramee @grandjeanmartin @mariechristineb Qu'en dites-vous? Vous-vous qu'on change ou qu'on ajoute des choses? Vous pouvez intervenir directement dans le texte. D'avance merci! 
PS: Des idées pour ajouter une image sont bienvenues!

@jenniferisasi It is not urgent, can wait for you to have a look when you can. 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by mariechristineb** [comment]
@spapastamkou j'ai fait un commit au lieu de faire les changements dans une review, j'espère que ça va?

**Comment by spapastamkou** [comment]
@mariechristineb c'est plus que parfait, merci beaucoup!

**Comment by jenniferisasi** [comment]
@spapastamkou the post is good to go. I would only add maybe a link to the institution you mention (I think it is only one) since it is the usual Internet thing to do, but that is up to you

**Comment by spapastamkou** [comment]
Ok, I made some last additions, one photo included. Needs approval review to be merged. If you find the photo too big, someone drop me a comment and I will reduce the size. Otherwise we are ok with this, I think.

**Review by mariechristineb — CHANGES_REQUESTED** [review]
As you suggested, I would make the image smaller, and maybe center it in the article instead of having it on the left - other than that, everything's looking good!

**Comment by spapastamkou** [comment]
thank you so much, @jenniferisasi ! I ended up putting the image in a p tag with an align attribute and it is finally centered.

**Review by mariechristineb — APPROVED** [review]

**Pull request merged**
