### PR TITLE
Create translator-guidelines

### PR DESCRIPTION
**Pull request by jenniferisasi**
As per issue #1199 I have created a file for translator-guidelines in English for the three teams to collaborate. I will be adding to it, but please make any changes that you see fit. Assigning a few people but anyone can collaborate. 

This is a DRAFT pull request, so it won't be approved or merged until we explicitly request a review

### CODE REVIEW

**Comment by jenniferisasi** [comment]
Notes: 
- The division of author and translator guidelines means the author-guideline files need to be edited to avoid duplicates or confusion (such as the markdown template)
- I am copying all the instructions about plain text, etc. that still apply for writers, but I'm making changes to address translators as well as the markdown template.

**Comment by spapastamkou** [comment]
Thank you @jenniferisasi. How about making links towards the authors guidelines for instructions about writing, formatting and markdown? And concentrate on more translation-specific instructions such as the parts you have for example [here ](https://programminghistorian.org/es/guia-para-revisores#traducciones)in Spanish. While also introducing parts for inclusive writing (if any) and technical problems one might meet. I will contribute asap:)

**Comment by arojascastro** [comment]
I think it's good. We may add sentences saying that:

- we welcome translations in any variant of Spanish, but that we prefer using "tú" rather than "vos" or "usted" (this may also work for french and english, where they are other regional differences)
- we expect translators to translate variables and adapt code to make it work with accents and diacritics if possible
- we encourage translators to adapt images (changing titles, axes names, interface language, etc.)
- we appreciate the inclusion of explanatory notes and of bibliographic references in the target language

I am not sure if these recommendations should go here or in the document that @rivaquiroga is preparing.

**Comment by rivaquiroga** [comment]
That’s a good point @arojascastro. I think this document is like an overview of the process and the technical stuff involved in the translation (like file management, formatting, translating data and images, etc.). The other one is more oriented to style decisions (like using “tú” to address the reader), and to track our agreements about how to translate technical words. The idea is for it to be a wiki page, because we will probably be adding new agreements as we translate new lessons. 
What do you think?

**Comment by arojascastro** [comment]
I think these guidelines should contain an overview of our expectations - just a summary - and then provide a link to the wiki with further details.

**Comment by jenniferisasi** [comment]
I agree with @arojascastro and @rivaquiroga about this being an overview of our expectations to publish a translation and then having a wiki with detailed terminology, etc. 
@spapastamkou, the reason why I would prefer to have the brief markdown instructions here too is because it can get frustrating to having to navigate multiple pages. Of course we would need priority to a section such as [the one you refer to](https://programminghistorian.org/es/guia-para-revisores#traducciones). That's my take on this

**Comment by spapastamkou** [comment]
Could you coordinate the FR contribution here, on behalf of the francophone team, @mpuren? You could add in the PR whatever you think important for the translations and ask the rest of the FR team for input whenever you think necessary. What do you think?

**Comment by jenniferisasi** [comment]
I have finalized a standard page for translators. I have transposed the author guidelines to translation as the process of writing, submission, review and publication are the same in matters of working on markdown and GitHub. 

Please, let me know if you want us to change it further. Feel free to add to the document itself. 

@rivaquiroga how is the wiki page with recommendations coming along? That's the sentence and link this guide is missing with more specific translation details.

**Comment by arojascastro** [comment]
I think it looks very well. Congrats @jenniferisasi ! 

I would only clarify one sentence in *Translate a lesson* bullet list: "all variations are accepted" may be ambiguous. Maybe it would be clear to say "all linguistic variations are accepted" and perhaps give an example (British, American, Australian...) for each language. 

Thank you!

**Comment by jenniferisasi** [comment]
> "all variations are accepted" may be ambiguous. Maybe it would be clear to say "all linguistic variations are accepted" and perhaps give an example (British, American, Australian...) for each language.

You are right. Let me add that.

**Comment by jenniferisasi** [comment]
I have added a note on linguistic variations following @arojascastro suggestion. However, the English team would probably need to adjust the sentence according to issue #1209 as @acrymble added a point they will take into account: 
- Which version(s) of English we publish in (UK, US, Canadian, Australian, etc).

**Comment by arojascastro** [comment]
Some warnings:

- ./_site/en/lessons/understanding-regular-expressions.html
  *  External link http://regex.learncodethehardway.org/book/ failed: 404 No error
- ./_site/en/translator-guidelines.html
  *  internally linking to adam.crymble@gmail.com, which does not exist (line 182)
     <a href="adam.crymble@gmail.com">Adam Crymble</a>
  *  internally linking to en/translator-guidelines, which does not exist (line 211)
     <a href="en/translator-guidelines">the raw text on GitHub</a>
- ./_site/es/lecciones/escritura-sostenible-usando-pandoc-y-markdown.html
  *  External link http://cli.learncodethehardway.org/book/ failed: 404 No error
- ./_site/posts/PH-espanol-in-DH2018.html
  *  External link https://dh2018.adho.org/en/ failed: 404 No error
htmlproofer 3.10.2 | Error:  HTML-Proofer found 5 failures!
The command "_build/build.sh" exited with 1.

**Comment by acrymble** [comment]
@mdlincoln introduced some short codes for adding in managing editor details rather than hard coding it

**Comment by jenniferisasi** [comment]
> Some warnings: by @arojascastro 

Yes, I will check them little by little these days. But it clearly shows that we have an issue with external links in some lessons. I wrote to ADHO on May 6 about the webpage for DH2018 but haven't gotten back with the a solution yet.

**Comment by mpuren** [comment]
Thank you very much for these guidelines @jenniferisasi, they will be very useful. Maybe we can add a sentence concerning the use of inclusive writing for Spanish and French translations in the section Translating a lesson. I don't think a new section is needed for that. For French, we can also add a link towards guidelines (http://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?Th=1&Th_id=274) to help translators. I don't know if there are the same kind of guidelines for Spanish?

**Comment by jenniferisasi** [comment]
Thanks @mpuren! Yes, I agree with the inclusive language note, however this would have to go on our specific guidelines and this one is just the base in English for us to translate.

**Comment by jenniferisasi** [comment]
Is everyone happy with the wording in this file? Trying to close this by the next PH call.

**Comment by mdlincoln** [comment]
Sorry for the delay @jenniferisasi. I'm merging now because the PR check (which combines link fixes on this branch and in other branches) is passing.

**Pull request merged**
