### PR TITLE
initial commit for tfidf lesson

### PR DESCRIPTION
**Pull request by ZoeLeBlanc**
Just waiting for the author's bio and for his sign off on the abstract before merging.

Everything else should be good to go with the lesson, but please lmk if you see something I missed.

Thanks!

### CODE REVIEW

**Comment by acrymble** [comment]
Hi @ZoeLeBlanc I will take a look at everything. When editing future lessons remember that the workflow for publishing is:

5) Inform the Managing Editor to Publish

The Managing Editor will publish the lesson by moving the files to the main website and check everything over. To make this person’s job easier, post a list in the submission ticket of all files that need to be moved to publish the lesson. This should normally include:

    The lesson .md file
    The directory for any accompanying files (images, data, etc)
    The gallery icons
    A bio if the author is new

All except the bio should be represented as files somewhere in the ph_submissions repo. The bio can be placed in the ticket directly.

**Review by acrymble — DISMISSED** [review]
Thanks @ZoeLeBlanc for such a great job editing this lesson. I've read through it carefully now and I have a few minor queries that I think you can resolve quite easily.

Firstly, can you confirm that you've tried (including code and data) the lesson in its current form? We often find that in the process of review lessons get tinkered with and then something stops working but the full finished lesson doesn't get tried again until we send it out in the world.

In terms of minor issues. Please look at the following:

**Copy edits needed:**

* Missing table of contents
* Namely, if you want to know what words or phrases characterize a set of documents, it address how you can isolate one document’s most important words from the kinds of words that tend to be highly frequent in all documents in that language. (grammar)
* "the" should not be not italicized in "the _Programming Historian_".
* Addition, multiplication, and division are the primary mathematical operations necessary to follow along.  (this should be in the "before you begin" section because it's a required skill)

**Links or references needed** (usually Wikipedia is the best choice for linking)

Please add in lots of extra links on technical terms and cultural references. These let readers who don't know jargon words click a link for a quick explanation.

*Codeacademy’s “Introduction to Python” course,... introductory Python lessons on The Programming Historian
* (string, integer, float, list, tuple, dictionary), working with variables, writing loops in Python, and working with object classes/instances.
* Experience with Excel or an equivalent spreadsheet application if you wish to examine the linked spreadsheet files. You can also use the pandas library in python to view the CSVs. (can you suggest Libre Office?)
* Miniconda
* Python library called BeautifulSoup
* the Cochrane Collaboration
* Nellie Bly
* Elizabeth Cochrane Seaman
* Ironclad Manufacturing Company (basically any culturally specific term should be linked to wikipedia if possible so readers have somewhere easy to turn if they have never heard of something).
* corpus
* Scikit-Learn’s tf-idf implementation (reference needed)
* natural logarithm of a variable,
* Different normalization schemes would produce different scales. (a link or a reference to where we can learn more?)
* Jupyter Notebook
* loop-and-append operation
* list of stopwords
* tokenize
* Python library
* sparse matrix
* numpy array
* Nellie Bly, Willa Cather, W.E.B. Du Bois, Upton Sinclair, Ida Tarbell,
* stemming or lemmatization
* Chi-square test
* P-value

**Rights Query:**

To this end, I’ve prepared a dataset of 366 New York Times historic obituaries scraped from https://archive.nytimes.com/www.nytimes.com/learning/general/onthisday/. On each day of the year, The New York Times featured an obituary of someone born on that day. (Can we host that material legally? Even so do we need a note to say that while the lesson is CC-BY the data is not?)

**Internationalisation query:**

* Are "obituaries" commonly understood around the world? Or is that part of some cultures and not others? Maybe just a few words to say what it is, or a link to Wikipedia?
* You’ll notice that many of the historic figures are well known (to Americans of a certain age? can this statement be made culturally neutral?)
* but python stopwords='english' is available (what about other languages? Thinking about translation in future...)

**Formulas:**

* Use mathjax formatting rather than images for mathematical formulae
* Just asking because I dont' know and we should get it right: is it "n" rather than "N"?
* or example, Scikit-Learn’s implementation represents N as N+1, calculates the natural logarithm of (N+1)/dfi, and then adds 1 to the final result. (why?)

**Pedagogical Query:**

* To make the idf and tf-idf equations more concrete, I’ve added two new columns to the terms frequency table from before. The first new column represents the derived idf score, and the second new column multiplies the Count and Idf columns to derive the final tf-idf score.  (But how do I as the user do this? If I have to learn, I need to know how to replicate your work. Are you going to tell me soon? (you are...just let me know))
* or convenience, one might name a variable n so it’s easier and faster to type when referencing it. (this is a bad example in a statistics-focused lesson because "n" is often used in stats. I suggest "x" instead).

@mdlincoln might have additional comments on formatting.

It looks like a great lesson. Thanks @ZoeLeBlanc

**Comment by ZoeLeBlanc** [comment]
Thanks for the feedback Adam and apologies for mixing up the workflow. I really appreciate you going through and checking everything over.

I've listed the changes I've implemented here. I've pretty much gone ahead with all your listed changes, but feel free to let me know if I've missed anything. 

 -  Added the missing table of contents
-  Rewrote this section for clarity. "Namely, if you want to know what words or phrases characterize a set of documents, it address how you can isolate one document’s most important words from the kinds of words that tend to be highly frequent in all documents in that language." (grammar)
- Fixed "the" should not be not italicized in "the Programming Historian".
-  In this section, Matt's trying to make the reader feel comfortable with understanding algorithms. I think adding basic arithmetic to the "before you begin" section might be something that can be assumed, just like reading and writing. "Addition, multiplication, and division are the primary mathematical operations necessary to follow along. (this should be in the "before you begin" section because it's a required skill)"
- added links or references as needed
- tbh I’m not sure about the rights question. Have we had this issue before? I’m not a CC expert either so I really don’t know what the best approach. A quick google seems like web scraping is a grey area legally so not sure what that means for how we host the dataset.
- realize this dataset is very American, but I think Matt does a good job of talking about the constructed nature of the dataset. I did add links for all the historical figures he lists so hopefully that’s sufficient for those unfamiliar with them (tbh some were new to me too!)
- I added a link to the initial stop words list but tbh this is a huge debate over which stopwords to include for various languages. I think the fact that Matt highlights where you could change the code is sufficient.
- added mathjax formulae 
- large N here represents total number of documents in the corpus, whereas n would just represent a sampling from the corpus
- I’m confused by your question here. Are you asking how to calculate idf? Or tf-idf? Matt goes over the math for both of these formulae but doesn’t include the code since that’s abstracted in the scikit implementation. Are you suggesting that we include code as well?
- changed the _n_ variable to _x_ variable

Let me know if there's anything else I can do and Matt sent his final bio, so at this point I just need reviewers to sign off.

Thanks for all your help 😊

**Review by mdlincoln — APPROVED** [review]
ship it

 (ignore the last part of the gif)

**Comment by ZoeLeBlanc** [comment]
oh just realized was I suppose to wait for @acrymble to merge? Did I just mess up the Managing Editor workflow twice?? Oh gosh... dissertation brain is really messing with my ability to flow instructions.

Apologies if I did screw up Adam, but hopefully any additional changes can be merged in another branch. Next time I'll definitely remember to leave the branching and merging to you.

Should I go ahead and do the twitter bot and inform the author and reviewers?

**Comment by acrymble** [comment]
Yes, continue with the workflow on the editorial guidelines.

**Pull request merged**
