### PR TITLE
Update authors info and avatar for Eric Brasil

### PR DESCRIPTION
**Pull request by ericbrasiln**
As requested on issue #2302 , PR to update the `/data/ph_authors.yml` file with information about the new editor Eric Brasil. It also includes the editor's avatar in png format.

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by DanielAlvesLABDH** [comment]
Obrigado Eric. Parece-me que está tudo bem. Vamos aguardar apenas a revisão das traduções.
Dear colleagues from the EN, ES and FR teams, please check the translation of Eric's bio info. Thanks!

**Comment by DanielAlvesLABDH** [comment]
Dear @anisa-hawes the build is failing because of two broken links.
- ./_site/en/lessons/correspondence-analysis-in-R.html
  *  External link https://doi.org/10.18637/jss.v025.i01 failed: 404 No error
- ./_site/en/lessons/data_wrangling_and_management_in_R.html
  *  External link https://www.jstatsoft.org/article/view/v059i10 failed: 404 No error
On both links there is a warning of "Site Maintenance". Can you help on this, please?

**Review by rivaquiroga — APPROVED** [review]

**Comment by rivaquiroga** [comment]
@DanielAlvesLABDH, ES translation looks fine.
Regarding de broken links, when they are not working due to site maintenance, you can try again a couple of ours later to see if they are already up. I just re-run the build and now they are working :rocket:

**Review by spapastamkou — APPROVED** [review]

**Comment by DanielAlvesLABDH** [comment]
Thank you Riva! And Sofia!

**Review by DanielAlvesLABDH — APPROVED** [review]
@ericbrasiln as alterações foram aprovadas e este PR está pronto a seguir! Podes fazer merge. Parabéns pela primeira tarefa no PH! Abraço

**Review by svmelton — APPROVED** [review]

**Comment by ericbrasiln** [comment]
@DanielAlvesLABDH  
Obrigado, será um prazer trabalhar no projeto.
Merge efetuado!
 Uma dúvida: Vocês normalmente apagam ou mantém o branch depois do merge?

**Comment by DanielAlvesLABDH** [comment]
Obrigado @ericbrasiln. Eu tenho mantido sempre os branches. Algo que tenho de esclarecer numa próxima reunião.

**Pull request merged**
