### PR TITLE
Build now ignores blog posts per #2106

### LINKED ISSUE #2106: link checker to ignore blog
Can we please have our link checking service that activates on pull requests just ignore broken links in the blog? They aren't really core maintenance priorities and they really slow down simple updates. Asking @programminghistorian/technical-team if this is easy to do?

### PR DESCRIPTION
**Pull request by ZoeLeBlanc**
This PR has our build sequence ignore blog posts so that it doesn't prevent builds from happening and will close #2106 when merged.

We still need to come up with appropriate documentation to indicate that links may or may not be live on the blog.

### Checklist

- [ ] Assign yourself in the "Assignees" menu
- [ ] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [ ] Add the appropriate "Label"
- [ ] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Review by jenniferisasi — DISMISSED** [review]
I think we are fine with this.

**Comment by acrymble** [comment]
@ZoeLeBlanc is this something we can merge? Or that we can help you with?

**Comment by ZoeLeBlanc** [comment]
This PR is pretty much ready but just wondering where to add the info that the links are note kept up to date?

Thinking maybe in the blog description:
```
The Programming Historian blog is our space to share news about the project, ideas for how you might use technology in your work, and exciting examples of the Programming Historian applied in the real world. Subscribe to the RSS feed for new blog posts.
```
I could add "and please be advised these posts are not actively maintained and links may not work." Thoughts anyone?

**Comment by acrymble** [comment]
@ZoeLeBlanc I think it's incredibly unusual for a website to keep links updated. So I don't think any warning is needed.

**Comment by ZoeLeBlanc** [comment]
Screen Shot 2021-08-09 at 1 20 48 PM
These are the links ☝🏽 that are currently breaking in these lessons. I have meetings all afternoon and so won't get to this for a bit. If you want to move quicker @acrymble feel free to push up and merge a fix for them and that should clear the path to merge #2225 

Sorry for the delays!

**Comment by jenniferisasi** [comment]
I will finish something I have for work and then work on these broken links to be able to merge this issue.

**Comment by jenniferisasi** [comment]
Ok, I think I've removed all broken links now

**Comment by ZoeLeBlanc** [comment]
Thanks for all your hard work @jenniferisasi 🙏🏽 !!

**Review by jenniferisasi — APPROVED** [review]

**Comment by jenniferisasi** [comment]
Victory!

**Pull request merged**
