### PR TITLE
publishing map warper translation

### PR DESCRIPTION
**Pull request by hawc2**
Preparing to publish the translation of [Introduccion a Map Warper](https://programminghistorian.org/es/lecciones/introduccion-map-warper) into English, per ph-submissions ticket [#426](https://github.com/programminghistorian/ph-submissions/issues/426).

@anisa-hawes I could use some help getting the images to render. The original lesson in ph-submissions has links directly to that Github repo, because of a convention in the original spanish that seems to work best for rendering checklist images. 

@svmelton @rivaquiroga can you both review this pull request once @anisa-hawes and I work out the final markdown issues? It will be good to have both of you give this a look over since this lesson will be the first translation into English, and the new translation involves some adaptation of the original to new data and with new images, 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by hawc2** [comment]
@anisa-hawes just an update, I got all the links working it seems, but please double check.

@ericayhayes you worked alot on finessing the markdown, do you mind checking it one last time here on this [preview](https://deploy-preview-2711--ph-preview.netlify.app/en/lessons/introduction-map-warper)?

**Review by rivaquiroga — DISMISSED** [review]

**Comment by anisa-hawes** [comment]
Hello @hawc2. I've removed the words 'Step 4.' from title at line 228. This seemed out of place, because none of the other titles or sub-titles include numbers.

I also tested indenting liquid syntax, to see if this would resolve an issue I note in the Netlify Preview where an ordered list interspersed with images is being automatically re-numbered, and re-starts at 1. several times over...

That didn't work, so I'm going to try something else...

**Comment by anisa-hawes** [comment]
Hmm.... No, that didn't work either.

I note that Sarah [noted the same issue](https://github.com/programminghistorian/jekyll/pull/2708#discussion_r998877688) in the Shiny lesson. But I can't seem to click into the detailed diff to see how she resolved it?

**Comment by anisa-hawes** [comment]
[I've adjusted ](https://github.com/programminghistorian/jekyll/pull/2711/commits/746b133c587beeb7a70445caeca46c116ce7cfbb)the Markdown syntax for the ordered list between lines 174-207 to avoid the numbering re-starting at 1 several times over.

The way to do this was changing 1. to 1\., 2. to 2\. etc.

(I'll add this to my technical notes for setting up lessons).

**Review by anisa-hawes — DISMISSED** [review]

**Review by svmelton — DISMISSED** [review]

**Review by rivaquiroga — DISMISSED** [review]

**Comment by hawc2** [comment]
Thanks @anisa-hawes and everyone for approving. I made one minor line edit fix so the images list the Figure numbers in the captions, I guess that automatically 'dismissed your reviews' so at least one person needs to approve again before I can merge.

**Comment by anisa-hawes** [comment]
Thank you, @hawc2. I can re-approve when these checks are complete.

**Comment by anisa-hawes** [comment]
Oh, hang on... I thought that alt-text had been added to the images in this lesson? [Has something been missed](https://github.com/programminghistorian/ph-submissions/issues/426#issuecomment-1213892420)?

I've added the alt-text for the Figure images in, if you want [to check you're happy with them](https://github.com/programminghistorian/jekyll/pull/2711/commits/c3c04920af6739cfcd0b561a6f79725b8770ed96) @hawc2.

**Review by anisa-hawes — APPROVED** [review]

**Comment by hawc2** [comment]
Thanks all! Publishing now!

**Comment by anisa-hawes** [comment]
Hooray! ✨ This is our first translation into English! ✨ 

Gisele is away, but I'm happy to help co-ordinate some Twitter celebrations once the DOI is live.

**Pull request merged**
