### PR TITLE
Update colaboradores.md

### LINKED ISSUE #2775: Small correction to /es/colaboradores
I am making a small correction to /es/colaboradores.

### PR DESCRIPTION
**Pull request by anisa-hawes**
This is a very small correction – just removing an extra bullet point, l.42 of es/colaboradores.md

Closes #2775 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] ~~if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description~~
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Hello @GeeAlmeida,

Sorry to have missed this!  A small correction is needed. There's an extra bullet point in /es/colaboradores which makes our list a bit confusing.

Do you have time to Review this for me?

To re-cap: you can see the changes by clicking into the **Files changed** tab at the top of this page. On the left you will see deletions, and on the right hand side you will see additions. When you're happy click 'Viewed' in the upper right. Next, select Review Changes. A pop-up allows you to Comment, Approve or Request Changes then click to submit your review.

**Review by GeeAlmeida — COMMENTED** [review]
Yes, OK now!

**Comment by anisa-hawes** [comment]
Thank you, @GeeAlmeida.

Could you click into the **Files changed** tab, click to confirm you've 'Viewed' (upper right), then click 'Submit Review'.

**Comment by GeeAlmeida** [comment]
> Thank you, @GeeAlmeida.
> 
> Could you click into the **Files changed** tab, click to confirm you've 'Viewed' (upper right), then click 'Submit Review'.

I see a message that says "your review was submitted successfully" - I don't see the button you said...

**Review by GeeAlmeida — APPROVED** [review]

**Comment by GeeAlmeida** [comment]
> > Thank you, @GeeAlmeida.
> > Could you click into the **Files changed** tab, click to confirm you've 'Viewed' (upper right), then click 'Submit Review'.
> 
> I see a message that says "your review was submitted successfully" - I don't see the button you said...

Found it! Should all be ok now!

**Comment by anisa-hawes** [comment]
Screenshot 2022-12-02 at 17 44 54

Screenshot 2022-12-02 at 17 45 31

**Pull request merged**
