### PR TITLE
new original ES lesson: "Introducción a ImagePlot... " 

### PR DESCRIPTION
**Pull request by rivaquiroga**
New ES original lesson: "Introducción a ImagePlot y la visualización de metadatos de colecciones de imágenes"

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
 - [ ]  ~~if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description~~
- [x] Add the appropriate "Label"
- [x] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by jenniferisasi** [comment]
@rivaquiroga a note to say @mdlincoln is looking for an about to be published lesson.

**Comment by rivaquiroga** [comment]
@mdlincoln, @drjwbaker, this lesson is ready to be published and looking for a DOI

**Comment by mdlincoln** [comment]
We're working on the bulk upload of back-issue data now, and once that is sorted (hopefully in a day or two!) this lesson will be the test run of the new doi submission process with Sussex - which will involve just filling out a regular metadata form and emailling it to our contact, they'll send back the DOI to use. Will keep you updated, and thanks for your patience

**Comment by mdlincoln** [comment]
@rivaquiroga Thanks for your patience. After talking with Sussex some more, we arrived at an even simpler process that doesn't involve any forms! I have written documentation here:

https://github.com/programminghistorian/jekyll/wiki/How-to-Request-a-new-DOI

Please follow the instructions (and let me know if anything is unclear or confusing).

**Comment by rivaquiroga** [comment]
Thanks, @mdlincoln!

----
**DOI checklist**

- [x] Send mail to Sussex Library Cataloging
- [x] Add DOI to header and update PR
- [x] Merge PR
- [x] Check new lesson is loading at its public URL
- [x] Respond to Sussex email with CrossRef XML
- [x] Check DOI redirects when Sussex reply
- [x] Celebrate!

**Comment by rivaquiroga** [comment]
@jenniferisasi, @JoshuaGOB, this PR is now ready to be reviewed :rocket:

**Review by jenniferisasi — APPROVED** [review]
¡Excelente! Se ve genial, ¿no?

**Comment by rivaquiroga** [comment]
:tada: The lesson is now available at https://doi.org/10.46430/phes0046 :tada:

**Comment by JoshuaGOB** [comment]
Yay, gracias a todas. Thank you to all!

On May 15, 2020, at 09:47, Riva Quiroga <notifications@github.com> wrote:

﻿
🎉 The lesson is now available at https://doi.org/10.46430/phes0046 🎉

**Pull request merged**
