### PR TITLE
Publicar_introducao-ao-markdown

### PR DESCRIPTION
**Pull request by DanielAlvesLABDH**
*Publicar a tradução da lição "Introdução ao Markdown"*

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by DanielAlvesLABDH** [comment]
Could someone from the technical team (@programminghistorian/technical-team) help me with this? The build shows an error on the YAML header that I can't identify, and also a problem with a link... Thanks

**Comment by rivaquiroga** [comment]
@DanielAlvesLABDH, it seems that you have full links to PH website on the lesson (e.g. https://programminghistorian.org/en/lessons/sustainable-authorship-in-plain-text-using-pandoc-and-markdown). You need to use relative paths (/en/lessons/sustainable-authorship-in-plain-text-using-pandoc-and-markdown), so you need to remove https://programminghistorian.org from all of them.

**Comment by DanielAlvesLABDH** [comment]
Thanks @rivaquiroga! I corrected 2 links, but the error persists. In the middle of the lesson there are also other links using https://programminghistorian.org but they were like this in the original lesson, I think. They are examples for the lesson

**Comment by rivaquiroga** [comment]
It looks like the one on line 232 needs to be changed to (/pt/)

**Comment by DanielAlvesLABDH** [comment]
In lines 228, 232 and 246 there are those types of links but I don't think we should change that, because they are examples

**Comment by DanielAlvesLABDH** [comment]
I think I understand now. Hope now it works

**Comment by rivaquiroga** [comment]
In the original lesson line 228 is: `For more tutorials, please visit the [Programming Historian](/ "Programming Historian main page").` They are not using the complete url.
The Spanish version is like this:
`Para más tutoriales visita la página [The Programming Historian en español](/es).`

**Comment by DanielAlvesLABDH** [comment]
Many thanks for the help @rivaquiroga! Now it is finished!
@josircg quando puder fazer uma última revisão e aprovar, podemos publicar!

**Comment by rivaquiroga** [comment]
:tada:
This was a very tricky lesson to debug, as the content of the lesson involves creating links to PH website :open_mouth:

**Comment by jenniferisasi** [comment]
Excelente, @DanielAlvesLABDH! Que alegria ter este tutorial em mãos para uma aula que lecionarei em meados de julho e que requer instruções em português para alguns.

**Review by josircg — APPROVED** [review]

**Pull request merged**
