### PR TITLE
Issue 3116 : Publish /en/lesson/interactive-visualization-with-plotly

### LINKED ISSUE #3116: Preparing to publish new EN lesson interactive-visualization-with-plotly
I am opening this Issue to prepare interactive-visualization-with-plotly for publication.

### PR DESCRIPTION
**Pull request by anisa-hawes**
Preparing files for publication.

Closes #3116 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Add the appropriate "Label"
- [x] If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above
- [x] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Manager @anisa-hawes 
- [x] Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)
- [x] Assign at least one individual or team to "Reviewers"
  - ~~[ ] if the text needs to be translated, please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines), then assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR.~~

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Hello @hawc2.

I’ve staged interactive-visualization-with-plotly for publication. You can [read it through in Preview](https://deploy-preview-3117--ph-preview.netlify.app/) and let me know if you note anything which you'd like to adjust.

I'm tagging @scottkleinman here too. I've checked through and I think the interactive `html` plots are displaying + behaving as we intended, but I appreciate your perspective on this!

If you're both happy, we can publish this lesson next Wednesday when our colleagues at Sussex will be around to activate our DOI, and Charlotte & I can launch the promotions on social media.

Thank you,
A.

**Comment by hawc2** [comment]
@anisa-hawes this looks pretty perfect to me. I'm happy to report I was able to comfortably read this whole lesson on my phone, even all the interactive plots worked well on mobile.

**Comment by anisa-hawes** [comment]
Hello @hawc2. 

Thank you for this feedback! 

Scott has written to me separately to confirm that he's read the lesson as staged here in Jekyll, and is happy with the functionality and rendering of all the plots.

I'll request your review here now.

As explained above, I'd like to wait to publish this on Wednesday when we can also activate the DOI and launch promotion.

Thank you. A.

**Comment by hawc2** [comment]
@anisa-hawes I made one edit I should've caught earlier, I changed most occurrences of "tutorial" to "lesson". Should be good to go

**Review by hawc2 — APPROVED** [review]

**Pull request merged**
