### PR TITLE
Oct 2020 $15 patron

### PR DESCRIPTION
**Pull request by drjwbaker**
add new $15 patron to ES and FR (EN fixed via https://github.com/programminghistorian/jekyll/pull/1901)

*add the reason for your pull request here*

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] ~if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description~
- [x] Add the appropriate "Label"
- [ ] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by acrymble** [comment]
@drjwbaker is it possible to add this to the open pull request? As this will have to be added there anyway once the pages change:

https://github.com/programminghistorian/jekyll/pull/1901

**Comment by drjwbaker** [comment]
But I thought #1901 is for the EN-only pilot, right? This PR is for ES/FR pages.

**Comment by acrymble** [comment]
Ok. Are we doing a separate pull request to add him to the English page later?

**Comment by drjwbaker** [comment]
I did that https://github.com/programminghistorian/jekyll/pull/1901/commits/7d36d1fdcad1279d1e6ec298db586a9cc3afdf44

**Comment by acrymble** [comment]
@drjwbaker reminder that the Portuguese pages are now live (but not linked on the menu) so I think this needs adding to that file too.

**Comment by drjwbaker** [comment]
@acrymble Ack. I'd totally missed that. Thanks Adam. Fixed now.

**Comment by drjwbaker** [comment]
This just needs a review.

**Review by walshbr — APPROVED** [review]

**Pull request merged**
