### PR TITLE
S Graham's sonification tutorial

### PR DESCRIPTION
**Pull request by shawngraham**

### CODE REVIEW

**Comment by ianmilligan1** [comment]
Thanks for your submission, @shawngraham. **A live preview of your lesson [can be found here in our ph-submissions repo](http://programminghistorian.github.io/ph-submissions/lessons/sonification).**

I will be assuming the role of editor for your submission. First, I'll give it a read through and try the lesson and chat with you about the initial submission. After you've had a chance to respond to my initial suggestions, I'll solicit at least two peer reviewers and we'll engage with that process throughout. I'll make sure to keep you in the loop concerning all stages.

By default, our conversation on GitHub will be open. However, if you need to discuss anything privately, you can [e-mail me](mailto:i2millig@uwaterloo.ca). You can also contact @miriamposner if you feel there's a need for an ombudsperson to step in.

**Comment by ianmilligan1** [comment]
@shawngraham, thanks for this! [This commit consists of a first pass and some comments for you](https://github.com/programminghistorian/ph-submissions/commit/db9414364d078083f0e0b75ef52f4f554040315a). They're relatively minor. In particular:
- There are quite a few in-text citations - could we add some hyperlinks for reader convenience? 
- A few screenshots would help when introducing new software packages.  
- Making clear your structure of providing a conceptual introduction followed by a hands-on example (which I think is a great model, but it's different than many of our lessons so best to keep readers in the loop).  
- and assorted tiny typographical and markdown shenanigans.

Once you respond to these, can you ping me and I'll reach out to our reviewers. 

As always, a pleasure to work with you! :smile:

**Comment by shawngraham** [comment]
Ok, cool. You had me submit pull requests in two places. Where do I go now to make the edits you suggest? The ph-submissions repo you link to above? That's where I should be working now, right?

**Comment by ianmilligan1** [comment]
Yeah, as that's the repo I'll send to reviewers so they can read your lesson in all its glory. Thanks Shawn.

As we shift over to the new submission system, wanted to make sure we also had a request here so all of our watchers can participate in the conversation!

**Comment by shawngraham** [comment]
If I add screenshots, do you want me to store them in the sonification subfolder, and you want that funky link stuff rather than standard markdown, right?

**Comment by ianmilligan1** [comment]
Yes please - in a local subdirectory called `images`. And yeah, the [funky image stuff as seen here](http://programminghistorian.org/new-lesson-workflow) rather than standard markdown. Thanks as always!

**Comment by wcaleb** [comment]
The images subdirectory already exists over at the ph-submission repo; it's right under the root directory. Sorry that you've gotten caught in the midst of our experiments with the new system, but like Ian I think the best thing would be to make all your edits and added files over on the other repo, rather than on the branch you used to make this pull request. 

Sent from my iPhone

W. Caleb McDaniel
Associate Professor of History
Duncan College Master
Rice University

http://wcm1.web.rice.edu/
http://www.duncancollege.net/

**Comment by shawngraham** [comment]
Hmm.

I've just been addressing the issues Ian annotated my piece with in the ph-submissions folder, so @wcaleb I didn't see you note before making another pull request.I've been shoving my screenshots into a 'sonification-supporting-materials' folder, which also includes my sample data. 

Just so I'm clear:

In this repo (ph-submissions), I am to
1a. put my images into the images subfolder under the root directory
1b. leave my data files in my 'sonification-supporting-materials' folder?

Then, you want me to go back to the original jekyll repository that the new lesson workflow references and
2a. update my sonification.md file there
2b. put my images into an images subfolder there
2c. leave my data files in my 'sonification-supporting-materials' folder?

**Comment by ianmilligan1** [comment]
Why don't you just do 1a and 1b, @shawngraham? We won't touch the original one until the lesson's ready to go live at this point.

**Comment by wcaleb** [comment]
Again, sorry for the confusion @shawngraham! Since we're developing this new submission workflow as we speak, it's still [only partially documented](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/index.md). Meanwhile, the old workflow is still documented with different instructions!

But since we've already got you going on the new `ph-submissions` repo, let's go ahead and proceed with the newer instructions. That means you should put all your images in the root `images` folder, and all your data in the root `assets` folder, of the `ph-submissions` repo. [I've actually gone ahead and done this for you](https://github.com/programminghistorian/ph-submissions/commit/11112f12c6e40fdf43d2dfd4f6d72d1d32037c01) for clarity's sake. 

In the long run this will be easier than the lesson-specific subdirectory, because now you can write all of your image and data URLs beginning with `../images` and `../assets`, as they will need to be when they are finally published. It eliminates the step of having to change these URLs at "press time."

Hope this all makes sense, and sorry again. Perhaps to avoid further confusion or the possibility of later merging outdated files, we should pretend like you didn't make this pull request (I've closed it for now). Except for the Markdown style guide, you can also safely disregard the `new-lesson-workflow` instructions since you're now our guinea pig for the experimental workflow!

**Pull request closed without merging**
