### PR TITLE
Editor roles

### PR DESCRIPTION
**Pull request by mdlincoln**
Closes: #303 

This is a test implementation of editor role badges and definitions.

Preview at: https://editor-roles--ph-dev.netlify.com/project-team

To-do:

- [x] Display `(Spanish)` qualifier for roles with editors, but don't have separate definitions.
- [x] Clicking on a badge should show you the definition (either by skipping down to the definition [easy] or showing a popup [a bit more tricky])
- [x] Spanish translations for terms and definitions needed
- [x] Adjust HTML/CSS so bios don't overflow

### CODE REVIEW

**Comment by acrymble** [comment]
Looks great.

I'd like to cut the bios though. Just name and affiliation. The information readers need is captured by the tags.

**Comment by ianmilligan1** [comment]
FWIW, I like knowing a brief bio from somebody before I contact them or work with them, gives me some context.

**Comment by acrymble** [comment]
Opinions always worthwhile @ianmilligan1 but so that we can move forward can you be specific about what we (all) should have on our profile? I think consistency is key, and we discussed this at a call a few months ago and I believe we agreed that the editor interests left a lot of gaps, so weren't as useful as we might have intended.

At the moment the differing lengths of people's bios has caused some css issues as well (icons below pics).

**Comment by ianmilligan1** [comment]
I think what we have right now is fine, with the addition of tagging. I guess we can put word limits if you think they're too long for CSS reasons.

But bios are one way for folks to be creative, express themselves, and let people know who they're dealing with.

**Comment by acrymble** [comment]
If a personalised bio is important to people then the quickest solution is just to adjust the CSS. Otherwise the max is 2 lines per person.

It's also been pointed out to me that because the whole section is labelled 'Editorial Board', the tag for that is actually redundant.

**Comment by ianmilligan1** [comment]
Whatever is easiest works for me - making folks switch to two-line bios or adjusting the CSS. But I do think a brief biographical statement is important.

**Comment by mdlincoln** [comment]
I agree with @ianmilligan1 that I appreciate the bios tell me a bit more than just affiliation.

Regardless what we eventually stipulate for bios, however, I'd like to fix the CSS so that it still looks good _no matter how long_ the bio.

**Comment by acrymble** [comment]
Minor point, but can we add a "Team Description" header (or something like that), to separate it from the people?

**Comment by mdlincoln** [comment]
Thanks @vgayolrs for making those translations so quickly. I'll go ahead and merge this tomorrow - in the meantime, please let me know if there are any further comments or improvements we'd like to see.

**Pull request merged**
