### PR TITLE
Add phrase suggested by Amanda Visconti

### PR DESCRIPTION
**Pull request by wcaleb**
I liked the phrase "novice friendly" in this tweet by @amandavisconti. I revised our opening paragraph to include it, as well as to implement some changes that @fredgibbs @acrymble and I discussed on last Skype call.

https://twitter.com/Literature_Geek/status/674208656276238336

### CODE REVIEW

**Comment by ianmilligan1** [comment]
Looks great, @wcaleb - thanks for putting this in.

**Comment by wcaleb** [comment]
Got positive feedback from @acrymble on Twitter, as well.

**Comment by fredgibbs** [comment]
I like it.  Maybe instead of the current last line ( We regularly publish new lessons, and we welcome [submissions])--through destroying the brevity of the new version--we could have emphasize the collaborative editing a bit more upfront: "We regularly publish new lessons, and we always welcome [proposals for new lessons](new-lesson-workflow) on any topic. Our editorial mentors will be happy to work with you throughout the lesson writing process. If you'd like to be a reviewer or if you have suggestions to make Programming Historian a more useful resource, please see our [contribute](contribute) page.

**Comment by acrymble** [comment]
look sfine to me. We can user test it once you have it up. Easy to keep tweaking. Thanks @wcaleb

**Pull request merged**
