### PR TITLE
Publicar criar exposicao omeka

### PR DESCRIPTION
**Pull request by DanielAlvesLABDH**
Publicar tradução da lição "Creating an Omeka Exhibit"

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by DanielAlvesLABDH** [comment]
Dear @anisa-hawes or anyone from the @programminghistorian/technical-team, I found two broken links in a EN lesson when trying to publish this one. See the errors below
/en/lessons/data-mining-the-internet-archive.html
  *  External link http://archive.org/details/lettertowilliaml00doug failed: 404 No error
  *  External link http://archive.org/download/lettertowilliaml00doug failed: 404 No error
I have looked at the file of the lesson, everything seems fine, and the problem seems to be in the Internet Archive, that shows the following message: "Items may be taken down for various reasons, including by decision of the uploader or due to a violation of our Terms of Use."
Is there a procedure already for this? Can you help, please? Thanks in advance

**Comment by spapastamkou** [comment]
@DanielAlvesLABDH I just tested the links and have access to the contents of Internet Archive with no problem

**Comment by DanielAlvesLABDH** [comment]
Thank you @spapastamkou now it is working, yes. My bad luck with the links,  the server probably was with errors at that exact time 😀

**Comment by DanielAlvesLABDH** [comment]
Só falta receber o DOI. Depois disso e da revisão final, pode ser publicada!

**Comment by DanielAlvesLABDH** [comment]
DOI adicionado

**Review by joanacvp — APPROVED** [review]
Inseri ligeiras correcções. Está pronto a ser publicado.

**Comment by DanielAlvesLABDH** [comment]
Dear @ZoeLeBlanc this lesson was merged more than 20 minutes ago and it doesn't show on the live website. Any mistake from my part? Problems with the platform? Can you check, please? Thanks

**Pull request merged**
