### PR TITLE
The Programming Historian en français

### PR DESCRIPTION
**Pull request by mdlincoln**
This is the pre-publication branch for the French edition of the site. All work on translations and adding French lessons ought to go through this branch so that we can preview all the changes as a whole.

Preview URL: <https://deploy-preview-1070--ph-dev.netlify.com/>

I will be responsible for final merging, so please don't merge this yet!

### CODE REVIEW

**Comment by mdlincoln** [comment]
@programminghistorian/french-team I've enabled metadata checking for translated lessons, so if you go to check the [travis-ci/pr results](https://travis-ci.org/programminghistorian/jekyll/builds/462202096) it now lists fields that need to be added/corrected in the French lesson drafts.

**Comment by drjwbaker** [comment]
Changes to `about.md` (https://github.com/programminghistorian/jekyll/pull/1070/commits/65c5ab14e89c928a8b6c83beb215e017b59f0d3b) and addition of `support-us.md` (see https://github.com/programminghistorian/jekyll/issues/915 - changes required to recognise support via CMU for Matt's time) affect ES (`guia-editor.md` + new page) and FR translations above. @mariajoafana @spapastamkou can the ES and FR teams get this translation work done for the FR launch?

**Comment by mdlincoln** [comment]
@drjwbaker I think one or two links in your additions are [broken](https://travis-ci.org/programminghistorian/jekyll/builds/471030660)

**Comment by drjwbaker** [comment]
Sorry, fixed.

**Comment by acrymble** [comment]
Hi everyone, I'm having trouble keeping up to speed with what's happening in this process because it's quite complex. Can we get a clear update as to what we're waiting on before these pages go live? 

I ask because it's difficult to keep all of the core infrastructure pages in sync while the French pages aren't published. If the French infrastructure pages are finished, can we just publish them and put a note that says lessons are coming soon? And if they aren't finished, can we put a clear plan in place to get them done so we can resolve it?

**Comment by spapastamkou** [comment]
All recent changes in core pages have been integrated here, thing missing is an update as per PR #1144. I can stick to it (but not before next week). 

If we publish, perhaps this could help go quicker with editing then publishing the lessons directly. Think would also be good to make a quick final review of the pages, especially the guidelines, just in case. 

One the other hand, this place is good bcz we have a global view of what's going on and we have something like a month and some dust before going live. Do not know what would be more practical for @mdlincoln , @mpuren , @fdlaramee ?

**Comment by mdlincoln** [comment]
If we're agreed that it's alright to publish everything BUT the lesson pages, then that works for me - @acrymble you are right that it would make further editorial page tweaks easier to do systematically. What I might do is, just for the `/fr/lecons` page, add in a banner explaining that lessons are coming soon, i.e. late Spring 2019. What do we think about that?

**Comment by mdlincoln** [comment]
There being no outcry... I'll merge sometime closer to the end of the week when I have some time.

**Comment by mdlincoln** [comment]
@programminghistorian/french-team I've added a little banner that will show up on:

- home page: https://deploy-preview-1070--ph-dev.netlify.com/
- french home page: https://deploy-preview-1070--ph-dev.netlify.com/fr/
- french lessons page: https://deploy-preview-1070--ph-dev.netlify.com/fr/lecons/

until we have the first lessons published. Does that phrasing look ok?

You can edit the text here: https://github.com/programminghistorian/jekyll/blob/french-staging/_includes/french-alert.html

**Comment by fdlaramee** [comment]
Hi @mdlincoln -- I would make a small change: "leçons en français" (lessons in French) rather than "leçons de français" (French lessons in the sense of "lessons of French".) 

(I'm always afraid of breaking something -- in a case like this, should I just commit to the french-staging branch or create a pull request?)

**Comment by spapastamkou** [comment]
wow!

**Pull request merged**
