### PR TITLE
Create Travailler avec des fichiers texte

### PR DESCRIPTION
**Pull request by spapastamkou**
New FR translated lesson

### CODE REVIEW

**Comment by spapastamkou** [comment]
@mdlincoln I have a problem here: In yaml there is a python_warning that I currently have "false" and this eventually enabled the build to pass. As long as it was "true", all checks failed because they located somewhere an href I was not able to find, that sent to a FR page that does not exist (/fr/lessons/introduction-et-installation) and I suspect comes from the translator's fork (FR lessons pages of the PH start with /fr/lecons/). I sneaked around jekyll to find this python_warning but I had no success.  What can I do to fix this?

**Comment by acrymble** [comment]
The English version of the lesson links to a lesson that it doesn't look like you've translated yet. Is that the problem?

**Comment by spapastamkou** [comment]
@acrymble And the ES version points to an already translated lesson as well. The PH FR has not yet published a translation of that lesson; however, the translator does have it in his fork so there must be a link somewhere pointing to his repository that travis finds (and fails) when this python_warning is true, and I don't:-)

**Comment by acrymble** [comment]
This isn't about your problem, but I see that you are linking to English lessons where lessons aren't yet translated. Do you have plans to go back and change these later? How will you keep track of that? It seems like a lot of work to me.

**Comment by spapastamkou** [comment]
@acrymble we have a sheet to register lessons with a priority to translate once they are mentionnel in one published translation. But yes, this might not necessarily remind to go back and change the links once the lesson is published. Perhaps we should find a more effective way to organize us on this AND include this in the translation editor's tasks. I know that once this very lesson is published, I need to go to "Introduction à la stylométrie avec Python" and replace the link/adapt the text where this lesson is for now mentionned in its EN version. But I know bcz I am editor to both translations and have it somewhere in the back of my mind. Thanks for pointing this, I will soon open a ticket to discuss on this.

**Comment by mdlincoln** [comment]
I think you are making it much more complicated than it needs to be. This lesson is written pointing to the English lesson. If that English lesson eventually gets translated, links appear at the top of the lesson pointing to those translations. Choices are presented to the reader, and it reduces load into he editors to constantly go back and change links in lessons.

**Comment by spapastamkou** [comment]
@mdlincoln, thank you for your comments, I understood somewhat better (and also found the file with the script). However, I still don't get if python_warning needs to be set to true or to false. I have now set it to true so that we are all able to see the problem travis finds. It detects a french title in the EN lessons directory and I do not see where this comes from to fix it (sorry!).

**Comment by mdlincoln** [comment]
I'm very sorry for the delay in reviewing the core of this problem. Thanks for your patience @spapastamkou. @acrymble is right:

In `_data/snippets.yml`, the python warning is defined. The original english warning says:

>`This lesson was written using Python v. 2.x. Code may not be compatible with newer versions of Python. "[Python Introduction and Installation](/en/lessons/introduction-and-installation)" provides instructions for how you can install Python 2.x alongside newer versions.`

The french version got translated literally, and tries to point to `/fr/lessons/introduction-et-installation` which doesn't exist! You will need to edit `snippets.yml` to have it either point to the English lesson for now, or remove the link and just leave the python 2 warning.

**Review by mdlincoln — CHANGES_REQUESTED** [review]
Change the link in `settings.yml` under `python-warning.fr` so that it doesn't contain an invalid link.

**Comment by spapastamkou** [comment]
Thank you @mdlincoln, I corrected the FR part in the file (with link to the EN lesson). 
As the travis buil failed afterwards because of errors in links, I updated the following files: 
- a dead link in `_posts/2018-05-22-Uses-Of-The-Programming-Historian.md` @acrymble (replaced with Internet Archive link)
- a dead link in `/en/lessons/introduction-to-ffmpeg.md` @walshbr (replaced with Internet Archive link) 
-  the url to @jenniferisasi 's web site in `_data/snippets.yml` 
Please, Adam, Brandon and Jennifer, verify if all ok. 

Otherwise, this translation is ok to publish.

**Review by acrymble — APPROVED** [review]

**Comment by walshbr** [comment]
That works for me re: the FFMPEG lesson.

**Review by mdlincoln — APPROVED** [review]

**Comment by mdlincoln** [comment]
Congrats! 🎊

**Comment by spapastamkou** [comment]
thanks for doing this in the middle of the ACH conf, Matt :-) and thanks to
all!

>

**Pull request merged**
