### PR TITLE
Suggested Citations

### LINKED ISSUE #767: Volume & Issue numbers
- [x] How do we want to split into volumes/issues? Volume by year, and that's it?
- [ ] Generate these from published date metadata (we should _not_ be manually typing these volume numbers into these metadata)
- [x] Display suggested citation on lesson page

### PR DESCRIPTION
**Pull request by mdlincoln**
Closes #767

Thoughts?

Example lesson in english: https://deploy-preview-771--ph-dev.netlify.com/lessons/text-mining-with-extracted-features

Example lesson in spanish: https://deploy-preview-771--ph-dev.netlify.com/es/lecciones/escritura-sostenible-usando-pandoc-y-markdown

### CODE REVIEW

**Comment by acrymble** [comment]
Did you use a particular style guide for this?

I think it's common practice to include 'translators' in citations. I would suggest we do this (but not 'editors')

**Comment by acrymble** [comment]
Thanks @mdlincoln.

There's a typo in the Spanish one:

Dennis Tenen y Grant Wythoff, "Escritura sostenible en texto plano usando Pandoc y Markdown," traducido por Víctor Gayol, The Programming Historian en **espanõl** 2 (2017), https://programminghistorian.org/es/lecciones/escritura-sostenible-usando-pandoc-y-markdown.

And one final flourish: I would recommend either a comma after the publication title (before volume number) or 'vol.' to really hit home that we've got volume numbers.

So like this?

Dennis Tenen y Grant Wythoff, "Escritura sostenible en texto plano usando Pandoc y Markdown," traducido por Víctor Gayol, The Programming Historian en español, vol. 2 (2017), https://programminghistorian.org/es/lecciones/escritura-sostenible-usando-pandoc-y-markdown.

**Comment by arojascastro** [comment]
Is it possible to change "Escritura sostenible en texto plano usando Pandoc y Markdown,"  to "Escritura sostenible en texto plano usando Pandoc y Markdown", - we put commas after punctuation marks... I am not sure that's what you meant Matthew, if so, sorry.

**Comment by acrymble** [comment]
For some reason people get very picky about citation style. I wonder if it would be easiest for @mdlincoln if we just suggested a standard citation style that we display, and follow those rules? People can always adapt it to their own particular needs. It looks like @mdlincoln has chosen Chicago Manual of Style, which is fine with me, even if it's not exactly what I'd do naturally.

**Comment by mdlincoln** [comment]
I'm using CMOS, yes. Given that it's a "suggested" citation, I trust that readers can reformat it for their particular needs, as long as we're including the pertinent info?

**Review by acrymble — CHANGES_REQUESTED** [review]
espanõl is spelled wrong in /snippets.yml. Otherwise fine.

**Comment by mdlincoln** [comment]
🤕 good catch @acrymble - will fix

**Review by acrymble — APPROVED** [review]

**Comment by arojascastro** [comment]
Again, I insist that in Spanish we put commas or full points after quotations `"` so it should be `"title of the lesson",`

**Pull request merged**
