### PR TITLE
Publish Analyse de documents avec tf-idf

### PR DESCRIPTION
**Pull request by spapastamkou**
*New FR translated lesson: Analyse de documents avec tf-idf*

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by spapastamkou** [comment]
Le build se refait, attendons un peu - j'avais vert tout à l'heure, avant d'ajouter les reviewers, et la prévisualisation était correcte.  
Màj: cela a l'air ok!

**Comment by anisa-hawes** [comment]
Dear @spapastamkou,

Thank you for this!

I've been in touch with Matthew recently (he's soon to publish a new two-part lesson with us, [#436](https://github.com/programminghistorian/ph-submissions/issues/436)) and he's advised that his affiliation and bio need updating. I've made the EN changes here in your branch, and added his orcid too.

Could you make these small adjustments to FR?

If anyone from the @programminghistorian/portuguese-team has a moment, the new bio text: is "Matthew J. Lavin is an Assistant Professor of Data Analytics specializing in Humanities Analytics at Denison University. His scholarship focuses on book history, cultural analytics, and turn-of-the-twentieth-century U.S. literature and culture."

**Comment by spapastamkou** [comment]
@anisa-hawes Thanks for the update. We can change the bio in FR and PT (@programminghistorian/portuguese-team please be aware) if necessary, but I have a question: do we have to update the bios of the authors after they have written the lessons for us in a given moment of their career?

**Comment by spapastamkou** [comment]
@anisa-hawes Obviously I commented without seeing your comment, must have been in the same time:)

**Comment by anisa-hawes** [comment]
Good question, @spapastamkou. I think we do, because authors have one bio within ph_authors, rather than multiple hard-coded bios specific to the lessons they've written in the past.

**Comment by anisa-hawes** [comment]
Hello @joanacvp. I hope you're well. May I ask if this PT bio would read correctly?

```
    pt: |
      Matthew J. Lavin é professor assistente de análise de dados com especialização em Análise de Humanidades na Denison University. A sua pesquisa actual focam-se na história do livro, análise cultural e literatura e cultura dos Estados Unidos da América na viragem para o século XX.
```

**Comment by ericbrasiln** [comment]
Oi @anisa-hawes 

I think is better like this (but I'm thinking as a brazilian):
```
    pt: |
      Matthew J. Lavin é professor assistente de análise de dados com especialização em Análise de Humanidades na Denison University. Suas pesquisas actuais têm como foco a história do livro, análise cultural e literatura e cultura dos Estados Unidos da América na virada para o século XX.
```

**Comment by anisa-hawes** [comment]
Thank you, @ericbrasiln. I really appreciate your input!

**Comment by joanacvp** [comment]
Thanks for the help @ericbrasiln <https://github.com/ericbrasiln>.

*Joana Vieira Paulino*
Laboratório de Humanidades Digitais (dhlab.fcsh.unl.pt), Instituto de
História Contemporânea
Faculdade de Ciências Sociais e Humanas – NOVA FCSH

Colégio Almada Negreiros - Campus de Campolide da NOVA, 1099-085
Lisboa | Portugal

E-mail: ***@***.***

Web: www.fcsh.unl.pt | 40anos.fcsh.unl.pt





Anisa Hawes ***@***.***> escreveu no dia quinta, 30/06/2022
à(s) 12:48:

**Comment by spapastamkou** [comment]
Thank you @anisa-hawes and @ericbrasiln for the updates. 
@datalogism Je crois que nous n'avons pas d'autres mises à jour à attendre ici pour des bios ou des liens. Comme c'est ta leçon, quand tu es content du résultat, n'hésite pas à approuver ou, si ce n'est pas le cas, à demander des modifs :-)

**Comment by datalogism** [comment]
Ok perfect ! Thank you @anisa-hawes , @ericbrasiln, @joanacvp and @spapastamkou for your help on that :)
I totally approve your updates ! Let's publish it !

**Comment by spapastamkou** [comment]
@datalogism Merci! Il faut en plus faire une approving review pour pouvoir merger:-)

**Review by datalogism — APPROVED** [review]
I approve all these changes

**Pull request merged**
