### PR TITLE
Added files via upload as per #975 

### PR DESCRIPTION
**Pull request by jenniferisasi**
I'm adding the file for lesson "Crear una exposición con Omeka"

NOTICE: Are you attempting to submit a lesson to the Programming Historian? We no longer accept lesson submissions by pull request to this repository. Please consult our [guidelines for submitting a lesson](http://programminghistorian.org/new-lesson-workflow) for further instructions.

If your pull request instead concerns some issue with the formatting or functioning of our site, or some error in an existing lesson, please see our technical contribution guidelines: https://github.com/programminghistorian/jekyll/wiki/Making-technical-contributions

### CODE REVIEW

**Review by arojascastro — APPROVED** [review]
Gracias

**Comment by arojascastro** [comment]
I think it's not passing the checks because a trouble with a post: 

> - ./_site/posts/PH-espanol-in-DH2018.html
>*  External link https://github.com/programminghistorian/jekyll/tree/gh-pages/_promo failed: 404 No >error
>htmlproofer 3.9.0 | Error:  HTML-Proofer found 1 failure!

Let's see once they publish that file...

**Comment by acrymble** [comment]
If you can approve my pull request on the Bogota blog post @arojascastro I have fixed that problem there...

**Comment by acrymble** [comment]
Ahh thanks you did. It should be ok now!

**Comment by arojascastro** [comment]
Nope, something is wrong, but I do not see it... :S

**Comment by acrymble** [comment]
normally you have to re-base the branch to the newly updated gh-pages. I think only Jennifer can do that?

**Comment by jenniferisasi** [comment]
I won't let me do anything with the pull request button 
screen shot 2018-08-13 at 7 02 26 am

I tried to make a change to do a new pull but I was not successful either. If @arojascastro cannot do a rebase on the pull request, I will try again later today. 

Thanks!

**Comment by acrymble** [comment]
This affects all open pull requests, so I think we need advice from @mdlincoln or @walshbr on how to rebase.

**Comment by arojascastro** [comment]
I think we have a @mdlincoln situation!

**Comment by walshbr** [comment]
Pull and take a look now @jenniferisasi? I merged gh-pages back into the pull request branch, and that looks to have pulled in the recent changes made to gh-pages and fixed the travis checks.

**Comment by acrymble** [comment]
How did you do that @walshbr !?!?

**Comment by walshbr** [comment]
I did it all locally -  terminal is usually less picky about permissions than the web/app interfaces for GitHub. In my own copy of the repository, I checked out this branch and did the merging there:

```
$ git pull
$ git checkout --track origin/Issue-975
$ git merge gh-pages
$ git push
```
First line to make sure I was current. Second line makes a new branch based on this pull request. Third line takes the gh-pages changes and merges them into the pull request, and then the fourth pushes those changes up here. 🎉

**Comment by jenniferisasi** [comment]
Looks like it works now! Thanks @walshbr for the fix. And now someone has to do the merging, right? Guidelines say "NEVER MERGE YOUR OWN PULL REQUEST"  :)

**Comment by acrymble** [comment]
I never follow that rule. Maybe I should

**Pull request merged**
