### PR TITLE
Change to diversity policy wording.

### PR DESCRIPTION
**Pull request by drjwbaker**
Revised diversity policy per https://github.com/programminghistorian/jekyll/issues/1423#issuecomment-526149402 Requires @programminghistorian/spanish-team & @programminghistorian/french-team translation (sorry..)

### CODE REVIEW

**Comment by acrymble** [comment]
I will try to make this easier to translate:

French team please help us translate the following on the /apropos.md page (changed sentences in bold):

Le Programming Historian en français s'attache au principe de la diversité. Nous tenons à garantir un espace libre de toute discrimination envers les personnes contribuant au projet indépendamment du genre, de l'orientation sexuelle, des situations d'handicap, de l'apparence, de la taille corporelle, de l'origine, de l'âge, de la religion ou de l'expérience technique. Notre engagement en faveur de la diversité est aussi valable pour notre Conseil éditorial **dont la politique s'assure que les membres représentant un sexe ou une nationalité ne constituent pas plus que 50% + 1 de l'ensemble du conseil. Ce principe vise à garantir la diversité des points de vue qui bénéficient ainsi au projet**. Cette politique évolue constamment et toute proposition venant de la communauté est la bienvenue.

New sentences:  

**our Editorial Board, which has adopted a diversity policy whereby we aim to ensure that members from any one gender or any one nationality do not comprise more than 50% + 1 of the members on the team. We encourage individuals from under-represented groups to apply to our Editorial Board when positions are advertised, and we commit to considering and discussing a candidate's potential to offer different perspectives to those already on the team when deciding between two equally qualified candidates.**

If someone from the French team can help us translate that we can add it to the files and  approve this pull request.

**Comment by acrymble** [comment]
Spanish team please help us translate the following on the /acerca-de.md page (changed sentences in bold):

En The Programming Historian estamos comprometidos con la diversidad y defendemos la necesidad de mantener un espacio de trabajo sin ningún tipo de acoso u hostigamiento basado en el género, identidad, orientación sexual, capacidades, físico, peso, etnia, edad, religión o nivel de conocimiento técnico de los participantes y colaboradores. Asimismo, nuestro compromiso con la diversidad se extiende a la composición del Consejo Editorial **garantizando que los miembros de un mismo género o nacionalidad no alcanzan una ratio superior al 50% +1 del total. Con esto pretendemos que el proyecto se siga beneficiando de puntos de vista distintos**. La medida está sujeta a revisiones futuras, por lo que aceptamos el envío de sugerencias de los miembros de la comunidad.

New sentences:

**our Editorial Board, which has adopted a diversity policy whereby we aim to ensure that members from any one gender or any one nationality do not comprise more than 50% + 1 of the members on the team. We encourage individuals from under-represented groups to apply to our Editorial Board when positions are advertised, and we commit to considering and discussing a candidate's potential to offer different perspectives to those already on the team when deciding between two equally qualified candidates.**

If someone from the Spanish team can help us translate that we can add it to the files and approve this pull request.

**Comment by drjwbaker** [comment]
Thanks Adam. I should have done that the first time. Noted for next time. Apologies FR and ES teams. Forgive me 😁

**Comment by fdlaramee** [comment]
French is done.

**Review by spapastamkou — DISMISSED** [review]

**Comment by drjwbaker** [comment]
Thanks @jenniferisasi

**Comment by drjwbaker** [comment]
Thanks all for their efforts. Can I please get a review on this so I can merge the PR (I raised the PR so I can't be the one to review the PR).

**Review by fdlaramee — APPROVED** [review]

**Comment by jenniferisasi** [comment]
If no one on the @programminghistorian/spanish-team reviews my translation soon, I'll approve the review myself so we can close the PR @drjwbaker

**Review by rivaquiroga — APPROVED** [review]

**Comment by drjwbaker** [comment]
Looks like we can merge. Thanks all for their efforts.

**Pull request merged**
