### PR TITLE
Create mobile-research-database

### PR DESCRIPTION
**Pull request by rblades**

### CODE REVIEW

**Comment by rblades** [comment]
Written in Sublime Text 2.

**Comment by acrymble** [comment]
Thanks @rblades have you been in contact with an editor, or is this an unsolicited submission? Either way, it will help us get you to the right editor.

And thanks for your submission.

**Comment by fredgibbs** [comment]
@acrymble I've already talked to @rblades about this, though obviously I neglected to update the pipeline page about it.

**Comment by acrymble** [comment]
Thanks @fredgibbs. I'll leave you to it.

**Comment by acrymble** [comment]
is this still active, or did it move to submissions? Or should we close?

**Comment by fredgibbs** [comment]
This is not active at present, so I'm going to close this thread. If we get a resubmission, we can pipe it through the submissions branch, which didn't exist at the time of the original request.

**Comment by rblades** [comment]
This completely slipped my mind! I agree with your decision to close. I will look at this again and resubmit. Thank you.

**Pull request closed without merging**
