### PR TITLE
Fix bug on 'Creating and Viewing HTML files with Python'

### LINKED ISSUE #1777: Python lesson sequence and accessing files as binary
I received a note from a reader who is having problems with this lesson and is using Windows. It appears to be the same error referenced in #1768. @walshbr would you be able to take a look at this, or would you rather I tag someone else in? 
screenshot

### PR DESCRIPTION
**Pull request by rivaquiroga**
Closes #1777 + propagates changes to Spanish translation

### Checklist

- [X] Assign yourself in the "Assignees" menu
- [X] Assign at least one individual or team to "Reviewers"
  ~~- [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description~~
- [X] Add the appropriate "Label"
- [x] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by walshbr** [comment]
A few things:

Those lines were specifically introduced as an attempt to fix an earlier error. Here is the one that introduced the 'b' - https://github.com/programminghistorian/jekyll/pull/1630. It was a proposed solution here - https://github.com/programminghistorian/jekyll/issues/407. So can you just confirm that the things work as expected and run on windows with the change? I don't understand windows file formats enough to be able to comment.

But the other thing to note is that, as these files are part of the Python sequence, you also need to update with the changes in these files - /assets/python-lessons.zip and python-es-lecciones.zip. There is a different zip file for each python lesson, and IIRC, you'll need to just make sure you update the zip files following the one in which the error appears. 

And the 'wb' usage actually appears in several places.…I'm trying to get a list to you. It would be _great_ to be able to grab all of those now.

**Comment by walshbr** [comment]
Screen Shot 2021-01-27 at 4 27 18 PM
This is a list of the files and the instances in the number of times that 'wb' appears in them. Let me know if that doesn't make sense?

**Comment by walshbr** [comment]
We might have just been pointed to the two files you pinpointed based on where the bugs were reported, but they'll be issues throughout the Python sequence.

**Comment by rivaquiroga** [comment]
Yes, it was checked on Windows. I'll check the zip files. Thanks for noting that! 
Regarding the rest of the lessons, all of them are going to be checked: https://github.com/programminghistorian/jekyll/issues/1885#issuecomment-768589101

**Comment by walshbr** [comment]
Awesome - thank you!

**Comment by rivaquiroga** [comment]
Regarding the previous change that added the 'b', I suspect that we trusted the solution proposed by a reader without checking it on Windows :grimacing:

**Review by svmelton — APPROVED** [review]

**Pull request merged**
