### PR TITLE
Implement DOI in lesson header per Issue #1860

### PR DESCRIPTION
**Pull request by jenniferisasi**
Per issue #1860 I am implementing the display of the DOI url in the lesson header for easier citation (currently that information is only displayed at the very end in the suggested citation part). 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [ ] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by jenniferisasi** [comment]
@acrymble and @arojascastro how do you like it? 

@walshbr this was super easy to implement in there so now I am worried something might break. 

I am going to try to include a tiny icon next to it like we have the Orcid to make it more visible.

**Comment by walshbr** [comment]
Cool! A couple things:

Did you want the DOI's to be a link? Not sure it's necessary since it is a link to the current page. But is a bit weird to see a link that is not linked. Looks like there is a closing </a> tag but no opening tag in what's up there so far, but you're still working i see. So just ignore that if you're still working on it!

As per a conversation about the PT version coming online, it sounds like there is, theoretically, a situation in which a journal might not have DOIs (if the provider does not agree to provide them) until we can figure out another solution. So the DOI piece should probably be in an if statement that checks to see if the lesson has a DOI provided and display it if yes or ignore that code block if not.

**Comment by jenniferisasi** [comment]
Thank you @walshbr! 

re the link being a clickable link: I know, looks weird to me too, but we don't even have it clickable in the citation for the same reason... so I'm going to leave it just like that. To me it makes more sense to have `DOI: x38fhd` but they state not to do that in their guidelines. 

re no DOI for some lessons, thanks for bringing that to my attention! I was not aware that we don't have that yet set up for Portuguese. Ok, let me see if I can figure an if statement

**Comment by walshbr** [comment]
I think the conversation about DOIs was more about a potential future that could happen, separate from the PT lessons. But it'd still be good to safeguard against that here while you're at it.

**Review by walshbr — DISMISSED** [review]

**Comment by acrymble** [comment]
Cool @jenniferisasi!

I noticed that the grey font colour is the label colour (eg, like 'DIFFICULTY') rather than the value colour (eg, like 'Low'). It's also in caps so presumably you've applied the label styling for css. Are those intentional decisions?

Thanks for doing the coding.

**Comment by jenniferisasi** [comment]
One day I will know enough Jekyll, html, yml and liquid tags that I will be able to make all the changes at once, I promise.

**Comment by jenniferisasi** [comment]
> Cool @jenniferisasi!
> 
> I noticed that the grey font colour is the label colour (eg, like 'DIFFICULTY') rather than the value colour (eg, like 'Low'). It's also in caps so presumably you've applied the label styling for css. Are those intentional decisions?
> 
> Thanks for doing the coding.

Turns out that was an easy fix, just html tags.

**Review by acrymble — APPROVED** [review]

**Pull request merged**
