### PR TITLE
Adding new editors bio&details at the project team page #762 

### PR DESCRIPTION
**Pull request by amsichani**
I ve added my details @ the project team page (mirroring @acrymble 's entry, as suggested)

### CODE REVIEW

**Comment by ianmilligan1** [comment]
Looking good!

You'll see an "x" noting that the build failed. If you go to the "Details" link at the bottom of this pull request, you can see what's going on.

In this case:

```
- ./_site/es/equipo-de-proyecto.html
  *  internal image /avatars/Anna-Maria-Sichani.png does not exist (line 346)
- ./_site/project-team.html
  *  internal image /avatars/Anna-Maria-Sichani.png does not exist (line 349)
```

To make the red X happy, if you upload your avatar to the avatars folder (while staying on this pull request) it should turn magically green. 😄

**Comment by acrymble** [comment]
Your university is 'King's College London', not 'Kings University London'.

The translation should be done before we accept the pull request, if I understand the workflow correctly.

**Comment by amsichani** [comment]
thanks for your comments @ianmilligan1  and @acrymble ! I 've uploaded my avatar img (I 'm not sure if it needs any change in terms of dimensions-cropping etc) and it should be green by now. I 'd say its better to wait for the Spanish translation before accepting the PR ;) 
Please do check also  the role tags I ve put on my entry - not 100% sure of my exact role!

**Comment by acrymble** [comment]
Thanks @amsichani . I think the image needs to be a square, so I've reuploaded a cropped version.

The tags look fine. We can discuss your role more when we speak at the meeting.

**Review by acrymble — APPROVED** [review]
This looks fine to me.

**Comment by amsichani** [comment]
I ve PR again for adding my surname on the bio - sorry for the omission !

**Pull request merged**
