### PR TITLE
Danielle Onboarding

### PR DESCRIPTION
**Pull request by daniellesanchesDH**
*add the reason for your pull request here*

### Checklist

- [X] Assign yourself in the "Assignees" menu
- [X] Assign at least one individual or team to "Reviewers"
  - [X] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [X] Add the appropriate "Label"
- [ ] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

I´m requesting reveu of @ph_authors in spanish and french

### CODE REVIEW

**Review by DanielAlvesLABDH — CHANGES_REQUESTED** [review]
The photo file seems too small and has two extensions ".png.jpg"

**Comment by daniellesanchesDH** [comment]
@DanielAlvesLABDH we made the changes.

**Review by DanielAlvesLABDH — CHANGES_REQUESTED** [review]
All the references to NOVA-FCSH must be in uppercase. The rest seems fine

**Review by DanielAlvesLABDH — DISMISSED** [review]

**Review by rivaquiroga — DISMISSED** [review]

**Comment by acrymble** [comment]
@programminghistorian/technical-team can someone help us rebase this to the most up to date version of the file? We have multiple people trying to add themselves at the same time, so we will have a few conflicts. If there's a better way we can do this please let me know.

**Comment by walshbr** [comment]
@acrymble it's not a big deal - they're merge conflicts yes technically, because the same line in the file was edited two different ways. But it's pretty clear and easy to take apart - each edit added an entire person. It's much more difficult when the merge conflicts are more subtle. I can just take care of these as they come up if you ping me.

**Comment by walshbr** [comment]
Needed a dash before the first line for the one person entry - I pushed that change up.

**Review by spapastamkou — DISMISSED** [review]

**Review by rivaquiroga — DISMISSED** [review]

**Comment by acrymble** [comment]
This branch is now behind because we've added 2 new people to the project team page. Can we get some help fixing this @programminghistorian/technical-team and then can we just merge it so that we can let the Portuguese team work on the file? Sorry for all of the requests, but we've got people waiting to access ph_authors.yml

**Comment by ZoeLeBlanc** [comment]
@acrymble I'll fix the merge conflict and push up so that we can merge in this branch.

**Review by acrymble — APPROVED** [review]

**Comment by acrymble** [comment]
@daniellesanchesDH we had to update the files because other people were editing them as well, but everything should be ok now. Please Merge the pull request as soon as possible, and delete the branch that you were editing the files on (there is a button that appears after you click the 'Merge pull request' button.

@DanielAlvesLABDH once this is merged your team can translate this file and we will pause further changes for a month.

**Pull request merged**
