### PR TITLE
Joana vieira paulino onboarding

### PR DESCRIPTION
**Pull request by joanacvp**
*add the reason for your pull request here*

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [ ] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

I am requesting revue on @ph_authors in spanish and french.

### CODE REVIEW

**Review by DanielAlvesLABDH — CHANGES_REQUESTED** [review]
Seems fine, missing ES version of the bio

**Comment by joanacvp** [comment]
> Seems fine, missing ES version of the bio

@DanielAlvesLABDH I just translated my bio to spanish, but I just need a review from a spanish team member to check if everything is ok.

**Review by arojascastro — APPROVED** [review]
It looks perfect from my point of view 👍

**Review by DanielAlvesLABDH — APPROVED** [review]

**Comment by joanacvp** [comment]
> It looks perfect from my point of view 👍

Thank you very much @arojascastro

**Review by svmelton — APPROVED** [review]

**Comment by acrymble** [comment]
@joanacvp can you please merge this pull request as soon as possible? We have 4 other people trying to add themselves to this file.

**Comment by joanacvp** [comment]
> @joanacvp can you please merge this pull request as soon as possible? We have 4 other people trying to add themselves to this file.

@acrymble thank you for the attention. I already merged it

**Comment by spapastamkou** [comment]
Hi @joanacvp, welcome! If you want to add your bio in FR, here you are:

bio: 
Joana Vieira Paulino a un doctorat en histoire, avec une spécialisation en histoire contemporaine, de la Faculté des sciences humaines et sociales de l'Université nouvelle de Lisbonne, Portugal.  Elle est chercheuse au Laboratoire des humanités numériques et à l'Institut d'histoire contemporaine de la même institution.

affiliation: 
Université nouvelle de Lisbonne, Portugal

**Pull request merged**
