### PR TITLE
Issue 651 - internationalization policy

### PR DESCRIPTION
**Pull request by acrymble**
As per #651, I have added the agreed text to the author guidelines and editor guidelines.

This is ready for a Spanish translation.

### CODE REVIEW

**Comment by acrymble** [comment]
Thanks @jenniferisasi for the translation. Can someone review the Spanish changes (in particular the editors guidelines).

**Review by drjwbaker — APPROVED** [review]

**Review by drjwbaker — CHANGES_REQUESTED** [review]
Do we need a line here on what editors should do? For sustainability we write "editors should use these areas as guidelines to ensure that lessons are as sustainable as possible from the date of publication." So after the bullet list, add something like "Editors should work closely with authors to ensure that these criteria are met. Where this is not possible, justifications for not meeting them should be clearly and transparently outlined in the relevant ticket".

**Comment by arojascastro** [comment]
I can review @jenniferisasi's translation and move it to the right file hopefully later today.

**Comment by acrymble** [comment]
I've added @drjwbaker 's suggested text (slightly amended) to the English language editor's guidelines. I can't translate that for Spanish I'm afraid, so someone else will have to do it:


> Editors should work closely with authors to ensure that these criteria are met. Where this is not possible, justifications for not meeting them should be clearly and transparently outlined in the relevant review ticket

**Review by drjwbaker — APPROVED** [review]

**Review by arojascastro — APPROVED** [review]
I revised the translation and added that last paragraph. Thanks.

**Comment by acrymble** [comment]
Big thanks to @arojascastro for helping us adopt this policy.

**Pull request merged**
