### PR TITLE
Issue 1181 - missing data from Geospatial Analysis lesson

### PR DESCRIPTION
**Pull request by acrymble**
This pull request should add the missing files, as well as includes 2 updates to code lines submitted by the author. This was a confusing situation, so the pull request needs someone to actually try the lesson again to make sure it all works. I am submitting a pull request so that we can preview it easily.

re: #1181

### CODE REVIEW

**Comment by mdlincoln** [comment]
Sorry for the delay in getting to this - I will be able to take a look tomorrow.

**Review by mdlincoln — CHANGES_REQUESTED** [review]
Thank you for your patience.

Regretfully, the new data are not acceptable in their current form. 

The new shapefile geometries are invalid, and thus the data are unplottable.

```
> library(sf)
> library(tmap)
> County_Aggregate_Data <- st_read("data/County1990/")
Reading layer `US_county_1990' from data source `/Users/mlincoln/Development/bridges/konigsbergr/data/County1990' using driver `ESRI Shapefile'
replacing null geometries with empty geometries
Simple feature collection with 3141 features and 20 fields (with 3140 geometries empty)
geometry type:  POLYGON
dimension:      XY
bbox:           xmin: 1584238 ymin: 409629.1 xmax: 1666567 ymax: 467600.4
epsg (SRID):    NA
proj4string:    +proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs
There were 50 or more warnings (use warnings() to see the first 50)

plot(County_Aggregate_Data$geometry)

Error in plot_sf(x, ...) : 
  NA value(s) in bounding box. Trying to plot empty geometries?
```

Note the warnings when reading the shapefile. It is possible that this may have occurred when trying to simplify the geometry of the shapefile. Rather than simplifying the geometry for the entire US county file, I recommend the author provide a shapefile that is _already_ subset to just North and South Carolina, without trying to do any geometry simplification, and that the author rewrite the intro to match the newly provided data. I've tested this and it's just 5mb when zipped.

[carolina1990.zip](https://github.com/programminghistorian/jekyll/files/3232972/carolina1990.zip)

Further down in the lesson, the command

```r
geocoded_addresses <- read.csv("data/GeocodedAddresses.csv", as.is=TRUE)
```

fails because there is no file `GeocodedAddress.csv` in the supplied zip file. I'm going to stop this review here since entire data files are still missing.

**Comment by mdlincoln** [comment]
the geocoded csv seems to have been uploaded as a separate file instead of put in the archive. I'm still going to wait to continue the review until we can get an acceptable shapefile.

**Comment by acrymble** [comment]
I've sent this back to the author.

**Pull request closed without merging**
