### PR TITLE
Merge redesign into live site

### PR DESCRIPTION
**Pull request by mdlincoln**
Well @fredgibbs , it looks like everything merges fine. I only had to manually fix two conflicts where lines in research.md and an edited author bio were close enough for git to flag. Everything else goes smoothly. Any additional bits to fix, or do you think we're ready to merge?

### CODE REVIEW

**Comment by mdlincoln** [comment]
@fredgibbs there's one bug that @acrymble brought to my attention - the sort buttons on the lesson display page aren't actually working! My js-fu is weak - do you know what's causing this?

**Comment by fredgibbs** [comment]
bah. i have no idea when this stopped working, nor could i find the offending commit. i've been futzing with it for a while and think i've got it working again, but in the process have considerably altered the html and css for my own sanity and to make future debugging (esp with list.js) easier, but now i need to redo the css to match the clearer html code. it will take me a few hours on monday to get everything ready to commit. sorry for the delay on the merge.

**Comment by mdlincoln** [comment]
Sounds good!

**Comment by fredgibbs** [comment]
sorting should be fixed with fd8af36, but could use extra eyes and clicks. this might also be a good time to briefly consider #429 and whether we want to make any amendments to topic buttons before we launch and blog about the new functionality.

**Comment by mdlincoln** [comment]
Yep, it looks like things are working for me now.

I don't think we need to hold the launch for #429. I'm going to work out quick abstracts for #406 and ensure that the YAML check looks for abstracts in lessons.

Also, since I foolishly put commits onto this PR in conflict with your work on `redesign`, I'm going to close this PR and reopen with a fresh merge PR once I finish the above tasks.

**Pull request closed without merging**
