### PR TITLE
Adding tiago project team

### LINKED ISSUE #2220: Technical Onboarding of Tiago
This is a checklist of items that @drjwbaker needs to work through with our new Digital Humanities Publishing Assistant (in support of the Jisc and TNA funded project ‘Programming Historian publications: developing computational skills for digital collections’), @tiagosousagarcia (from 9 August 2021).

- [x] add to Github
- [x] work station assessment
- [x] dedicated email?
- [x] introduce to Project documentation on website
- [x] introduce to Wiki
- [x] introduce to Github tickets
- [x] add to project team page & confirm happy with pull requests
- [x] share funded project specific documentation
- [x] establish welcome meetings with project team members (over the coming weeks)

### PR DESCRIPTION
**Pull request by tiagosousagarcia**
Adding myself to the project team page

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Review by drjwbaker — DISMISSED** [review]
once build checks pass, looks good to me.

**Comment by tiagosousagarcia** [comment]
I'm getting a 404 error on ./_site/en/lessons/intro-to-twitterbots.html which, from looking at other pull requests (ex. #2225), seems to be the case for everyone. I assume I should wait for a fix, @drjwbaker?

**Comment by drjwbaker** [comment]
Yeah, looks like it is a global hold up until we get that link resolved.

**Comment by jenniferisasi** [comment]
OMG I think my update thru the terminal is correct 🎉🎉🎉🎉

@ZoeLeBlanc looks like your teaching yesterday worked 🤩

**Review by jenniferisasi — APPROVED** [review]

**Comment by jenniferisasi** [comment]
@tiagosousagarcia this is now ready to merge and, if you are confortable with the process (per #2220) you can close the issue. Thanks!

**Comment by tiagosousagarcia** [comment]
Many thanks @jenniferisasi!

**Pull request merged**
