### PR TITLE
Update directrizes-autor.md

### PR DESCRIPTION
**Pull request by aracele**
*add the reason for your pull request here*

### Checklist

- [ ] Assign yourself in the "Assignees" menu
- [ ] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [ ] Add the appropriate "Label"
- [ ] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by walshbr** [comment]
@DanielAlvesLABDH - is this the pull request you emailed me about? if it's actually ready to be merged into the main timeline I can go ahead and review and do so. I'd only worry about keeping it on a correct branch if it is still in  progress.

**Comment by DanielAlvesLABDH** [comment]
@walshbr I still need to make some changes on it. Do I make those here or in the https://github.com/programminghistorian/jekyll/tree/issue-1891

**Comment by walshbr** [comment]
I think if it's just a matter of a couple changes we can have you do those here. I'll merge the main branch back into this one so it's up to date.

**Comment by DanielAlvesLABDH** [comment]
Fine by me. Will do that now. Thanks

**Comment by DanielAlvesLABDH** [comment]
@walshbr the changes are finished

**Review by DanielAlvesLABDH — APPROVED** [review]

**Comment by walshbr** [comment]
Ok @DanielAlvesLABDH I'll review this and let you know if I see any errors

**Comment by walshbr** [comment]
@DanielAlvesLABDH this looks OK - go ahead and merge. As I mentioned before, we'll want to make sure that we do a sweep through of all the pages once everything is live, on the final pull request that actually makes the pages public.

**Review by walshbr — APPROVED** [review]

**Pull request merged**
