### PR TITLE
fixed search rendering issue

### LINKED ISSUE #2324: Troubleshoot search building
After discussing the search with @anisa-hawes she pointed out that for some reason the Gravity Models isn't returned in the search.

I need to do some testing to understand what's going on but please let me know if you've had other search-related issues.

### PR DESCRIPTION
**Pull request by ZoeLeBlanc**
This PR closes #2324 . Turns out gravity model having ampersand in the title causes all sorts of character encoding issues (i.e. computers read it as &amp; instead of &), which was breaking our search logic. 

I did update the title name in the lesson, and also wrote code in lesson filter to do a hard fix if we have continued issues (in case someone in the future uses an ampersand).

Should be good to go now! 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by jenniferisasi** [comment]
Of course it was something silly like that! Glad it didn't involve more work @ZoeLeBlanc. 

Now, I've never seen that "mixed content - ph-preview error before" 🤔 the error looks to be prompted by code lines within files in our `assets` folder. Why is this a problem now? The links work.

**Comment by ZoeLeBlanc** [comment]
Very strange! The error is saying that we have links to http instead of https, so it's throwing an error. This is a helpful overview of the whole issue with mixed content https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content

I'm just confused why now?? Has something changed in our config for the builds? Or maybe netlify is working properly for the first time 😬 ? Seems very random on the timing 🤔 . Guess I'll have to  fix these eventually 😅

**Comment by jenniferisasi** [comment]
> Very strange! The error is saying that we have links to http instead of https, so it's throwing an error. This is a helpful overview of the whole issue with mixed content https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content
> 
> I'm just confused why now?? Has something changed in our config for the builds? Or maybe netlify is working properly for the first time 😬 ? Seems very random on the timing 🤔 . Guess I'll have to fix these eventually 😅

Yeah, I looked it up to try to understand the error. I read something longer than that, and it mentioned CSS and JS files could prompt errors, but it still goes back to domains. As far as I know nothing has changed on our side of things... the lines of code refer to other websites so I'm checking things the simple way: check the URLs 

In assets/fetch-and-parse-data-with-openrefine/pg1105.html:
- link http://purl.org/dc/terms/ is now actually https://dublincore.org/specifications/dublin-core/dcmi-terms/
- link http://id.loc.gov/vocabulary/relators/ is now actually https://id.loc.gov/vocabulary/relators.html

Those two are websites proper. However, the CDN links are still `http:// ` and I believe it could be because they are files and not the website itself?

The links are displaying correctly on the lesson itself... everything is fine in the Netlify preview.
Screen Shot 2021-12-15 at 8 39 38 PM

**Review by anisa-hawes — APPROVED** [review]

**Comment by anisa-hawes** [comment]
Do we need to update these assets/ links before merging here?

**Review by anisa-hawes — DISMISSED** [review]
Apologies, I have just checked the Netlify preview again and something doesn't look right. 

If I understand correctly, when we perform a keyword search in the Lesson Directory, our site is full text searching the body text of all lessons, not just titles. 

Usually this shows in the search results as highlighted keywords. But this isn't showing in the same way now...

**Comment by anisa-hawes** [comment]
Search results for "Gravity" on live site, showing highlighted keywords:
Screenshot 2021-12-16 at 11 43 36
Search results for "Gravity" on Netlify preview, without highlighted keywords:
Screenshot 2021-12-16 at 11 43 19

**Comment by ZoeLeBlanc** [comment]
Search doesn't work on netlify so that's it's own thing! One issue might be that I altered some of the code in the lessonfilter js so I could take that out and see if this works. All we really need to do is alter the title in the gravity lesson to have the unicode ampersand which I already did... once that percolates to the search everything should be fixed.

**Comment by anisa-hawes** [comment]
Okay. Now seems to be failing because of a broken link to Inscriptions of Roman Tripolitania (2009) from [this](https://inslib.kcl.ac.uk/index.html) project website built by King's College London.

Inscriptions of Roman Tripolitania, by J. M. Reynolds and J. B. Ward-Perkins, enhanced electronic reissue by Gabriel Bodard and Charlotte Roueché (2009). ISBN 978-1-897747-23-0. Available: http://inslib.kcl.ac.uk/irt2009/

I'll investigate.

**Comment by anisa-hawes** [comment]
I think we could use this instead: https://irt.kcl.ac.uk/irt2009/index.html

**Review by anisa-hawes — APPROVED** [review]

**Comment by ZoeLeBlanc** [comment]
Thanks for fixing that link @anisa-hawes ! I'm gonna go ahead and merge and hopefully the search for gravity models works 🤞🏽 !!

**Comment by anisa-hawes** [comment]
I still can't retrieve Gravity Models lesson with a search ?!

**Comment by ZoeLeBlanc** [comment]
I can access it here https://programminghistorian.org/en/lessons/?search=gravity. Maybe it took a few minutes for the search to rebuild 🤔

**Comment by anisa-hawes** [comment]
Perfect! I can retrieve it now!

**Pull request merged**
