### PR TITLE
Publicar Introdução ao MySQL com R

### PR DESCRIPTION
**Pull request by DanielAlvesLABDH**
*Publicar a tradução da lição Introduction to MySQL with R*

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by DanielAlvesLABDH** [comment]
Hi @anisa-hawes, this PR fails because of a broken link in the lesson https://programminghistorian.org/en/lessons/extracting-illustrated-pages. The broken link is https://requests.readthedocs.io/en/master/. The main website works (https://requests.readthedocs.io/en/latest/), but I can't identify the correct or updated link. Can you help? Thanks

**Comment by anisa-hawes** [comment]
Hello @DanielAlvesLABDH. 

I wonder if <https://requests.readthedocs.io/en/latest/user/install/#install> would be a good substitution in this case. This page covers the steps towards Installation of Requests, which seems right for the context.

I'm happy to update the link in /en/lessons/extracting-illustrated-pages so that you can move this PR, and PR [2605](https://github.com/programminghistorian/jekyll/pull/2605) forwards. 

If it doesn't cause you too much delay, I'd also like to recommend that we take this opportunity before publication to replace all external links in these two new PT lessons, with perma.cc archival links. I can do that this afternoon, and will update you when they're ready.

Thank you for your patience, 
Anisa

**Comment by DanielAlvesLABDH** [comment]
Hi @anisa-hawes that would be a great help, yes! Many thanks!

**Comment by DanielAlvesLABDH** [comment]
Olá @aracele. Será que você pode ajudar com a revisão final desta tradução? A Danielle está com pouco tempo. Desde já agradeço

**Review by aracele — DISMISSED** [review]
Oi @DanielAlvesLABDH parece tudo correto para mim, exceto por um pequeno erro de digitação na Linha 164, onde está escrito "My SQL" separado em vez de "MySQL". Excelente trabalho!

**Comment by DanielAlvesLABDH** [comment]
Hi @anisa-hawes. This PR gets the error "htmlproofer 4.2.0 | Error:  invalid option: --alt-ignore". Really can't figured out how to solve this. Please, can you help? Thanks!

**Comment by anisa-hawes** [comment]
Thank you @DanielAlvesLABDH! Yes, I noted that the error specifies `invalid option: --alt-ignore`. The same Error is preventing Sarah  from publishing #2624. 

We recently updated the site #2615 so that alt text added to our figure images can be accessed by users of screen readers. 

I have been doing a bit of searching online, and I'm wondering if we need to make an adjustment so that the flag reads `--empty-alt-ignore` instead. This will mean that the ruby-html-proofer test will ignore any images with empty alt attributes (at the moment, almost all of the images on our website are missing alt text).

But I'm not sufficiently confident to make this change, without first hearing from Zoe (who is feeling unwell at the moment). I'll be in touch as soon as I have worked out what is needed. Sincere apologies for the hold up, and thank you for your patience.

**Comment by anisa-hawes** [comment]
Hello @DanielAlvesLABDH. Wonderful news! @ZoeLeBlanc has worked her magic ✨ and this PR is ready to go! Thank you again for your patience. Anisa

**Comment by DanielAlvesLABDH** [comment]
Wonderful news @anisa-hawes ! Many, many thanks @ZoeLeBlanc , what a great work! Magical indeed 
Anita, could you approve this? I already made the changes requested. Thanks

**Review by anisa-hawes — APPROVED** [review]

**Comment by anisa-hawes** [comment]
Dear @DanielAlvesLABDH, I have a question about how this lesson has been dated. It is the most recently published, yet I notice that it doesn't appear at the top of the list shown in [Índice de Lições](https://programminghistorian.org/pt/licoes/) when I order the lessons by date. I note that the YAML header specifies:

```
date: 2018-05-03
translation_date: 2021-12-18
```

Do you think it would be preferable to adjust the `translation_date` so that it reflects the date the translation has been published (rather than when the translator completed their work, which was before the peer review and revision process began)? Let me know if this is something which has already been discussed/agreed ! But I'd be interested to better understand how other editors of translations use this field. Perhaps @rivaquiroga or @spapastamkou could share their practice?

**Comment by DanielAlvesLABDH** [comment]
Hi @anisa-hawes. Thanks for the comment. I have been using the date of the creation of the revision ticket as the date of the translation. I keep that consistent, so if we agree that it should be the date of publication, we can change. If that is the date used in the other teams for me it's fine

**Comment by anisa-hawes** [comment]
Ah, okay. Do you know if that is how the other MEs do it too? 

My question is linked to the understanding that the `date:` field represents the date that the original lesson was published. 

I'd be interested to hear how Riva, Sofia and Sarah use the `date:` and `translation_date:` fields. I could open an Issue to discuss/agree this?

**Comment by rivaquiroga** [comment]
At the Spanish team we use publication date.

**Pull request merged**
