### PR TITLE
Add guidelines on editorial board diversity

### PR DESCRIPTION
**Pull request by acrymble**
To close issue #619 - Editorial Board Diversity suggestion.

I have changed the two 'about' pages with the agreed text. @arojascastro has asked for a review from another member of the Spanish team, since this was a difficult translation.

### CODE REVIEW

**Comment by mdlincoln** [comment]
Thank you @acrymble these look good. I'll wait for review by the spanish team before merging.

FYI for future pull requests, it's helpful to use a simple, short description of the change being made for the title of the PR, rather than titling it with the rather opaque issue number.

**Comment by jenniferisasi** [comment]
@arojascastro your translation is good!

**Comment by mdlincoln** [comment]
@jenniferisasi if you are happy with the translation, please submit an "Approve" review for this PR [following these instructions](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#adding-a-pr-review)

**Comment by mdlincoln** [comment]
Pinging @jenniferisasi again - let me know if you have any trouble with this process!

**Review by jenniferisasi — APPROVED** [review]
Diversity policy translation approved.

**Comment by mdlincoln** [comment]
🎉

**Comment by jenniferisasi** [comment]
Sorry @mdlincoln, crazy week here and I thought it was going to take me longer.

**Pull request merged**
