### PR TITLE
Spanish Managing Editor Handover (#2890)

### LINKED ISSUE #2890: Spanish Managing Editor Handover
We have a new Managing Editor: :sparkles: @jenniferisasi :sparkles: 
I'm working on updating the following:

- [x] the field `team_roles` in `ph_authors.yml`
- [x] our emails in `ph_authors.yml`
- [x] the field `managing_editor` in `snippets.yml`
- [x] the name provided on our Lesson Query forms
- [x] the Managing Editor's name across our Wikipedia entries **Done!**
- [x] the Managing Editors list on [our Wiki](https://github.com/programminghistorian/jekyll/wiki/Managing-Editor-Handover)
- [x] the Editorial Team on [our Wiki](https://github.com/programminghistorian/jekyll/wiki/Editorial-Team)

### PR DESCRIPTION
**Pull request by rivaquiroga**
I'm updating `snippets.yml`, `ph_authors.yml`, and all our lesson query forms.

Closes #2890

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Add the appropriate "Label"
- ~~[ ] If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above~~
- [x] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Assistant @anisa-hawes 
- [x] Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)
- [x] Assign at least one individual or team to "Reviewers"
  - ~~[ ] if the text needs to be translated, please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines), then assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR.~~

### CODE REVIEW

**Comment by rivaquiroga** [comment]
@anisa-hawes, Alex still has the "editorial" label. Should we remove it?

**Comment by anisa-hawes** [comment]
Thank you, @rivaquiroga. I have made one small adjustment – I note that Daniel and Marie have the role `- managing` but not `- editorial`.

**Comment by rivaquiroga** [comment]
Broken links are a nightmare :skull:

**Comment by anisa-hawes** [comment]
Don't worry, @rivaquiroga! I can come back to this tomorrow!

A temporary outage on berkeley.edu/, I think. Almost all the links from this page are broken:
https://www.berkeley.edu/search/?q=Potter%E2%80%99s+Wheel+ABC

**Review by anisa-hawes — APPROVED** [review]

**Pull request merged**
