### PR TITLE
Update author-guidelines / guia-para-autores / consignes-auteurs / directrizes-autor

### LINKED ISSUE #2141: Process to avoid content overlap in original lessons in different languages
With more original lessons arriving in now our four languages, a new and exciting issue arises: how to avoid content/methodology overlap in new lessons instead of getting the already published ones translated. 

Originally, there was no such problem because EN lessons were being translated into ES|FR|PT with datasets or examples sometimes changed (localized). Now we are receiving new lessons that are not being translated (as of today) to EN, for example. 

Examples of current potential overlap: 
- New lesson proposal in EN "[Georeferencing and Displaying Historical Maps using Map Warper and StoryMap JS](https://github.com/programminghistorian/ph-submissions/issues/349)" overlaps partially with "[Introducción a Map Warper](https://programminghistorian.org/es/lecciones/introduccion-map-warper)". @mariajoafana suggests to the editor to check how much overlap there is to avoid double content, so to speak, and a good starting moment/example to consider translating from ES to EN (so the new original lesson could point to the translation of the ES original lesson). 
- Two currently under review lesson proposals in ES and EN share some approach/tool, as both use `ggplot2` to visualize data (and I want to acknowledge that something like this is trickier as it is a popular package to create plots and used in many lessons). These are: "[Visualización y animación de tablas históricas con R](https://github.com/programminghistorian/ph-submissions/issues/330)" and "[Visualizing data with R and ggplot2](https://github.com/programminghistorian/ph-submissions/issues/354)"

In the AGM meeting today (May 25, 2021) a few ideas came up: 
- Having a spreadsheet with available lessons; 
  - this is already a thing in our [Translation concordance page](https://programminghistorian.org/translation-concordance) but I am guessing it is not checked (given the idea) 
- @rivaquiroga suggested making it explicit on the author guidelines for authors to check on the translation concordance to see what methods have been already published on in any language. 
- How can MEs or editors at large be aware / control that this overlap doesn't happen remains the bigger question, as not to put further work, on particularly, MEs. 
- It might be a 'project' for the Global Team. 

I'm adding a question:
- what can we do to get people interested in translating between the rest of possible pairs of languages: ES:EN; ES:FR; ES:PT; FR:EN; FR:ES, and so forth? 

Finally, we all realize/know that complete overlap is not going to happen because many of the lessons are guided by they research question and a dataset or set of materials, or because working in a particular language might need a substantial modification of the method (i.e. for NLP analysis). However, in some cases we have instructions on how to use an standalone platform and its use is not tied to the language of the content (map warper, omeka, etc.). In those cases, some of us believe, there is no reason for a new lesson but for a translation, which would highly add value to everyone and recognize that non-English speakers are also creators of knowledge/methods in DH.

### PR DESCRIPTION
**Pull request by anisa-hawes**
I am adding a sentence to Step 1 of our Author Guidelines (at paragraph 30) to direct authors to our Lesson Concordance document.

I’d like to ask if anyone from the @programminghistorian/spanish-team @programminghistorian/french-team and @programminghistorian/portuguese-team has time to translate the following sentence into ES, FR and PT:

_Please also take a moment to check our [Lesson Concordance document](https://docs.google.com/spreadsheets/d/1vrvZTygZLfQRoQildD667Xcgzhf_reQC8Nq4OD-BRIA/edit#gid=0) to see which methods we have already covered in our published or forthcoming lessons._ 

Thank you to Daniel, Riva and Gwenaëlle for their translations! 

Closes #2141 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [ ] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by DanielAlvesLABDH** [comment]
PT
Por favor, reserve um momento para verificar o nosso documento de Concordância de Lições para ver quais os métodos já abordados nas nossas lições publicadas ou futuras

**Comment by anisa-hawes** [comment]
Thank you, @DanielAlvesLABDH! Wishing you a restful weekend.

**Comment by anisa-hawes** [comment]
Thank you @rivaquiroga 🙂

**Comment by anisa-hawes** [comment]
Hello @programminghistorian/french-team,

Does anyone have time to translate these two sentences?

_Please also take a moment to check our [Lesson Concordance](https://docs.google.com/spreadsheets/d/1vrvZTygZLfQRoQildD667Xcgzhf_reQC8Nq4OD-BRIA/edit#gid=0) document to see which methods we have already covered in our published or forthcoming lessons._

**Comment by InesSalome** [comment]
> Hello @programminghistorian/french-team,
> 
> Does anyone have time to translate these two sentences?
> 
> _Please also take a moment to check our [Lesson Concordance](https://docs.google.com/spreadsheets/d/1vrvZTygZLfQRoQildD667Xcgzhf_reQC8Nq4OD-BRIA/edit#gid=0) document to see which methods we have already covered in our published or forthcoming lessons._

Hello @anisa-hawes, here is a proposal :

FR
Merci de prendre aussi le temps de consulter notre table de Concordance des Leçons afin de voir quelles méthodes ont déjà été traitées dans nos tutoriels publiés ou à venir. 

Have a good week-end !

**Comment by anisa-hawes** [comment]
Thank you, Gwenaëlle @InesSalome! Much appreciated! Wishing you a restful weekend too ✨

**Comment by anisa-hawes** [comment]
Hello @jenniferisasi. This PR represents the addition of a few sentences to direct authors to our Lesson Concordance document. Translations into ES, FR and PT are complete.

**Review by jenniferisasi — APPROVED** [review]
Looks good!

**Pull request merged**
