### PR TITLE
Updating advice to users at rubygems-update step

### LINKED ISSUE #1955: Mac Catalina bug for "Building a static website with Jekyll and GitHub Pages"
I love the "Building a static website with Jekyll and GitHub Pages" tutorial and have it bookmarked in my toolbar for easy reference! Today I tried to follow the instructions on a new Mac laptop running Catalina, and ran into permissions problems that couldn't be solved with any of the tips. What worked for me was, after brew install ruby, running export GEM_HOME="$HOME/.gem". Thought I'd pass it along as an update suggestion!

### LINKED ISSUE #2028: Mac M1 Big Sur issues for "Building a static website with Jekyll and GitHub Pages"
Same as @quinnanya this is a great tutorial, but it is not working for me on my current machine (Mac/M1/Big Sur). Everything is fine up to the Homebrew install, this is different on M1 based Macs ([https://docs.brew.sh/Installation#macos-requirements](https://docs.brew.sh/Installation#macos-requirements)). 
I could not install Ruby & Ruby Gems/Jekyll according to the instructions, in fact ended up breaking my system Ruby and had to reinstall (my fault, not the tutorial's, but without the right instructions, it is surprisingly easy to trash Ruby). 
This might be an edge case as I had setup the M1 Mac via Migration Assistant from an Intel machine with Homebrew and Ruby installed. However, I do think that Ruby installation on the Mac is fraught with problems which is not helped by the semi-deprecated/out-of-date system Ruby and the Apple Silicon transition, and the guide doesn't take this into account. One alternative route might be recommending a script (e.g. [https://github.com/monfresh/install-ruby-on-macos](https://github.com/monfresh/install-ruby-on-macos)) - I'm sure there are other laptop scripts available too) which standardises and takes some of the pain out of installing Ruby on a new Mac.

_Originally posted by @johnpilbeam in https://github.com/programminghistorian/jekyll/issues/1955#issuecomment-773189924_

### PR DESCRIPTION
**Pull request by anisa-hawes**
I am updating the advice for users who encounter a permissions error after they attempt `gem install rubygems-update`.
Closes #1955 and Closes #2028.

Hello Spanish team,

May I ask for your help to translate and update the following phrases from `en/lessons/building-static-sites-with-jekyll-github-pages.md`?

The ES version of this lesson has previously been amended, but requires some small further changes so that the commands suggested are consistent with the EN version. 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [ ] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Review by rivaquiroga — DISMISSED** [review]

**Comment by rivaquiroga** [comment]
@Anisa-ProgHist, the translation is now updated :rocket:

**Comment by anisa-hawes** [comment]
Note to self: 

- re-test on Big Sur
- consider warning box instead? See https://getbootstrap.com/docs/4.0/components/alerts/ for code
- important to speak with Sarah before proceeding

**Comment by anisa-hawes** [comment]
Hello @programminghistorian/spanish-team. I have added an alert warning box at lines 204-6 of `en/lessons/building-static-sites-with-jekyll-github-pages.md`. Do you have time to translate this so we can add it to the ES version too?

**Comment by rivaquiroga** [comment]
@Anisa-ProgHist, done.

**Comment by anisa-hawes** [comment]
This build appears to be failing due to a broken link within the EN lesson geospatial-data-analysis.md

link http://lincolnmullen.com/projects/dh-r2/ in paragraph 38 is failing
Could this be a suitable alternative?: https://dh-r.lincolnmullen.com/

What do you think @JMParr?

**Comment by rivaquiroga** [comment]
@Anisa-ProgHist, that broken link was fixed on https://github.com/programminghistorian/jekyll/pull/2251 a couple of days ago. So you need to bring the changes from `gh-pages` to this branch. If you are not sure how to do that, I can show you tomorrow in our meeting.

**Comment by anisa-hawes** [comment]
Ah! Thank you, @rivaquiroga! I would really appreciate that.

**Pull request closed without merging**
