### PR TITLE
Support translate - French

### PR DESCRIPTION
**Pull request by acrymble**
We are checking over the newly translated French IPP pages here. Please do not merge (also our branch is very far behind).

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by acrymble** [comment]
There're some markdown syntax issues on pi.md. And the menu hasn't been updated yet. Will fix.

**Comment by acrymble** [comment]
@mariechristineb can you take a look at the preview (https://app.netlify.com/sites/ph-preview/deploys/604393d48dc54400088997f2) and let me know if you're happy with how those 3 pages look?

**Comment by mariechristineb** [comment]
@acrymble looks good to me - in snippets.yml, I swapped 'Donations' for 'Dons', hope that won't break everything

update: the build looked fine, but I made a last change to the title on line 213 ('Dons individuels') and wasn't sure what to do with the link on line 214 (`/nous-soutenir#dons`) - should it now just be` /dons`?

**Comment by acrymble** [comment]
@programminghistorian/technical-team our branch is really far behind (even before the Portuguese site went live). Is it easier for me to just create a new branch with the desired updates and re-do the pull request? Or is there another way?

**Comment by ZoeLeBlanc** [comment]
Hmm that's a great question @acrymble ! I would normally suggest just pulling from gh-pages into this branch but I wonder if that will mess up the git history too much... do you have thoughts @walshbr?

**Comment by walshbr** [comment]
I don't think we are especially careful about our git history, so I think it's fine to merge gh-pages into this branch. It might be good to resolve the conflicts at the bottom of the pull request before doing so though.

**Comment by ZoeLeBlanc** [comment]
I just fixed the merge issues so this branch is up to date but the build failed because of this following link:
```
- ./_site/fr/dons.html
Ran on 462 files!
  *  internally linking to ipp, which does not exist (line 0)
     <a href="ipp">programme de Partenariat institutionel</a>
```
I'm pretty sure looking at the snippets.yml that this is supposed to be `/fr/pi` but wanted to check before I made a change. Thanks!

**Comment by acrymble** [comment]
@walshbr I've run into a problem trying to re-direct the old /support-us page to the new /individual page. I tried to follow your instructions in _Originally posted by @walshbr in https://github.com/programminghistorian/jekyll/issues/1943#issuecomment-782862364_

But I think having 2 redirects at the top of /en/individual.md is causing an error. Did I mis-read you?

**Comment by walshbr** [comment]
Sorry if you have two redirects for a single page, they'd need to be like this I think:

redirect_from:
  - /post/123456789/
  - /post/123456789/my-amazing-post/

I think it was erroring because you had two separate redirect_from keys, but let me know if you try that and it  doesn't work?

**Comment by acrymble** [comment]
@walshbr Really sorry but that doesn't work. Unless I did it subtly wrong.

**Comment by walshbr** [comment]
I'll take a look!

**Comment by walshbr** [comment]
@ZoeLeBlanc or anyone else on the @programminghistorian/technical-team - this has me pretty stumped. I at least corrected the syntax for the redirect_from pieces on the new pages, but it's still giving this error - 

  Liquid Exception: undefined method `[]' for nil:NilClass in /_layouts/blank.html

I thought it could be because the pt translations are blank on lines 261 and 272 of _data/snippets.yml, but when I filled those in with stub text it didn't correct things. It looks like the error is coming from lines 122 to 130 of _includes/menu.html, because if I comment those out the site builds. But I wasn't to able to narrow down what else seemed to be going on. Can you try to take a look when you get a chance? I won't have time to look at this again for a few days.

**Comment by acrymble** [comment]
@walshbr I can roll back to the part before I tried deleting the old page. This pull request is already messy (my fault). So I can try addressing it in a clean attempt if that's easier?

**Comment by walshbr** [comment]
I think that's not necessary @acrymble - they only started failing when you tried adding the second redirects to those three pages, right? That is supposedly the correct syntax, so it seems like somewhere on our site we might have hard-coded in something that assumes a 1:1 relationship with redirects and can't account for 1:many.

**Comment by walshbr** [comment]
Just FYI @acrymble the tech team has basically all been working on this off and on throughout the day today w/ a lot of back and forth on slack - it was bit thornier than anticipated. Just wanted you to know we're working on it and will update the branch once we get it working.

**Comment by acrymble** [comment]
Thanks @walshbr and I'm very sorry to everyone on the tech team. I didn't want to create any work for you all. I thought this was just a content thing :(

**Comment by walshbr** [comment]
Not your fault! I think it just exposed some architectural things in the ways we had the translations wired together that @ZoeLeBlanc is sorting through.

**Comment by ZoeLeBlanc** [comment]
Woot! Looks like the fix worked and we are in business 🎉 🍾 !! We need to definitely write up a bit in the wiki about redirects and translation.

I also noticed that on pt the supporting us menu items look weird so we might want to check that before merging (but at the same time this is a lot of commits already so I would probably say go ahead and we can open another branch for that issue). Thanks @programminghistorian/technical-team for all your help with this (shoutout @walshbr & @jenniferisasi 🙌🏽 )!!!

**Comment by walshbr** [comment]
Yay! Thanks, team.

**Comment by acrymble** [comment]
Thanks @ZoeLeBlanc and @walshbr. Is there anything I need to know to finish the redirects? I had only done this on one language version as a test, so I have to do the other two still.

**Comment by walshbr** [comment]
@ZoeLeBlanc should confirm since she actually rewrote a bit of the way our translation logic worked to get it to work. But _think_ you should be able to just use the conventional syntax for having multiple redirects now (what I shared before): 

redirect_from:
- /post/123456789/
- /post/123456789/my-amazing-post/

Does that sound right, @ZoeLeBlanc?

**Comment by ZoeLeBlanc** [comment]
Yup that's right @walshbr ! @acrymble go ahead and use the same syntax as earlier, and let me know if you run into any more issues (🤞🏽 it's fixed though!)

**Comment by acrymble** [comment]
I'm still not good at decyphering our new error messages @programminghistorian/technical-team. Is this a 404 error related to the internet archive, or did I do the redirects wrong?

**Comment by ZoeLeBlanc** [comment]
It's not you @acrymble! The Web archive is sending the pdf so slowly over the web that is generating a 404 error. Let me quickly discuss a solution with the tech team but we'll likely either change our build config to ignore this error or try to find an alternative link.

**Comment by acrymble** [comment]
Thank you everyone. I believe this is now ready for review @jenniferisasi .

It adds the new French-language support pages, and redirects the 3 old /support pages to the new ones to avoid confusion to any visitors.

**Comment by jenniferisasi** [comment]
It looks good, @acrymble! Thanks to everyone for working on this.

**Review by jenniferisasi — APPROVED** [review]

**Comment by spapastamkou** [comment]
thank you all for your work on this, folks!

**Pull request merged**
