### PR TITLE
Publish /en/lessons/text-mining-youtube-comments

### LINKED ISSUE #3336: Preparing to publish a new EN original lesson text-mining-youtube-comments
I am opening this Issue to prepare a new EN lesson for publication.

### PR DESCRIPTION
**Pull request by anisa-hawes**
Preparing files for publication.

Closes #3336

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Add the appropriate "Label"
- [x] If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above
- [x] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Manager @anisa-hawes 
- [x] Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)
- [x] Assign at least one individual or team to "Reviewers"
  - ~~[ ] if the text needs to be translated, please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines), then assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR.~~

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Hello @hawc2,

I’ve staged text-mining-youtube-comments for publication. You can [read it through in Preview](https://deploy-preview-3337--ph-preview.netlify.app/) and let me know if you note anything which you'd like to adjust.

If you're happy, we can publish it tomorrow, and then launch the promotions on social media.

--

Thank you,
A.

**Comment by hawc2** [comment]
@anisa-hawes thank you to you and @charlottejmc for all your work on this lesson, it has come out very beautifully, and we're grateful! We really like the featured image too, fits the lesson well.

A few last changes, I'm adding here as final edits I'll leave to you to make before publication: 

- [x] 1) I realized my ORCiD is missing, here it is: 0000-0001-7030-6070

- [x] 2) Because of the new additions we made with 'renv' installing some packages, there's one line that should change in the lesson code, both as it appears in the lesson itself and the accompanying R script we provide. For this line, we should remove the `"quanteda.textmodels",` from this section, as it does not need to be installed a second time:

`install.packages(c("tidyverse", "quanteda", "quanteda.textmodels", "quanteda.textplots"))`

So it should read: 

`install.packages(c("tidyverse", "quanteda", "quanteda.textplots"))`

- [x] 3) At least one of the internal links to a heading section is slightly broken. The first time [Querying YouTube’s API] appears, I think the link included the apostrophe in s so it doesn't go anywhere upon clicking. Some of the other section heading links didn't seem to be working for me, but maybe that's this preview and my slow hotel internet...

- [x] 4) In first paragraph of Querying YouTube's API, the following word should have a space added so `YouTube's APIv3` reads `YouTube's API v3`. 

These are the only changes I saw in a last look over the lesson. Please feel free to go ahead and approve this pull request after you've made these final edits, so we can publish on time tomorrow. 

If you need my help with anything like reviewing drafts of the Twitter posts, could you email me at my personal email address so I can be responsive on short notice tomorrow while I'm at the conference?

**Comment by anisa-hawes** [comment]
Thank you, @hawc2!

I've worked through (and checked off) the [small edits you've listed above](https://github.com/programminghistorian/jekyll/pull/3337#issuecomment-2274858123). I've checked through to ensure that that every section link now works as it should.

The "evergreen" posts for social media are not urgent - please email these to Charlotte in September. For now, we will be using the template-form announcements which we've prepared on our side (thanking all contributors + sharing the DOI). We will post an announcement upon publication, and schedule a follow-up post to go out 21 days after publication.

Thank you ✨

**Comment by hawc2** [comment]
Perfect, thank you @anisa-hawes. It's ready for publication!

**Review by hawc2 — APPROVED** [review]

**Pull request merged**
