### PR TITLE
Update ph_authors.yml

### PR DESCRIPTION
**Pull request by pymentha**
*add the reason for your pull request here*

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Review by DanielAlvesLABDH — CHANGES_REQUESTED** [review]
Olá @pymentha! As alterações que fizeste no ficheiro contém alguns erros. Essencialmente com o espaçamento face ao início de cada linha. Vê o exemplo da colega Gwenaëlle Patat umas linhas mais acima...

**Comment by pymentha** [comment]
Opa! Já vou ver. Obrigado.

Ricardo M Pimenta

Em seg., 22 de mar. de 2021 18:18, Daniel Alves ***@***.***>
escreveu:

**Comment by DanielAlvesLABDH** [comment]
Olá @pymentha , o erro ocorre ainda, em princípio pelo mesmo motivo. Eu vou corrigir, mas sempre que os "checks" falharem você pode ver as mensagens de erros se clicar em "details" no "build_programming_historian". Se os "checks" passarem (a verde) pode visualizar como vão ficar as mudanças clicando em "details" no "netlify". Abraço

**Comment by DanielAlvesLABDH** [comment]
As falhas eram no endereço Twitter (não pode levar o @) e no endereço web (faltavam aspas). Tem de associar a este PR também a inclusão da sua foto: "uploading a square black and white avatar (.png) of yourself to /[avatars](https://github.com/programminghistorian/jekyll/tree/gh-pages/avatars)."

**Review by DanielAlvesLABDH — DISMISSED** [review]

**Comment by DanielAlvesLABDH** [comment]
@programminghistorian/technical-team this PR is failing because of broken links related to the deletion of "lesson-requests" files. How can we solve this? Or is it something that only the Technical Team can solve?

**Comment by walshbr** [comment]
If you look here - https://github.com/programminghistorian/jekyll/pull/2084/checks?check_run_id=2203365254  -  the errors are broken links from past blog posts that linked to the lessons page. That's not a tech team fix really - someone just needs to adjust those past blog posts to remove those links. @jenniferisasi those pages are gone entirely right? Is there something you wanted to do  with those blog posts (they look like newsletter blog posts but I could be wrong).

**Comment by DanielAlvesLABDH** [comment]
Thanks @walshbr , I have noticed that. I will wait Jennifer reply. If I can do that change just let me know

**Comment by jenniferisasi** [comment]
I'll edit the posts

**Review by DanielAlvesLABDH — APPROVED** [review]

**Comment by DanielAlvesLABDH** [comment]
@pymentha este PR está pronto, pode fazer o merge e fechar

**Pull request merged**
