### PR TITLE
Add Zoe to README

### PR DESCRIPTION
**Pull request by mdlincoln**
lol almost forgot

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  ~- [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description~
- [ ] Add the appropriate "Label"
- [x] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
~- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above~

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by spapastamkou** [comment]
Your name is also mentionned twice in the editor guidelines page in all languages. I'll replace it with "technical team" in this PR and ask the tech team to review (and change if there is a better idea).

**Comment by spapastamkou** [comment]
@programminghistorian/technical-team I squatted Matt's PR to modify the editor guidelines: his name is mentionned twice and I replaced it with "technical team" to have a generic and sustainable term. Please review if you are ok with this. If nobody can change the ES page I will make a separate issue to ask the ES team to do so. Thanks.

**Review by svmelton — DISMISSED** [review]

**Review by ZoeLeBlanc — DISMISSED** [review]
Looks great to me 👍

**Comment by acrymble** [comment]
In order to close this ticket can someone from the @programminghistorian/spanish-team please remove references to "Matt Lincoln" from this file and replace it with something generic but appropriate?: https://github.com/programminghistorian/jekyll/blob/gh-pages/es/guia-editor.md

Thank you.

**Comment by rivaquiroga** [comment]
@acrymble, I can work on this during the afternoon (UTC -4)

**Review by rivaquiroga — APPROVED** [review]

**Comment by acrymble** [comment]
This pull request will affect the Portuguese core pages translation. 
@ZoeLeBlanc can we merge this to avoid that problem?

**Review by walshbr — APPROVED** [review]

**Comment by ZoeLeBlanc** [comment]
Thanks for the final review @walshbr 🙏 . I'm gonna go ahead and merge now

**Pull request merged**
