### PR TITLE
preparing image classification lesson for publication

### PR DESCRIPTION
**Pull request by hawc2**
@anisa-hawes @scottkleinman I'm preparing @nabsiddiqui's lesson for publication here, will let you know if I have any questions

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Add the appropriate "Label"
- [ ] ~~If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above~~
- [x] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Assistant @anisa-hawes 
- [x] Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] ~~if the text needs to be translated, please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines), then assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR.~~

### CODE REVIEW

**Comment by hawc2** [comment]
@anisa-hawes i'm guessing the current error about 'liquid syntax' relates to the javascript code embedded in the lesson. I don't think we've had too many javascript lessons

**Comment by anisa-hawes** [comment]
The build error detail specifies:

```
Liquid Exception: Liquid error (line 28): comparison of Array with Array failed in feed.xml
```

Line 28 of the file `sketch.js` reads: `if (error) {`. 

Perhaps it would be helpful for us first to test:

- highlighting the javascript ? 
```
```js
```
- using `{% raw %}{% endraw %}` at that line ?

**Comment by anisa-hawes** [comment]
Hello @scottkleinman and @nabsiddiqui,

Reviewing this in the Netlify Preview, I have a thought about Figure 9.

In my view, we should always provide cut-and-pasteable code, rather than showing it in screenshots. This supports our broader aim to improve the readability and usability of our lessons. If you agree, I can make this change on your behalf.

I realise that, in this case, what is shown is output rather than input – but I still think it is best practice to insert a code block rather than an image.

cc.: @hawc2

**Comment by nabsiddiqui** [comment]
@anisa-hawes That works for me.

**Comment by scottkleinman** [comment]
Thumbs up for me too.

**Comment by hawc2** [comment]
Looks good to go to me @anisa-hawes. Once you approve, I can go ahead and publish mid-day tomorrow

**Comment by anisa-hawes** [comment]
It seems these checks are failing due to a GitHub Actions update: https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/.

I will take a look at the instructions provided and see if I can work out what is needed to fix it later this afternoon. Thank you, @ZoeLeBlanc for identifying the culprit!

**Pull request merged**
