### PR TITLE
UofL workshop

### PR DESCRIPTION
**Pull request by acrymble**
Adds a workshop at University of London to the research pages.

### CODE REVIEW

**Comment by drjwbaker** [comment]
@acrymble This is failing due to an error with `./_site/en/lessons/analyzing-documents-with-tfidf.html` which has nothing to do with this PR. @programminghistorian/technical-team: help please.

**Comment by jenniferisasi** [comment]
> @acrymble This is failing due to an error with `./_site/en/lessons/analyzing-documents-with-tfidf.html` which has nothing to do with this PR. @programminghistorian/technical-team: help please.

Let me check, but by just looking at that path I think the .html is off. 

Update: no! My bad. That's the url for the website, so it's html. Let me keep checking.

**Comment by jenniferisasi** [comment]
So, the url "https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/feature_extraction/stop_words.py" for "preselected list" in the lesson in the sentence that reads: 
> This setting will filter out words using a preselected list of high frequency function words such as ‘the’, ‘to’, and ‘of’. 
Takes us to a 404. 

The link has an added _ before stop_words 

https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/feature_extraction/_stop_words.py 

Let's edit that file

**Comment by jenniferisasi** [comment]
Ok, I fixed that issue, now... but it looks like is doing nothing here...

**Review by jenniferisasi — APPROVED** [review]

**Comment by jenniferisasi** [comment]
@walshbr do you know why all these new pull request are getting the same issue with a link I just fixed?

**Comment by walshbr** [comment]
@jenniferisasi if you pushed up the fix it won't get automatically merged into a pull request that was created before the fix. i can make that merging happen in a sec.

**Comment by walshbr** [comment]
That did it @jenniferisasi - I'll take a look at a couple PRs and do that same merging. But ping me if I miss one?

**Pull request merged**
