### PR TITLE
Issue 3102 publish /en/lesson/transcribing-handwritten-text-with-python-and-azure

### LINKED ISSUE #3102: Preparing to publish new EN lesson transcribing-handwritten-text-with-python-and-azure
I am opening this Issue to prepare transcribing-handwritten-text-with-python-and-azure for publication.

### PR DESCRIPTION
**Pull request by anisa-hawes**
Preparing files for publication.

Closes #3102 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Add the appropriate "Label"
- [x] If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above
- [x] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Assistant @anisa-hawes 
- [x] Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)
- [x] Assign at least one individual or team to "Reviewers"
  - ~~[ ] if the text needs to be translated, please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines), then assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR.~~

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Hello @hawc2. 

I’ve staged transcribing-handwritten-text-with-python-and-azure for publication. You can [read it through in Preview](https://deploy-preview-3103--ph-preview.netlify.app/) and let me know if you note anything which you'd like to adjust. 

We can publish it next week when our colleagues at Sussex will be around to activate our DOI, and Charlotte and I can launch the promotions on social media.

Thank you,
A.

**Comment by anisa-hawes** [comment]
Olá @DanielAlvesLABDH,

May I ask for your help to check a Portuguese translation of this author's bio? 

```
bio:
    en: |
      Jeff Blackadar has a Master of Arts in History with a specialization in Data Science from Carleton University.
    pt: |
      Jeff Blackadar é licenciado em História pela Carleton University com uma especialização em Ciência de dados.
```

(Jeff has published with us previously, and that lesson has been translated in to PT [/pt/licoes/introducao-mysql-r](https://programminghistorian.org/pt/licoes/introducao-mysql-r) but now their bio has changed).

**Comment by hawc2** [comment]
Thanks Anisa. This looks good to go to me. Only one minor revision - From the abstract, I don't think we need this sentence: "Google Colab is used as the example Python programming environment."

**Review by hawc2 — DISMISSED** [review]

**Comment by anisa-hawes** [comment]
Thank you, @hawc2.

I'm just awaiting Daniel's confirmation that he is happy with the PT translation of Jeff's revised bio.

---

Hello @DanielAlvesLABDH,

I wondered if you could check my attempted Portuguese translation here. This author has published with the English journal before, and the PT journal translated that lesson. Their bio need to be updated, so I'd like to check with you that this is correct and reads well to you? Many thanks, Anisa

```
bio:
    en: |
      Jeff Blackadar has a Master of Arts in History with a specialization in Data Science from Carleton University.
    pt: |
      Jeff Blackadar é licenciado em História pela Carleton University com uma especialização em Ciência de dados.
```

**Comment by anisa-hawes** [comment]
Thank you for your help with the PT translation, @joanacvp! 

--

Hello @hawc2,

This is ready! I've adjusted the abstract as you suggested and have revised my Portuguese translation of Jeff's revised bio with Joana's support.

Re-requesting your review now. 

When the merge has completed, I'll liaise with our colleagues at Sussex to activate the DOI and then we will launch our announcements on social media.

Thank you,
Anisa

**Review by hawc2 — APPROVED** [review]

**Pull request merged**
