### PR TITLE
remove outdated data from authors.yml

### LINKED ISSUE #1675: Clear out unneeded personal information from author pages
To avoid carrying personal information we no longer require, I'll go through our author page and make sure to delete any information relating to former team members that we no longer require (eg, email addresses). (Can you tell who just took a data protection test?)

### PR DESCRIPTION
**Pull request by acrymble**
Closes #1675 
Removes some old data about former team members that is no longer required.

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by acrymble** [comment]
I don't think I understand the travis error:

> - ./_site/en/lessons/research-data-with-unix.html

>   *  External link https://openhatch.org/missions/windows-setup/install-git-bash failed: 404 No error

> htmlproofer 3.15.1 | Error:  HTML-Proofer found 1 failure!

> The command "_build/build.sh" exited with 1.
cache.2

> store build cache

**Comment by walshbr** [comment]
You can ignore this piece in the error - 

"htmlproofer 3.15.1 | Error: HTML-Proofer found 1 failure!

The command "_build/build.sh" exited with 1.
cache.2

store build cache"

That is just telling you something went wrong. The meat of the error is in the first two lines, and they say that research-data-with-unix.html has an error with this URL - https://openhatch.org/missions/windows-setup/install-git-bash -  not resolving.

**Comment by acrymble** [comment]
@walshbr how do we normally resolve problems with lessons that pop up during the course of unrelated pull requests?

**Comment by walshbr** [comment]
I don't think there is a good workflow for it. In the past I believe we've just corrected those small issues in the pull request even though they're unrelated. Technically that might be a bad practice because they're not an issue related to the PR in question. But I'm not sure it matters too much - @mdlincoln might have further thoughts about how much we should care about lumping fixes into a single PR.

**Comment by mdlincoln** [comment]
Broken urls: "if you find it, you fix it": https://programminghistorian.org/en/editor-guidelines#4-confirm-all-links-and-yaml-headers-are-functioning-correctly

Go snag the Wayback machine link and replace it.

**Comment by acrymble** [comment]
@mdlincoln I've tried to do this, but increasingly I'm finding internet service providers in the UK are blocking the wayback machine. I've noticed this in the past year, and I suspect it's related to concerns about copyright or some legislative change I haven't heard of.

That means I'm not able to access waybackmachine URLs or make this update.

**Comment by drjwbaker** [comment]
> @mdlincoln I've tried to do this, but increasingly I'm finding internet service providers in the UK are blocking the wayback machine. I've noticed this in the past year, and I suspect it's related to concerns about copyright or some legislative change I haven't heard of.
> 
> That means I'm not able to access waybackmachine URLs or make this update.

If we find this we should report to the UK Web Archive, as they recommend the use of Wayback Machine for the sustainability of URLs and have (some) lobbying power in the UK. I don't think we should move away from WBM because UK ISPs are getting twitchy on copyright.

**Comment by acrymble** [comment]
@drjwbaker If we're reporting it, Vodafone is definitely blocking it though they denied it when I called them. I'm on Sky right now and couldn't get in. I can sometimes get in on 3.

**Comment by drjwbaker** [comment]
@acrymble I'm on Sky and it works fine right now, even without my VPN on.

**Comment by acrymble** [comment]
@drjwbaker when you have time, can you post the relevant internet archive link here so I can update the lesson?

**Comment by drjwbaker** [comment]
https://web.archive.org/web/20190318191709/https://openhatch.org/missions/windows-setup/install-git-bash

**Review by rivaquiroga — APPROVED** [review]

**Pull request merged**
