### PR TITLE
add mapping lesson kp

### PR DESCRIPTION
**Pull request by kimpham54**
Adding the Mapping with Python and Leaflet lesson @ianmilligan1

### CODE REVIEW

**Comment by ianmilligan1** [comment]
Thanks, @kimpham54 - just a heads up, I am the editor assigned to this lesson. I'll start working it through the review process.

**Comment by kimpham54** [comment]
thanks!

**Comment by ianmilligan1** [comment]
Update on @kimpham54's submission as of 5 November: I've reached out to two peer reviewers. Given the busy-ness of the academic term right now, we've settled on 10 December as our goal for reviews. They'll post comments here.

Just to provide context for my own role: as the editor on this lesson, I will be responsible for finding reviewers and clarifying required/suggested changes with the author. My role is to mediate between reviewers and authors, and keep the process on track in a timely manner, etc. If anybody needs to contact me outside this forum, my e-mail is [i2millig@uwaterloo.ca](mailto:i2millig@uwaterloo.ca), although in keeping with public scholarship and peer review we generally encourage discussions to take place on this pull request.

Looking forward to being in touch with everybody in a little over a month.

**Comment by kimpham54** [comment]
need to incorporate difficulty level, see #91. i'd say this can be classified as an intermediate lesson

**Comment by ianmilligan1** [comment]
Agree re: #91 - intermediate would sit well with this one.

**Comment by jburnford** [comment]
This is a good intermediate lesson with two goals: to teach basic geocoding of
CSV data and provide a very basic introduction to Leaflet web mapping. The
geocoding lesson is pretty useful and builds on earlier Python lessons from the
Programming Historian. I think the editors should consider how to keep the
lessons as consistent as possible. The early lessons use Komodo edit, while most
of the more recent lessons use the shell. This lesson uses a text editor. I
think it is important that students can progress through the lessons and not get
hung up on these differences. I personally think that Python’s IDLE is a good
tool that combines a text editor and shell (I’m not sure if it is much use for
HTML though, in which case Text Wrangler comes in handy). Throughout the Python
section we are clearly shown what to do, but I don’t know that many of the steps
are explained in enough detail for someone on the edge of beginner/intermediate.
I’ve used pandas before, so I was happy to just follow along and had a general
sense what I was doing, but a newer user might not learn much beyond cutting and
pasting some code that works, but without understanding why. It might also be
worthwhile to expand on the problems with geocoding. Adding the City column does
mostly fix the errors we get the first time we run the geocoder, but most of the
time we can’t add this precise of a “helper”. What do we do if we’re running
this on 500+ lines and it is wrong 15% of the time? Is there another step to
clean the data? Or would you simply do it manually in Excel or using find
replace in a text editor for all of the wrong locations?

The Leaflet section was interesting, as I’ve been meaning to learn Leaflet, but
also a little disappointing, as it is a very basic introduction. I like the
exercise approach, but I was hoping to get beyond creating a maps with a few
dozen points and the ability to click to view some attribute data. I was able to
geocode and create a similar map with all the rows of data in under five minutes
using Google:
https://www.google.com/maps/d/edit?mid=zcYbIluB78iw.kJ5-tS6qf0K4&usp=sharing
My desire to learn Leaflet comes from being underwhelmed by this kind of web
mapping, so it was a bit disappointing to spend a couple hours to learn to do
what I already know how to do in five minutes. To address this concern, it would
be great if you could add a section to the end on next steps. Suggesting we
should try a time-based visualization is great, but where do we learn that? Is
there a particularly good book on Leaflet that people could turn to and build on
what they’ve learned here? Do we need to start by doing some more advanced
Javascript tutorials?

These concerns aside, I enjoyed the tutorial and I think it will make a good
addition to the Programming Historian once the issues I’ve noted below are
addressed.
1.  The link for the original CSV downloads HTML from the Github page and not
   the correct raw data. Fix the link or add instructions to click through and
   download.
2.  Generating points from the place names is one option and the right option
   for this exercise, but you might also want to mention the option to download
   or create polygons for this data. There are polygons for this particular
   dataset.
3.  (Note: programmers like to use "0" instead of "1" to indicate the first
   value in an index) – I’d say Python uses “0” instead of “1” to indicate the
   first value in an index.
4.  Typo: is where yu indicate
5.  There is not enough information here:
   1.  capabilities user-input static (Google's non-static geocoding service
      not in geopy)
   2.  I’d expand or remove this line. The other lines are clear enough for an
      intermediate user.
6.  The data does not come with an underscore between Area and Name: “Area Name”
   not “Area_Name”. (see more on this below)
7.  Google Geocoder resulted the errors mentioned on the first try and I did not
   get it working.
   1.  I think you need to either expand on why humanists might want to use the
      Google tool or simplify the lesson focusing on the open tool and simply
      mentioning that users can experiment with other options on the own.
8.  It was not clear that we were continuing to build the function “main” as we
   added the geolocator and latitude/longitude steps. It would be better if the
   code blocks included the pervious code as it builds and shows the student
   how it expands.
9.  Option two is not clear. I don’t see how I’m meant to convert
   geocoding-output.csv into a vrt file? Are we meant to type this out by hand?
   You need to spell this out a little more clearly. Is there really not tool
   that will do this aside from the web tool that 99% of the people reading
   this tutorial will use?
10. Clean up: {% include figure.html src="../images/webmap-02-countrycolumn.png"
    caption="Add a new Country column to your spreadsheet" %}
11. You suggest we add a column for Country and City and then just use the
    Country column, which still does not create usable results. Switching to
    City does work, though Outer London remains a problem. I’m guessing we’re
    not going to use inner, outer or greater London data, so maybe we should
    have deleted it from the start?
12. Add a reminder to save census.geojson after you’ve fixed the data
13. Will the Simple server work from a Windows machine?
    1.  Is this step needed if we’re working from a directory? Double clicking
       on mymap worked.
14. This would not be very helpful for someone who is stuck: Do you see a map
    now? Good! If not, you can troubleshoot by inspecting the browser, or by
    going back and retracing your steps.
15. My map at this point still includes Outer London in the Indian Ocean; maybe
    we could have deleted this earlier?
16. Typo: each poit of data is represented by an icon
17. When creating the map we run into the same problem with “Area Name”; I’m
    guessing you made the change to the original CSV and forgot to add that step
    to the tutorial. I tried changing the leaflet code to remove the underscore,
    but not surprisingly, it breaks the map. I’m going to recreate my
    census.geojson file now with the underscore added, but the needs to be
    addressed at the start of the lesson. You might also delete inner, outer and
    greater London at that point?
18. Where is the stations.geojson data?

**Comment by ianmilligan1** [comment]
Thanks @jburnford - your comprehensive and careful review is _very_ appreciated.

@kimpham54, we're still waiting on one more review (which I've been informed is in the final stages of prep), and then I'll review these, give some suggestions as well, and we'll be on the path towards revisions. 

Be in touch shortly.

**Comment by shawngraham** [comment]
I agree with Jim's overall assessment here, and think this will be a welcome addition to the Programming Historian. 

I think though there may be a fundamental issue in that this tutorial is trying to do too much. The author has I think at least 3 separate tutorials, each one of which would be valuable to Programming Historian readers. If the Geocoding, the ogr2ogr, and leaflet sections were spun into separate lessons, the author could go into the greater detail that both Jim and I are looking for. I've pasted below the individual notes I made while I was working through this material. I've deleted any bits and pieces that duplicated comments or issues that Jim comments on.

---

link to working tutorial files should go directly to the folder, eg https://github.com/kimpham54/proghist-mappingAPI/tree/master/tutorial-files

---

> Import your folder in a text editor such as TextWrangler for OS X, Notepad++ for Windows, or Sublime Text

I know this is pitched as 'intermediate', but I could see this as being problematic. It wasn't immediately obvious to me how I do this, as I don't tend to work with text editors in this particular way. Nor, after having gone through the whole thing, is it apparent what this step does/means.

---

Obtaining the source csv. The link we really want is the raw - https://raw.githubusercontent.com/Robinlovelace/Creating-maps-in-R/master/data/census-historic-population-borough.csv

Perhaps show the reader how to grab with curl etc from command line?

`curl https://raw.githubusercontent.com/Robinlovelace/Creating-maps-in-R/master/data/census-historic-population-borough.csv > census.csv

## `

Is it desirable to send the reader off-site to learn how to install the ancillary materials? Should there be a quick 'here's how to get pip'?

---

> On OS X or Linux, the following commands will install the necessary packages:

Explain why numpy, dateutils etc are necessary?

---

I get the following errors on an up-to-date Mac, up-to-date everything else:

```
File "geocoder.py", line 17, in <module>
    main()
  File "geocoder.py", line 12, in main
    io['latitude'] = io['Area_Name'].apply(geolocator.geocode).apply(lambda x: (x.latitude))
  File "/Library/Python/2.7/site-packages/pandas/core/frame.py", line 1969, in __getitem__
    return self._getitem_column(key)
  File "/Library/Python/2.7/site-packages/pandas/core/frame.py", line 1976, in _getitem_column
    return self._get_item_cache(key)
  File "/Library/Python/2.7/site-packages/pandas/core/generic.py", line 1091, in _get_item_cache
    values = self._data.get(item)
  File "/Library/Python/2.7/site-packages/pandas/core/internals.py", line 3211, in get
    loc = self.items.get_loc(item)
  File "/Library/Python/2.7/site-packages/pandas/core/index.py", line 1759, in get_loc
    return self._engine.get_loc(key)
  File "pandas/index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas/index.c:3979)
  File "pandas/index.pyx", line 157, in pandas.index.IndexEngine.get_loc (pandas/index.c:3843)
  File "pandas/hashtable.pyx", line 668, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12265)
  File "pandas/hashtable.pyx", line 676, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12216)
KeyError: 'Area_Name'
```

---

> Tip 1: If you want to pass the filenames from the command line rather than changing the input file name in the python script everytime, you can import the python 'sys' library to pass through arguments.

example of how this works.

---

> Tip 2: If you run it too many times because you get a timeout error, like this if you use the GoogleV3 geo

I'm not sure what you're telling me here

---

Option 1 for creating geojson - the animated figure shows the user dragging across a csv file, which might be confusing? maybe can you create a video clip that shows the user exactly what you're telling them?

---

Installing GDAL is not straightforward. More info here. 

---

Perhaps the ogr2ogr portion should be spun off into a separate ancillary lesson? I was lost at 'Make sure that OGRVRTLayer, SrcDataSource have the same name as your filename (census_geocoded.vrt).' I think you're talking about your raw csv file becomes the .vrt? 

---

On cleaning the data - this should perhaps come first, just after the download of the data. You could write something to the effect: There are many 'Londons' in the world - it can help improve the accuracy of the geocoder if we add a bit more context. In this case, we can do this by adding another column with 'Country' ... etc.

---

I think I would spin the leaflet tutorial out from this tutorial as well.  I can imagine a reader might want to geocode, but then use CartoDB or some other service to do the mapping. This would also address some of Jim's concerns, as you could go into greater detail all the different ways leaflet could be used - you'd answer the 'what's in it for me' question.

**Comment by ianmilligan1** [comment]
Thanks also for your review, @shawngraham - very much appreciated.

OK, we now have two reviews in. Over the next few days, let me review them, study the lesson, and provide some synthesis comments on it. In a dream world, this could happen tomorrow, but in a realistic world it may need to wait until early next week.

**Comment by ianmilligan1** [comment]
Again, my sincerest thanks to @kimpham54 for writing the lesson and to @jburnford and @shawngraham for taking time to write their insightful reviews of the lesson. 

The two reviews provide good pathways forward. Both were overall supportive of publication and quite encouraging, and both provide excellent ideas for revising the piece to make it even more accessible and useful for our readers.

Both mentioned the issue of text editor, something that we as an editorial team should discuss a bit more (as @jburnford notes, we originally used Komodo Edit, but now have a good hodgepodge of platforms out there). It is true that importing a folder wouldn't be straightforward for some of our users. Maybe give a quick walkthrough using Sublime Text, one of the few cross-platform editors out there?

Some specifics:
- @jburnford gives many suggestions about adding some more detail, justification, and apparatus to make the significance of the lesson clearer. I think for most you can respond to them in the text of the lesson to clear things up. In cases like cleaning up the data, I think you could mention how to do it on a small scale on Excel, and provide suggest some links to other options that you might do on a larger scale?
- For leaflet, an additional section about what Leaflet is and makes possible - a few exemplar project links? - and how it's a good platform to invest in would be useful. What does it do that's different than Google Maps? Just make it super explicit.
- @shawngraham suggests three different tutorials. I'm not quite sure we've got enough material for three separate lessons, and I'm personally a fan of longer tutorials where appropriate than hiving them up (a stylistic decision), but it's advice worth heeding. I think that by adding more detail as appropriate from @jburnford's review, a longer lesson can make more sense: perhaps adding some level 1 headers to make it more structured, three chapters within a broader lesson?
- The specific itemized list provided by both @jburnford and @shawngraham are both useful, and I think they can all be pretty easily implemented. The `area_name` vs `area name` issue threw errors for both reviewers, a minor tweak. 

OK! Overall, I think these are good, feasible suggestions for revisions. Feel free to ping me either on or offline as you start moving forward on revisions.

The next steps will be @kimpham54 revising the lesson as time permits, I'll play-test and review one last time, and we should be able to get this up on _Programming Historian_ by early 2016.

Again, thanks to all.

**Comment by acrymble** [comment]
is this still active here or should it be closed? Not clear if this was moved to submissions but we're more than 7 months old.

**Comment by kimpham54** [comment]
still active, my deep deep apologies i hope to address all of the feedback i've received and incorporate those comments and update the lesson for review. my plan is to resume work on this by the end of the summer

**Comment by ianmilligan1** [comment]
This wasn't moved to submissions as it came under the old system – my sense is that @kimpham54 is just really busy with too many cool things. 

Kim, why don't we have a check in Skype at some point in August? My schedule's pretty good all month during workdays.

**Comment by kimpham54** [comment]
yes we should definitely touch base again. How about on August 12th?

**Comment by ianmilligan1** [comment]
Aye, pick a time - my day is fully open!

**Comment by kimpham54** [comment]
great, how about 1? i'm available also at 12 or after 3

**Comment by ianmilligan1** [comment]
Great - I will schedule this for 1pm on August 12th. Talk to you then!

**Comment by mdlincoln** [comment]
Hey @ianmilligan1 what's the status of this submission? I'm hoping to close these old PRs if possible... but if this lesson is still in development, it's no problem to leave open.

**Comment by kimpham54** [comment]
@mdlincoln @ianmilligan1 just pushed my fixes to github. the submission is ready for another review

**Comment by ianmilligan1** [comment]
OK thanks @kimpham54 – what I will do is probably migrate this over to our new submissions branch, and then I will review and get back to you asap.

Sorry for the delay on this, life has been hectic.

**Comment by ianmilligan1** [comment]
Actually @kimpham54 – would you be able to move this over to the [PH-Submissions repo](https://github.com/programminghistorian/ph-submissions) – I realize it's hard to work on a pull request like this whereas you have all the files locally. 

I'll add you as a contributor there. Let me know if you have any questions!

**Comment by ianmilligan1** [comment]
Moved over to ph-submissions for previewing, integrating with our new workflow. 😄

**Pull request closed without merging**
