### PR TITLE
Newsletter 2 (sept. 2019)

### PR DESCRIPTION
**Pull request by jenniferisasi**
English and Spanish versions of the Newsletter #2 ready for review; French version following shortly.

### CODE REVIEW

**Review by rivaquiroga — DISMISSED** [review]

**Review by arojascastro — DISMISSED** [review]
I read the newsletter in Spanish! Nothing to comment. Thanks for your work!

**Review by drjwbaker — DISMISSED** [review]
Fine from an EN perspective. Thanks so much for writing this!

**Comment by jenniferisasi** [comment]
Thanks @rivaquiroga, @arojascastro and @drjwbaker for reviewing the ES and EN versions. If I could get anyone in the @programminghistorian/french-team to double check the post it would be great (else, I'll still merge it this evening because I had it revised at home and, if truly necessary, I can still introduce changes later)

**Comment by spapastamkou** [comment]
I think it needs some changes in FR but won't be able to work on this before tomorrow morning on behalf of @programminghistorian/french-team, @jenniferisasi. Maybe @fdlaramee or @grandjeanmartin can help?

**Review by mdlincoln — DISMISSED** [review]

**Comment by mdlincoln** [comment]
FYI the English post wasn't rendering because there was an `_` in the filename. **Reminder: you can't just check travis, but you also need to check the netlify build - this would have shown you that the English post was not showing up!** It's a weird eccentricity of how Jekyll handles posts unfortunately.

**Comment by jenniferisasi** [comment]
> FYI the English post wasn't rendering because there was an `_` in the filename. **Reminder: you can't just check travis, but you also need to check the netlify build - this would have shown you that the English post was not showing up!** It's a weird eccentricity of how Jekyll handles posts unfortunately.

Thanks for catching that up @mdlincoln, I don't know how come I did one underscore in that file but hyphens on the other two. Noted for future posts

**Comment by fdlaramee** [comment]
@jenniferisasi Made some adjustments to the French text and approved the PR. If @grandjeanmartin and/or @spapastamkou want to give it another read, I promise I won't be offended. 😀

**Review by fdlaramee — APPROVED** [review]

**Comment by jenniferisasi** [comment]
Merci @fdlaramee! I'll give it a couple hours in case they want to make further changes, but I plan to have it online soon so that it is available as of Oct 1 for those to the East (of where I'm located).

**Pull request merged**
