### PR TITLE
Closing the translation of the PH Portuguese platform - Issue 1891

### PR DESCRIPTION
**Pull request by DanielAlvesLABDH**
Concluded the translation of the following files to Portuguese: activities.yml; ph_authors.yml; snippets.yml; teamroles.yml; topics.yml; lessons-requests.md; translator-guidelines.md; lesson-retirement-policy.md; and author-guidelines.md

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [ ] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by walshbr** [comment]
@DanielAlvesLABDH am I right in understanding that

a) this is ready for review
b) this will conclude all translation needs
c) after merging this, PT ProgHist should be public?

If those are all correct I'll go through and have a look.

**Comment by DanielAlvesLABDH** [comment]
Yes to all @walshbr thanks! The only one that I have some doubts is ph_authors.yml because I didn't saw the bios from Joana and Danielle there. But maybe that will be resolved after the comparison with other branches (sorry if I'm making some confusion here, but still learning).

**Comment by walshbr** [comment]
No worries! Yeah this is an older pull request so it needs to be updated with the latest stuff on the main site. I just updated it, so it should be in synch now. Will check when I get a second.

**Comment by walshbr** [comment]
@DanielAlvesLABDH are there any lessons that have been translated? not seeing any in the pt/licoes folder. were you planning to make this go public without them?

**Comment by DanielAlvesLABDH** [comment]
@walshbr as I understood the translation of the platform was the first step. From the talk with @acrymble I got the impression that only after that we should start planning the inclusion or translation of the lessons. We were unable to make both things at the same time. Of course, if we need to have one or two lessons first before the site go live, we will wait. In the last meeting of the PT team we already planned a schedule for the first lessons. So, what is our advice? Should we go live or wait for the first lessons? Thanks for the help

**Comment by walshbr** [comment]
If the plan all along has been to launch the PT portion of the site publicly with no lessons in it I might just need to double check a few pieces - @acrymble can you confirm that's the plan? Sorry if that's been mentioned elsewhere and I missed it - totally possible. My head is everywhere these days!

I'll need to check to make sure the architecture of the site doesn't assume in certain places that you'll have lessons. For example the front page looks like this right now when I get it up and running, but that might just be a matter of something we missed rather than a limitation of how it's wired together. 

Screen Shot 2020-10-02 at 10 59 54 PM

**Comment by acrymble** [comment]
It's not up to me. But it would seem to make sense to launch a publication with some actual content.

Can you make the pages live @walshbr without the front page and menu (PT) links? Then the pages are done but no one is likely to find them until there is something to see.

**Comment by DanielAlvesLABDH** [comment]
Thank you both for the clarification. I will talk with the rest of the team and see if we have one or two lessons that can be translated in a shorter time. It makes more sense to go live with some content yes!

**Comment by walshbr** [comment]
Let me look into this to see what is possible and get back to you!

**Comment by jenniferisasi** [comment]
I think we asked the French team to have a minimum of lessons ready on launch? I've tried to look for that on tickets but failed, so, @spapastamkou did we ask for lessons before you launched?

Wouldn't that also solve the ISBM request "problem"? 

@DanielAlvesLABDH the first Python lessons are short, if you could start with those, it could be "fast": https://programminghistorian.org/en/lessons/introduction-and-installation

**Comment by DanielAlvesLABDH** [comment]
Thanks @jenniferisasi those lessons are the first target for us. I sent an email to all the team today, asking.

**Comment by spapastamkou** [comment]
We had launched the web site once we had the first lesson ready - it felt better to propose even a minimum of content. Notable difference though, we did not have to translate this ourselves after translating the main pages: we had a small stock of translations that were offered to us by students of a DH department, so we just had to organize the review process. Note also that as soon as we launched we received very quickly spontaneous volunteer translations, so get ready just in case PT team:-)

**Comment by walshbr** [comment]
I'll take a look early next week to see if it's an actual technical requirement we have at least one lesson and let you know. It's not my decision either, but to me it makes sense to have at least one lesson just as a teaser of what's to come.

**Comment by DanielAlvesLABDH** [comment]
Thanks to all! We will wait for the first lesson

**Comment by walshbr** [comment]
ok! I'll take care of this later this week then. Both to see if it's a technical requirement we have a lesson and to see about making the pages exist without putting the language button / interface in place.

**Comment by walshbr** [comment]
I checked into this a little more - part of the issue I was seeing was there was an issue with the workflow for how to set up a new language. Just a piece to the series of steps that was missing. I fixed that and updated the wiki. So it looks like we might be able to launch with zero lessons in the future, FWIW. 

When we do a final look for the pieces to publish them with the first lesson I'll build the pages - they're blocked by a line in config.yml for now to save the netlify preview some build time. I think go ahead and merge @DanielAlvesLABDH and ping me with any other questions or on the pull request to make the thing live with the first lesson and we can do a final pass. But things look OK so far!

**Review by walshbr — APPROVED** [review]

**Comment by DanielAlvesLABDH** [comment]
Thank you for all your work @walshbr . This means that I can merge this PR? Meanwhile we decided to only publish the site when we have at least one lesson translated. We are in the process of doing that. More news soon...

**Comment by walshbr** [comment]
Yep  @DanielAlvesLABDH go ahead and merge this!  Sounds good.

**Pull request merged**
