### PR TITLE
Create consignes-traducteurs.md 

### PR DESCRIPTION
**Pull request by spapastamkou**
création de la page Consignes aux traducteurs et aux traductrices.

### CODE REVIEW

**Comment by fdlaramee** [comment]
Bonjour @spapastamkou -- Le texte est traduit et prêt à être révisé. J'attire ton attention sur trois questions précises:

Ligne 41: Vérifier que le répertoire des images sur ph-submissions est bien le même pour les traductions françaises que pour les leçons originales. Il n'y a pas de sous-répertoire pour des images associées à une traduction française dans ce répertoire en ce moment alors je ne peux pas le confirmer moi-même.

Ligne 46: Je ne connais pas de traduction française de 'pull request' alors j'ai laissé le terme en anglais.

Ligne 40 et 62: Je ne connais pas non plus de version française des manuels d'instruction de GitHub; s'il en existe un et que tu le connais, il faudrait ajuster les liens vers la documentation dans ces deux paragraphes.

Voilà; s'il y a autre chose que je puisse faire, j'aurai du temps vendredi matin heure du Québec.

**Comment by mdlincoln** [comment]
Hello @programminghistorian/french-team team - does this PR need more editing? Or is it ready to merge?

**Comment by fdlaramee** [comment]
Hi @mdlincoln -- Of the three details I asked @spapastamkou to double-check, only the first is potentially problematic: is the images directory on ph-submissions the same for French translations and for original English/Spanish lessons, or is there a separate directory or subdirectory?

The other two questions involve vocabulary (I don't think that there is an official French translation for "pull request") and the existence or nonexistence of French documentation for Github. If you can answer the question about the images directory we can probably go forward.

**Comment by spapastamkou** [comment]
Thank you @fdlaramee for all this work to which I was able to contribute after a long (and disconnected!) leave. I fixed some minor typos, added the anchor links in the beginning of the file and, finally, proposed some terms that it seems to me are of wider use (for example: "navigateur" instead of "fureteur" web). Please check to see if you are ok with these.  
As for your 1st question: there is no separate repository for the images of the FR (or ES) translated lessons, so everything is ok. 
For the 2nd: I am not aware of an existing translation for "pull request" and I think we used the term in English in another page. 
For the 3rd: there does not exist a FR translation of the Github documentation (this would be a nice project:))
So I believe we are fine for this page.  

However, after updating the branch, all builds fail because of some dead links in a 2016 blogpost. I tried to replace them with internet archive links, @mdlincoln, but not all of them are archived (here is a non-archived one: https://digital.houstonlibrary.org/cdm/singleitem/collection/curriculum-project/id/17/rec/2). What to do in this case? Here is the link for the travis report just in case: https://travis-ci.org/programminghistorian/jekyll/builds/575873539?utm_source=github_status&utm_medium=notification

**Comment by fdlaramee** [comment]
@spapastamkou Thanks Sofia; all fine by me!

**Review by mdlincoln — APPROVED** [review]

**Comment by mdlincoln** [comment]
Reminder @fdlaramee that if you wish to indicate your approval for changes, you must formally add your pull request review: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#adding-a-pr-review

I've done it for you this time.

**Comment by fdlaramee** [comment]
@mdlincoln Thanks; I didn't think I should be the one to approve the PR in this case since I had performed most of the translation.

**Comment by spapastamkou** [comment]
it should have been me, pardon

**Pull request merged**
