### PR TITLE
Targeted English IPP/Patreon pages

### PR DESCRIPTION
**Pull request by acrymble**
DO NOT MERGE. This is an attempt to preview only (because I don't know how to do that locally).

This updates the English-language support pages and will (eventually) make it a targeted menu item aimed at our different types of donors. Done in collaboration with Comms team. In particular, it moves "policy" information to our wiki (https://github.com/programminghistorian/jekyll/wiki/Donations-and-Fundraising-Policies), splits individual and IPP donations onto two pages and attempts to make both easier to action and more enticing. This follows the model used by Open Library of Humanities.

When ready it needs to be added to the menu (yml files currently locked as PT are translating them). and the old page changed to a redirect.

We will have to decide later if other languages need this, similar, or different information to target donations in their own contexts (and even if we will bother seeking donations in all languages, as this is requires active management for each language). It is clear that one type of messaging does not work for all, so we should shift away from translating this type of material.

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by acrymble** [comment]
@jenniferisasi I've done some additional tinkering since our conversation, in part to make the page actually look nice. When you get a chance, take a look and let me know what you think. We can't merge while the .yml files are still being edited, but we can play around with it until we're happy.

**Comment by acrymble** [comment]
@jenniferisasi I think I managed to do it without screwing any thing up but please check the menus are done correctly. It's ready for your review and merging if it's ok.

For info for the rest of the team, we aren't translating this immediately because we will be seeking feedback from potential IPP partners and therefore may need to revise this again. In the meantime links have been added to the existing page in non-English versions.

**Comment by jenniferisasi** [comment]
@acrymble this looks fantastic! I like how you made a menu for ES and FR with the links to places in the original page.

Not sure why Travis CI has been running since yesterday? (I checked the PR and was waiting for it to run before commenting and then I took a few hours off) I am going to check the _data file as well, try to figure it out

**Comment by jenniferisasi** [comment]
So, no idea why Travis is stuck @programminghistorian/technical-team anyone?

**Review by jenniferisasi — DISMISSED** [review]

**Comment by walshbr** [comment]
Perhaps because of the conflicts in _data/snippets.yml. I might fix those and then see if it still stalls out? I can help out if you can't figure it out though.

**Review by walshbr — DISMISSED** [review]
The merge conflicts will need to be resolved before merging.

**Comment by walshbr** [comment]
Just tried to resolve them - let's see if that works.

**Comment by walshbr** [comment]
And FWIW in the future - you can go to  https://travis-ci.com/github/programminghistorian/jekyll/pull_requests to directly see the status of the processes on travis itself. There's a little button to restart the build if something gets hung up.

**Comment by walshbr** [comment]
Travis ran - one error
  *  External link https://programminghistorian.org/en/individual failed: 404 No error

**Comment by acrymble** [comment]
That's one of the new pages that doesn't yet appear on the site. Could that be why it says the link doesn't exist?

**Comment by walshbr** [comment]
Someone had edited the lessons template previously to use an absolute link rather than a relative one - https://github.com/programminghistorian/jekyll/pull/1901/commits/a5969edd6338b0b78d11003de64172eaea1928b6 - that means that it would come up as a 404 unless the site was live. The relative URLs mean it should work when developing like this, which is why we try to use them. Should be good to go now.

**Review by jenniferisasi — APPROVED** [review]
Looks good to me, @acrymble !

**Pull request merged**
