### PR TITLE
Issue 3396

### LINKED ISSUE #3396: Potential issue with Setting Up an Integrated Development Environment for Python (Windows)
I have a report that this https://programminghistorian.org/en/lessons/windows-installation article doesn't work. I'm not totally sure what the issue is (I was told it second hand) but it may be that the article suggets learners use Komodo Edit when they need Komodo IDE. 

I have also marked this article for possible retirement as it does not make a clear methodological contribution, which - as @anisa-hawes is aware, though I appreciate this hasn't been communicated to MEs yet @hawc2 @jenniferisasi @marie-flesch @ericbrasiln - is a threshold the publisher like to introduce for lesson maintenance given that our publishing estate is now very large and we do not have sufficient resources to fix issues with lessons that replicate information easily found elsewhere or through AI/LLM pair programming (which may mean, that in some cases EN articles are retired whilst ES/PT/FR articles stay live).

### PR DESCRIPTION
**Pull request by charlottejmc**
I have updated the link to download Komodo Edit across the en, es, fr and pt versions.

Closes #3396 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Add the appropriate "Label"
- [x] If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above
- [x] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Manager @anisa-hawes 
- [x] Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines), then assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR.

### CODE REVIEW

**Comment by charlottejmc** [comment]
Hi @hawc2, I've requested your review for this PR which hopefully solves the problem flagged by an external contributor, which James has shared in Issue #3396. The download is a bit slow on my end, but it works. Let me know if you think this fix is enough to close the related issue!

**Comment by anisa-hawes** [comment]
Hello @hawc2,

You'll note that Charlotte has updated the download links to make things clearer. I'm satisfied that this resolves the immediate problem, and the lessons remain usable for now.

Let's continue the conversation about how we decide which lessons can be maintained and which should be retired.

Thank you. A.

**Comment by hawc2** [comment]
Thanks @anisa-hawes and @charlottejmc. This looks like a good fix.

With that said, I don't know if it is as simple as replacing every mention of the Komodo Website with the Active State Website. They're very different kinds of websites and it may be worth alerting the reader to that. The link currently provided doesn't bring up a website, it just downloads the file. I wonder if we could link to the Active State website with this link, and then provide in addition the specific download link.

https://downloads.activestate.com/Komodo/releases/12.0.1/

This gives the reader some context what they're downloading. I also think it's best practice to tell the reader what the Active State site is, a place for hosting open source software it seems. If I we're reading this I'd be worried Active State is not a real website and I might be downloading a virus or something. I had never heard of it before now.

Did the Komodo website shut down entirely? Is it worth adding a brief note about this change and why it's happening? Has Komodo been sunset? This context seems important to provide for the reader with a sense of how it works in 2024.

**Comment by charlottejmc** [comment]
Thank you for your notes, @hawc2!

I've made some further edits to address your points, which I think are indeed important. 

I made the download link more explicit, and also linked directly to ActiveState (they are the developers behind Komodo Edit, apparently!).

In the warning box I added, I linked to [this blog post](https://www.activestate.com/blog/activestate-komodo-ide-now-open-source/) which explains why ActiveState decided to retire Komodo Edit (and Komodo IDE). Hopefully this should provide some helpful context.

I also suggested readers use a different programme instead – would you agree?

If you agree to these changes, I can coordinate the translations into the other languages.

**Review by hawc2 — DISMISSED** [review]

**Comment by charlottejmc** [comment]
Hello @jenniferisasi and @ericbrasiln, I've made some changes to the EN original lesson, because Komodo Edit has been retired (although it's still usable). I've made the new download link easier to find, and I've added a warning box which tells readers that it's probably best to use another option if they can.

Would you kindly be able to translate  my changes (or coordinate their translation!) into ES and PT? You'll see in the [files changed](https://github.com/programminghistorian/jekyll/pull/3401/files) tab that I've made an edit to both your files already, but you can **ignore that commit**, and use my EN/FR changes as an example instead.

Thank you very much for your help 😊

**Comment by ericbrasiln** [comment]
Hello @charlottejmc,

Thank you for the update! I've included the changes in the Portuguese lesson file in the **Issue-3396** branch. Please let me know if there’s anything else I can help with.

**Comment by charlottejmc** [comment]
Super! Obrigada, @ericbrasiln.

**Comment by jenniferisasi** [comment]
Sorry for my delay @charlottejmc! I have just translated the two paragraphs into Spanish - and hopefully the checks will run to be ready to merge.

**Comment by anisa-hawes** [comment]
Hello all, 

The broken links blocking this build are under investigation in #3413 !

**Comment by charlottejmc** [comment]
Thank you @jenniferisasi for the translation! The broken links are now working again, so this PR is ready to merge 🎉

**Review by anisa-hawes — APPROVED** [review]
Thank you for coordinating @charlottejmc! And thanks to all for their translations and contributions.

**Pull request merged**
