### PR TITLE
Adding my avatar and bio, closes  #1858

### LINKED ISSUE #1858: Adding my bio and avatar
As part of my onboarding process (issue #1829), I'm adding my bio and my avatar to be included in the Project Team page.

### PR DESCRIPTION
**Pull request by aracele**
Adding my avatar as part of my onboarding process (#1829).

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by DanielAlvesLABDH** [comment]
Aracele, probably the problem is similar to the one I had, my image was not square. Please check that. Also see this https://github.com/programminghistorian/jekyll/pull/1813

**Comment by acrymble** [comment]
Hi @aracele . The image is also quite large (1000px). Our system will not resize the file, so this means every time someone visits the Project Team page they have to download a large image. This is not a problem everywhere but it may be a problem for people in countries with poorer internet connections. I would suggest reducing it to about 400px square.

But the problem with your pull request is that there is a broken link elsewhere on the website. You will probably need help from someone on the @programminghistorian/technical-team for this.

**Comment by josircg** [comment]
@aracele I "squared" the image with this site. https://fengyuanchen.github.io/photo-editor/

**Comment by aracele** [comment]
Thank you, guys! I'm uploading a smaller file. Hope it works.

**Comment by walshbr** [comment]
Just a note that it looks like something is going on with the caching that Travis uses when checking the links - they're sometimes showing up as broken here and sometimes fixed. But they definitely remain down (ProfHacker is gone as far as I can tell for good). Right now they're showing up as fixed, but they're definitely still broken. 

If they show up again, and you get a red X, follow the instructions here for exploring the travis build issues - https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions. We generally operate on a "if you find a broken link in your pull request you fix it" model here, so this would be good practice. But if you look through that wiki page and can't figure out how to find the error and troubleshoot it let me know. 

If the rest of the pull request looks good otherwise, I would go ahead and approve/merge, even knowing that there are some broken links Travis is being weird about. We'll get them in the future, and it's the nature of the internet for it to rapidly rot in front of our eyes.

**Comment by aracele** [comment]
So, since I need translation for my bio, should I assign French and Spanish team here?

**Comment by walshbr** [comment]
Yep - that sounds right @aracele

**Comment by aracele** [comment]
> Yep - that sounds right @aracele

Thank you @walshbr !

**Comment by aracele** [comment]
Dear Team, could you please translate my bio? Thank you in advance! :)

@rivaquiroga & @programminghistorian/spanish-team 
@spapastamkou & @programminghistorian/french-team

**Review by JoshuaGOB — DISMISSED** [review]

**Review by fdlaramee — APPROVED** [review]

**Comment by aracele** [comment]
@DanielAlvesLABDH are we ready to merge this? :)

**Comment by walshbr** [comment]
Ah the protocol might be clear. @aracele - we usually leave it to the person who opened the pull request to be the one to actually click the merge button after getting all approving reviews. I think that helps the process because the creator of the PR often knows best when the work is done.

**Pull request merged**
