### PR TITLE
Issue 2631

### LINKED ISSUE #2631: Publish vacancy for new French Managing Editor
I am preparing to publish an advertisement for a new French Managing Editor on the Vacancies / Vacantes / Postes vacants / Vagas pages our website.

### PR DESCRIPTION
**Pull request by anisa-hawes**
I am publishing an advertisement for a new French Managing Editor on the Vacancies / Vacantes / Postes vacants / Vagas pages our website.

Closes #2631 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Review by matgille — CHANGES_REQUESTED** [review]
Small modification required: I would drop the articles before "Rédacteur en chef". 
Something I missed at the time of the redaction is the translation of workflow. I prefer to use "chaîne de traitement", it seems more accurate to me. 

Otherwise it's perfect, thanks a lot Anisa !

**Comment by anisa-hawes** [comment]
Thank you, @matgille! I have made those changes.

**Review by matgille — CHANGES_REQUESTED** [review]
Thanks for the modifications, I think something went wrong with the replacement of  "flux de travail" with "chaîne de traitement", it doesn't appear in the update file !

Thanks again

Matthias

**Review by matgille — DISMISSED** [review]
= ) Thank you !!

**Review by matgille — APPROVED** [review]
It's perfect, I think we can merge the pull request. Thank you very much !

Matthias

**Pull request merged**
