### PR TITLE
Temporal Network Analysis lesson

### PR DESCRIPTION
**Pull request by mdlincoln**
This is still going through final edits, but since we need to confirm the formatting of tables and an animation, I wanted to do it over on the main site.

**Lesson Preview**: https://deploy-preview-1053--ph-dev.netlify.com/en/lessons/temporal-network-analysis-with-r

- [x] It looks this lesson contains a full link to "https://programminghistorian.org". All internal links should start with "/" followed by the relative page path, and not use the full domain name.
- [x] 'reviewers' is missing.
- [x] 'difficulty' is missing.
- [x] 'activity' is missing.
- [x] 'topics' is missing.
- [x] 'abstract' is missing.
- [x] 'editors' is missing.
- [x] 'review-ticket' is missing.
- [x] 'Alex Brey' is not currently listed in ph_authors.yml.
- [x] must select gallery image
- [x] post twitter summary
- [x] finagle CSS

### CODE REVIEW

**Comment by mdlincoln** [comment]
@alexbrey for a lesson avatar image, what do you think of:

1) https://www.flickr.com/photos/britishlibrary/11058271455/

or 

2) https://www.flickr.com/photos/internetarchivebookimages/20208859124

or

3) https://www.flickr.com/photos/internetarchivebookimages/14560969000/

Also feel free to search for other pics if none of those appeal.

**Comment by mdlincoln** [comment]
I also tightened up the padding on the table cells slightly so that your columns hopefully display better - let me know what you think.

**Comment by mdlincoln** [comment]
@alexbrey I just have a last few editorial thoughts in addition to the formatting fixes I've made:

1. In note 4 you mention there are some ways to deal with variation based on your averaging decisions, but that it's too complex to get into. If you have some link or paper that interested readers could go to in order to at least get an introduction to this topic, that would be a useful addition to the footnote.

2. In the section on forward & backward reaching, you do this kind of non-idomatic R thing of assigning `sets <- NULL` and then populating it with the results of two different `tReach` function calls... am I right that this just produces an R `list`? And then all you end up doing is plotting each of those elements separately. Why not just:

```r
fwd_reach <- tReach(dynamicCollabs),
bkwd_reach <- tReach(dynamicCollabs, direction = "bkwd")

plot(fwd_reach, bkwd_reach)
```

This seems more R-like, but maybe I'm missing something?

**Comment by mdlincoln** [comment]
@alexbrey I also need you to post a brief bio in this comment thread so that I can add it to the lesson footer.

**Comment by mdlincoln** [comment]
I've checked in with @alexbrey by email, still waiting to hear from him on these final comments.

**Comment by alexbrey** [comment]
Thanks very much for your help with this final checklist @mdlincoln, and apologies for the slow reply.

- I'm a big fan of the hourglass with the ouroboros, but it's a little pixellated so I'd probably vote for number 3 with the sundial. Those are all great finds, and any would be fine with me.
- The padding on the table cells looks great!
- As far as note 4 goes, I'm hoping to present a paper on these approaches at in a DH venue somewhere, and write it up for my website. If it's possible, it would be great to add that link later once I've written it up somewhere. If you know of anything worth linking to now I'd be happy to add that.
- I agree that your approach to plotting the values is more in fitting with the R idiom. I adjusted this in the ph-submissions/lessons folder, but it's not showing up as a change in the netlify preview.
- Bio: Alexander Brey is a Research Associate at the Center for Advanced Study in the Visual Arts. His research investigates mechanisms for and perceptions of cross-cultural exchange in medieval visual culture, with a focus on the Islamic world.

Thank you again for your time and consideration in wrapping up these final issues.

**Comment by mdlincoln** [comment]
I've updated all the final points here. And yes, if you open up a ticket here with a new citation once you have it, we can update the lesson.

I'll get this merged in tonight/tomorrow and then publicize tomorrow morning!

**Comment by mdlincoln** [comment]
@programminghistorian/english-team can I get a PR review on this cool new lesson?

**Pull request merged**
