### PR TITLE
add new translation on powershell

### PR DESCRIPTION
**Pull request by arojascastro**
Please approve this addition. 

Links may be broken until we fix issue #854

### CODE REVIEW

**Review by vgayolrs — APPROVED** [review]

**Comment by arojascastro** [comment]
Should I merge this? I think the only problem are those external links. Or should I wait until we merge issue #854

**Comment by vgayolrs** [comment]
@arojascastro I'm a little out of date to answer your question...

**Review by mdlincoln — CHANGES_REQUESTED** [review]
After merging that old PR, there's still one broken link on this new page (I think you just need to add a forward slash before `es` so it's `/es...` instead, and don't forget to include the `lecciones` segment of the path

```
- ./_site/es/lecciones/introduccion-a-powershell.html
  *  internally linking to es/introduccion-e-instalacion, which does not exist (line 873)
```

**Comment by arojascastro** [comment]
I fixed that link but still is not validated.

**Review by mdlincoln — APPROVED** [review]

**Pull request merged**
