### PR TITLE
Update about.md

### PR DESCRIPTION
**Pull request by drjwbaker**
Suggested location for deposit wording. Discuss.

### CODE REVIEW

**Comment by ianmilligan1** [comment]
This looks good to me, @drjwbaker!

**Review by mdlincoln — APPROVED** [review]

**Review by mdlincoln — CHANGES_REQUESTED** [review]
Looks good - now we need a Spanish translation.

**Review by vgayolrs — APPROVED** [review]
Translation in progress

**Comment by vgayolrs** [comment]
done @mdlincoln

**Review by mdlincoln — APPROVED** [review]

**Pull request merged**
