### PR TITLE
Add crossref pt

### PR DESCRIPTION
**Pull request by ZoeLeBlanc**
Adding Crossref.xml and fixed links so that PT can go live 🎉 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [ ] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Review by walshbr — DISMISSED** [review]

**Comment by jenniferisasi** [comment]
Uh OH! I hate to be the messenger of bad news! Are you seeing the PT logo also with this font? It is not the same one we have for the others; I had an issue with it too for the newsletter that @acrymble flagged cos I didn't realize on time. 

Screen Shot 2021-01-28 at 11 04 50 AM

**Comment by ZoeLeBlanc** [comment]
Thanks for catching that @jenniferisasi ! Did you create a different version of the logo for the newsletter? I'm not sure who created this initially 🤔

**Comment by DanielAlvesLABDH** [comment]
I think the new image is here: https://github.com/programminghistorian/jekyll/pull/1971/

**Comment by jenniferisasi** [comment]
I used one @acrymble sent me but it has the URL below; and I have it on png not svg
ph-pt

**Comment by ZoeLeBlanc** [comment]
Just added updated SVGs, if y'all could let me know if they look ok that would be great!

**Comment by walshbr** [comment]
@DanielAlvesLABDH and @jenniferisasi FWIW we were discussing at the call (I think after you left, @jenniferisasi) the need for some sort of blog post announcing the new language journal, rather than just quietly tweeting about it! We were trying to strategize after making it a meaningful launch.

**Comment by ZoeLeBlanc** [comment]
Never mind still working on the images

**Comment by DanielAlvesLABDH** [comment]
@walshbr Joshua sent me an email on Monday asking for a blog post to announce the launching of the website. I'm writing...

**Comment by walshbr** [comment]
Perfect :)

**Comment by jenniferisasi** [comment]
I just opened an issue #2000 to record the process of the blogpost to announce PT launch

**Comment by ZoeLeBlanc** [comment]
I tried redoing the png in Illustrator but not sure I got it right. Would you mind taking a look @jenniferisasi ? Thanks!

**Comment by jenniferisasi** [comment]
> I tried redoing the png in Illustrator but not sure I got it right. Would you mind taking a look @jenniferisasi ? Thanks!

They look like the correct ones to me @ZoeLeBlanc, thanks! I don't know how to do svg I must say.

**Comment by ZoeLeBlanc** [comment]
Thanks @jenniferisasi ! If someone wants to give the PR a review, we can merge it in 😊

**Review by jenniferisasi — DISMISSED** [review]
Everything looks good to me! I would wait till @walshbr can double-check it as well, if not, it's ready!

**Review by DanielAlvesLABDH — DISMISSED** [review]
Made some changes. For me it's fine!

**Comment by walshbr** [comment]
I think a snippet might not have gotten translated? It looks like the "support us" menu, FWIW. If you can't find where to edit I can try to track it down in the file for you. 

Screen Shot 2021-01-28 at 6 26 28 PM
Screen Shot 2021-01-28 at 6 26 12 PM

**Review by walshbr — CHANGES_REQUESTED** [review]
Support us snippets need to be addressed.

**Comment by ZoeLeBlanc** [comment]
Thanks for catching this @walshbr ! @DanielAlvesLABDH @programminghistorian/portuguese-team would you be able to add these edits to this branch so we can merge it in and go live?

It looks like it's just in the `snippets.yml` and begins with `menu-support-us`. Let us know if you have any questions and thanks for your help!

**Comment by DanielAlvesLABDH** [comment]
> Thanks for catching this @walshbr ! @DanielAlvesLABDH @programminghistorian/portuguese-team would you be able to add these edits to this branch so we can merge it in and go live?
> 
> It looks like it's just in the `snippets.yml` and begins with `menu-support-us`. Let us know if you have any questions and thanks for your help!

Done!

**Review by DanielAlvesLABDH — APPROVED** [review]

**Comment by ZoeLeBlanc** [comment]
This looks good to me @DanielAlvesLABDH ! @walshbr or @jenniferisasi can you double check? Thanks!

**Review by jenniferisasi — APPROVED** [review]

**Comment by jenniferisasi** [comment]
I don't know how I missed that on my first review, apologies!

**Review by walshbr — APPROVED** [review]

**Comment by walshbr** [comment]
We'll need to double check the lesson itself to make sure everything looks good when it's up. Also we'll need to add PT to the RSS feed - I can open a ticket for that.

**Comment by ZoeLeBlanc** [comment]
Thanks @walshbr ! I'll send up off the crossref.xml to Tim right now so that hopefully we can get the DOI tomorrow at some point. 

Kudos to @walshbr @DanielAlvesLABDH @jenniferisasi for all your help getting this past the finish line. Excited to announce PT officially once we have the lesson and DOI, as well as blog post, but until then still very exciting to have this step complete 🎉 🍾

**Comment by DanielAlvesLABDH** [comment]
Many thanks to all of you, to all the wonderful PH team for the hard work and collaboration! Obrigado!

**Pull request merged**
