### PR TITLE
Correspondence Analysis in R

### PR DESCRIPTION
**Pull request by mdlincoln**
I'm staging these lessons for final checks.

Original submission issue: https://github.com/programminghistorian/ph-submissions/issues/78

- [x] avatar image
- [x] author bio
- [x] add to twitter bot
- [x] move ph-submissions text to `published/`

### CODE REVIEW

**Comment by mdlincoln** [comment]
@greebie are you comfortable adding your brief bio text by PR to our `ph-authors.yml`? The relevant location is here: https://github.com/programminghistorian/jekyll/blob/correspondence-analysis-in-R/_data/ph_authors.yml#L771

You can also just post your bio as a comment here and I'll add it.

**Comment by mdlincoln** [comment]
My two suggestions for a lesson avatar (remember, these will be cropped into squares)

["Corresponding" shells](https://www.flickr.com/photos/britishlibrary/11305899614/in/photolist-ie4G4G-hUS7a1-jYZxQd-hWN2R7-hQT9HP-icYn8U-i9g9p5-hRMgEi-hN8gAp-i75ipz-hMHZcu-hTHr2S-hRtbpA-ie8gs8-icuDRY-i8yP9k-i8cPWz-hMKjzN-hTLe7L-hMkkKu-hQDWkP-hTacEh-i6SpB9-i7bNgP-hMrhx4-icrUB6-i9h8rT-i3vB8z-hMD3u2-i7cSPB-hPDTB7-hSftNx-hRrp1c-hSg9we-i99cCz-ie74Fz-hRarjU-n99ViX-ie2XLD-hZpaAo-hV4XqT-i6CFGS-hLDfwf-i3SX5K-hMo2qZ-icWoHF-i2Q4EJ-i7957y-hQMZfP-idGZa9)



["Multidimensional" cube](https://www.flickr.com/photos/britishlibrary/11045637363/)



([other prism-like possibilities here](https://www.flickr.com/search/?user_id=12403504%40N02&view_all=1&text=prism))

I'm open to other suggestions if you see something in that flickr group that looks nice.

**Comment by mdlincoln** [comment]
Also, you can see a web preview of this PR at: https://deploy-preview-604--ph-dev.netlify.com/lessons/

**Comment by greebie** [comment]
I like the multidimensional cube as a header.  It has a more mathematical feel to it.  Also I added a file change request with my bio.  Thanks again!

**Comment by mdlincoln** [comment]
I don't see any PR for your bio - did you send it in yet? Either that or GitHub is being incorrigible - just post it here for me to add.

**Comment by greebie** [comment]
Blargh.  :)  

Ryan Deschamps is a Postdoctoral Fellow at the University of Waterloo where he helps design unique tools for managing and studying web archives. His research interests include Canadian digital history, public policy, and quantitative methods in the social sciences.

**Comment by greebie** [comment]
Found it - it was my fault - I edited the file in a fork, but did not submit the pull request.  Sorry!

**Comment by mdlincoln** [comment]
OK, I'm going to merge this and put this lesson live! I'll give it a day of being "soft published" so that we can give it a final look over, and then begin advertising it on Twitter on Friday :)

**Pull request merged**
