### PR TITLE
Update introduccion-al-web-scraping-usando-r.md

### LINKED ISSUE #2806: Applying Perma.cc links to newly published ES lesson
Happy New Year, @rivaquiroga!

Today is my first day back at work. I'm going to add perma.cc links into your newly published lesson: [Introducción al web scraping usando R](https://programminghistorian.org/es/lecciones/introduccion-al-web-scraping-usando-r) ✨

### PR DESCRIPTION
**Pull request by anisa-hawes**
Applying Perma.cc links to newly published ES lesson introduccion-al-web-scraping-usando-r

(It wasn't possible to archive the Amazon.es Condiciones de Uso y Venta / Conditions of Use and Sale page).

Closes #2806 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [ ] Assign at least one individual or team to "Reviewers"
  - [ ] ~~if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description~~
- [x] Add the appropriate "Label"
- [ ] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Thank you, @rivaquiroga. I didn't adjust any of the links within the working code, and I translated the text in places so that I understood if the links represented any direct action. But let me know if I've inadvertently archived links which hinder the reader as they work through the lesson, or done anything which doesn't make sense.

**Comment by rivaquiroga** [comment]
Thanks, @anisa-hawes! I'll check it tomorrow

**Comment by rivaquiroga** [comment]
Thanks, @anisa-hawes! Looks good. I only changed two links.
What do you think of archiving the Amazon link on line 138 (https://www.amazon.es/gp/help/customer/display.html?nodeId=201909000)?

**Comment by anisa-hawes** [comment]
Thank you @rivaquiroga! 

Yes, I tried to archive that page several times but unfortunately it seems that it isn't possible using Perma.cc.

I just tried generating it again, and all that is captured is a generic message "Click here to return to the Amazon home page": https://perma.cc/F62N-NMQ5

However, I was able to capture it with ArchiveWeb.Page (which is the tool I use day-to-day in my freelance practice) but I have not found a simple solution / workflow for using Webrecorder instead of Perma.cc in our context. 

Screenshot 2023-01-11 at 14 32 35

**Review by rivaquiroga — APPROVED** [review]

**Comment by rivaquiroga** [comment]
Thanks, @anisa-hawes!

**Pull request merged**
