### PR TITLE
add Joshua to Global Team

### PR DESCRIPTION
**Pull request by acrymble**
As discussed at the May 2020 Project Team meeting, we've added @JoshuaGOB and his role as New Publications Manager to the 'Global' team. This pull request updates that on the Project Team pages.

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Review by JMParr — DISMISSED** [review]

**Comment by acrymble** [comment]
Dear @programminghistorian/technical-team friends can I get some help interpreting my Travis error here?

**Comment by walshbr** [comment]
This link in a French lesson is broken @acrymble - 

- ./_site/fr/lecons/preserver-ses-donnees-de-recherche.html
  *  External link https://itunes.apple.com/gb/app/id404010395?mt=12 failed: 404 No error

**Comment by acrymble** [comment]
Thanks @walshbr I fixed it. Would you mind reviewing so I can merge?

**Review by walshbr — APPROVED** [review]

**Comment by walshbr** [comment]
Reviewed! @acrymble

**Pull request merged**
