### PR TITLE
Bug feedback pages update 

### LINKED ISSUE #1908: Update `feedback` page
Rework the wording on all _feedback_ pages to make it clear what type of bugs can be reported (and fixed) and what type we cannot attend to. 

https://programminghistorian.org/en/feedback

### PR DESCRIPTION
**Pull request by jenniferisasi**
This is a PR to update the pages following #1908  

@programminghistorian/french-team and @programminghistorian/portuguese-team note how in the ES page on the Option 3 I added a note that says something along the lines of "if you are not confortable using GitHub or don't know English send us an email" because the repo is in English only; I recommend you do the same. I updated the snippets file to reflect on the menu that the page is "to report bugs" and not opinions or general problems. 

@programminghistorian/technical-team sorry to ping you but is there any reason why this feedback pages have a date on YAML? I think we could get rid of them but maybe I am missing something. 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [ ] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #1908` to the description above

### CODE REVIEW

**Comment by ZoeLeBlanc** [comment]
@jenniferisasi removing the date field looks fine to me. Maybe try deleting it locally to double check that nothing breaks 😅

**Review by rivaquiroga — DISMISSED** [review]

**Comment by jenniferisasi** [comment]
Obrigada pela tradução @DanielAlvesLABDH!

**Review by rivaquiroga — DISMISSED** [review]

**Comment by jenniferisasi** [comment]
I have tried to edit the FR page to ease a bit of work for the @programminghistorian/french-team. 

Until they confirm it is all correct, probably not so there would be edits, there is no need to approve the changes yet.

**Comment by mariechristineb** [comment]
@jenniferisasi I updated the French translation just now

**Review by spapastamkou — DISMISSED** [review]

**Comment by acrymble** [comment]
Is there a reason this is stuck @jenniferisasi ?

**Comment by jenniferisasi** [comment]
@acrymble it is stuck cos I got stuck in the branches and then I forgot about it. 

@walshbr I am doing what you told me to do to update the branch but nothing is happening? So I am still stuck 😬

**Comment by walshbr** [comment]
I'm not sure why this was hanging up - going to ping @ZoeLeBlanc on slack about it. But I remerged gh-pages into this one and the errors it gave are below  - 

Found 579 internal links in the cache...
- ./_site/pt/apoie-nos.html
  *  internally linking to /pt/feedback, which does not exist (line 627)
     <a href="/pt/feedback">Envie a sua sugestão</a>
  *  internally linking to /pt/feedback, which does not exist (line 334)
     <a class="dropdown-item" href="/pt/feedback" role="menuitem">Reportar um erro</a>
- ./_site/pt/contribua.html
  *  internally linking to /pt/feedback, which does not exist (line 190)
     <a class="dropdown-item" href="/pt/feedback" role="menuitem">Reportar um erro</a>
  *  internally linking to /pt/feedback, which does not exist (line 436)
     <a href="/pt/feedback">Envie a sua sugestão</a>
  *  internally linking to /pt/feedback.html, which does not exist (line 355)
     <a href="/pt/feedback.html">feedback</a>
- ./_site/pt/directrizes-autor.html
  *  internally linking to /pt/feedback, which does not exist (line 146)
     <a class="dropdown-item" href="/pt/feedback" role="menuitem">Reportar um erro</a>
  *  internally linking to /pt/feedback, which does not exist (line 700)
     <a href="/pt/feedback">Envie a sua sugestão</a>
- ./_site/pt/directrizes-editor.html
  *  internally linking to /pt/feedback, which does not exist (line 264)
     <a class="dropdown-item" href="/pt/feedback" role="menuitem">Reportar um erro</a>
  *  internally linking to /pt/feedback, which does not exist (line 941)
     <a href="/pt/feedback">Envie a sua sugestão</a>

etc etc etc. There are a bunch more but they all seem to be pointing to the fact that this /pt/feedback page doesn't exist.

**Comment by DanielAlvesLABDH** [comment]
Hi @walshbr I will take a look in the morning. Is this something that we (pt team) have made wrong? Because everything seems to be working fine on Friday...

**Comment by walshbr** [comment]
Not sure - I just merged the thing in but haven't looked too closely. I can take a look tomorrow - since that file does appear to be on this branch it looks like something weird is going on that isn't related to anything you did.

**Comment by ZoeLeBlanc** [comment]
Pretty sure the pt/feedback file got renamed to pt/reportar-um-erro but the links to it in snippets.yml and other files did not get updated. Definitely something small that can wait for tomorrow though!

**Review by ZoeLeBlanc — APPROVED** [review]
Everything looks great to me 👍🏽 and seems like it's building no problem now 🎉

**Review by DanielAlvesLABDH — APPROVED** [review]
Thanks for this @ZoeLeBlanc. Were you able to identify the origin of that change? The file name change? Because I don't remember doing it

**Comment by walshbr** [comment]
@DanielAlvesLABDH looks like it was you seven months agoaccording to the git blame link but not a big deal! Probably just an accidental holdover from way back. https://github.com/programminghistorian/jekyll/blame/be5696e3b78a04ca3bfdb34b696df79289055264/_data/snippets.yml#L140.  As I understand it that interface tells you who made the last change to each line in a file. I don't really have a reason to  dig into the git blame interface very much, though, so I might be misreading it. @ZoeLeBlanc might have a better read.

**Comment by DanielAlvesLABDH** [comment]
Thanks for clarifying @walshbr ! 7 months ago was on my pre-history phase on GitHub! Sorry for the mess! ;-)

**Comment by jenniferisasi** [comment]
Thanks @walshbr and @ZoeLeBlanc as usual for your technical expertise.

**Pull request merged**
