### PR TITLE
Creating Common Similarity Measures lesson

### PR DESCRIPTION
**Pull request by svmelton**
Creating PR for [Common Similarity Measures lesson](https://github.com/programminghistorian/ph-submissions/issues/275).

Could someone from @programminghistorian/spanish-team check my translation of John R. Ladd's bio in ph_authors.yml?

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by walshbr** [comment]
lmk if this is ready to review @svmelton from the tech team side? I saw you pushed a couple commits.

**Comment by jenniferisasi** [comment]
Checking the translation @svmelton, needs some edits that I will do myself. (I have to check how to translate early modern studies...)

**Comment by svmelton** [comment]
> lmk if this is ready to review @svmelton from the tech team side? I saw you pushed a couple commits.

Yes, that would be great!

**Review by walshbr — APPROVED** [review]
Looks like it's all working to me! I'll add the tweets to the bot when it's live.

**Pull request merged**
