### PR TITLE
Unified home page

### LINKED ISSUE #855: Language-independent landing page
Now that all English pages are under the `/en` path except the current `index.html`, we still need to settle on what our lading page at <https://programminghistorian.org> should look like.

One possibility could be showing this intro paragraph in each language on the front page, maybe running as three columns across the screen.

screenshot-2018-5-20 the programming historian programming historian

### PR DESCRIPTION
**Pull request by mdlincoln**
Hey all, I've done another pass at a unified homepage that will serve as the new page people get when they go directly to https://programminghistorian.org. The current homepage will now go under `/en`.

Closes #855 

To-do:

- [x] do we want some copy to display on this page at all?
- [x] need to get the logo centering to work on small viewports 😱 

Please take a look at the preview and add your comments:

https://deploy-preview-1088--ph-dev.netlify.com/

### CODE REVIEW

**Comment by mdlincoln** [comment]
I was thinking it could be nice to push this color theme across the whole site, so EN, ES, and FR have different colored headers and footers. Thoughts?

**Comment by arojascastro** [comment]
I was actually thinking about using colors to distinguish editions lately -  I like it. 

Some ideas: 

- I still think it's very empty on both sides. Maybe we could use some free space to display news, blog entries, things that are common and that are updated contantly? A Social media bar? A carrousel displaying latests lessons? I know this is a lot of work and I do not want to give you more work, but maybe we can considerer it in the future.
- This may be controversial... but why not *The Programming Historian **in English***?

**Comment by drjwbaker** [comment]
> This may be controversial... but why not The Programming Historian in English?

I agree. We are the Programming Historian. One of our three publications is *The Programming Historian in English* (or a similar name).

**Comment by drjwbaker** [comment]
I think sidebar would break the mobile view.

**Comment by drjwbaker** [comment]
I suggest no text, but keep working on the design to squish everything up (personally, I'm not so worried about the white space on the side).

**Comment by walshbr** [comment]
This looks great, Matt. I like the idea of PH in English. But wondering if that means we would also want to update our suggested citations to be uniform across languages (add the "in English" bit to the English suggested citation):

Shawn Graham, Scott Weingart, and Ian Milligan, "Getting Started with Topic Modeling and MALLET," The Programming Historian 1 (2012), https://programminghistorian.org/en/lessons/topic-modeling-and-mallet.


Shawn Graham, Scott Weingart, y Ian Milligan, "Introducción a Topic Modeling y MALLET", traducido por Ulrike Henny-Krahmer, The Programming Historian en español 3 (2018), https://programminghistorian.org/es/lecciones/topic-modeling-y-mallet.

I also like the idea of consistent color theming for each language.

**Comment by mdlincoln** [comment]
FWIW CSS is driving me insane right now - I can either get:

1. Vertically centered logo on desktop and NOT horizontally centered on mobile
2. NOT vertically centered logo on desktop and horizontally centered on mobile

Any ideas, bootstrap folks?

**Comment by acrymble** [comment]
I feel like this works well if you know what the Programming Historian already is. But if you just came to the page there isn't any context. Maybe it needs a strapline for each (eg. learn digital skills for humanities work).

Can we tweet this widely and ask friends too for feedback? We need to field test this a bit.

**Comment by mdlincoln** [comment]
@acrymble yes, I agree this definitely needs some text - maybe one line description in each language?

Our core description that shows up on each front page is one possibility:

>We publish novice-friendly, peer-reviewed tutorials that help humanists learn a wide range of digital tools, techniques, and workflows to facilitate research and teaching.

**Comment by mdlincoln** [comment]
This could look like

**Comment by spapastamkou** [comment]
Very nice work, Matt, thanks a lot. Wonder what would that give if we kept the basic title (The Programming Historian) in all versions in one line and put the language part (en français and so on) in the line beneath. Not really a subtitle, just split in parts so that we have the common title for all and then the linguistic specificity of each. 

And just 2 questions: 
- will there be no image at all (I ask because I like the current image a lot:))? 
- if the title changes to The Programming Historian in English, perhaps there will be an impact for the existing ISSN number? https://portal.issn.org/faq#1.10

**Comment by jenniferisasi** [comment]
I like it overall, but I really like @spapastamkou idea of having the language specific beneath "The Programming Historian"

**Comment by mdlincoln** [comment]
The question about changing to "The Programing Historian in English" is an important one, but separate, so I'm going to open a new ticket for that.

**Comment by drjwbaker** [comment]
Look good @mdlincoln. Is there any reason why the gap between the header and the PH EN block is bigger than the gap between each block? Also, that the gap between the header and the blocks and the footer and the blocks is different. Again, is there a reason for this? I accept CSS IS A PAIN!!! as an acceptable answer :)

**Comment by vgayolrs** [comment]
Very nice work @mdlincoln !!

**Comment by mdlincoln** [comment]
I'll finish off the finetuning @drjwbaker once I schedule my dedicated sprint time for the French integration.

**Comment by drjwbaker** [comment]
Works for me. If we can go smaller with the text (perhaps p rather than h4?) and close the gap to the PH above that would be great, though no worries if that is a massive faff.

**Comment by acrymble** [comment]
should they look more button-like? Does that say "click me" to anyone else?

**Comment by arojascastro** [comment]
I am sorry for posting annoying messages, but shouldn't *lecons* be *leçons* ?

**Comment by spapastamkou** [comment]
yes, @arojascastro is right for "leçons".

**Pull request merged**
