### PR TITLE
Translation concordance inconsistency - Closes #2002

### LINKED ISSUE #2002: Translation Concordance Bug - Pt Lesson Template
Take a  look at why that file appears twice, under English and Pt. 

Screen Shot 2021-01-28 at 8 01 14 PM

### PR DESCRIPTION
**Pull request by jenniferisasi**
Closes #2002

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)

### CODE REVIEW

**Comment by jenniferisasi** [comment]
Ok, well, the yaml fix worked because now all 3 lesson templates we have are aligned in the table. Something wrong with some links...

Screen Shot 2021-02-25 at 6 30 36 PM

**Comment by jenniferisasi** [comment]
1) - ./_site/en/lesson-template.html
21 *  internal image /IMAGE-FILENAME does not exist (line 0) 

It is an example and not an actual image... how can we escape it? 

2) *  internally linking to /en/lesson-template.md, which does not exist (line 0)
19 <a href="/en/lesson-template.md">Download the English Language Lesson template (.md)</a>

That is what I am creating... 

@programminghistorian/technical-team help please

**Comment by walshbr** [comment]
Back when we built things with Travis we could ignore particular folders and files -   --file-ignore '/.+/assets/.*/','/.+/retired/.*/', '/.+/retirada/.*/', '/.+/retrait/.*/' \. I assume @ZoeLeBlanc has the same set up with the GitHub integration we're using now. So maybe she can drop that file into the ignored list? I'm not sure how to do so.

**Comment by ZoeLeBlanc** [comment]
So I just tried running your branch locally @jenniferisasi and I got a 404 error for those template pages. Were you able to get this working locally? What happened when you would click on lesson template?

**Comment by jenniferisasi** [comment]
I need to check on this...

**Comment by jenniferisasi** [comment]
Can the superpowers in the @programminghistorian/technical-team do the magic to get this PR in tune with the site now? It is behind by several months, I'm afraid.

**Comment by ZoeLeBlanc** [comment]
Happy to help @jenniferisasi ! Gimme a few minutes and I'll see if I can get it up to date 😊

**Comment by ZoeLeBlanc** [comment]
Just to clarify @jenniferisasi  you want the templates to now be `html` files instead of `md` right? All the current errors I think are from that change, not the updates to gh-pages (at least as far as I can tell since I didn't get any merge errors, just these ones).

I can push up the merged in version but wanted to check with you first about the errors (since they'll still happen regardless of updating the branch). Thanks!

**Comment by jenniferisasi** [comment]
Thanks @ZoeLeBlanc! I think so? Does it look like a proper table when you check it? If so, you can merge. Or we can skip the 'lesson template' files that were causing it to break/look bad as it is in progress for some teams.

**Comment by ZoeLeBlanc** [comment]
@jenniferisasi the table and links looked great and were all working when I built it locally! 

Before we exclude the files, will lesson templates be switching from md to html files permanently? If yes, then we can exclude them for now. If not, then we should fix the bug so that we don't kick the can down the road. 

Let me know which option makes the most sense and I can push up once we've figured it out 😊

**Comment by jenniferisasi** [comment]
`will lesson templates be switching from md to html files permanently?`

I have to check all this again [checking] 

Ok, maybe I was wrong this morning. They are .md files that people can download (or copy paste) with all the symbols and such for headings, italics, etc. as a model. So they don't need to be converted to html for the good looks, cos its purpose is to show how markdown is written. Makes sense?
Screen Shot 2021-05-05 at 3 04 39 PM

**Comment by ZoeLeBlanc** [comment]
Should be good to go now @jenniferisasi ! but definitely double check that everything is still working before you merge 👍🏽

**Comment by jenniferisasi** [comment]
Thanks so much @ZoeLeBlanc. Looks fantastic now. I see a few pages that are not matching, but I know why: it's the Support Us that are awaiting division/re-doing in some languages but are not a problem. Now I only need review approval :)

**Review by ZoeLeBlanc — APPROVED** [review]
couldn't review all 143 files but reviewed the changes and it looks good! Merge away 🚢

**Pull request merged**
