### PR TITLE
Issue 2812

### LINKED ISSUE #2812: Updating Detecting Text Reuse with Passim
Following correspondence with [David Smith](http://www.ccs.neu.edu/home/dasmith/) maintainer of the tool [Passim](https://github.com/dasmiq/Passim), I am preparing some minimal updates to the EN and FR lessons:

/en/lessons/detecting-text-reuse-with-passim
/fr/lecons/detecter-la-reutilisation-de-texte-avec-passim

These edits will ensure that readers can still find the code needed to run the new Passim version 1.

--

Meanwhile, David has also suggested some more extensive revisions to update the tutorial for Passim version 2.

I leave it up to @hawc2 (perhaps in dialogue with @amsichani who was the original editor) to decide if the more extensive update is required here. In [the link David has shared](https://github.com/programminghistorian/ph-submissions/compare/gh-pages...dasmiq:ph-submissions:passim2), I'm not able to see the rich diff, so it is not simple for me to identify where the changes are. If it is decided that an update to version 2 is useful, I'd like to suggest that we ask David to send me the specific line edits.

### PR DESCRIPTION
**Pull request by anisa-hawes**
I am updating /en/lessons/detecting-text-reuse-with-passim and /fr/lecons/detecter-la-reutilisation-de-texte-avec-passim

- Integrating updates prepared by the tool maintainer David Smith to reflect a new version of Passim
- Adding `modified:` to reflect the date of this modification

Closes #2812

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Hello @hawc2,

As suggested in my email, I've prepared the minimal update to Passim version 1. 

Would you like to implement this change now, or wait to discuss more/hear Anna-Maria's thoughts?

-- 

cc. @marie-flesch 

Dear Marie, 

As [explained previously](https://github.com/programminghistorian/jekyll/pull/2804#issuecomment-1363947490) when I carry out a Lesson Maintenance task on a lesson that we've published in more than one language, the update sometimes involves small additions or changes to the text itself. In this case, very minimal!, but if you would like to glance at the [Files Changed tab (above)](https://github.com/programminghistorian/jekyll/pull/2815/files) you will be able to double-check the additions I've made to the FR lesson. 

Thank you, 
Anisa

**Comment by hawc2** [comment]
@anisa-hawes thanks! Let's do the minimal update now and then talk with David and Anne-Marie about the more extensive update

**Review by hawc2 — DISMISSED** [review]

**Review by marie-flesch — CHANGES_REQUESTED** [review]
Hi Anisa, 

There are a couple things to change in this sentence, paragraph 85:
"Avant d’installer cet ensemble de logiciel, vous aurez besoin de télécharger le code source de Passim la version 1 depuis GitHub :"

It should be replaced by:
"Avant d’installer cet ensemble de logiciels, vous aurez besoin de télécharger le code source de la version 1 de Passim depuis GitHub :"

**Comment by anisa-hawes** [comment]
Strange things are happening with two DOI links on our site which are currently functioning as redirects...

https://doi.org/10.1109/BDCloud-SocialCom-SustainCom.2016.76 redirecting to https://ieeexplore.ieee.org/document/7723730

https://doi.org/10.1109/CITS.2013.6705711 redirecting to https://ieeexplore.ieee.org/document/6705711

🤔

**Review by hawc2 — APPROVED** [review]

**Review by jenniferisasi — APPROVED** [review]

**Review by jenniferisasi — APPROVED** [review]

**Comment by anisa-hawes** [comment]
Dear @marie-flesch, 

Thank you for your corrections! 

I have made those small changes. I expected to able to mark that conversation as resolved, but I can’t see how to do it… Chatting with our lovely colleague @jenniferisasi, I realise that I’m not able to merge this PR unless I re-request your review (even though Alex and now Jenn have also reviewed).

Apologies for the need to trouble you for a second time with this!

Anisa

**Review by marie-flesch — APPROVED** [review]

**Comment by marie-flesch** [comment]
no problem @anisa-hawes! Is it because I did something wrong?

**Comment by anisa-hawes** [comment]
Thank you, @marie-flesch! 

No, I don't think so.... I am a bit confused as to why this happened...

Going forwards, one way to do it would be to navigate to Files Changed, then hover over the specific line of code where you'd like to request a change, and click the + icon to add a comment. I should then be able to reply or click to confirm that the correction has been resolved.

That process is explained here, Step 4: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request

**Comment by marie-flesch** [comment]
Ok, thank you @anisa-hawes , I'll do that!

**Pull request merged**
