### PR TITLE
Issue 3121

### LINKED ISSUE #3121: Update lesson topics
Following the (now closed) issue #3111, in which I added `data-visualization` to our list of potential lesson topics, I am now preparing to retroactively add this topic to the relevant lessons in our directory.

### PR DESCRIPTION
**Pull request by charlottejmc**
I have added the new topic `data-visualization` to the relevant lessons.
Closes #3121 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Add the appropriate "Label"
- [x] If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above
- [x] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Manager @anisa-hawes 
- [x] Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)
- [x] Assign at least one individual or team to "Reviewers"
  - ~[ ] if the text needs to be translated, please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines), then assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR.~

### CODE REVIEW

**Comment by charlottejmc** [comment]
Hello @hawc2, @jenniferisasi, @marie-flesch and @DanielAlvesLABDH,

I have gone through our lesson directory to add the new `data-visualization` topic to the lessons I could see mentioned 'visualization'. 

I was wondering whether you might have a quick scan to determine if these all seem correct to you, and if you can think of any additional lessons which could use the topic?

If so, feel free to let me know in a comment below.

Thank you! ✨

**Comment by DanielAlvesLABDH** [comment]
Dear @charlottejmc, many thanks for this work. The definition of data visualization can be challenging but looking at your list I would say to include also all the lessons that deal with GIS or similar mapping tools.
The list from the PT lessons that I would include in this new tag would be:
https://programminghistorian.org/pt/licoes/explorar-analisar-dados-rede-python
https://programminghistorian.org/pt/licoes/analise-correspondencia-pesquisa-historica-R
https://programminghistorian.org/pt/licoes/manipulacao-transformacao-dados-R
https://programminghistorian.org/pt/licoes/analise-sentimento-R-syuzhet
https://programminghistorian.org/pt/licoes/aplicacao-web-interativa-r-shiny-leaflet
https://programminghistorian.org/pt/licoes/georreferenciamento-qgis
https://programminghistorian.org/pt/licoes/camadas-vetoriais-qgis
And all the others that you mention, also.
I hope this helps

**Comment by charlottejmc** [comment]
Thank you @DanielAlvesLABDH, I've now updated the lessons you mentioned (and their counterparts in EN and ES, when they have any).

**Comment by marie-flesch** [comment]
Thank you for this Charlotte! For French, I don't see any other lesson this topic could be added to.

**Review by hawc2 — APPROVED** [review]
Looks good to me!

**Comment by charlottejmc** [comment]
Since @jenniferisasi has given me her input on Slack already, I'll now merge the branch and close the related issue. Thank you all for your comments! Don't hesitate to let me know if you think of any other lesson in the future.

**Pull request merged**
