### PR TITLE
Changes related to becoming a charity in England and Wales

### PR DESCRIPTION
**Pull request by drjwbaker**
per https://github.com/programminghistorian/jekyll/issues/2276.

@acrymble: I think I've caught all the times we mention the Ltd on the site, but I'd be grateful for a sanity check.

@programminghistorian/spanish-team @programminghistorian/french-team @programminghistorian/portuguese-team: when Adam has confirmed he is happy, this needs translation. Note that changes across the 3 pages are consistent and small edits.

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by drjwbaker** [comment]
@anisa-hawes: there is a broken link in https://programminghistorian.org/en/lessons/working-with-batches-of-pdf-files that is causing the build to fail. I've replaced https://docs.microsoft.com/en-us/windows/wsl/initialize-distro with https://docs.microsoft.com/en-us/windows/wsl/ (kinda annoying that Microsoft moved their docs!) in this PR to fix it. But I'm wondering if the description of the WSL setup in the article needs testing. I did this recently and it looks just about right. Do you have a Windows 10 machine to test this? (because it would be hard to for me to go through the process again without losing my local install/settings). Alternatively, we could simply the text here and just point to the microsoft docs on how to setup WSL. What do you think? Do you have time to take a look after this temporary URL fix goes through?

**Comment by acrymble** [comment]
@drjwbaker can I defer the review to @anisa-hawes please?

**Comment by drjwbaker** [comment]
> 
> 
> @drjwbaker can I defer the review to @anisa-hawes please?

Done.

**Comment by spapastamkou** [comment]
@drjwbaker FYI the setup works, I tested it on my machine that runs on Windows 10. I will use"your" link in PR #2291 to avoid conflicts (I had inserted the internet archive link to fix the lesson).

**Comment by drjwbaker** [comment]
Excellent. Thanks for checking @spapastamkou. I believe this is ready to go then once reviewed.

**Review by anisa-hawes — DISMISSED** [review]

**Comment by anisa-hawes** [comment]
Hello @drjwbaker. Would you like me to Merge this? Or would you prefer to wait, so that the translations are merged within this PR?

**Comment by drjwbaker** [comment]
Ideally, merge with translations. Though I note we have a build issue in the PR that might need attention sooner.

**Comment by anisa-hawes** [comment]
Is this the problem link? https://github.com/impresso/PH-Passim-tutorial/blob/master/explore-Passim-output.ipynb?
Is that Jupyter notebook still available?

**Comment by drjwbaker** [comment]
Not as far as I know. The build originally failed because of a bad link at https://github.com/programminghistorian/jekyll/pull/2292/files#diff-94cd0766c3506bcc9aab9057b2c4c1020c8f2090ee741c9c4842d9bdd04ed53f which I since fixed in this PR.

**Comment by rivaquiroga** [comment]
@anisa-hawes, Spanish translation is ready

**Review by anisa-hawes — APPROVED** [review]

**Comment by drjwbaker** [comment]
Pulled to resolve broken URL causing build isses. Per https://github.com/programminghistorian/jekyll/pull/2295#issuecomment-926415647 I will open a separate ticket for FR/PT translation of charitable status.

**Pull request merged**
