### PR TITLE
Add editor instructions to include ToC Liquid code

### LINKED ISSUE #641: Document use of generated ToC for all lessons in editor guidelines
During the redesign, we updated all lessons with the following Liquid filter:

```
{% include toc.html %}
```

This generates a ToC based on the header structure of the lesson. I need to document this in the editor guidelines.

### PR DESCRIPTION
**Pull request by mdlincoln**
Closes #641

This will require translation.

### CODE REVIEW

**Review by vgayolrs — COMMENTED** [review]
Ok, I take this.

**Comment by mdlincoln** [comment]
@vgayolrs You need to "Approve" your review in order for us to merge this PR. In the "Files changed" tab, set your Review to "Approve"

screen shot 2017-10-27 at 5 25 29 pm

**Comment by mdlincoln** [comment]
@vgayolrs @mariajoafana @arojascastro I need someone to submit an "approved review" for this change, now that @vgayolrs has added his changes 😮

**Review by vgayolrs — APPROVED** [review]
Ok, thanks @mdlincoln And sorry, I was out of town...

**Pull request merged**
