### PR TITLE
Update logistic-regression.md

### LINKED ISSUE #3283: Fix formula formatting in /en/logistic-regression
There seems to be an issue with the way formulas are formatted in /en/logistic-regression. I will apply `$$` formatting instead.

### PR DESCRIPTION
**Pull request by charlottejmc**
I've changed the formatting in the lesson to use `$$` around mathematical formulas. 

Closes #3283 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Add the appropriate "Label"
- [x] If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above
- [x] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Manager @anisa-hawes 
- [x] Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)
- [x] Assign at least one individual or team to "Reviewers"
  - ~[ ] if the text needs to be translated, please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines), then assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR.~

### CODE REVIEW

**Comment by charlottejmc** [comment]
This is not rendering in the Netlify preview how I anticipated. I'll come back to this next week!

**Comment by miy-h** [comment]
It looks that the symbol `|` in math block is parsed as Markdown's table delimiter by kramdown, a Markdown parser used in jekyll. Maybe it is a bug of kramdown, but fixing it is difficult because kramdown is not actively maintained.

Instead, I suggest replacing `X|Y` with `X \vert Y` in math block. `\vert` represents `|` exactly in TeX and can be rendered by MathJax.

**Comment by charlottejmc** [comment]
Hello @miy-h,

Thank you so much for contributing to this issue. Your solution worked perfectly! We're just fixing a separate build issue before merging this PR, but you can see from the [Netlify preview](https://deploy-preview-3284--ph-preview.netlify.app/) that your suggestion was successful :) 

ありがとうございました ✨

**Review by anisa-hawes — APPROVED** [review]
Many thanks for your contribution @miy-h! 

\+ Thank you @charlottejmc for coordinating.

**Pull request merged**
