### PR TITLE
Adding PT project in EN, ES, FR about pages - Issue 2217

### LINKED ISSUE #2217: Adding the PT project in EN, FR and ES About pages
I noticed that the About / A propos / Acerca pages do not list the PH in PT in the History of the project part (see here for the EN page: https://programminghistorian.org/en/about#history-of-the-project). We should add a phrase that in 2021 we added a Portuguese version just like in the [PT page](https://programminghistorian.org/pt/sobre#hist%C3%B3ria-do-projeto).

### PR DESCRIPTION
**Pull request by spapastamkou**
*Adding the PT publication in the history of the project in the EN, ES and FR about pages. Closes #2217*

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by spapastamkou** [comment]
I updated all "about" pages (FR but also EN and ES) as per @jenniferisasi 's suggestion in #2217. 
Furthermore, for the ES publication: a) I added the link towards the ES website because the link that was provided `https://github.com/programminghistorian/jekyll/wiki/Additional-Language-Sub-Teams-Policy` is no longer functionnal (in short: it sends to nothing); b) also, I deleted a small phrase saying there were plans for translating the ES original lessons into EN (that was a intention at the time this description was added in the page but I believe there were further discussions recently about the "ownership" of the translations and is more complicated than this). 

@rivaquiroga @jenniferisasi @svmelton Please take a look to see if changes are correct in your languages and if you agree with them or have other suggestions. Thanks!
@Anisa-ProgHist FYI just in case it is of interest to you:)

**Review by rivaquiroga — DISMISSED** [review]

**Comment by anisa-hawes** [comment]
Hello @spapastamkou. I have made one small adjustment to en/about.md. A pair of square brackets were missing in paragraph 39:  `*[Programming Historian en español]({{site.baseurl}}/es)*`

**Comment by anisa-hawes** [comment]
This build is failing due to a broken link on the PT Research page: pt/pesquisa.md

Daniel Alves, ['Ensinar Humanidades Digitais sem as Humanidades Digitais: um olhar a partir das licenciaturas em História'](http://www.latec.ufrj.br/revistas/index.php?journal=educaonline&page=article&op=view&path[]=1176), _Revista EducaOnline_, v. 15, n. 2 (2021).

It seems that www.latec.ufrj.br has provisionally changed to www2.latec.ufrj.br, however the Portal de Revistas does not appear to be accessible from there.

**Comment by spapastamkou** [comment]
thanks @Anisa-ProgHist! 
For the broken link problem, there is more discussion in PR #2218, perhaps we'll know a bit more soon

**Review by jenniferisasi — APPROVED** [review]
Fantastic, @spapastamkou! I'll keep an eye to re-approve once we solve the broken link.

**Comment by jenniferisasi** [comment]
It worked with @ZoeLeBlanc's final touch 🥺

Leaving it open for @spapastamkou to see tomorrow morning or whenever she can :)

**Comment by spapastamkou** [comment]
thanks @jenniferisasi @rivaquiroga @Anisa-ProgHist @ZoeLeBlanc ! I can merge the branch now.

**Pull request merged**
