### PR TITLE
add Lux to IPP

### PR DESCRIPTION
**Pull request by drjwbaker**
Add - [niversité du Luxembourg to IPPs

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] ~if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description~
- [x] Add the appropriate "Label"
- [ ] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by drjwbaker** [comment]
I *think* I've edited the right pages, but I'm not 100% sure where you and @acrymble are changing the IPP pages for ES/FR/PT. So if I've done the wrong thing, say, and I'll fix it.

**Review by acrymble — APPROVED** [review]

**Comment by acrymble** [comment]
@drjwbaker can you ping me when you merge this? I've got to merge a branch using the same set of files so don't want to mess it up.

**Comment by drjwbaker** [comment]
Do you want me to merge this first? If so, I can do it now.

**Comment by acrymble** [comment]
yes please

**Comment by drjwbaker** [comment]
@acrymble Merged.

**Pull request merged**
