### PR TITLE
Create comprendre-les-expressions-regulieres.md

### PR DESCRIPTION
**Pull request by spapastamkou**
Publishing Comprendre les expressions régulières, FR translation of Understanding Regular Expressions lesson. 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by spapastamkou** [comment]
@mdlincoln ``jekyll 3.8.5 | Error:  undefined method `>' for nil:NilClass``  I should understand there is a ``>`` somewhere it should not be?

**Comment by mdlincoln** [comment]
this might also be an error caused by the `abstract` because it has so many `'` marks. Please use pipe notation:

```
abstract: |
  abstract starts
```

NOTE: you must indent the line after the `|`!

**Comment by jenniferisasi** [comment]
I was trying to find the error to help and to learn, without success. Hoping to learn more, I wonder with your comment @mdlincoln: 
> this might also be an error caused by the `abstract` because it has so many `'` marks. Please use pipe notation:

Is the pipeline a form to escape punctuation and special characters? Any abstract in French could have even more `'` because the apostrophe is for elision, a very common feature of the language. It is the same character as the one in English for don't, didn't, couldn't, etc. I am wondering the escape thing because I see we have the pipeline for titles and abstract (which can include special characters and punctuation marks) but not on names, where there could also potentially be apostrophes and, certainly, accent marks and `ñ` or `ç`?

Thanks for teaching us, and your patience!

**Comment by mdlincoln** [comment]
`|` is very useful for any string in YAML that could contain `"` or `'`. It doesn't have anything to do with non-ASCII characters however. `"` and `'` are special in YAML because they can mark what is a string.

If an author name has `'` in it, the best way to express it would be to put double quotes around the whole name:

```
- "Apos'trophe Name"
```

and then the YAML will be happy.

**that said** I've tried adding a pipe to the abstract which was probably necessary anyway, but I'm still getting the error. I'm trying some things out, since so much of this lesson contains reserved punctuation since it's about regular expressions. Stand by.

**Comment by mdlincoln** [comment]
Documenting my thought process as I look at this:

Because the error is specifically being thrown by Jekyll, not by the YAML parsing library, this gives me some reason to believe the error is NOT in the YAML. I can't image what quite yet, since the english lesson certainly had all these `>` characters as well and has no problems at all.

Somewhere in this file, a special character is hiding that is causing Jekyll to go 🤢

**Comment by mdlincoln** [comment]
I was partly wrong! It was an error in the YAML, but really it was an error in my Ruby code. This new md file uses `translation-date`, but the correct form is `translation_date`. The reason that the check script doesn't provide a _useful_ message is:

I check all the fields to see if a required field like `translation_date` is missing. If one is missing, I add a message to the array of errors that the check script will need to print (because there could be more than one error.)

Unfortunately, I also try to call `translation_date` in a later part of the script, to check that it is later than the `date` of the original lesson. (That's literally why Ruby is confused by `>` - I ask it to check that one date is greater than the other, but when there's no translation date, Ruby thinks I'm asking it to say if `Nil` is greater than a Date type. Which is a good reason for it to get angry.) 

This is the line in question: 

https://github.com/programminghistorian/jekyll/blob/642326e53cf0ddf0e815954ab4b1919e88bf1379/_plugins/validate_yaml.rb#L153-L155

This ruby code just assumes that `translation_date` will be there - if it isn't, everything explodes.

I'm going to add a piece of logic around that check so that the script will not crash if `translation_date` isn't there. I'll push that new check script on to this branch, so we can confirm that it will work.

keep standing by...

**Comment by mdlincoln** [comment]
[The latest check still fails](https://travis-ci.org/programminghistorian/jekyll/builds/642175553?utm_source=github_status&utm_medium=notification), but now it is giving understandable error messages. @spapastamkou can now finish editing the lesson markdown and hopefully the checks will make sense now.

Thank you very much for your patience (and for finding a bug in the check code 🐞 that was not too hard to fix!)

**Comment by spapastamkou** [comment]
I am done I think \o/! Thank you @mdlincoln - I regularly make this mistake with translation_date (because I think of translation-editor etc) but somehow I manage to realize before getting to the PR. Thank you for the detailed comments, I keep this PR to my diigo to have a small memo. Thank you as well, @jenniferisasi ! 

Quotes " gave me a hard time as some  images wouldn't show because there were too many of them in the code. I deleted most of them and in one case I inserted directly FR quote marks, and it worked:) However, I suggest we consider in the @programminghistorian/technical-team whether in case we use FR quote marks in FR texts we should prefer their html code instead for « » (which is far from urgent).

**Comment by spapastamkou** [comment]
@programminghistorian/french-team you can review whenever ready as most problems solved. Thanks!

**Comment by jenniferisasi** [comment]
Yay @spapastamkou! Using the French quotation marks seems like an original resource for this issue; as you said, it is not a pressing issue for the tech-team but I think it will have to be discussed in the context and together with #1636?

**Comment by mdlincoln** [comment]
FYI I opened a ticket on slowly compiling a resource about how & when to escape characters. Ideally we shouldn't have to compromise what characters we want to use, but it can be hard to know how to do it for YAML vs. includes vs. code blocks, etc. etc. Honestly, I often google it myself because even I can't keep it all in my head. I don't know if I'll be able to get to it soon, but I know it's a need.

**Comment by spapastamkou** [comment]
Hey @programminghistorian/french-team, I need [a review](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-reviews#about-pull-request-reviews) from one member so that I can merge the branch and have the lesson published. @mariechristineb or @MaelleAmand would one of you like to help?

**Review by mariechristineb — COMMENTED** [review]
I had a look, and everything seemed fined, but I wasn't quite sure what I should be looking for exactly, so I didn't want to approve merging right away, @spapastamkou

**Comment by spapastamkou** [comment]
Thank you very much, @mariechristineb! 
If everything seems fine to you, you just review by approving, and then this allows merging. Technically it was (normally) ok, bcz there were some issues here that we resolved with teamwork. If you did not find any "coquilles" in the text, please go on and approve. The best would be to merge as well, as it is better if the person who raises the pull request does not do the merge him/herself.

**Comment by mdlincoln** [comment]
This seems to be stalled @programminghistorian/french-team ??

**Review by mariechristineb — APPROVED** [review]
Sorry for the delay - I wasn't quite sure how much I'm supposed to read in detail at this stage, but I had another look now and all seems fine

**Pull request merged**
