### PR TITLE
Update ph_authors.yml

### LINKED ISSUE #2767: Antoine Henry stepping down from the FR team
@icolab is stepping down for the FR team. Here is a list of what we have to do at the team level: 

- [x] Remove Google Groups access (@anisa-hawes)
- [x] Remove Google Analytics access (@acrymble) (Not applicable but I ping AC to be sure)
- [x] Remove Github Jekyll access @anisa-hawes 
- [x] Remove from ProgHist Ltd register of members (@drjwbaker)
- [x] Remove Twitter access (@anisa-hawes)
- [x] Change team: true to team: false, and add team_end: YYYY to the  _data/ph_authors.yml file to remove the person from the Project Team page (@anisa-hawes)
- [x] Open issues assigned to the editor: none (@spapastamkou)
- [x] Review service integrations page to ensure that they do not have any associated integrations tied to their accounts: @anisa-hawes (I'd say no but I ping AH to be sure)

### PR DESCRIPTION
**Pull request by anisa-hawes**
I am updating `ph_authors.yml` to reflect that Antoine Henry is stepping down from the French team.

To do this, I've changed their team status to `false`, and added a new line that reads `team_end: 2022`

Closes #2767

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] ~~if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description~~
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Hello @marie-flesch,

Do you want to practice the workflow for Reviewing a Pull Request? (No problem if not! – Let me know 🙂)

I've set out the changes I intend to make [in my initial comment](https://github.com/programminghistorian/jekyll/pull/2768#issue-1470038704):

> I am updating `ph_authors.yml` to reflect that Antoine Henry is stepping down from the French team. 
> To do this, I've changed their team status to `false`, and added a new line that reads `team_end: 2022`

Directly above, you will note the six 'build checks' that GitHub has processed and passed. If you click on the word '**details**' at the right end of the final line **netlify/ph-preview/deploy-preview — Deploy Preview ready!** you will be able to review a Preview of the changes as they will look on our website.

The changes I've made here (to the file `ph_authors.yml`) will be visible on the Project Team pages of our website across EN (/en/project-team), ES (/es/equipo-de-proyecto), FR (/fr/equipe-projet) and PT (/pt/equipe). So in the Preview, take a moment to click through to those pages and double check that:

- Antoine Henry's profile photo + bio has been removed from the _Programming Historian en français_ team list
- Antoine Henry's name is included in the _Historique des membres de l’équipe du projet_ list

You can also see exactly what the changes are by clicking into the Files changed tab at the top of this page. On the left you will see deletions, and on the right hand side you will see additions. 

When you're happy: click 'Viewed' in the upper right. 
Next: select Review Changes. A pop-up will allow you to Comment, Approve or Request Changes then submit your review.

**Review by marie-flesch — APPROVED** [review]
Looks good!

**Comment by marie-flesch** [comment]
Thank you @anisa-hawes for including me in this review! It was very helpful 😀

**Comment by anisa-hawes** [comment]
Excellent! Thank you, @marie-flesch!

**Pull request merged**
