### PR TITLE
Update author-guidelines.md

### PR DESCRIPTION
**Pull request by drjwbaker**
fixed missing link

OT: if we want to make edits (minor or major) do we just make them, or raise a PR like this and get someone else to merge? The latter is good practice - SWC et al do it hence I tend to do it out of habit - but takes more person time.

### CODE REVIEW

**Comment by mdlincoln** [comment]
Thanks @drjwbaker. Usually minor typo fixes can just be directly pushed - though if it happens to be on a page that is being actively developed (like the author guidelines) or has particularly extensive edits should be a PR: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions

**Review by mdlincoln — CHANGES_REQUESTED** [review]
It looks like the Atom recommendation is not present in es/guia-para-autores - @vgayolrs can you please check the translation?

**Comment by drjwbaker** [comment]
@mdlincoln And are the Travis build fails I'm seeing here normal?

**Comment by mdlincoln** [comment]
Editor guidelines have instructions for interpreting the build failures: https://programminghistorian.org/editor-guidelines#10-confirm-all-links-and-yaml-headers-are-functioning-correctly

**Comment by mdlincoln** [comment]
In this case, the errors are coming from another page on the site - ~if you have time, you could open another PR!~

**Comment by mdlincoln** [comment]
I went ahead and fixed them. You'll still see breaking builds until you merge the latest `gh-pages` branch back on to this one - but that's just a technicality - i'm more concerned about getting the Spanish translation re-aligned first.

**Comment by drjwbaker** [comment]
Okay. Get it. Weird that it reported broke after I only added a link though :|

**Comment by mdlincoln** [comment]
@drjwbaker this was not ready to merge - as I requested above, we need to get the Spanish translation updated first.

Don't worry about un-merging now - but @vgayolrs @arojascastro @mariajoafana could you please take a look at the changes made? Thanks very much!

**Comment by mdlincoln** [comment]
Re: the odd reporting of links - as noted in https://programminghistorian.org/editor-guidelines#10-confirm-all-links-and-yaml-headers-are-functioning-correctly, the way that html-proofer does caching means that it will sometimes surface broken links on different pages during unrelated commits.

**Comment by drjwbaker** [comment]
@mdlincoln So re https://github.com/programminghistorian/jekyll/pull/626#issuecomment-336917231 I now read that I/we *shouldn't* just push minor fixes without requesting a review because we need to wait for ES translation/realignment first.

**Comment by drjwbaker** [comment]
I'd like to talk about pushing at https://github.com/programminghistorian/jekyll/issues/617 Because I'm feeling uncertain/uneasy about our practice.

**Comment by ianmilligan1** [comment]
@drjwbaker sounds like a good idea... I've been pushing to master here for minor tweaks as it seems to be habit, but agreed that moving to PRs is probably a better practice (esp. with the Spanish translation). And by not merging our own PRs, always gets another set of eyes on things.

**Comment by drjwbaker** [comment]
@ianmilligan1 It takes more time. And I'm loath to add more process to what I'm realising is an already complex process. But there are benefits, especially a) when someone with experience knows that X needs to be attended to before Y is committed and b) avoiding a project having single point of failure. So let's discuss.

**Comment by drjwbaker** [comment]
(and move rest of the chat from here to another Issue and/or the monthly call)

**Comment by mdlincoln** [comment]
@drjwbaker oh I am VERY glad to have this convo! As this convo demonstrates, it's a fiddly and tough balance, and currently our practice is a bit of a mishmash. Just opened #630

**Comment by mdlincoln** [comment]
@vgayolrs Reminder - can someone from the Spanish team please review the changes made in this PR and push translations?

**Pull request merged**
