### PR TITLE
OCR & Machine Translation

### PR DESCRIPTION
**Pull request by svmelton**
Adding the files for the new OCR & Machine Translation lesson

### Checklist

- [X] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by svmelton** [comment]
This should be set for review. I'm not sure where we are in the discussion of translating author bios, so tagging @rivaquiroga @spapastamkou and @DanielAlvesLABDH in case we need translation.

**Comment by walshbr** [comment]
@svmelton - was there something you wanted the technical team to check out in particular?

**Comment by svmelton** [comment]
> @svmelton - was there something you wanted the technical team to check out in particular?

Sorry, I probably should have waited to tag you until I heard from the language teams. Just the PR review!

**Comment by walshbr** [comment]
@svmelton - Ok! A couple things I noticed - this image (and the previous one as well) need to be grayscale. It also looks like this particular avatar image needs to be cropped to be a square as well.

**Review by DanielAlvesLABDH — DISMISSED** [review]

**Comment by amsichani** [comment]
> @svmelton - Ok! A couple things I noticed - this image (and the previous one as well) need to be grayscale. It also looks like this particular avatar image needs to be cropped to be a square as well.

thanks @walshbr ! I will have a closer look at the images now.

**Comment by amsichani** [comment]
I ve updated the image in question @svmelton. Do amend it so we can check again the  preview. Cheers!

**Comment by svmelton** [comment]
> I ve updated the image in question @svmelton. Do amend it so we can check again the preview. Cheers!

Thanks @amsichani! I just replaced the image.

**Comment by spapastamkou** [comment]
@svmelton For the FR team: we translate an author's bio if/when we translate the corresponding lesson in FR. But if it is necessary to do it in this PR, just let me know.

**Comment by svmelton** [comment]
> @svmelton For the FR team: we translate an author's bio if/when we translate the corresponding lesson in FR. But if it is necessary to do it in this PR, just let me know.

Thanks, that's good to know! We can wait until/if we do the translation. I think we just need a final review from @programminghistorian/technical-team and we should be ready to publish.

**Review by walshbr — APPROVED** [review]

**Pull request merged**
