### PR TITLE
Issue 3266

### LINKED ISSUE #3266: Updating en/computer-vision-deep-learning to reflect transition from Kaggle to Google Colab
The lesson `en/computer-vision-deep-learning` (`-pt1` and `-pt2`) was originally accompanied by a Jupyter notebook, which was hosted on the authors' personal Kaggle account. This was a problem for us, as we did not have access to it for maintenance, and therefore could not ensure sustainability into the future.

Since the publication of this lesson, we've developed some [guidelines](https://github.com/programminghistorian/jekyll/wiki/File-Management#3-assets) on the use of notebooks within lessons, and decided that we would only host notebooks through our own Google account, therefore using Google Colab over any other cloud-based option. 

The lesson's authors have very kindly reached out with a copy of their original notebook now on Colab, which has just been uploaded to [/assets/computer-vision-deep-learning-pt-1](https://github.com/programminghistorian/jekyll/tree/gh-pages/assets/computer-vision-deep-learning-pt1) in [commit 3f72563](https://github.com/programminghistorian/jekyll/commit/3f7256327c5c355b8b3d55083cea6859b563c759).

We now need to **update the text within the lesson** (both parts) to reflect this change. 

I will prepare a first draft of these updates, and involve the managing editor and the lesson's original authors by asking them to review the PR and ensure they are happy with the changes.

### PR DESCRIPTION
**Pull request by charlottejmc**
I have suggested some changes to the lesson text, to reflect the fact that readers are now using the accompanying Jupyter Notebook on Google Colab rather than on Kaggle, as was originally the case. 

The biggest change was the `### Kaggle section` (now ### Google Colab), which I have updated to ensure the instructions are now relevant to Colab. 

Closes #3266 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Add the appropriate "Label"
- [x] If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above
- [x] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Manager @anisa-hawes 
- [x] Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)
- [x] Assign at least one individual or team to "Reviewers"
  - ~[ ] if the text needs to be translated, please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines), then assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR.~

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Hello @hawc2,

Daniel @davanstrien has very kindly provided us with a revised version of the codebook associated with `computer-vision-deep-learning-pt1` and `computer-vision-deep-learning-pt2` to support us to migrate it from Kaggle to Google Colab. 

We’ve now uploaded it to our organisationally hosted Colab space. @charlottejmc and I have made some additional adjustments to the codebook so that it consists of the code + essential line comments only, headings and subheadings that mirror the lesson, and does not extend or replicate the lesson’s commentary. (You’ll remember that one codebook is linked to both parts of the lesson).

We’ve also prepared a first draft of revisions to the original EN lesson which you can review in [`rich-diff` here](https://github.com/programminghistorian/jekyll/pull/3267/files) so that the sections and sentences that refer to the specifics of working with Kaggle are removed. We'd be grateful for your thoughts/comments/suggestions.

Thank you.
Anisa

**Comment by charlottejmc** [comment]
Hi @davanstrien,

Thanks again for your patience as we make these changes.

I've tried to ensure my edits are accurate, but please do carefully review them and flag anything that doesn't seem right to you.

- Could you please take a close look at the `## Suggested Experiments` section in **Part 1** (line 436 of [computer-vision-deep-learning-pt1.md](https://github.com/programminghistorian/jekyll/blob/Issue-3266/en/lessons/computer-vision-deep-learning-pt1.md), as I wasn't able to determine myself whether this would still work the same on Colab.
- **Part 2** of the new Colab notebook _seemed_ to be missing a code block (compared to the lesson text) under 'Loading Data':
```
from fastai.vision.all import *
```
I have chosen to add this in to the notebook, but please let me know if it needs to be removed. 
- I noticed there may be some discrepancies between the notebook and the lesson code. For example, in **Part 2**, at line 969 of [computer-vision-deep-learning-pt2.md](https://github.com/programminghistorian/jekyll/blob/Issue-3266/en/lessons/computer-vision-deep-learning-pt2.md), the results show `0.6308501468079952`, compared to `0.5519872296565753` in the Colab notebook. This may be totally fine. I just thought I would point it out.

**Comment by hawc2** [comment]
Great, thanks everyone for this big improvement to the code for the lesson!

**Review by hawc2 — APPROVED** [review]

**Comment by anisa-hawes** [comment]
Thank you for approving this, @hawc2.

I've written to Daniel to ask if he can advise on the [two small queries raised above](https://github.com/programminghistorian/jekyll/pull/3267#issuecomment-2118035028). 

But if you're happy as things are, we could make those tweaks at a later date (if necessary)?

**Comment by hawc2** [comment]
oh ok @anisa-hawes yeah let's make those changes first if possible

**Comment by anisa-hawes** [comment]
Hello @davanstrien and @kasparvonbeelen,

As I mentioned in my email, when migrating the codebook which accompanies this lesson from Kaggle to Colab, we noted [a few points of query](https://github.com/programminghistorian/jekyll/pull/3267#issuecomment-2118035028) which we'd like to ask for your advice on:

1. In the `## Suggested Experiments` section in **Part 1** (lines 436-443 of the Markdown file [computer-vision-deep-learning-pt1.md](https://github.com/programminghistorian/jekyll/blob/Issue-3266/en/lessons/computer-vision-deep-learning-pt1.md)), you outline some options for adjusting various settings and parameters. **Are these options for experimenting available in Colab as they were in Kaggle?**

2. We noticed that the line of code `from fastai.vision.all import *`  seemed to be missing from Part 2 'Loading Data' of the revised codebook, although it appears [in the corresponding section of the lesson](https://deploy-preview-3267--ph-preview.netlify.app/en/lessons/computer-vision-deep-learning-pt2#loading-data). We've added this, but would like to confirm it with you. **Is the line `from fastai.vision.all import *` correctly included [in the revised codebook](https://nbviewer.org/github/programminghistorian/jekyll/blob/gh-pages/assets/computer-vision-deep-learning-pt1/computer-vision-deep-learning-pt1-2.ipynb)?**

3. We noted some discrepancies between the `f1_score values` quoted in the notebook and in the lesson. **Am I correct in understanding that these precision metrics vary each time they are calculated?**

You can review [a full preview of the revised lesson here](https://deploy-preview-3267--ph-preview.netlify.app/en/lessons/computer-vision-deep-learning-pt1), and review [the revised codebook as it will be here](https://nbviewer.org/github/programminghistorian/jekyll/blob/gh-pages/assets/computer-vision-deep-learning-pt1/computer-vision-deep-learning-pt1-2.ipynb).

We're grateful for your help to resolve these queries. 

Your lessons have proved popular with our community, and we're excited to have received proposals for potential translations into Spanish and French 🙂

**Comment by charlottejmc** [comment]
Following @anisa-hawes' comment, I've done a bit more investigating and we both agree on my findings:
- Q1: This section is about playing around with certain variables within fastai, which is a package that can be installed using Kaggle and Colab interchangeably. So, this will probably not need any updates.
- Q2: We can't be exactly sure about this without the authors' direct input, but it does seem logical to repeat the same code cells/ code blocks across the markdown and the notebook
- Q3: I've looked into the `f1_score` value, it's apparently normal that it would vary every time the model is run.

**Comment by charlottejmc** [comment]
Merging this PR with @hawc2's approval. @davanstrien and @kasparvonbeelen, if you find anything that still needs to be changed, please do let us know and I will reopen a branch.

**Pull request merged**
