### PR TITLE
Add stickers to images part of repo

### PR DESCRIPTION
**Pull request by drjwbaker**
Per https://github.com/programminghistorian/jekyll/wiki/Brand-Guidelines we have logos on the repo, but not stickers. This PR adds what we have. Thanks @acrymble for digging these out!

@jenniferisasi: this relates to https://github.com/programminghistorian/jekyll/issues/1629, so when you get some time (I know you are very busy right now so no hurry!), can you please regularise these and add to the wiki.

### CODE REVIEW

**Comment by acrymble** [comment]
@drjwbaker you're not supposed to delete the checklist in the ticket. You're supposed to use it to make sure you've done the pull request properly.

**Comment by acrymble** [comment]
These images have already been regularised and added to the wiki and the repo: https://github.com/programminghistorian/jekyll/tree/gh-pages/images/logos

**Comment by drjwbaker** [comment]
> @drjwbaker you're not supposed to delete the checklist in the ticket. You're supposed to use it to make sure you've done the pull request properly.

Sorry, bad habit.

**Comment by drjwbaker** [comment]
> These images have already been regularised and added to the wiki and the repo: https://github.com/programminghistorian/jekyll/tree/gh-pages/images/logos

My bad. Ignore me.

**Pull request closed without merging**
