### PR TITLE
Issue 2200

### LINKED ISSUE #2200: Correção de link e verificar utilização do Komodo Edit nas lições de Python
A lição https://programminghistorian.org/pt/licoes/instalacao-windows tem um erro no link do Komodo Edit e o software aparentemente já não se encontra disponível, apenas a versão IDE (https://www.activestate.com/products/komodo-ide/download-ide/). Peço ao @josircg que faça uma verificação no link quando possível (https://github.com/programminghistorian/jekyll/blob/gh-pages/pt/licoes/instalacao-windows.md) e um teste ao Komodo IDE para perceber se temos de actualizar a lição. Obrigado e abraço

### PR DESCRIPTION
**Pull request by DanielAlvesLABDH**
*Corrigir links nas lições de instalação do Python Closes #2200*

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Review by josircg — CHANGES_REQUESTED** [review]
Alterei o link do UTF para a versão em português

**Comment by DanielAlvesLABDH** [comment]
Obrigado Josir

**Review by josircg — CHANGES_REQUESTED** [review]
O link final do Komodo Edit está com "hhttps"

**Comment by DanielAlvesLABDH** [comment]
Acho que está a funcionar. Tem problema de ser https?

**Comment by josircg** [comment]
Tem 2 "hh". Ao invés de https, está "hhttps"

Em dom., 12 de set. de 2021 às 08:25, Daniel Alves ***@***.***>
escreveu:

**Comment by DanielAlvesLABDH** [comment]
Olá @josircg. Podemos fechar isto. É só preciso o teu OK!

**Review by josircg — APPROVED** [review]

**Pull request merged**
