### PR TITLE
Publicar lição "De HTML para Lista de Palavras (parte 1)"

### PR DESCRIPTION
**Pull request by DanielAlvesLABDH**
Publicar lição "De HTML para Lista de Palavras (parte 1)"

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by DanielAlvesLABDH** [comment]
Olá @ericbrasiln, vou retomar as publicações de lições depois de longo silêncio ;-) Gostava de contar com a tua ajuda numa última revisão das mesmas e aprovação do PR. São lições de Python muito curtas. Desde já agradeço. Abraço

**Comment by anisa-hawes** [comment]
Hello @DanielAlvesLABDH. 

I'll take this opportunity to slot in the perma.cc links and adjust a few small elements of typesetting!

**Comment by DanielAlvesLABDH** [comment]
Many thanks @anisa-hawes! Will try to respond to the other (many) issues in the next days...

**Comment by anisa-hawes** [comment]
I'm also wondering if we need to add in the sequencing to the YAML here, @DanielAlvesLABDH?

Or is the plan to add that when you have translated the entire 15 lesson sequence?


```
next: HTML-lista-palavras-2
previous: manipular-strings-python
```

**Comment by DanielAlvesLABDH** [comment]
Yes @anisa-hawes, the plan is to make a full revision of all the 15 lessons and them introduce the sequence when all are published

**Comment by ericbrasiln** [comment]
Bom dia @DanielAlvesLABDH 
Farei as revisões até segunda-feira.

**Review by ericbrasiln — APPROVED** [review]
Olá, @DanielAlvesLABDH 
Li e executei os comandos da lição e tudo está funcionando bem.
Aprovo o PR.

**Comment by DanielAlvesLABDH** [comment]
Obrigado @ericbrasiln!

**Pull request merged**
