### PR TITLE
Update changes becoming charity fr

### LINKED ISSUE #2297: FR/PT translation needed: changes related to becoming a charity in England and Wales
Further to https://github.com/programminghistorian/jekyll/issues/2276 and https://github.com/programminghistorian/jekyll/pull/2292 I merged the pull request with EN and ES text only in three places because the PR contained a broken URL that was stopping builds.

The pages where translation is needed are:

> https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/snippets.yml
>> old `This project is administered by ProgHist Limited, Company Number [12192946](https://beta.companieshouse.gov.uk/company/12192946).`
>> 
>> new `This project is administered by ProgHist Ltd, Charity Number [1195875](https://register-of-charities.charitycommission.gov.uk/charity-search/-/charity-details/5181272/charity-overview) and Company Number [12192946](https://find-and-update.company-information.service.gov.uk/company/12192946).`

> https://github.com/programminghistorian/jekyll/blob/gh-pages/en/about.md
>> old `The Programming Historian is an international volunteer-driven project whose financial activities are administered by ProgHist Limited, a Not for Profit Company Limited by Guarantee that is registered in England, Company Number [12192946](https://beta.companieshouse.gov.uk/company/12192946).`
>> 
>> new `The Programming Historian is an international volunteer-driven project whose financial activities are administered by ProgHist Ltd, a charity registered in England and Wales ([1195875](https://register-of-charities.charitycommission.gov.uk/charity-search/-/charity-details/5181272/charity-overview)) and incorporated in England and Wales as a company limited by guarantee ([12192946](https://find-and-update.company-information.service.gov.uk/company/12192946)).`

> https://github.com/programminghistorian/jekyll/blob/gh-pages/en/ipp.md
>> old `The *Programming Historian* is an international volunteer-driven project whose financial activities are administered by ProgHist Limited, a Not for Profit Company Limited by Guarantee that is registered in England, Company Number 12192946.`
>> 
>> new `The *Programming Historian* is an international volunteer-driven project whose financial activities are administered by ProgHist Ltd, a charity registered in England and Wales ([1195875](https://register-of-charities.charitycommission.gov.uk/charity-search/-/charity-details/5181272/charity-overview)) and incorporated in England and Wales as a company limited by guarantee ([12192946](https://find-and-update.company-information.service.gov.uk/company/12192946)).`

So you'll see that the changes are small and tend to repeat themselves.

@programminghistorian/french-team @programminghistorian/portuguese-team: could someone take a look at this please?

### PR DESCRIPTION
**Pull request by mariechristineb**
*FR translation for charity - closes #2297*

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by mariechristineb** [comment]
@spapastamkou j'ai traduit 'charity' par 'organisation caritative', c'est le terme normalisé en droit des fiducies de common law

**Comment by drjwbaker** [comment]
Thanks so much for doing this.

**Review by spapastamkou — APPROVED** [review]

**Comment by spapastamkou** [comment]
Mille mercis @mariechristineb  et pour la traduction et pour l'amélioration du texte, c'est tellement mieux maintenant!

**Comment by spapastamkou** [comment]
(Just did a little update of the branch.)

**Pull request merged**
