### PR TITLE
fixed tf-idf lesson bug

### PR DESCRIPTION
**Pull request by ZoeLeBlanc**
Fixing bug #1542 with this PR. Changed both the lesson and zip files to make sure that the loop of the files called the string version of the filename, instead of the actual file path.

### CODE REVIEW

**Comment by ZoeLeBlanc** [comment]
Hey @mdlincoln the merge is being blocked because I don't have Francois's avatar but when I pull from gh-pages it isn't there either...? Any thoughts? Should I just add it manually to my branch?

**Comment by mdlincoln** [comment]
Is Halloween extended this year? Because this feels like the dawn of the dead [issue]: https://github.com/programminghistorian/jekyll/issues/400

Way back when that avatar file got uploaded, it had a special character in it, and it was either committed or changed by someone who had an outdated git client and/or had not followed this: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#filenames-with-special-characters

Off the top of my head this second, I can't remember whether the solution is for you to turn precomposition ON or OFF based on your situation... but you might try each and see what works?

**Comment by ZoeLeBlanc** [comment]
@mdlincoln I've tried both versions of the settings for my git config and then created new local branches and it seems like every time I pull down from this branch it just automatically deletes Francois' avatar. Is it supposed to stop that from happening?
The way I see it I have two options, either I copy my code changes to a new branch from gh-pages and redo this PR, or I just manually add his avatar. Any thoughts?

**Comment by mdlincoln** [comment]
When you first pull, can you `git checkout -- $AVATARPATH` to undo the change that the pull did? and then commit the changes you intended to make?

**Comment by ZoeLeBlanc** [comment]
So first sorry for not saying THANK YOU! for helping me because this is truly driving me nuts. I haven't been able to get this working following you idea to to try and reset the file into the index. Any chance I can just delete this PR and branch, and just start over?? I know it's not best practices but since these changes are so minimal rather would take the path of least resistance. Otherwise I might need you to pull down this branch and reset the file because my computer is not liking it. Thanks again Matt!! Really appreciate your help 😊

**Comment by mdlincoln** [comment]
YEah let's close it out and start fresh :)

**Pull request closed without merging**
