### PR TITLE
draft post on retirement policy

### LINKED ISSUE #713: Blog post announcing new retirement policy
Once #612 is merged, I'll push a blog post announcing the new public retirement & sustainability policy guidelines.

### PR DESCRIPTION
**Pull request by mdlincoln**
Comments and improvements welcomed!

Closes #713

### CODE REVIEW

**Comment by acrymble** [comment]
Thanks Matt. The only thing I would flag is the use of "PH" instead of 'Programming Historian' in a few of the new files. I don't think we use that acronym formally.

This is great work. Thanks to everyone involved.

**Comment by mdlincoln** [comment]
Thanks @acrymble - could you please click on the "Add your review" link below, next to the red "Review required" alert, select "Approve" and then click "Submit review"?

**Review by acrymble — CHANGES_REQUESTED** [review]
Thanks Matt. The only thing I would flag is the use of "PH" instead of 'Programming Historian' in a few of the new files. I don't think we use that acronym formally.

This is great work. Thanks to everyone involved.

**Review by acrymble — APPROVED** [review]
These changes affect other files, not this one:

**Pull request merged**
