### PR TITLE
Update ipp.md

### LINKED ISSUE #2727: Editing https://programminghistorian.org/en/ipp
The Institutional Partnership page needs to include the following sentence:
Gold partners are offered two exclusive bespoke workshops per year for their students and researchers on how to get started using digital humanities tools.

### PR DESCRIPTION
**Pull request by GeeAlmeida**
Edited ipp.md to include a sentence on workshops to Gold Tier supporters.
Closes #2727 
### Checklist

- [X] Assign yourself in the "Assignees" menu
- [X] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [X] Add the appropriate "Label"
- [ ] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Thank you for preparing this @GeeAlmeida. I'll take a look when the build checks are complete. 

We'll need to follow up with a second PR to update /es/pia, /fr/pi and /pt/ppi.

**Comment by anisa-hawes** [comment]
Hello @GeeAlmeida. I've suggested [some minor adjustments](https://github.com/programminghistorian/jekyll/pull/2728/commits/097c02824cd23077835b0525890c20cfd02ec791). What do you think?

**Comment by rivaquiroga** [comment]
I can translate the Spanish file now if you want.

**Comment by anisa-hawes** [comment]
Hello @rivaquiroga. I'll create a new Issue + PR to update  /es/pia, /fr/pi and /pt/ppi.

Gisele has scheduled a Tweet to celebrate the first Gold Tier partnership first thing tomorrow, and that links to the EN page so I'll merge this in now.

**Review by anisa-hawes — APPROVED** [review]

**Pull request merged**
