### PR TITLE
Add Treasurer and Sponsorship roles

### PR DESCRIPTION
**Pull request by drjwbaker**
Edits required to add Treasurer and Sponsorship roles to the site. Needs ES translation and to be added into FR translation work.

### CODE REVIEW

**Comment by acrymble** [comment]
I think the words we want in french are:

trésorier
coordinateur de sponsoring

**Comment by acrymble** [comment]
And in Spanish?

tesorero
coordinador de patrocinio

**Comment by vgayolrs** [comment]
@acrymble @drjwbaker Treasurer = "tesorero" and Sponsorship Coordinator =  "Coordinador de patrocinio" makes sense. But both terms are masculine. Terms in feminine are "Tesorera" and "Coordinadora de patrocinio". In order to keep our inclusive language policy I suggest: Tesorería (treasury) and Cordinación de patrocinio (Sponsorship Coordination).

**Comment by vgayolrs** [comment]
I'm going to aprove this and open a new pull request for the Spanish translation.

**Review by vgayolrs — DISMISSED** [review]

**Comment by spapastamkou** [comment]
Terms in FR:
 trésorier(e)
chargé(e) des donations 
Will take care of the Fr part

**Comment by mdlincoln** [comment]
We either need to merge this before I start doing the French integration process, or we need to close it and re-do it after I'm done. Can you take a look and see if this is all set yet @drjwbaker ?

**Comment by drjwbaker** [comment]
As far as I can see, it is done.

**Comment by spapastamkou** [comment]
I'll deal with that parallel to #1074 and will let you know here.

**Review by mdlincoln — APPROVED** [review]

**Comment by mdlincoln** [comment]
I've added blank definitions in `french-staging` version of `_data/teamroles.yml` to be filled in.

**Comment by spapastamkou** [comment]
Commited FR translations as per #1076

**Pull request merged**
