### PR TITLE
Update 2020-06-29-plan-s.md

### PR DESCRIPTION
**Pull request by drjwbaker**
Correct point 5 and add a note on the edit.

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by drjwbaker** [comment]
@acrymble I figured it out. You need to click where it says "The build" to see the report.
Screenshot 2020-07-01 at 08 53 02

**Comment by drjwbaker** [comment]
Fixing the build error now.

**Comment by drjwbaker** [comment]
Checks passed. Over to you @acrymble.

**Review by acrymble — APPROVED** [review]

**Comment by ZoeLeBlanc** [comment]
@drjwbaker feel free to delete this branch unless you want to push up to it again. Thanks 🙏

**Comment by drjwbaker** [comment]
@ZoeLeBlanc I think there are a lot of branches I need to clear, as I never do it.......

**Comment by walshbr** [comment]
✂️ ✂️  @drjwbaker

**Comment by drjwbaker** [comment]
Okay. I'll learn to do it and do it when I get a minute. Promise.

**Comment by ZoeLeBlanc** [comment]
No worries @drjwbaker! Happy to help if you have questions. All you really need to do is click the `Delete branch` button underneath the comments once it says Pull request successfully merged and closed 👇 . 

Screen Shot 2020-07-02 at 11 36 51 AM

**Pull request merged**
