### PR TITLE
Publish heurist

### PR DESCRIPTION
**Pull request by spapastamkou**
*New FR lesson: Introduction à Heurist*

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by spapastamkou** [comment]
@programminghistorian/technical-team @ZoeLeBlanc I just noticed that a `ph_authors.yml.bak` backup file was created in this `publish-heurist` branch while I was working on this pull request. Should I do something before the branch is merged (say, delete the file)? Thanks!

**Comment by spapastamkou** [comment]
I deleted the backup file so all ok here - good to merge after review.

**Comment by ZoeLeBlanc** [comment]
Sorry for not seeing this earlier @spapastamkou but this all looks great now 👍🏽

**Comment by spapastamkou** [comment]
no problem, @ZoeLeBlanc, I experimented a bit alone and it worked:)

**Comment by spapastamkou** [comment]
@icolab ou quelqu'un @programminghistorian/french-team, avez-vous la possibilité d'approuver la pull request? Merci d'avance!

**Review by icolab — APPROVED** [review]

**Comment by icolab** [comment]
C'est fait :-)

**Pull request merged**
