### PR TITLE
adding new blog post about PH/JISC/TNA papers

### PR DESCRIPTION
**Pull request by tiagosousagarcia**
Adding a new blogpost with information about the selected proposals for PH/JISC/TNA call for papers

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by tiagosousagarcia** [comment]
A link is failing in the [this lesson](https://programminghistorian.org/fr/lecons/detecter-la-reutilisation-de-texte-avec-passim) -- the last footnote -- perhaps someone from the @programminghistorian/french-team can suggest an alternative?

**Comment by spapastamkou** [comment]
https://wiki.digitalclassicist.org/Text_Reuse

Le mer. 17 nov. 2021 à 10:06, tiagosousagarcia ***@***.***> a
écrit :

**Comment by tiagosousagarcia** [comment]
Thanks @spapastamkou, thought that would be the case

**Comment by spapastamkou** [comment]
thank you for changing the link!

>

**Comment by tiagosousagarcia** [comment]
@programminghistorian/english-team -- the same link is failing in English, so I've changed it to what @spapastamkou suggested but added @svmelton as a reviewer to confirm it

**Comment by anisa-hawes** [comment]
Hello @tiagosousagarcia. I had not seen that you'd taken steps to fix the broken links in `detecter-la-reutilisation-de-texte-avec-passim.md` and `detecting-text-reuse-with-passim.md` so I did that in PR #2378. I've resolved the conflict here, so your blog post PR is ready for review.

**Review by drjwbaker — APPROVED** [review]

**Pull request merged**
