### PR TITLE
Issue 2999

### LINKED ISSUE #2999: Update broken link across cleaning-data-with-openrefine, limpieza-de-datos-con-OpenRefine, nettoyer-ses-donnees-avec-openrefine, limpar-dados-openrefine
I am preparing to replace a broken link to the Powerhouse (museum in Sydney) which has recently updated its website address from http://www.powerhousemuseum.com/ [404] > **https://powerhouse.com.au/**.

It appears that this museum has changed its name several times during the past few years. It was previously known as the Powerhouse Museum, then Museum of Applied Arts and Science, now Powerhouse.

This link features in the following lessons:

/en/lessons/cleaning-data-with-openrefine
/es/lecciones/limpieza-de-datos-con-OpenRefine
/fr/lecons/nettoyer-ses-donnees-avec-openrefine
/pt/licoes/limpar-dados-openrefine

The dataset associated with these lessons was downloaded at the time the original lesson was written, and is hosted on our assets repository so I believe it is still possible for readers to follow the steps: https://programminghistorian.org/assets/phm-collection.tsv 

However, a short section of wording will need to be adjusted because the tab separated values (`.tsv` file) does not appear to be available from their website any longer:

> The Powerhouse has been very actively disclosing its collection online and making most of its data freely available. From the museum website, a tab-separated text file under the name phm-collection.tsv can be downloaded, which you can open as a spreadsheet. The unzipped file (58MB) contains basic metadata (17 fields) for 75,823 objects, released under a [Creative Commons Attribution Share Alike (CCASA) license](http://creativecommons.org/licenses/by-nc/2.5/au/). In this tutorial we will be using a copy of the data that we have archived for you to download (in a moment). This ensures that if the Powerhouse Museum updates the data, you will still be able to follow along with the Lesson.

### PR DESCRIPTION
**Pull request by anisa-hawes**
Preparing to update the following lessons:

/en/lessons/cleaning-data-with-openrefine
/es/lecciones/limpieza-de-datos-con-OpenRefine
/fr/lecons/nettoyer-ses-donnees-avec-openrefine
/pt/licoes/limpar-dados-openrefine

- [x] Replacing a broken link to the Powerhouse (museum in Sydney) which has recently updated its website address from http://www.powerhousemuseum.com/ [404] > https://powerhouse.com.au/. (It appears that this museum has changed its name several times during the past few years. It was previously known as the Powerhouse Museum, then Museum of Applied Arts and Science, now Powerhouse.)

- [x] Adjusting a short section of wording about the dataset being feely available to download, so that it reads in the past tense not present tense.
  - [x] EN
  - [x] ES
  - [x] FR
  - [x] PT 

- [x] [Maybe also necessary to update figure 1., which shows the website. This has changed significantly, and shows the museum as having a different name !]

Closes #2999 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Add the appropriate "Label"
- [x] If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above
- [x] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Assistant @anisa-hawes 
- [x] Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines), then assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR.

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Hola @rivaquiroga,

I'd like to adjust the ES lesson at lines 65 and 67 so that it reads in the past tense rather than present tense. 

Would the following be correct?

> El Museo Powerhouse de Sídney ofreció .... 

> El museo dio a conocer activamente su colección en línea y puso la mayoría de sus datos a libre disposición.  

> Anteriormente, se podía descargar del sitio web del museo un archivo de texto separado por tabuladores llamado phm-collection.tsv y abrirlo como hoja de cálculo.

Thank you for your help here 🙂

**Comment by rivaquiroga** [comment]
It's perfect!

**Comment by anisa-hawes** [comment]
Olá @DanielAlvesLABDH,

I'd like to ask for your help to adjust this PT lesson at lines 67 and 69 so that it reads in the past tense rather than present tense.

Would the following be correct?

> O Powerhouse, em Sydney, permite-lhe exportar gratuitamente os metadados da sua coleção no seu sítio Web. 

> O museu divulgou ativamente a sua coleção em linha e disponibilizou gratuitamente a maior parte dos seus dados. 

> No seu sítio Web, era possível descarregar um ficheiro de texto separado por separadores denominado `phm-collection.tsv` e abri-lo como uma tabela de dados.

Thank you.
Anisa

**Comment by anisa-hawes** [comment]
Bonsoir @marie-flesch,

I'd like to ask for your help to adjust the wording of this FR lesson so that lines 61 and 63 read in the past tense rather than the present tense. I see that an Editor's note was added which already makes things clearer in this case.

Would the following adjustment be correct?

> Le Powerhouse Museum de Sydney a mis à disposition sur son site web un ensemble de métadonnées librement utilisables sur sa collection (Note de la rédaction : l'ensemble de données, téléchargé à l'origine en 2013, n'est peut-être plus disponible à l'adresse indiquée, mais il est néanmoins fourni ci-dessous). 

> Le Powerhouse Museum a rendu sa collection largement disponible en ligne et la plupart de ses données librement accessibles. 

> Sur le site web du musée, il était possible de télécharger un fichier texte séparé par des tabulations appelé `phm-collection.tsv` sous la forme d'une feuille de calcul.

With thanks,
Anisa

**Comment by marie-flesch** [comment]
Just a couple things:

Remove the "s" at the end of "librement utilisables" below:
> Le Powerhouse Museum de Sydney a mis à disposition sur son site web un ensemble de métadonnées sur sa collection librement utilisable~~s~~  (Note de la rédaction : l'ensemble de données, téléchargé à l'origine en 2013, n'est peut-être plus disponible à l'adresse indiquée, mais il est néanmoins fourni ci-dessous).

The wording of this sentence makes it unclear if most the datasets are still available or not:
> Le Powerhouse Museum a rendu sa collection largement disponible en ligne et la plupart de ses données librement accessibles.

If they still are (present tense): 
> Le Powerhouse Museum a rendu sa collection largement disponible en ligne et la plupart de ses données **sont** librement accessibles.

If they aren't anymore (past tense):
> Le Powerhouse Museum a rendu sa collection largement disponible en ligne et la plupart de ses données **étaient** librement accessibles.

All good:
> Sur le site web du musée, il était possible de télécharger un fichier texte séparé par des tabulations appelé `phm-collection.tsv` sous la forme d'une feuille de calcul.

**Comment by DanielAlvesLABDH** [comment]
Hi @anisa-hawes, the Portuguese version is perfect. Thanks!

**Comment by anisa-hawes** [comment]
Hola @jenniferisasi, 

May I ask if you have time to review this PR? 

The name + website address of the museum in the lesson case study have changed!  

I've updated the links, and also adjusted the translations very slightly to shift wording from present tense to past tense: previously, the museum made data about its collections freely available but that doesn't seem to have carried over with their relaunch/new design. The translations have already been checked by Riva, Marie and Daniel.

From our point of view, what is most important is that the lessons can still be used. We have the sample data [hosted locally](https://programminghistorian.org/assets/phm-collection.tsv), so readers can work with that.

I've also updated Figure 1 across EN, ES, FR and PT so that it shows the current website with its new name. 

Thank you,
A.

**Review by jenniferisasi — APPROVED** [review]
All looks good! Thanks for taking the time to address this issue :)

**Pull request merged**
