### PR TITLE
Translation link

### PR DESCRIPTION
**Pull request by mdlincoln**
1. Inserts links to translations into the header of original lessons.
2. Refactors the way that translations link back to originals.

I'd appreciate a review of the modified Spanish snippets; I'm not quite sure if I am using capitals and lowercase appropriately here for the language names, but I tried to copy what was already published on the page.

On the technical side, I think this suggests a much larger refactoring job in the way that we establish "identity" for lessons. Right now the workarounds like `redirect_from` and so forth rely on the core assumptions that we are always translating _from_ English _into_ Spanish. It uses a lot of string interpolation and guessing. This refactoring instead locates the actual target lesson and draws directly on its metadata, which ought to ensure more correctness. It'd also somewhat future-proof us, as it'd easily allow for spanish lessons to be originals and english ones to be translations, to add French translations, etc...

That larger refactor to implement this pattern across the site is another job (and will need to be completed to accomplish #685) but this fix has helped me figure out a path forward that I think will also clarify the code-base a fair amount.

### CODE REVIEW

**Review by arojascastro — APPROVED** [review]
I do not understand much the changes in lesson.html, but I guess they are fine. In respect of "inglés", I added an accent and changed to lowercase.

**Comment by walshbr** [comment]
Great refactoring! Looks to be good to merge to me, but I'll let you do that - wasn't sure if you had more to do on the PR first.

**Review by walshbr — APPROVED** [review]

**Comment by mdlincoln** [comment]
Thank you @arojascastro for that fix! I should have noticed that...

Also, here are example previews:

Original lesson: https://deploy-preview-784--ph-dev.netlify.com/lessons/graph-databases-and-sparql

Translation: https://deploy-preview-784--ph-dev.netlify.com/es/lecciones/sparql-datos-abiertos-enlazados

Do we want to put quotation marks around the titles?

**Comment by arojascastro** [comment]
I think it's fine in that context. Thank you a lot @mdlincoln

**Pull request merged**
