### PR TITLE
Update ph_authors.yml

### LINKED ISSUE #2022: PH_author profile creation
Dear ones, 

I will elaborate the content for my profile to be displayed on the PH page.

Best Regards,
Jimmy

### PR DESCRIPTION
**Pull request by JimmyMedeiros82**
Hello everyone,
I added my personal information to the PH Authors page.
The content is at the end of the document.
Finally trying to move forward with this activity. I apologize for the delay in completing this process.
Regards,

*add the reason for your pull request here*

### Checklist

- [ ] Assign yourself in the "Assignees" menu
- [ ] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [ ] Add the appropriate "Label"
- [ ] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Review by DanielAlvesLABDH — CHANGES_REQUESTED** [review]
Olá @JimmyMedeiros82 na biografia em português falta um "J" no seu nome e tem uma gralha em "Porgrama". Tendo em conta que a biografia aparece em 4 línguas, por favor, peça revisão também aos colegas que coordenam cada uma das equipes para que possam verificar.

**Comment by JimmyMedeiros82** [comment]
> Ola @DanielAlvesLABDH que trabalhão que estou lhe dando!
Faço um novo pull request ou edito o que está feito?

**Comment by DanielAlvesLABDH** [comment]
Basta regressar ao ficheiro e voltar a editar, usando o mesmo branch. As alterações sucessivas são depois comparadas e no final fica a última edição. Para associar os colegas basta ir ao separador "Reviewers", onde colocou o meu nome e o do Joshua.

**Review by rivaquiroga — DISMISSED** [review]

**Comment by rivaquiroga** [comment]
Hi @JimmyMedeiros82, 
I made a small change in the Spanish translation.
BTW, the build is failing because you haven't upload your picture. It goes in the `avatars` folder and should be named: `jimmy-madeiros.png`. If you need any help, let us know :)

**Comment by DanielAlvesLABDH** [comment]
Thanks for the help @rivaquiroga Obrigado!

**Comment by JimmyMedeiros82** [comment]
Thanks @DanielAlvesLABDH  and @rivaquiroga !

I added my photo in the avatar folder.

**Comment by spapastamkou** [comment]
@JimmyMedeiros82 There seems to be a problem with your avatar image in all sites except for the EN. 
medeiros

**Comment by DanielAlvesLABDH** [comment]
Hi @spapastamkou , I think that error as to do with the fact that @JimmyMedeiros82 uploaded the photo in another PR https://github.com/programminghistorian/jekyll/pull/2033

**Comment by spapastamkou** [comment]
thanks @DanielAlvesLABDH, so it should be fixed once the other PR is merged, and this branch updated before merging.

**Review by spapastamkou — DISMISSED** [review]

**Review by DanielAlvesLABDH — DISMISSED** [review]

**Comment by rivaquiroga** [comment]
@JimmyMedeiros82, it seems that the build is failing because the name of the picture you uploaded was not in lower case. Should be `jimmy-medeiros.png`.

**Comment by DanielAlvesLABDH** [comment]
Thanks @rivaquiroga. I was looking at the file, missed that

**Review by rivaquiroga — DISMISSED** [review]

**Comment by DanielAlvesLABDH** [comment]
Sorry @rivaquiroga, corrected a small typo in the name of the institution

**Review by rivaquiroga — APPROVED** [review]

**Pull request merged**
