### PR TITLE
Create  2020-04-30-call-for-editors.md

### PR DESCRIPTION
**Pull request by svmelton**
Creating blog post

*add the reason for your pull request here*

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by jenniferisasi** [comment]
@svmelton I will give it a last check, and then do you have a particular date to publish it in mind? It is Friday, so I was thinking Monday? I have to send a few emails too and I am going to wait for Monday, always seems like a better idea.

**Comment by svmelton** [comment]
> @svmelton I will give it a last check, and then do you have a particular date to publish it in mind? It is Friday, so I was thinking Monday? I have to send a few emails too and I am going to wait for Monday, always seems like a better idea.

Monday works! I'll update the file name and extend the due date.

**Review by jenniferisasi — CHANGES_REQUESTED** [review]
I suggest changing "and citizens of non-English speaking countries" to "peoples of the global south"

**Comment by jenniferisasi** [comment]
Oh! Just saw that you responded @svmelton. I can make the changed I suggested but wanted you to also kind of approve first.

**Comment by svmelton** [comment]
> Oh! Just saw that you responded @svmelton. I can make the changed I suggested but wanted you to also kind of approve first.

Thanks! Just made the edit.

**Review by jenniferisasi — APPROVED** [review]

**Pull request merged**
