### PR TITLE
Add publications and presentations of 1/2 2021 on 'research'

### PR DESCRIPTION
**Pull request by jenniferisasi**
Updating our research pages to include various presentations, publications and workshops carried out during the first half of 2021 (till May 5)

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [ ] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Review by DanielAlvesLABDH — CHANGES_REQUESTED** [review]
Hi @jenniferisasi ! Thanks for the changes. If possible just change the names of the months to initial caps... The rest is fine

**Comment by jenniferisasi** [comment]
Thanks @DanielAlvesLABDH, I should have paid more attention to that. I'll update since I just got word of an additional presentation.

**Review by DanielAlvesLABDH — DISMISSED** [review]

**Comment by spapastamkou** [comment]
Just used the PR to fix a typo and some placenames in French (other than the what this PR was about). I'll review (myself) only if you are ok @jenniferisasi (so that you can merge) because my updates dismissed Daniel's review

**Comment by jenniferisasi** [comment]
I need someone to approve this :)

**Review by rivaquiroga — DISMISSED** [review]

**Review by spapastamkou — DISMISSED** [review]

**Comment by spapastamkou** [comment]
I updated the branch but now the build fails, I am afraid you have to wait until #1994 is merged for this to be fixed @jenniferisasi

**Review by spapastamkou — APPROVED** [review]

**Comment by spapastamkou** [comment]
you only need to check the previews and, if all is ok, you can merge @jenniferisasi

**Comment by acrymble** [comment]
@jenniferisasi I think this needs merging

**Pull request merged**
