### PR TITLE
New lesson: Add analisis-voyant-tools

### PR DESCRIPTION
**Pull request by jenniferisasi**
markdown file to jekyll/es/lecciones folder and images to jekyll/images/analisis-voyant-tools

### CODE REVIEW

**Comment by jenniferisasi** [comment]
I need to edit a few things yet.

**Comment by jenniferisasi** [comment]
Sorry for the ton of editing I'm doing but Travis and myself are having a fight with the assets folder and links to items in it.

**Comment by jenniferisasi** [comment]
Lesson learned: When there are multiple files on a corpus, compress the folder as a .zip and link to it in the lesson. 

Ready for review and merge

**Review by arojascastro — APPROVED** [review]
It looks great to me! Muchas gracias por el trabajazo

**Pull request merged**
