### PR TITLE
Publish Linear & Logistic Regression lessons

### PR DESCRIPTION
**Pull request by svmelton**
### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Review by hawc2 — COMMENTED** [review]
The lessons render correctly. 

One change to consider is that the summary of each lesson be rewritten slightly. If you see the attached screenshot, the way the two lessons appear next to each other, it almost looks like duplicates, since the only difference in title is one word. It doesn't help that both lesson summaries have the exact same sentence structures. 

phreview


Instead of saying "This lesson is the second of two" it could be more explicit: "This lesson is the second in a two-part lesson focusing on ..." Having Part 1 and Part 2 in the title might've helped as well, but that might be more trouble than its worth to change.

**Comment by svmelton** [comment]
Thanks @hawc2! I added in your suggested wording. If everything else looks good, I think we're ready to publish once you approve the PR!

**Comment by drjwbaker** [comment]
Suggest:

> This lesson - the second in a two-part lesson focusing on regression analysis - provides an overview of logistic regression, how use Python (scikit-learn) to make a logistic regression model, and a discussion of interpreting the results of such analysis.

**Comment by drjwbaker** [comment]
(my bad on the overviews being so similar!)

**Comment by rivaquiroga** [comment]
We faced a similar situation in the Spanish team and decided to add “part 1” and “part 2” to the title.

04C3F40F-0872-42FE-9570-F34D531E83A4

**Comment by spapastamkou** [comment]
If I may, I think it is good to also make the distinction in the title, as @rivaquiroga suggests, it would be good for the web indexation of the titles (to avoid confusion). We received a proposal for a two-part lesson in French, it is useful to see all this! @programminghistorian/french-team

**Comment by svmelton** [comment]
Thanks all! I agree with those suggestions and have made the edits.

**Comment by drjwbaker** [comment]
Note that we now have one lesson called..

> "Linear Regression Analysis with Scikit-learn (part 1)"

..and one called ..

> "Logistic Regression Analysis with Scikit-learn (part 2)"

That is, the first words are different, but we are calling when pt 1 and pt 2 of the same lesson. Are we sure that makes sense? They are a series on regression analysis with Scikit-learn, so if we want to represent that, perhaps we end up with..

> "Regression Analysis with Scikit-learn (part 1 - Linear)"

> "Regression Analysis with Scikit-learn (part 2 - Logistic)"

..or something to that effect.

**Comment by hawc2** [comment]
I like @drjwbaker suggestion for "Regression Analysis with Scikit-learn (part 1 - Linear)"

@svmelton I also think both summaries should be revised the same way, so the first one says: "This lesson is the first of a two-part lesson focusing" - I just find the phrase "the first of two" to be very vague

**Comment by svmelton** [comment]
Thanks @hawc2 and @drjwbaker! I think we're in good shape with the title and abstract now.

I did get a build error, and I'm not sure what it means. Could someone from @programminghistorian/technical-team take a look?
Screen Shot 2022-07-12 at 10 38 33 PM
.

**Comment by anisa-hawes** [comment]
I'm not certain what this error means either.... Do you have time to take a look, @ZoeLeBlanc? 

@svmelton: ~~One issue I noted when reviewing the Preview, is that the lesson images are in colour – they should be grey scale for consistency.~~ Update: this is done.

**Comment by anisa-hawes** [comment]
Screenshot 2022-07-18 at 17 11 41

Hello @svmelton and @drjwbaker. I'm sorry to say that [I haven't found a solution](https://github.com/programminghistorian/jekyll/pull/2606#issuecomment-1186974905) to the problem causing this build error .... but in the meantime, I've updated the two gallery images so that they are greyscale.

**Comment by svmelton** [comment]
Thank you for fixing the images, @anisa-hawes!

**Comment by anisa-hawes** [comment]
Hello @svmelton. Wonderful news! @ZoeLeBlanc has worked her magic ✨ and this PR is ready to go! Thank you for your patience. Anisa

**Review by anisa-hawes — APPROVED** [review]

**Pull request merged**
