### PR TITLE
Add alt attributes

### PR DESCRIPTION
**Pull request by walshbr**
Refs #2072. This fulfills one piece of the accessibility audit by using alt text when we have it for images. 

### Checklist

- [ ] Assign yourself in the "Assignees" menu
- [ ] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [ ] Add the appropriate "Label"
- [ ] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by walshbr** [comment]
There are a few pieces that need translation here - https://github.com/programminghistorian/jekyll/pull/2124/files. There is a single sentence as alt text for the main landing page: "Image from Scientific American of a woman at an Electrical Counting Machine." This needs to be translated into all languages @DanielAlvesLABDH @rivaquiroga @spapastamkou. If you want to drop the sentence in here I can add it in for you. Or you can edit the branch if you'd like and let me know when you've done so.

And then @DanielAlvesLABDH there is one thing we missed while launching the PT journal. The one published lesson has an avatar_alt attribute right now that reads "A large barrel" - line 28. That needs to be translated into PT, as right now the alt-text is rendering in English.

Let me know if you have any other questions! There will be other pull requests related to the accessibility ticket, but I actually don't think many (any?) of them will involve translation.

**Comment by walshbr** [comment]
@ZoeLeBlanc - the checks are picking up a broken link here - 

./_site/es/lecciones/retirada/introduccion-control-versiones-github-desktop.html

But that lesson is retired. Can we ignore retired lessons from the checks?

**Comment by jenniferisasi** [comment]
To avoid running the build again for a simple sentence: Imagen de Scientific American que muestra a una mujer trabajando en una máquina contadora eléctrica. 

For example.

**Comment by jenniferisasi** [comment]
> @ZoeLeBlanc - the checks are picking up a broken link here -
> 
> ./_site/es/lecciones/retirada/introduccion-control-versiones-github-desktop.html
> 
> But that lesson is retired. Can we ignore retired lessons from the checks?

Left her a message saying the same thing on #1994 this morning

**Review by DanielAlvesLABDH — COMMENTED** [review]
@walshbr this should be the PT translation: "Imagem da Scientific American de uma mulher a usar uma máquina de contagem elétrica"

**Comment by walshbr** [comment]
Thanks @DanielAlvesLABDH.  Could you also translate this?

"A large barrel"

I'll update the files when I go back in.

**Comment by DanielAlvesLABDH** [comment]
> 
> 
> Thanks @DanielAlvesLABDH. Could you also translate this?
> 
> "A large barrel"
> 
> I'll update the files when I go back in.

"Um barril grande"

**Comment by walshbr** [comment]
Thanks! Now I think I just need the FR translation of "Image from Scientific American of a woman at an Electrical Counting Machine" - @programminghistorian/french-team

**Comment by walshbr** [comment]
Thanks! This should be good to merge once we deal with the broken link issue.

**Comment by spapastamkou** [comment]
@walshbr Cool, I can review later if needed.

**Review by spapastamkou — APPROVED** [review]

**Pull request merged**
