### PR TITLE
Translation of platform pages to PT, closes #1818

### LINKED ISSUE #1818: Translating PH to Portuguese
The Portuguese team has translated pages Index.md, Lessons.md, Project-team.md, Feedback.md, Contribute.md, Privacy-policy.md, About.md, research.md, reviewer-guidelines.md, support-us.md and Editor-guidelines.md (https://github.com/programminghistorian/jekyll/tree/gh-pages/pt). We want now to proceed to the other pages of the platform. The notes we get from @acrymble were that we were supposed to contact for advice. Don't know if this is the best way to do that, but since I need to practice on GitHub and with "issues" it sounded adequate.

### PR DESCRIPTION
**Pull request by DanielAlvesLABDH**
This will make all the changes to Portuguese in the next files: Index.md, Lessons.md, Project-team.md, Feedback.md, Contribute.md, Privacy-policy.md, About.md, research.md, reviewer-guidelines.md, support-us.md and Editor-guidelines.md

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by walshbr** [comment]
Thanks @DanielAlvesLABDH - is this ready for me to look at from a tech standpoint? I noticed a couple files still have the placeholder English text in them - directrizes-autor.md and directrizes-tradutor.md. There are also a bunch of snippets that still need translating that will cause errors when we try to get things all set up, but wasn't sure if you were trying to just get a subsection of them done. To my mind it might make sense to wait to ping us for review until you've made a first pass at _all_ the pages that need translating for the initial release, but open to suggestions!

**Comment by DanielAlvesLABDH** [comment]
Dear @spapastamkou @rivaquiroga and @svmelton in the about.md / sobre.md file (https://github.com/programminghistorian/jekyll/pull/1888/commits/0d17e1dcd5efa0b6ebdac8b9ac26d67ca3f397f3), besides translating to Portuguese we added a last sentence in the "History of the project / História do Projeto" section: "Em 2020, adicionámos uma [versão em português]({{site.baseurl}}/pt).", that can be translated to English as "In 2020, we added a Portuguese language version." or something similar. Once approved, you may want to incorporate that in the French, Spanish and English versions of the file. Thanks!

**Comment by DanielAlvesLABDH** [comment]
> 
> 
> Thanks @DanielAlvesLABDH - is this ready for me to look at from a tech standpoint? I noticed a couple files still have the placeholder English text in them - directrizes-autor.md and directrizes-tradutor.md. There are also a bunch of snippets that still need translating that will cause errors when we try to get things all set up, but wasn't sure if you were trying to just get a subsection of them done. To my mind it might make sense to wait to ping us for review until you've made a first pass at _all_ the pages that need translating for the initial release, but open to suggestions!

Thanks @walshbr The goal was to translate the first group of files. Talking to @acrymble I get the notion that was better to make first these files and then move to the other ones, but probably I didn't understand it correctly. We are in the process of translating the second group of files, that includes the ones you mention. Probably would be good for us to have some feedback now about this first effort before we move to the next stage, but feel free to suggest otherwise.

**Comment by walshbr** [comment]
Ok! I'll take a look and see what I can do with this batch and report back.

**Comment by walshbr** [comment]
I checked through the pages you have. Things seem to be OK? It's really difficult to granular checks until we get the actual thing launched, because a lot of the snippets are missing. So there will just be gaps on pages that, from poking around, look like they will be fixed when you get to the snippets file. So we'll want/need to go through and click through everything at the end again. 

In terms of whether to merge this - I think you should be good for merging these things in without affecting the live site. They won't appear linked anywhere, though it's possible that if someone happens to do a Google search in Portuguese for PH they will come up, depending on when Google indexes the site. They'll be out there as live pages, just functionally no one would be able to find them unless they get the path to the URL or from a Google search. @acrymble and @JoshuaGOB did you have any thoughts about this? I'm not actually sure with French if we merged everything all at once or did it a bit at a time. I'm personally inclined to say it would be OK to merge things in chunks like this, hidden from view more or less, so long as we're organized about it. 

In terms of general comments so far:

- On the feedback page, you mention contacting William Turkel - he is not on the project anymore. That should be the PT project manager, I believe. Probably just leftover from the placeholder text. 
- It's maybe worth noting that the screenshots for the guidelines pages still contain English text because they're just the same screenshot. I wanted to draw attention to it, but it would be a lot of work for you to redo all those screenshots in Portuguese. If you think you can get by with the screenshots in English I would keep them, but that's easy for me to say as an English speaker. 

So depending on what @acrymble and @JoshuaGOB think about merging this portion of the site with other translations outstanding I can approve this.

**Comment by DanielAlvesLABDH** [comment]
Thanks a lot for this evaluation @walshbr ! We will wait for Adam and Joshua...

**Comment by acrymble** [comment]
I'd be inclined to merge with maybe a warning banner text saying "soft launch" or something, in case someone finds it?

It's a huge amount of work to do the whole site at once, so this might be easier for everyone given that we all volunteer time.

**Comment by DanielAlvesLABDH** [comment]
Sorry @walshbr but I can't seem to find William Turkel mention on feedback.md (pt version)

**Comment by walshbr** [comment]
I swear I saw it @DanielAlvesLABDH, but now I can't find it either! So I wouldn't worry about it.

**Comment by walshbr** [comment]
Oh nevermind @acrymble and @JoshuaGOB - I misunderstood some of the code. The pt directory is explicitly _not_ being built, so it won't show up on the live site even if we merge this. The pages won't live in any form outside of the repository until after we modify _config.yml. So this is good to merge from my end. No need for a banner.

**Review by walshbr — APPROVED** [review]

**Comment by JoshuaGOB** [comment]
This is great @DanielAlvesLABDH and @walshbr 
Thank you to both of you!

**Review by JoshuaGOB — APPROVED** [review]

**Pull request merged**
