### PR TITLE
Issue 2536

### LINKED ISSUE #2536: Clarifying our policies on authorial copyright and publishing rights
In the process of applying to add _Programming Historian em português_ to the [Directory of Open Access Journals (DOAJ)](https://doaj.org/about/) (see #2528) we have been asked to clarify our policies on authorial copyright and publishing rights.

My understanding is that this links to some conversations you have already been having within the Project Team (initiated by @spapastamkou) about how we can keep a more formal record of the permissions authors have granted, as well as clarifying their (and our) rights. @acrymble and I have been talking about setting up a workflow for forward- and retrospective documentation of these agreements. An idea is establishing a form that authors can complete for our (and their) records, which offers a clearer explanation of terms than the short statement we currently ask them to paste into Issues in our Submissions Repo.

The DOAJ's suggestion is that we add the following two statements to our website:

**Authors' copyrights:**

EN: "Authors retain copyright and grant the journal the right of first publication, with the work simultaneously licensed under the Creative Commons - Attribution 4.0 International CC BY 4.0 License."

PT: "Os autores mantêm os direitos autorais e concedem à revista o direito de primeira publicação, com o trabalho simultaneamente licenciado sob a Licença Creative Commons - Atribuição 4.0 Internacional CC BY 4.0."

**Authors' publishing rights:**

EN: "Authors have permission to publish and distribute their work online in institutional / disciplinary repositories or on their personal homepage."

PT: "Os autores têm permissão de publicar e distribuir o seu trabalho online em repositórios institucionais / disciplinares ou na sua página pessoal."

I'd like to ask the Managing Editors @DanielAlvesLABDH @svmelton @spapastamkou and @rivaquiroga for their thoughts on this?

I see this Issue as comprising two key tasks:

- [x] adding the statements on authors' copyrights and publishing rights PR #2555 
- [x] gathering ideas about developing a Rights Agreement form, to help us document our agreements with authors, clarifying their rights as authors and our rights as publisher.

### PR DESCRIPTION
**Pull request by anisa-hawes**
This PR represents the next steps to rolling out use of our Authorial Copyright and Publishing Rights declaration forms in place of the Permission to Publish statements within issue comments.

Our ES and EN forms are already in use, and this PR will make it possible for the @programminghistorian/french-team and @programminghistorian/portuguese-team to begin actively pointing authors + translators to the download link, and using the form in their workflows too. 

- [x] upload FR PDF to [Forms](https://github.com/programminghistorian/jekyll/tree/gh-pages/assets/forms) 
- [x] add Form download link from the Open source, libre accès section of our /fr/consignes-auteurs

- [x] upload PT PDF to [Forms](https://github.com/programminghistorian/jekyll/tree/gh-pages/assets/forms) 
- [x] add Form download link from the Código aberto, Acesso aberto section of our pt/directrizes-autor

Closes #2536

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Hello @DanielAlvesLABDH and @spapastamkou,

Thank you for your input!

I'm excited that we are ready to take our next step to rolling out use of our Authorial Copyright and Publishing Rights declaration forms (replacing Permission to Publish statements within ph-submissions Issues).

Our ES and EN forms are already in use, and this PR will make it possible for the FR and PT teams to begin actively pointing authors + translators to the download link, and using the form in their workflows too.

I'd be grateful if you could check the wording I've added to /fr/consignes-auteurs (lines 55, 57) and /pt/directrizes-autor (lines 57, 59).

I'll update the ph-submissions template now, and will also writing this step into the re-draft of the Editorial Guidelines I'm working on.

**Comment by DanielAlvesLABDH** [comment]
Dear @anisa-hawes on line 59 I suggest small edits. See this: "Pedimos aos autores e tradutores para preencher [o formulário de declaração](/assets/forms/Direitos-autorais-e-permissao-para-publicar.pdf), reconhecer os direitos autorais e conceder permissão para publicar. Por favor, envie o formulário [ao/à nosso/a Assistente de Publicação](mailto:admin@programminghistorian.org)."

**Comment by spapastamkou** [comment]
Current text is: 
Nous demandons aux auteur(e)s, aux traducteurs et aux traductrices compléter [un formulaire de déclaration](/assets/forms/Droit-d-auteur-et-authorisation-de-publication.pdf) pour reconnaître le droit d'auteur et accorder l'autorisation de publier. Veuillez envoyer le formulaire [à notre assistante éditoriale](mailto:admin@programminghistorian.org).

I propose the following form: 
Nous demandons aux auteur(e)s, aux traducteurs et aux traductrices **de** compléter [un formulaire](/assets/forms/Droit-d-auteur-et-authorisation-de-publication.pdf) de cession non exclusive de droits d'auteur et d'autorisation de publication. Veuillez envoyer le formulaire [à notre assistante éditoriale](mailto:admin@programminghistorian.org). 

cc @marie-flesch

**Review by spapastamkou — CHANGES_REQUESTED** [review]
Current text (in authors guidelines) is: 
Nous demandons aux auteur(e)s, aux traducteurs et aux traductrices compléter [un formulaire de déclaration](/assets/forms/Droit-d-auteur-et-authorisation-de-publication.pdf) pour reconnaître le droit d'auteur et accorder l'autorisation de publier. Veuillez envoyer le formulaire [à notre assistante éditoriale](mailto:admin@programminghistorian.org).

I propose the following form: 
Nous demandons aux auteur(e)s, aux traducteurs et aux traductrices **de** compléter [un formulaire](/assets/forms/Droit-d-auteur-et-authorisation-de-publication.pdf) de cession non exclusive de droits d'auteur et d'autorisation de publication. Veuillez envoyer le formulaire [à notre assistante éditoriale](mailto:admin@programminghistorian.org).

**Comment by spapastamkou** [comment]
@anisa-hawes sorry for the late reply!

**Review by spapastamkou — APPROVED** [review]

**Pull request merged**
