### PR TITLE
deletes matchmaker text and link in Détecter la réutilisation de texte avec Passim

### PR DESCRIPTION
**Pull request by spapastamkou**
*A link that was inserted in the lesson before publication, in replacement of a dead link, is deleted following the authors request; same for the text that went with the link*

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by spapastamkou** [comment]
The build now fails because of link problems in the EN version of this lesson. I was planning a separate pull request also integrating updates the authors proposed for the original version, while working on the translation. I will however integrate them in this pull request asap to solve the problem at once. @amsichani @svmelton please be aware and I will tag you again once I make the commits.

**Comment by anisa-hawes** [comment]
Hello @spapastamkou. It seems like these are the two links causing a problem with the build now:

1. https://github.com/JSTOR-Labs/matchmaker
2. https://github.com/impresso/PH-Passim-tutorial/blob/master/explore-Passim-output.ipynb 

I've just checked, and 2. works fine. But 1. retrieves a 404. I've been looking at https://labs.jstor.org/projects/ but cannot find a suitable alternative link. Are you familiar with the Matchmaker project?

**Comment by spapastamkou** [comment]
@anisa-hawes These were issues resolved during the [FR translation review process](https://github.com/programminghistorian/ph-submissions/issues/372) together with the authors. They were not registered yet in the EN published lesson and this was the problem. All ok now.

**Comment by spapastamkou** [comment]
@svmelton @amsichani I updated the EN lesson as per [issue 334](https://github.com/programminghistorian/ph-submissions/issues/372), and commits of [relevant PR](https://github.com/programminghistorian/ph-submissions/pull/392#issuecomment-919921487) the authors had raised in ph-submissions.

**Comment by spapastamkou** [comment]
@ZoeLeBlanc Can you perhaps help me update this branch from gh-pages (my Github Desktop won't do me the favor...)? Thanks! 
Update: Zoe, I was able to eventually resolve this, all ok now.

**Comment by spapastamkou** [comment]
once approved, this is now ready to merge.

**Review by svmelton — APPROVED** [review]

**Comment by ZoeLeBlanc** [comment]
Kudos for resolving this on your own @spapastamkou 👏🏽 🥳 !!

**Pull request merged**
