### PR TITLE
Create Doacoes.md  New Portuguese Support-Us pages #2074 

### LINKED ISSUE #2074: New Portuguese Support-Us pages
Building on #1943 - Translate Support us

We need 3 new pages in Portuguese for our various fundraising pages to bring them in line with the other languages. These are

    /pt/ppi.md
    /pt/doacoes.md
    /pt/apoiadores.md

We also need to add a Middle Band price for middle income countries, set at £400 - see #1988.

We currently have no Portuguese IPP members, and I think it is far more important that the @programminghistorian/portuguese-team publish more lessons. So I will leave this here and will revisit it with @DanielAlvesLABDH once there are 6 PT lessons published.

### PR DESCRIPTION
**Pull request by JimmyMedeiros82**
I create the page "Individual Supporters" in Portuguese, called "doacoes". The link to the original page is https://programminghistorian.org/en/individual
It is part of the 3 new pages that will be created in Portuguese about fundraising. It is linked to the issue "New Portuguese Support-Us pages #2074 "

Closes #2074 

By markdown editor, text formatting was ok. When pasting the text here on Github it appeared different. If necessary, I make the adjustment.

*add the reason for your pull request here*

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by DanielAlvesLABDH** [comment]
Acho que está tudo certo agora. O erro que está a dar é da falta do ficheiro ipp.md, que ainda está a ser gerado. Quando estiver disponível, da minha parte isto está pronto Jimmy! Obrigado!

**Comment by acrymble** [comment]
@JimmyMedeiros82 I've put all 3 files onto one branch so we can update everything at the same time and make sure it works together.

**Comment by acrymble** [comment]
Thank you @JimmyMedeiros82 for translating these pages. I think you only missed one sentence in the ppi.md file:

> Rates are due annually from the date of first payment and are set in January each year. For a quote in another currency please email [Dr. James Baker](mailto:programminghistorian@gmail.com).

If you tell me the appropriate translation I can fix it (or you can do it).

**Comment by JimmyMedeiros82** [comment]
Hi Adam, sorry for forgetting. 
The translation is:

As taxas são anuais e consideramos a contagem a partir da data do primeiro pagamento. Os valores são definidos em janeiro de cada ano. Para uma cotação em outra moeda, por favor, envie um e-mail para [Dr. James Baker]mailto:programminghistorian@gmail.com).

I also forgot to translate:
Upper Income Countrie -> Países de renda alta
Middle Income Countries -> Países de renda média
ODA eligible countries-> Países elegíveis para ODA 

Thank you for the opportunity to collaborate. Sorry for the delay.

**Review by acrymble — APPROVED** [review]
I have checked the old page forwards properly, so this looks great. Thank you so much @JimmyMedeiros82. 

you can merge this.

**Review by DanielAlvesLABDH — APPROVED** [review]
Jimmy, muito obrigado por este trabalho de tradução e adaptação dos novos ficheiros. Fiz uma revisão geral e parece-me que está pronto a ser publicado. Abraço
Adam, thanks for your help on this. I made a final revision and all seems fine. Best

**Pull request merged**
