### PR TITLE
Remove the broken link and add some information to metadata #2150

### LINKED ISSUE #2150: Error/broken link "Penflip" of Markdown lesson
Hi, I'm Pao-Chuan, a new member that joining this program as the work placement of UCL. I'm working with Adam and feel really interesting and enjoyable, because I do learn something new continuously when checking if the tutorials/lessons still work properly.

When working on the lesson called "Sustainable Authorship in Plain Text using Pandoc and Markdown", I found that the link of "Penflip" appears an error after clicking on it in the "Useful Resources" section, I use Mac system to test this link through Google Chrome, Firefox and Safari, all the browsers announce “Your connection is not private." and it's not safe for user to visit anymore.

Besides, Adam and I  also tested this link through Window system, it doesn't work as well.

The screen shot of the error is provided.
12171623318584_ pic

### PR DESCRIPTION
**Pull request by pao-chuan**
The broken links "Penflip" have been removed from both English and Spanish versions of Markdown lessons, besides, there are some information including "lesson-testers" and "tested-date" have been added to the metadata of English version of Markdown lesson and two Omeka.net lessons.

Closes #2150 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by pao-chuan** [comment]
Hi everyone, I'm Pao-Chuan and working with Adam as my work placement. After discussing with Adam, we have decided to remove the broken link "Penflip" of the lesson "Sustainable Authorship in Plain Text using Pandoc and Markdown" (the link: https://programminghistorian.org/en/lessons/sustainable-authorship-in-plain-text-using-pandoc-and-markdown) and also the same in its Spanish version (the link: https://programminghistorian.org/es/lecciones/escritura-sostenible-usando-pandoc-y-markdown). 

Besides, after testing the lesson "Sustainable Authorship in Plain Text using Pandoc and Markdown" (the link: https://programminghistorian.org/en/lessons/sustainable-authorship-in-plain-text-using-pandoc-and-markdown) and also
two lessons about Omeka: "Creating an Omeka Exhibit" (the link: https://programminghistorian.org/en/lessons/creating-an-omeka-exhibit) and "Up and Running with Omeka.net" (the link: https://programminghistorian.org/en/lessons/up-and-running-with-omeka), I find it is still working so I have added "lesson-testers" and "tested-date" to their metadata.

**Comment by pao-chuan** [comment]
More Info: The broken link "Penflip" may cause some security risks.

**Comment by acrymble** [comment]
@ZoeLeBlanc can you please tell us if we've done the "lesson tester" YAML correctly? I believe this is the first time it's being applied.

**Comment by ZoeLeBlanc** [comment]
Overall looks great! The only thing to change @pao-chuan and @acrymble is that we tend to do first name last name for all our name fields (author, reviewers, editors, translators, etc...) so it would be ideal to keep that practice for lesson tester as well.

**Comment by pao-chuan** [comment]
Thanks for your advice @ZoeLeBlanc ! You mean cancel the comma symbol between my first name and last name?

**Comment by acrymble** [comment]
@svmelton @rivaquiroga 

This fix removes a suggested resource from the English and Spanish lesson "Sustainable Authorship in Plain Text using Pandoc and Markdown". The link no longer works and it was one of about 5 suggested further resources for readers to check out. The cleanest solution seemed like just removing the link, which @pao-chuan has done with this pull request.

Are you both happy with that approach as MEs?

We've tried to follow the workflow @rivaquiroga developed https://github.com/programminghistorian/jekyll/issues/2058

**Comment by rivaquiroga** [comment]
Sounds good to me. Thank you!

**Comment by acrymble** [comment]
@programminghistorian/technical-team can we please have help bringing this branch up to date? I think it's ready other than that.

**Comment by walshbr** [comment]
That should do it @acrymble

**Review by acrymble — APPROVED** [review]

**Pull request merged**
