### PR TITLE
Add 'Support Us' to top menu

### PR DESCRIPTION
**Pull request by drjwbaker**
add 'support us' page to top nav menu (apologies for the crude ES and FR translations of the page names)

### CODE REVIEW

**Comment by drjwbaker** [comment]
Re https://github.com/programminghistorian/jekyll/issues/1162#issuecomment-462159385 FR/ES translation needed of both menu name and 'Support Us' page. Happy to not merge this PR until will have translations in place (no hurry!)

**Comment by arojascastro** [comment]
Thank you for adding the tab in Spanish.

On the other side, is support page ready to be translated into Spanish? Already done? I am bit lost here. Sorry.

**Comment by drjwbaker** [comment]
@arojascastro No, as far as I understand the page the tab refers to has not been translated. I think this got lost in the Big FR PR. I don't think the FR page has been done either (@spapastamkou?). It requires a reduction of text in the 'Funding & Ownership' section of the About page (see https://programminghistorian.org/en/about#funding--ownership), which the 'Support Us' page now elaborates on in more detail. There isn't a hurry on this, so if it can be planned as part of the ongoing ES and FR workflow, I'd be grateful (and I'm keen to manage, help, support wherever I can!)

**Comment by spapastamkou** [comment]
no, there is no FR page either. I created a file, will commit once the translation is finished.

**Comment by drjwbaker** [comment]
@spapastamkou Quick work! Does this require a review by an FR team member?

**Review by drjwbaker — COMMENTED** [review]
`fr/nous-soutenir.md` looks good from a technical perspective.

**Comment by spapastamkou** [comment]
yes, would be good if @mpuren or @fdlaramee could take a look as well!

Le mar. 19 févr. 2019 à 12:52, James Baker <notifications@github.com> a
écrit :

**Comment by fdlaramee** [comment]
Fixed a few typos and phrasing issues. Looks very good!

**Review by mpuren — COMMENTED** [review]
Thanks @fdlaramee and @spapastamkou ! It looks very good to me too.

**Comment by drjwbaker** [comment]
So we just need the ES translation then are good to go, right?

**Comment by mdlincoln** [comment]
Yes. I've already added a blank file at `es/apoyanos.md` for the translation.

**Comment by jenniferisasi** [comment]
Noted. Will work on the translation of your `support-us` page into Spanish.

**Review by arojascastro — DISMISSED** [review]
I looked at Jennifer's translation. Gracias :)

**Comment by drjwbaker** [comment]
Huge thanks to @jenniferisasi & @arojascastro for doing the hard work here.

The final piece (that I think got buried in my note at https://github.com/programminghistorian/jekyll/pull/1166#issuecomment-462383614, sorry) is to reduce text at https://programminghistorian.org/fr/apropos#financement--propriet%C3%A9 and https://programminghistorian.org/es/acerca-de#financiamiento-y-propiedad to what is at https://programminghistorian.org/en/about#funding--ownership. In short, this is because most of the information about 'Funding and Ownership' is now on the new 'Support Us' page.

**Comment by mdlincoln** [comment]
So the remaining translation tasks are 

- [ ] update `/es/acerca-de#financiamiento-y-propiedad` @jenniferisasi 
- [ ] update `[/fr/apropos#financement--propriet%C3%A9]` @spapastamkou

**Review by mdlincoln — CHANGES_REQUESTED** [review]
So the remaining translation tasks are 

- [x] update `/es/acerca-de#financiamiento-y-propiedad` @jenniferisasi 
- [x] update `[/fr/apropos#financement--propriet%C3%A9]` @spapastamkou

**Comment by mdlincoln** [comment]
Hi @jenniferisasi just a reminder that `/es/acerca-de` the "financiamiento-y-propiedad" still needs to be updated, and then we'll be done!

**Review by mdlincoln — DISMISSED** [review]

**Comment by mdlincoln** [comment]
OK, I'm happy - any further revisions needed @programminghistorian/french-team or @programminghistorian/spanish-team ?

**Review by arojascastro — DISMISSED** [review]
looks good

**Review by mdlincoln — APPROVED** [review]

**Pull request merged**
