### PR TITLE
update Sofia affiliation and bio

### LINKED ISSUE #2460: Change of professional affiliation
I open the ticket to raise a pull request to change my professional affiliation.

### PR DESCRIPTION
**Pull request by spapastamkou**
*Updating my affiliation and bio. Closes #2460*

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by spapastamkou** [comment]
Ok, there is a failing link there. I'll wait a bit and try to fix this later. 
@datalogism Veux-tu par hasard profiter de ce PR pour mettre à jour ton affiliation pro? Si c'est le cas, n'hésite pas!

**Comment by datalogism** [comment]
Hello @spapastamkou  !
Oh oui carrement, il me suffit d'éditer directement https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/ph_authors.yml ?

**Comment by anisa-hawes** [comment]
Hello Célian @datalogism, Yes, `_data/ph_authors.yml` is the file to update! 

In the meantime, I'll take care of fixing the broken link

Please let me know if you have any questions.

**Comment by jenniferisasi** [comment]
@anisa-hawes maybe we can use this ticket to take my "Communications Manager" role off my profile?

**Comment by anisa-hawes** [comment]
Thank you, @jenniferisasi! That is on my list too! I'll update `/teamroles.yml` & `/ph_authors.yml` to reflect that now.

**Comment by jenniferisasi** [comment]
Thank you @anisa-hawes, I had forgotten about teamroles.yml

**Comment by anisa-hawes** [comment]
I've updated the broken link to the interview with Sam Aaron, para.382 of en/lessons/sonification. 

Replacing https://devchat.tv/ruby-rogues/215-rr-sonic-pi-with-sam-aaron with https://devchat.cachefly.net/rubyrogues/RR215SonicPi.mp3?rss=true

I'll keep an eye on this PR until you've made your edits Célian @datalogism.

**Comment by anisa-hawes** [comment]
On second thoughts, I think this link might be more robust: https://rubyrogues.com/221
because the domain https://devchat.tv has migrated to https://topenddevs.com/ and the interview/podcast can't be found directly on that site.

Apologies, I'll re-edit.

**Comment by amsichani** [comment]
> @anisa-hawes maybe we can use this ticket to take my "Communications Manager" role off my profile?

May I take advantage of the moment /PR and ask @anisa-hawes  to take my "Technical team" role off my profile?

**Comment by anisa-hawes** [comment]
That's done, @amsichani! 🙂

**Comment by spapastamkou** [comment]
thanks, @anisa-hawes ! And very glad this PR proves to be more broadly useful that I had thought:-) 
@datalogism Pour rappel, il faut faire les modifs à partir de cette branche (qui porte le nom de l'issue): https://github.com/programminghistorian/jekyll/tree/Issue-2460 Alternativement, tu n'as qu'à poser les infos en commentaire, et on s'en charge.

**Comment by datalogism** [comment]
Ola ! I just updated it my new affiliation/bio are in comments :) thank you for the updates

**Comment by anisa-hawes** [comment]
Thank you, Célian @datalogism!

EN: Célian Ringwald is a research engineer at INRIA in the Wimmics laboratory. He is in charge of the maintenance and development of the French chapter of DBpedia.

ES: @programminghistorian/spanish-team Are you able to help with a translation of Célian's bio?

FR: Célian Ringwald est ingénieur de recherche à l'INRIA au laboratoire Wimmics. Il est en charge de la maintenance et du developpement du chapitre français de DBpedia.

PT: @programminghistorian/portuguese-team Are you able to help with a translation of Célian's bio?

**Comment by DanielAlvesLABDH** [comment]
PT: Célian Ringwald é engenheiro pesquisador do INRIA no laboratório Wimmics. Ele é responsável pela manutenção e desenvolvimento da versão em francês da DBpedia.

**Comment by jenniferisasi** [comment]
> ES: @programminghistorian/spanish-team Are you able to help with a translation of Célian's bio?

Célian Ringwald es ingeniero investigador del INRIA en el laboratorio Wimmics. Está a cargo del mantenimiento y desarrollo de la sección en francés de DBpedia.
 
> PT: @programminghistorian/portuguese-team Are you able to help with a translation of Célian's bio?

~~Célian Ringwald é engenheiro de pesquisa do INRIA no laboratório Wimmics. Ele é responsável pela manutenção e desenvolvimento da seção francesa da DBpedia.~~


Ah, ignore my PT attempt, I see @DanielAlvesLABDH was on it already :)

**Comment by spapastamkou** [comment]
too crowded today, I was on it as well:-)

**Review by anisa-hawes — APPROVED** [review]

**Comment by spapastamkou** [comment]
thank you so much, @anisa-hawes, and thank you @jenniferisasi @DanielAlvesLABDH !

**Comment by datalogism** [comment]
Thank you so much @anisa-hawes, @DanielAlvesLABDH  and @jenniferisasi for the quick translations !

**Pull request merged**
