### PR TITLE
Update creacion-de-aplicacion-shiny.md

### LINKED ISSUE #3063: Replace broken link in es/lecciones/creacion-de-aplicacion-shiny
I am opening this Issue to investigate a replacement for a broken link in the ES lesson [Creación de aplicaciones web interactivas con R y Shiny](https://programminghistorian.org/es/lecciones/creacion-de-aplicacion-shiny).

The problem link is: <https://datos.gob.es/es/catalogo/ea0019768-hemeroteca-digital-listado>

This link appears twice in the lesson. 

At line 85, I think a suitable replacement would be: https://hemerotecadigital.bne.es/hd/publications which provides readers with the original list of titles (`bne_hemeroteca-digital.csv` has been created and is available for readers to work with in our assets repository).

At line 507, I think a suitable option would be: https://datos.gob.es/es/catalogo/ea0019768-hemeroteca-digital-listado-de-titulos.

As neither of these links represent direct actions (download, install, etc.) or include dynamic or interactive aspects, I think they can both be perma.cc. I'm not sure why I didn't do this originally, but I will do it now!

### PR DESCRIPTION
**Pull request by anisa-hawes**
I'm replacing two instances of a broken link in es/lecciones/creacion-de-aplicacion-shiny.

The problem link is: https://datos.gob.es/es/catalogo/ea0019768-hemeroteca-digital-listado
I've replaced it at lines 85 and 507, with perma.cc links.

Closes #3063 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Add the appropriate "Label"
- [x] If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above
- [x] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Assistant @anisa-hawes 
- [x] Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)
- [x] Assign at least one individual or team to "Reviewers"
  - ~~[ ] if the text needs to be translated, please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines), then assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR.~~

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Hola @jenniferisasi. Do you have a moment to review this PR for me? 

Do you think that my suggested replaced links (both now perma.cc) make sense?

**Comment by jenniferisasi** [comment]
Sure thing, @anisa-hawes! In checking the previous links (that don't work now), we need the same perma-link in both, the one with the list of titles: https://perma.cc/JT88-ZXPD

**Comment by anisa-hawes** [comment]
Thank you, @jenniferisasi. I'll make that adjustment.

**Review by jenniferisasi — COMMENTED** [review]
Yay!

**Review by jenniferisasi — APPROVED** [review]
Yay! approved

**Pull request merged**
