### PR TITLE
Update downloading-multiple-records-using-query-strings lesson to Pyt…

### PR DESCRIPTION
**Pull request by frederik-elwert**
Contributes to #1460.

In the course of updating the lesson, I also fixed a few small errors. I removed the `newDir` function, which was defined but then never used.

### CODE REVIEW

**Comment by acrymble** [comment]
Thanks for doing so much work @frederik-elwert. I have tried the entire lesson from start to finish and noticed 2 small errors.

First, the following sentence  has a typo (which I sure was mine originally):

you are trying to create a director with a * in it  (should say "directory")

--

Secondly,  the obo.py  code chunks have some mistaken duplication in the final few examples. In particular the startValue=0 variable, and the code to create a new directory are accidentally included twice.

**Comment by acrymble** [comment]
It looks like this pull request isn't coming direclty from our repository so I can't make the changes myself.  If you make the fixes @frederik-elwert I will review and approve.

**Comment by frederik-elwert** [comment]
Thanks for reviewing and catching those! Checked twice, I hope I spotted all the duplicates.

**Comment by acrymble** [comment]
Thanks.  I'm afraid  your fix has introduced a new typo.

There's a double-tab  now before "os.makedirs(cleanQuery)" in four code examples. This extra tab should be removed. Otherwise this is ready to republish and thanks for the work @frederik-elwert .

**Comment by frederik-elwert** [comment]
This is weird, I cannot remember touching that part. But thanks for spotting, should be fixed now.

**Review by acrymble — APPROVED** [review]
I have tested this code and the changes and I believe it is ready to push to the live site. Thank you for  all of your hard work and contributions to the project.

**Comment by acrymble** [comment]
@svmelton @alsalin As the managing editors, I'll leave this for you to merge. But I approve of the changes.

**Pull request merged**
