### PR TITLE
Update feedback.md

### LINKED ISSUE #2423: Create banner on "Report a bug" page
After several users creating PRs (from forks in their repo) directly to make changes to our materials, @anisa-hawes and I have decided to add a banner on the "Report a bug" site explicitly telling users NOT to do PRs. It might not be followed by all, but it doesn't cost us to add a banner and also gives Anisa a place to direct PR creators and say "it is a rule".

### PR DESCRIPTION
**Pull request by jenniferisasi**
add banner and remove language about forks and PRs

Closes #2423 

*add the reason for your pull request here*

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [ ] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Review by anisa-hawes — COMMENTED** [review]
EN is perfect!

**Comment by jenniferisasi** [comment]
All four banners are working. I'll wait for someone in the @programminghistorian/french-team and @programminghistorian/portuguese-team team to approve my attempts at writing their languages, and it will be done! 

Thanks in advance.

**Review by DanielAlvesLABDH — DISMISSED** [review]
Your Portuguese is fine @jenniferisasi! Thank you!

**Review by spapastamkou — APPROVED** [review]

**Comment by spapastamkou** [comment]
@jenniferisasi only changed the capitals to small, we use pull request from EN without guilt:-)

**Pull request merged**
