### PR TITLE
fixed documentation links and set_node_attributes

### PR DESCRIPTION
**Pull request by jrladd**
This update fixes the problem with NetworkX documentation links in #613

### CODE REVIEW

**Review by mdlincoln — APPROVED** [review]

**Comment by mdlincoln** [comment]
This looks good to me - @walshbr can you give it a glance as well before we merge?

(ignore the failing checks - we're still waiting on #611 to be fixed...)

**Comment by walshbr** [comment]
Was just testing the code blocks quickly, @jrladd, but I got an error on this line as well:
```
Traceback (most recent call last):
  File "network.py", line 88, in <module>
    sorted_degree = sorted(degree_dict.items(), key=itemgetter(1), reverse=True)
AttributeError: 'DegreeView' object has no attribute 'items'
```
Looks like the DegreeView object might have changed? Let me know if you're not running into that.

That'd be line 433 in the markdown file.

**Comment by jrladd** [comment]
Thanks, @walshbr, I think I see what happened. NetworkX 2.0 now outputs the results of G.degree() as a list of tuples instead of a dictionary. Should be a simple fix, just change:

`degree_dict = G.degree(G.nodes())`

into

`degree_dict = dict(G.degree(G.nodes()))`

and the rest of code down the line should work fine. Is there a best way to update this in the current pull request?

Testing it on my end, I did notice that I also had to update python-louvain to prevent the modularity stuff from throwing an error, but anyone installing the libraries recently shouldn't have that problem.

**Comment by walshbr** [comment]
@jrladd i believe if you push to your particular branch on your fork it should autoupdate the pull request. But let me know if you've already tried that and it's not working. Looking here - https://help.github.com/articles/committing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by jrladd** [comment]
Okay, looks like the new commit has been added here!

**Comment by walshbr** [comment]
Thanks @jrladd - I think it's worth covering your bases by also mentioning the update to python-louvain. I got the error too, since I was working through it way back when as well. Seems worth documenting the workaround to ensure that others have it straight for as many use cases as possible.

**Comment by jrladd** [comment]
Makes good sense to me! I added a short paragraph to the Data Prep section.

**Review by walshbr — APPROVED** [review]

**Comment by walshbr** [comment]
Thanks @jrladd looks good to me! All the code is running for me now. Should be ready to merge.

**Pull request merged**
