### PR TITLE
Check for presence of `review-ticket` in lesson YAML

### PR DESCRIPTION
**Pull request by mdlincoln**
Don't merge yet! I'm using this PR as a way to run a check of all the lessons that don't have a `review-ticket` entry in their YAML metadata re #812

### CODE REVIEW

**Comment by arojascastro** [comment]
Hoping to do this task next weeeknd. Sorry 😸

**Comment by arojascastro** [comment]
Done with translations. Ready to merge?

**Comment by mdlincoln** [comment]
Before we merge, I want to add code to display the links on the lesson page - this will mean all the links will be automatically checked by our link checker :)

**Comment by mdlincoln** [comment]
I'll be working on that a bit this morning.

**Comment by mdlincoln** [comment]
Examples of peer-review icon links:

English review with ticket: https://deploy-preview-816--ph-dev.netlify.com/lessons/getting-started-with-mysql-using-r

English review without ticket (for old lessons): https://deploy-preview-816--ph-dev.netlify.com/lessons/working-with-web-pages

Spanish review with ticket: https://deploy-preview-816--ph-dev.netlify.com/es/lecciones/introduccion-a-bash

**Comment by arojascastro** [comment]
Beautiful!

**Comment by mdlincoln** [comment]
If someone can approve this PR that would be nice :) I'll still hold off on merging for a few more days just to collect any additional feedback from the group.

**Review by arojascastro — APPROVED** [review]
very good

**Comment by acrymble** [comment]
Thanks @mdlincoln. I love it. Is it possible to make the second icon blue, but leave the words grey? At the minute I just wonder if it sends the message that those older lessons weren't peer reviewed because I think we sometimes associate grey with "no".

**Comment by mdlincoln** [comment]
I'll look at it in the next few days @acrymble

**Comment by mdlincoln** [comment]
How's this?

screenshot-2018-5-12 downloading web pages with python

**Comment by acrymble** [comment]
ya that's great.

**Pull request merged**
