### PR TITLE
Generate team history from author metadata

### LINKED ISSUE #702: Generate project team history via data files
Instead of having to maintain these manually on two separate pages, we should be able to list start/end years in the authors metadata so this stays up to date.

### PR DESCRIPTION
**Pull request by mdlincoln**
Closes #702

### CODE REVIEW

**Comment by mdlincoln** [comment]
@arojascastro @vgayolrs @mariajoafana @jamotilla @jenniferisasi right now the public list on the Spanish page uses the term "Present" - if we want to change that, you can edit this line in the snippets file (make sure to commit it to the `automated_project_history' branch so it gets added to this PR):

https://github.com/programminghistorian/jekyll/blob/230a11adfd867d9f15a2f2cc02eb8e0f136d3730/_data/snippets.yml#L222

**Comment by arojascastro** [comment]
Ok, thanks @mdlincoln I'll translate that snippet, but first of all we need to merge your brachn so I will approve this now.

**Review by arojascastro — APPROVED** [review]

**Comment by arojascastro** [comment]
Translate here da97760572f412f7e1e75a05588134d1de3fd57b

**Comment by mdlincoln** [comment]
Reminder @arojascastro - please add the translations onto the same PR, so that we can test and view all the changes before merging.

**Pull request merged**
