### PR TITLE
Issue 2572

### LINKED ISSUE #2572: Adding a new IPP to en/supporters, es/colaboradores, fr/nos-soutiens, pt/apoiadores
We have a new IPP! 🎉  The **University of Lancaster Library** have joined us!

### PR DESCRIPTION
**Pull request by anisa-hawes**
I am adding a new IPP to en/supporters, es/colaboradores, fr/nos-soutiens, pt/apoiadores

Closes #2572 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [ ] Assign at least one individual or team to "Reviewers"
  - [ ] ~~if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description~~
- [x] Add the appropriate "Label"
- [ ] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Hmm... The build is failing due to a 'broken' link within the lesson  /fr/lecons/intro-aux-bots-twitter.

http://cmuems.com/2015b/tracery-twitterbots/ >> upon visiting that page, I am encountering a security warning...

This link also appears in /en/lessons/intro-to-twitterbots, so it will need to be fixed/updated in both places.

**Comment by anisa-hawes** [comment]
I'm not certain what to suggest here. I'm unable to move past the security warning, and have tried several different browsers.

This link is one of several provided by the author to Other Bot Tutorials/Autres tutoriels et ressources sur les bots, and I think our best option may be to remove this from the list of suggested links?

**Comment by jenniferisasi** [comment]
> This link is one of several provided by the author to Other Bot Tutorials/Autres tutoriels et ressources sur les bots, and I think our best option may be to remove this from the list of suggested links?

I've tried to enter the site as well and it's not possible... so I think this is a good option as well.

**Comment by spapastamkou** [comment]
Agree too.

**Pull request merged**
