### PR TITLE
3 members stepping down - Issue 1967

### LINKED ISSUE #1967: FDL, Victor and Antonio leaving the team technical details
This issue is now modified to organize @fdlaramee, @arojascastro and @vgayolrs 's departure from the team. 

- [x] Remove Google Groups access (@jenniferisasi)  
- [x] Remove Google Analytics access (@acrymble)
- [x] Remove Github Jekyll access (@ZoeLeBlanc)
- [x] Remove from ProgHist Ltd register of members (@drjwbaker)
- [x] Remove Twitter access (@jenniferisasi)
- [x] Change team: true to team: false, and add team_end: YYYY to the  _data/ph_authors.yml file to remove the person from the Project Team page (@spapastamkou )
- [x] Check that they have no open issues assigned to them on either the Jekyll repository or the Submissions Repository (@spapastamkou ).
- [x] Review service integrations page to ensure that they do not have any associated integrations tied to their accounts ~(@mariajoafana)~ extraordinarily reviewed by @spapastamkou . 

~~Please edit if I forget something. 
@rivaquiroga Please let me know if you want me to update at the same time ph_authors.yml for Antonio as well.~~

### PR DESCRIPTION
**Pull request by spapastamkou**
*Updates files, web site for FDL, Antonio, Victor stepping down. Closes #1967*

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Review by rivaquiroga — APPROVED** [review]

**Comment by spapastamkou** [comment]
Thanks @rivaquiroga ! I'll wait for @ZoeLeBlanc and @mariajoafana as per #1967 and then I will merge.

**Review by ZoeLeBlanc — APPROVED** [review]
Looks good to me! Maybe double check that it's still update to date with gh-pages before you merge but otherwise everything looks good to me 👍

**Comment by spapastamkou** [comment]
Thanks @ZoeLeBlanc! I am not very clear if @fdlaramee has been removed from ghub, can you please confirm to be sure?

**Comment by walshbr** [comment]
@ZoeLeBlanc took care of removing him I believe.

**Comment by spapastamkou** [comment]
@walshbr Yes, we are ok for this, thanks to @ZoeLeBlanc. Waiting for confirmation from @mariajoafana that she reviewed the service integrations page in #1967 and then I can update the branch and merge.  
Update note: I reviewed the service integrations page, so I can merge here now.

**Pull request merged**
