### PR TITLE
Issue 2341

### LINKED ISSUE #2341: Adding tested-date: to two lessons
I am adding a `tested-date:` field to the yaml headers of basic-text-processing-in-r and cleaning-data-with-openrefine, which I have worked through recently.

### PR DESCRIPTION
**Pull request by anisa-hawes**
I am adding a tested-date: field to the yaml headers of en/lessons/basic-text-processing-in-r and en/lessons/cleaning-data-with-openrefine, which I have worked through recently.

Closes #2341

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] ~~if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description~~
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Hello @programminghistorian/technical-team. I wonder if anyone has time to take a look at this? Checking the previews via Netlify, I don't see the Tested date in the lesson's header... I expected it to follow Published and Modified. Have I made a mistake in the yaml?

**Comment by ZoeLeBlanc** [comment]
Hi @anisa-hawes! Pretty sure I see the problem. We have a bit of weird convention where yaml fields in the data snippets have '-' (so in this case `tested-date`) but on the lesson yaml fields we use underscores '_'

So if you change `tested-date` to `tested_date` it should work (I'm like 95% sure 😅 ). 

This is probably a good indication that we should standardize this practice one way or another, and use either underscores or dashes... maybe once @jenniferisasi is back online she can chime in if she knows why we use both.

Anyways let me know if that doesn't fix things 😊

**Comment by jenniferisasi** [comment]
Here I am! So, turns out the tested-date field/info is not showing on the lessons that have it already in the yml file: 
- sustainable-authorship-in-plain-text-using-pandoc-and-markdown.md
- up-and-running-with-omeka.md
- creating-an-omeka-exhibit.md

So something else is going on here and not necessarily these two lessons. I proceed to investigate, I am 99% sure Zoe is correct: 
Screen Shot 2021-10-23 at 10 42 07 AM
On `_layout/lesson.html` the `tested_date` if-loop is looking for a `tested_date` field on yaml (page), while also looking for its `tested-date` snippet for the language of the lesson ( "tested, testeado, etc.") on `_data/snippets.yml`

Is it a requirement to do it like that? Because on another example, we use only `-` and not the `_`:
Screen Shot 2021-10-23 at 10 44 37 AM

I am going to change one of the lessons in this issue to confirm this "theory"; from there, we can decide/see if we can standarize this to all tested-date so it's less confusing? The loop nows to look on the metadata/yaml or snippets file so it shouldn't be an issue, right @ZoeLeBlanc?

**Comment by jenniferisasi** [comment]
Efectivamente, the lesson metadata has to say `tested_date`; if we can, I say we normalize it all to one or the other
Screen Shot 2021-10-23 at 10 58 59 AM

**Comment by anisa-hawes** [comment]
Hello @ZoeLeBlanc. Shall we update `_data/snippets.yml` to replace `tested-date` with `tested_date`? 
(Or the other way around? Does `_` or `-` make better sense to you?)

**Review by acrymble — APPROVED** [review]

**Pull request merged**
