### PR TITLE
New Lesson: Add analisis-redes-sociales-teatro-1

### LINKED ISSUE #3094: New ES lesson: Análisis de redes sociales de personajes teatrales (Parte 1)
I am opening this ticket to begin the process of publishing "Análisis de redes sociales de personajes teatrales (Parte 1)" by David Merino Recalde. Will ping @anisa-hawes if/when any issue arises.

### PR DESCRIPTION
**Pull request by jenniferisasi**
*Please summarise the reason for your Pull Request here*

Closes #3094

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Add the appropriate "Label"
- [x] If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above
- [x] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Assistant @anisa-hawes 
- [x] Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines), then assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR.

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Update: Jenn and I are coming back to this with fresh brains next week 🙂

**Comment by jenniferisasi** [comment]
Ah, @anisa-hawes I can't approve my own PR (of course). But I've checked the paragraph from which you took out the reference to the assets folder and it's all good to go!! THANKS!

**Comment by anisa-hawes** [comment]
Hola @jenniferisasi! 

I can approve, but I have had another thought. Going forwards, I'd like us to aim to avoid any screenshots of tabular data so that we can improve the accessibility of our lessons. Rather, we should be replacing them with data tables formatted in Markdown (the ones I'd suggest replacing are figures 4., 5., 6., 7., 8.). The tables in this lesson are simple, so I've prepared these quickly. 

If you agree, I'll slot these in and remove the figures (and the corresponding `.png` files in /images) in those places. There might be some tiny adjustments to the Spanish, so I'll share a link to my commit and you can check any changes I make.

| id | label | atributo1 | atributo2 |
|----|-------|-----------|-----------|
| 1 | Nodo1 | --- | --- |
| 2 | Nodo2 | --- | --- |
| 3 | Nodo3 | --- | --- |

|       | 1 | 2 | 3 | 4 | 5 | 6 |
|-------|---|---|---|---|---|---|
| **1** | 0 | 9 | 0 | 0 | 0 | 0 |
| **2** | 4 | 0 | 0 | 0 | 0 | 0 |
| **3** | 0 | 0 | 0 | 0 | 0 | 0 |
| **4** | 0 | 0 | 0 | 0 | 0 | 0 |
| **5** | 0 | 0 | 0 | 0 | 0 | 0 |
| **6** | 0 | 0 | 0 | 0 | 0 | 0 |

| id | label | género | función |
|----|-------|--------|---------|
| 1 | Belisa | Mejuer | Dama |
| 2 | Finea | Mejuer | Criada |
| 3 | Celia | Mejuer | Dama |
| 4 | Lucinda | Mejuer | Dama |
| 5 | Fabia | Mejuer | Criada |
| 6 | Don Juan | Hombre | Galán |
| 7 | Tello | Hombre | Criado |
| 8 | Octavio | Hombre | Galán |
| 9 | Julio | Hombre | Criado |
| 10 | Conde Enrique | Hombre | Galán |
| 11 | Fernando | Hombre | Criado |

|  | Belisa | Finea | Celia | Lucinda | Fabia | Don Juan | Tello | Octavio | Julio | Conde Enrique |  Fernando |  
|--|--|--|--|--|--|--|--|--|--|--|--|
| Belisa |  |  |  |
| Finea  |  |  |  |
| Celia  |  |  |  |
| Lucinda |  |  |  |
| Fabia |  |  |  |
| Don Juan |  |  |  |
| Tello |  |  |  |
| Octavio |  |  |  |
| Julio |  |  |  |
| Conde Enrique |  |  |  |
| Fernando |  |  |  |

|  | Belisa | Finea | Celia | Lucinda | Fabia | Don Juan | Tello | Octavio | Julio | Conde Enrique |  Fernando |  
|--|--|--|--|--|--|--|--|--|--|--|--|
| Belisa |  | 1 |  |
| Finea  | 1 |  |  |
| Celia  |  |  |  |
| Lucinda |  |  |  |
| Fabia |  |  |  |
| Don Juan |  |  |  |
| Tello |  |  |  |
| Octavio |  |  |  |
| Julio |  |  |  |
| Conde Enrique |  |  |  |
| Fernando |  |  |  |

**Comment by jenniferisasi** [comment]
Super @anisa-hawes! No problem, I'll keep an eye on this PR :)

**Comment by anisa-hawes** [comment]
Hello @jenniferisasi. I think the tables are good (my `table-wrappers` are working as expected now! 😅 We needed a line break before the closing `</div>` tags).

If you have a moment to review the edits here, you will note that the only line of Spanish I adjusted is line 355: https://github.com/programminghistorian/jekyll/pull/3095/commits/2412e50ef0b27231fbe4bef78f89d2f973cec101

**Comment by jenniferisasi** [comment]
Line 355 looks good, @anisa-hawes!

**Review by anisa-hawes — APPROVED** [review]

**Pull request merged**
