### PR TITLE
Create 2017-12-30-noticias-PH-espanol.md

### PR DESCRIPTION
**Pull request by mariajoafana**
NOTICE: Are you attempting to submit a lesson to the Programming Historian? We no longer accept lesson submissions by pull request to this repository. Please consult our [guidelines for submitting a lesson](http://programminghistorian.org/new-lesson-workflow) for further instructions.

If your pull request instead concerns some issue with the formatting or functioning of our site, or some error in an existing lesson, please see our technical contribution guidelines: https://github.com/programminghistorian/jekyll/wiki/Making-technical-contributions

### CODE REVIEW

**Comment by arojascastro** [comment]
Gracias @mariajoafana! Solo dos cositas: 
- software --> programa
- Así mismo --> Asimismo

 ¿Lo cambias tú o lo apruebo y luego lo cambiamos?

**Comment by acrymble** [comment]
An image would make it snazzier.

**Comment by mariajoafana** [comment]
This is the image for the post
phespanol2017

**Review by mdlincoln — CHANGES_REQUESTED** [review]
Image file needs to be added to `mariajoafana-patch-1` branch

**Review by mdlincoln — APPROVED** [review]
Thanks!

**Pull request merged**
