### PR TITLE
Add Matthew Lincoln to editorial team

### PR DESCRIPTION
**Pull request by mdlincoln**
Also adds additional contact links

### CODE REVIEW

**Comment by ianmilligan1** [comment]
Welcome aboard!!! 🎉

**Comment by drjwbaker** [comment]
Woo!

**Comment by acrymble** [comment]
http://programminghistorian.org/es/equipo-de-proyecto can you do Spanish?

**Comment by drjwbaker** [comment]
A PR is basically an official announcement, right :)

**Comment by amandavisconti** [comment]
@mdlincoln Yay! Welcome!

**Pull request merged**
