### PR TITLE
Sequence in Python lessons

### PR DESCRIPTION
**Pull request by jenniferisasi**
Add sequence metadata field and numbers for the Python tutorials in Spanish to render series banner per issue #1945 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
- [x] Add the appropriate "Label"
- [ ] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

### CODE REVIEW

**Comment by jenniferisasi** [comment]
Mistakes I'm catching on the preview: 
- [x] "Esta lección es parte de una serie de -" is missing "14 lecciones" there (the last lesson, 15th, on the series, is not translated). 
- [ ] lesson 1 doesn't have the link for "next lesson"

These two errors will involve editing the `lesson.html` and probably an error in `{{ page.series_total }}` somewhere for ES; where is that series_total? Look for it. 
half-a-minute later [palm on face emoji]: it is on the metadata in the lessons.

snippets.yml is correct

~~Travis error, some broken link I'll look for:~~
~~- ./_site/posts/Uses-Of-The-Programming-Historian.html~~
~~469  *  External link http://torget.us/HIST5100/syllabus/ failed: 404 No error~~

**Review by rivaquiroga — DISMISSED** [review]

**Comment by acrymble** [comment]
Is there a reason this is stuck? @jenniferisasi

**Comment by walshbr** [comment]
This is ready to be merged, right @jenniferisasi?

**Comment by rivaquiroga** [comment]
Thanks a lot for this! 
Two comments:
- In the case of the first lesson of the series, there is no "siguiente lección" (next lesson) link. 
- Now ES appears as original, not EN

Captura de pantalla de 2021-03-25 11-42-31

**Comment by walshbr** [comment]
@rivaquiroga your second point should just be because the branch is out of date - I updated it with what is now in gh-pages, so give it a look when it finishes building. Should be fixed by another PR Zoe merged in this morning.

**Comment by walshbr** [comment]
Those two issues should be fixed now

**Comment by rivaquiroga** [comment]
Lesson 1 looks great now :tada:
But I'm still seeing ES as original 

Captura de pantalla de 2021-03-25 12-20-17

**Comment by walshbr** [comment]
ok NOW it should work when it rebuilds - sorry for some reason the merge didn't pull everything in. I might have done it incorrectly.

**Comment by rivaquiroga** [comment]
Looks awesome! Thanks @walshbr and @jenniferisasi 🎉

**Review by rivaquiroga — APPROVED** [review]

**Comment by ZoeLeBlanc** [comment]
Hi @jenniferisasi anything @programminghistorian/technical-team can do to help close this PR? Seems like it's working but might need to get refreshed and reviewed again with latest gh-pages branch.

Happy to help so just lmk 😊

**Comment by jenniferisasi** [comment]
Oh @ZoeLeBlanc yes, please, update this branch to the newest version cos I can't do it. Thanks!

I think it was stuck because it was already outdated? I don't know, I might have also just forgotten about this.

**Pull request merged**
