### PR TITLE
Update Supporters - Jisc / TNA

### PR DESCRIPTION
**Pull request by acrymble**
Adds the project support from Jisc / TNA to our /supporters pages.

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by jenniferisasi** [comment]
This was Daniel's article. Looks like they changed the entire journal elsewhere, but it says "provisionally". 
Screen Shot 2021-07-30 at 11 28 47 AM

I can't find the article in their new link, this is where I hit the wall http://www.educaonline.latec.ufrj.br maybe @DanielAlvesLABDH knows something.

**Comment by acrymble** [comment]
> This was Daniel's article. Looks like they changed the entire journal elsewhere, but it says "provisionally".
> Screen Shot 2021-07-30 at 11 28 47 AM
> 
> I can't find the article in their new link, this is where I hit the wall http://www.educaonline.latec.ufrj.br maybe @DanielAlvesLABDH knows something.

Didn't this happen like a week ago? I'm getting deja vu.

**Comment by DanielAlvesLABDH** [comment]
Dear Adam and Jennifer, that is probably related with the fact that a Brazilian server that kept central academic info burn last week. I think the journal was on that server...

**Comment by jenniferisasi** [comment]
Oh no @DanielAlvesLABDH that's terrible. Specially (adding to it) because I saw that the Cinemateca burnt yesterday too 😭 

I think for now it is best then if we delete the link.

**Comment by acrymble** [comment]
@DanielAlvesLABDH do you want to host a copy on our servers?

**Comment by DanielAlvesLABDH** [comment]
> @DanielAlvesLABDH do you want to host a copy on our servers?

Dear Adam, sorry for the delayed response. The article can be found also here: https://novaresearch.unl.pt/files/32228034/Ensinar_Humanidades_Digitais.pdf

**Comment by jenniferisasi** [comment]
I will approve and merge this once #2229 is merged.

**Review by anisa-hawes — APPROVED** [review]
Super!

**Pull request merged**
