### PR TITLE
Pt color change

### LINKED ISSUE #2072: Accessibility Audit
While poking around with #1524 the tech team, we were discussing some contrast issues on the site. I ran Chrome's lighthouse on our site and found a number of accessibility issues. We'll need to poke around more closely to get a clear sense, so this is just a ticket to document the accessibility audit for the site. We should probably open separate tickets downstream for actually fixing particular issues.

### PR DESCRIPTION
**Pull request by ZoeLeBlanc**
This PR slightly shifts PT color for accessibility contrast (thanks @walshbr for doing all the hard work on this one) and also closes #2072 with the remaining accessibility audit issues being temporarily archived until we start rebuilding the site infrastructure.

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [ ] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by jenniferisasi** [comment]
Screen Shot 2021-09-14 at 3 41 08 PM

How do we change the color of the "sticker"?

**Comment by ZoeLeBlanc** [comment]
Ohh darn just looking at this now and realizing that I made the sticker in Photoshop, so think I'm gonna have to track down this file and update it 😅. I'll try to get to that this week!

**Comment by ZoeLeBlanc** [comment]
Small update but I'm in the process of switching computers and switching my adobe account. If anyone has access to photoshop I can likely share the original file for the color tweaking, but I'll need likely two more weeks to get to this since I have to setup the new laptop from scratch 😭 .

**Comment by DanielAlvesLABDH** [comment]
Dear @ZoeLeBlanc could you send me the file? I think I can make the change with the help of a colleague here in Lisbon. Thanks!

**Comment by rivaquiroga** [comment]
@ZoeLeBlanc, is this file, right? https://github.com/programminghistorian/jekyll/blob/pt-color-change/images/logos/ph-pt.svg

**Comment by rivaquiroga** [comment]
I left a version with the new color in this brach in case that was the file: https://github.com/programminghistorian/jekyll/tree/pt-logo-background/images/logos

**Comment by ZoeLeBlanc** [comment]
Thanks for this @rivaquiroga ! I did have the original photoshop file somewhere but I can't find it, so I think that svg is our best bet. Also looks like you maybe already did this fix? If yes then extra thank yous 🙏🏽  and feel free to push up into this PR or create a new one 👍🏽

**Review by DanielAlvesLABDH — APPROVED** [review]
Thanks for this @rivaquiroga

**Comment by rivaquiroga** [comment]
I just pushed the changes to this branch. Looks good now.

**Comment by DanielAlvesLABDH** [comment]
Hello @ZoeLeBlanc! Can we merge this?

**Comment by ZoeLeBlanc** [comment]
Looks great to me@DanielAlvesLABDH 👍🏽 (I can't approve officially because I opened this PR 😅 ) but I"ll go ahead and merge it in!

**Pull request merged**
