### PR TITLE
Update Melton affiliation info

### PR DESCRIPTION
**Pull request by svmelton**
Updating my affiliation info with my new position. 

Dear @programminghistorian/french-team, @programminghistorian/spanish-team, @programminghistorian/portuguese-team: could you please translate the affiliation when you have a chance? Many thanks!   

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Review by anisa-hawes — DISMISSED** [review]

**Comment by anisa-hawes** [comment]
Thank you, @svmelton! And congratulations! 

I've approved this, but will await translations before merging.

**Comment by anisa-hawes** [comment]
Hello Gwenaëlle @InesSalome and Matthias @matgille, Might either of you have a moment to translate Sarah's new bio?

> Sarah Melton is a Product Education Strategist at SproutSocial.

Thank you!

**Comment by matgille** [comment]
`Sarah Melton est responsable de la stratégie formation produit chez SproutSocial` ? 
`Sarah Melton est responsable formation produit chez SproutSocial` ? 

I think the first possibility is more litteral but a bit less natural. I've found the second one in job postings on the internet, so it's used, but we lose the "Strategist" and I don't know if "*responsable*" (meaning here 'in charge of') would be a good translation of it. What do you think @svmelton ? Maybe the first option is better after all.

Any thought  @InesSalome ?

**Comment by anisa-hawes** [comment]
Hello @joanacvp. I hope you're well! May I ask if you have time to translate Sarah's new bio?

> Sarah Melton is a Product Education Strategist at SproutSocial.

Thank you!

**Comment by joanacvp** [comment]
Hello @anisa-hawes. It can be like this:

Sarah Melton desenvolve a Estratégia de Produtos Educativos na SproutSocial.

**Comment by anisa-hawes** [comment]
Thank you so much, @joanacvp!

**Comment by anisa-hawes** [comment]
Hello @rivaquiroga and @svmelton. Shall we add the DOIs for #2515 to this PR?

**Comment by rivaquiroga** [comment]
@anisa-hawes, sure! The DOI for the ES translation is `10.46430/phes0057`

**Comment by svmelton** [comment]
EN DOI is `10.46430/phen0097`!

**Review by anisa-hawes — APPROVED** [review]

**Comment by rivaquiroga** [comment]
@anisa-hawes, FYI, I already updated the Twitter bot with the new DOI for the XML lesson translation to Spanish. Once both links are active, we should probably announce on Twitter that the lesson has been updated.

**Comment by anisa-hawes** [comment]
Thank you, @rivaquiroga! I didn't think of that! An important detail! I've now updated the EN cells of our Twitter Bot Google Sheet. 

It seems like the EN DOI hasn't yet been activated, so I will wait until it is live then prepare a Tweet to promote the update! I'll collaborate with @jenniferisasi to create Tweets in both ES and EN.

**Comment by rivaquiroga** [comment]
@anisa-hawes, the link will be activated once @svmelton informs Library of Sussex that the lesson is now published and the XML updated.

**Comment by svmelton** [comment]
Should be submitted and live now @anisa-hawes!

**Comment by anisa-hawes** [comment]
Super! Thank you both!

**Pull request merged**
