### PR TITLE
Update ph_authors.yml

### LINKED ISSUE #2898: Orientation tasks for Alexandre Wauthier
This Issue represents introductory tasks for the orientation of **Alexandre Wauthier** @AlexandreWa who is a new member of our French editorial team.

## Bienvenue

Bienvenue, Alexandre! Welcome to the _Programming Historian_ Project Team! ✨ 

## What the PH team will do:

- [x] #2916
- [x] @anisa-hawes will introduce you to our Jekyll repository
- [x] @anisa-hawes will introduce you to our ph-submissions and editorial workflow
- [x] @ZoeLeBlanc will add you to our GitHub organisation so you can contribute to the site
- [x] @anisa-hawes will invite you to our Google Group, Slack and Discord communities

## What you need to do:

- [x] Provide/set up a Google-enabled email address for our Google Group
- [x] Provide/set up a GitHub username for our Submissions Repository
- [x] Read the [author, reviewer and translator guidelines](https://programminghistorian.org/fr/contribuer) pages of our website 
- [x] Read the [Privileges and Responsibilities of Membership page of our Wiki](https://github.com/programminghistorian/jekyll/wiki/Privileges-and-Responsibilities-of-Membership)
- [x] Read the [Code of Conduct](https://github.com/programminghistorian/jekyll/blob/gh-pages/CODE_OF_CONDUCT.md)

## The Culture of our Project

We have invited you to join the team because we value your opinions. We encourage all of our editors to contribute to discussions on GitHub or via email, and to civilly express their views, even if they disagree with any or all other members. This right to express one's opinions is central to our project. Please take this to heart.

### LINKED ISSUE #2916: @anisa-hawes will help you to add your profile to the Project Team pages of our website

### PR DESCRIPTION
**Pull request by AlexandreWa**
Adding Alexandre's profile to the Project Team pages.

Closes #2898
Closes #2916 

### Checklist

- [X] Assign yourself in the "Assignees" menu
- [X] Add the appropriate "Label"
- [x] If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above
- [x] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Assistant @anisa-hawes 
- [x] Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)
- [X] Assign at least one individual or team to "Reviewers"
- [ ] ~~if the text needs to be translated, please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines), then assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR.~~

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Dear @AlexandreWa.

I've made a few small adjustments to the `ph_authors.yml` file. On our Project Team pages, we use the `affiliation` field to briefly name the institution or organisation where members are based. The `bio:` field is more descriptive, but is reserved for Author Bio / À Propos de l'auteur(e) at the footer of lessons.

I also uploaded your avatar portrait to this PR so that we make all the changes in one push – the `ph_authors.yml` file is directly calling upon those `.png` images.

**Comment by anisa-hawes** [comment]
Please let me know if you're happy with your affiliation as it displays now, @AlexandreWa?

You can view the Netlify preview of the staged changes by [clicking 'Details' (above) at the right-hand side of netlify/ph-preview/deploy-preview — Deploy Preview ready!](https://deploy-preview-2918--ph-preview.netlify.app/)

(I'm not 100% clear on the relationship between the Humathèque, Campus Condorcet and the Centre national de la recherche scientifique française (CNRS). If you were telling someone where you worked, would you simply say Humathèque, Campus Condorcet?)

**Comment by spapastamkou** [comment]
@anisa-hawes This was also my case in my previous affiliation and it might help you understand better the articulation between the CNRS, who is the permanent employer, and the institution/research unit/ library in which the agent (I, Alexandre, and many others!) may be assigned. As far as I was concerned, the CNRS was my affiliation in ph-authors and I had clarified in the bio the unit in which I was assigned as follows: 
*Sofia Papastamkou est docteure en histoire et ingénieure d'études en humanités numériques au CNRS. Elle est affectée à la Maison européenne des sciences de l'homme et de la société Lille Nord de France.*
This way, everyone is visible (and happy):-)

**Comment by spapastamkou** [comment]
(and welcome @AlexandreWa!)

**Comment by anisa-hawes** [comment]
Thank you @spapastamkou. In that case, I think what we have seems right: _Alexandre Wauthier: Centre national de la recherche scientifique française (CNRS), France_.

If Alexandre authors a lesson in the future, his bio will be displayed:  _Alexandre Wauthier est ingénieur d'études au Centre national de la recherche scientifique française (CNRS). Il est chargé du traitement des donnnées scientifiques et bibliothécaire à l'Humathèque du Campus Condorcet._

**Review by anisa-hawes — APPROVED** [review]

**Comment by AlexandreWa** [comment]
Dear @anisa-hawes and @spapastamkou ,

Thanks for your answers! I agree for the full bio presentation _Alexandre Wauthier est ingénieur d'études au Centre national de la recherche scientifique française (CNRS). Il est chargé du traitement des donnnées scientifiques et bibliothécaire à l'Humathèque du Campus Condorcet_ (be careful with "do**nn**ées" misprint).

Nonetheless, I suggest another type of short presentation, inspired by @marie-flesch 's, shortly mentionning CNRS : _Alexandre Wauthier: Ingénieur d'études et bibliothécaire, Humathèque, Campus Condorcet-CNRS, France_, what do you think ?

**Pull request merged**
