### PR TITLE
publishing scalable reading of structured data

### PR DESCRIPTION
**Pull request by hawc2**
Starting a pull request for Scalable Reading of Structured Data: https://github.com/programminghistorian/ph-submissions/issues/419

This branch will need a rebase and some other finishing touches @anisa-hawes

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Looks good @hawc2! The re-base is done, and I've added in `lesson-partners:` + `partnership-url:` to the YAML header. 

Only other thing is that I notice you’ve uploaded the same gallery + original images as used in the last lesson you published by mistake.

**Comment by hawc2** [comment]
good catch @anisa-hawes, but looks like that's a problem in the ph-submissions repo too. Not sure how this happened, but it looks like different people uploaded each image, so maybe it's just a coincidence?

I can ping people on that issue ticket to let them know

**Comment by anisa-hawes** [comment]
Oh! 

How about something like this @hawc2: https://flic.kr/p/x1w8h9?

Or either of these, which are already square format: https://flic.kr/p/osQ26W or https://flic.kr/p/wa8bzd.

**Comment by hawc2** [comment]
Fine by me. @drjwbaker?

**Comment by anisa-hawes** [comment]
@drjwbaker [is happy with the honeycomb](https://github.com/programminghistorian/ph-submissions/issues/419#issuecomment-1278616531).  So I've update the `avatar_alt:` and now this is ready to publish.

**Review by anisa-hawes — APPROVED** [review]

**Pull request merged**
