### PR TITLE
Issue 1525 Lesson Sequence Reporting

### LINKED ISSUE #1525: Progress reporting for Lesson Sequences
A suggestion today from a workshop I was hosting.
For lessons that are part of a sequence, provide visual indicators of how far along you are in the series. For example (lesson 2 of 4).

This mostly relates to the Python and Geospatial series.

Assigning to @amsichani as Education manager

### PR DESCRIPTION
**Pull request by ZoeLeBlanc**
*add the reason for your pull request here*
Add sequence reporting to lessons for easier user navigation. This PR closes #1525.

### Checklist

- [X] Assign yourself in the "Assignees" menu
- [X] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [X] Add the appropriate "Label"
- [X] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [X] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [X] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Review by walshbr — CHANGES_REQUESTED** [review]
This seems good @ZoeLeBlanc, but it should probably also implement the lesson sequence ordering on the Python series as well.

**Comment by ZoeLeBlanc** [comment]
Thanks for the feedback @walshbr ! I wasn't sure how many lesson sequences there are but I can add the python one in. Do you know if there's others??

**Comment by ZoeLeBlanc** [comment]
Just added the Python Sequence @walshbr. Would love your thoughts on the following 👇 

Currently our solution is pretty much to hand code all sequence information. I think this works fine for shorter sequences (3-5 lessons), but the Python sequence is 15 lessons. This means any change in the lessons leaves the code very brittle.

So a few questions:
- should we come up with a programmatic solution to calculate total number of lessons? 
- do we want to have the ability to select a sequence and see the list of lessons?
- how do we want to deal with translations? Are sequences language-independent?

For now we could continue with this solution and revisit for future sequences, but would appreciate any thoughts 🙏

**Comment by acrymble** [comment]
@ZoeLeBlanc I dont' know if you've noticed yet but translations don't always happen in sequence order. This becomes even more difficult in those cases.

**Comment by walshbr** [comment]
I'd say we shouldn't worry about programmatically counting the lesson sequences. I think the lesson sequences are pretty rare, so it feels like we won't likely have many others to deal with in the future. Famous last words?

I'm inclined to say we should have them remain handcoded and that the language teams can be responsible for tracking which elements of the sequence have been translated. Does that seem reasonable?

**Comment by ZoeLeBlanc** [comment]
Thanks for the feedback @acrymble and @walshbr !

I think for now what you propose is the path of least resistance Brandon (fingers crossed it doesn't come back to bite us) so I'm inclined to go with it as well. If you don't mind looking over what I pushed up and giving me approval, then I can get this merged in 😊

**Comment by walshbr** [comment]
Yeah to date I have had I want to say four authors with big dreams of putting together lesson sequences, but they never materialize (understandably - it's a lot of work to author one less, let alone several). I think we can always revisit this later if it becomes an issue. I'd add that suggestion of yours to the backlog of tech feature ideas on the tech team wiki.

Is it worth pinging the language teams before merging to let them know that they would need to do something like this for their lesson sequences as they translate? Similarly is probably something that should go in the metadata template for the author/editor guidelines. But you can always just merge this now and open a ticket for that documentation later, once we're allowed to edit those docs again.

**Review by walshbr — APPROVED** [review]

**Pull request merged**
