### PR TITLE
Prepação para publicação da tradução Reconhecimento automático de manuscritos para o teste de idiomas não latinos

### LINKED ISSUE #3203: Preparando para publicar "Reconhecimento automático de manuscritos para o teste de idiomas não latinos"
Issue para publicação da tradução da lição "Reconhecimento automático de manuscritos para o teste de idiomas não latinos".

### PR DESCRIPTION
**Pull request by ericbrasiln**
Preparação para a publicação da tradução da lição "Reconhecimento automático de manuscritos para o teste de idiomas não latinos" Closes #3203 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Add the appropriate "Label"
- [x] If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above
- [x] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Manager @anisa-hawes 
- [x] Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)
- [X] Assign at least one individual or team to "Reviewers"
  ~~- [ ] if the text needs to be translated, please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines), then assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR.~~

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Great to collaborate with you today, @ericbrasiln! ✨ 

This looks wonderful! 

If you're happy with it, we will publish tomorrow 🙂

**Comment by ericbrasiln** [comment]
Yeah! I guess everything is fine!

**Comment by anisa-hawes** [comment]
Super! Thank you, @ericbrasiln!

As it is late in the day here in the UK, I will publish tomorrow when we can coordinate with colleagues at Sussex to activate the DOI. I appreciate your patience, and am looking forward to publishing this ✨

**Review by anisa-hawes — APPROVED** [review]
Congratulations on publishing this, @ericbrasiln! 

I'll update you when the DOI has been activated, and we've launched the promotions on social media. ✨

**Pull request merged**
