### PR TITLE
Add global roles

### PR DESCRIPTION
**Pull request by rivaquiroga**
For https://github.com/programminghistorian/jekyll/issues/1329: adding global roles descriptions to `teamroles.yml` and labels to`ph_authors.yml`.
French translation is missing. @spapastamkou, can you help me with that?

### CODE REVIEW

**Review by acrymble — CHANGES_REQUESTED** [review]
Thanks @rivaquiroga. Can we avoid the use of acronyms that some readers won't know? You've used "DH" and "HD" to represent digital humanities. I suspect we have many readers who don't know the acronym.

**Comment by rivaquiroga** [comment]
Done!

**Review by acrymble — DISMISSED** [review]

**Comment by acrymble** [comment]
@spapastamkou can you please arrange for someone to translate these 2 lines into French?

Coordinates the Global Team and facilitates communication with other Programming Historian teams.
Managing new global initiatives, as well as trying to improve the cultural and linguistic diversity of the team, our lessons, and of participation in Digital Humanities more generally.

**Comment by acrymble** [comment]
@spapastamkou @mpuren @fdlaramee this pull  request is just waiting for the French translation of 2 sentences. Can one of you help please?

Coordinates the Global Team and facilitates communication with other Programming Historian teams.
Managing new global initiatives, as well as trying to improve the cultural and linguistic diversity of the team, our lessons, and of participation in Digital Humanities more generally.

**Comment by spapastamkou** [comment]
Done, but the travis build fails because of dead links in a blogpost (had already tried to replace them with Internet archive links but some of them do not exist as I commented in PR #1390). I open a ticket.

**Comment by mdlincoln** [comment]
I'll update this based on the other PR in a moment

**Review by mdlincoln — APPROVED** [review]

**Review by spapastamkou — APPROVED** [review]

**Pull request merged**
