### PR TITLE
Issue 2612

### PR DESCRIPTION
**Pull request by anisa-hawes**
I am testing to find the liquid syntax needed to add alt text to figure images. I have added alt text to Figure 1 (para.86) of en/lessons/interactive-text-games-using-twine.md

This test is linked to resolving #2612.

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [ ] Assign at least one individual or team to "Reviewers"
  - [ ] ~~if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description~~
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Inspecting live pages on our website via the console, I see that the alt text is reverting to caption text, where there is no alt provided.

I was hoping to use this ^ test be able to check how new alt text I've entered appears in the console… But I'm unable to inspect elements in the console via the Netlify Preview. 

Meanwhile, trying and failing to get a grip on VoiceOver for Mac.

**Comment by ZoeLeBlanc** [comment]
Just did an update to the figure.html so the `alt` tag renders. It works with the screen reader extension on Chrome, but one thing that we might need to change is how we render the alt text for the Twine lesson. Right now it includes some markdown styling but the screen reader will read that directly so italics becomes asterisks and if we try to render it as html it will read the tags. So I would recommend removing those styles unless they are very important in the alt text but wanted to get your take @anisa-hawes before I went ahead and removed them.

**Comment by jenniferisasi** [comment]
Oooooh, we had to edit the file `figure.html`, I didn't think of that!

Given that formatting is not displayed visually (cos that's what alt text is for) I say markdown symbols should be avoided.

**Comment by anisa-hawes** [comment]
Thank you so much for your input here, @ZoeLeBlanc!  I've removed the Markdown styling from the alt-text I've introduced. I agree that we should agree to exclude any styling from alt-text going forwards.

**Review by jenniferisasi — APPROVED** [review]

**Pull request merged**
