### PR TITLE
Add new Patron level subscriber

### PR DESCRIPTION
**Pull request by drjwbaker**
Just added a single name to EN/ES/FR 'Support Us' page. No translation required.

### CODE REVIEW

**Review by acrymble — APPROVED** [review]

**Comment by acrymble** [comment]
sorry this is  being held up  by a mistake I made. I will fix it asap.

**Comment by drjwbaker** [comment]
Build fail?

**Comment by acrymble** [comment]
Yes, build fail my fault.

**Comment by drjwbaker** [comment]
Looks like we need to wait for something else to merge?

**Pull request merged**
