### PR TITLE
Newsletter End 2019

### PR DESCRIPTION
**Pull request by jenniferisasi**
Uploading files (images and md) for latest newsletter, end of 2019.

### CODE REVIEW

**Review by mdlincoln — DISMISSED** [review]
Looks great! So many good accomplishments to talk about 🎊

**Comment by jenniferisasi** [comment]
Need someone in the @programminghistorian/french-team to check on the FR version and it will be ready to go

**Comment by spapastamkou** [comment]
Working on it @jenniferisasi

**Comment by spapastamkou** [comment]
@jenniferisasi I would also propose to rename the FR file because in French "bulletin" is written with double l, and only for the sake of having a correct URL in this language. 
But this would differentiate this file from the files of the previous newsletters in FR. And overall this could of course be a small detail that maybe nobody will notice. Do as you think:)

**Comment by spapastamkou** [comment]
Fixed a broken link in a lesson that impeded the travis build.

**Comment by spapastamkou** [comment]
@jenniferisasi I checked the preview and the image does not display for the EN post, though ok for the FR and ES
PS: fixed

**Review by spapastamkou — DISMISSED** [review]

**Comment by jenniferisasi** [comment]
Thank you @spapastamkou for checking the language AND broken links. 

Let me change the name of the file to bulletin so that it is correct.

**Review by spapastamkou — APPROVED** [review]

**Pull request merged**
