### PR TITLE
Drjwbaker donations - updates FR nous-soutenir page

### PR DESCRIPTION
**Pull request by spapastamkou**
Updates FR 'support us' (nous soutenir) page as per merged #1504

### CODE REVIEW

**Review by grandjeanmartin — APPROVED** [review]

**Review by drjwbaker — APPROVED** [review]
Thank you!

**Comment by drjwbaker** [comment]
@spapastamkou For some reason this isn't showing on the live site https://programminghistorian.org/fr/nous-soutenir#donations @programminghistorian/technical-team: any ideas?

**Comment by walshbr** [comment]
@mdlincoln - I tried restarting the build on Travis and dumping my own cache/hard reloading, but neither got the thing to show up even though it's in the gh-pages repo. Do you have any ideas?

**Comment by spapastamkou** [comment]
To raise this pull request, I restored James' branch that had already been merged in PR #1504, updated it and then made a commit to it with the changes for the FR page. Maybe I should have created a separate branch, perhaps the problem comes from there?

**Comment by drjwbaker** [comment]
@walshbr @spapastamkou Do we just need to open a new PR to solve this problem?

**Comment by spapastamkou** [comment]
I am not very sure as to what to do but it is the only thing I can think of. I could try (this evening), @drjwbaker 
Also, found this in travis doc: https://docs.travis-ci.com/user/pull-requests/#my-pull-request-isnt-being-built

**Comment by walshbr** [comment]
That last sentence in that thing you linked to @spapastamkou didn't sound promising - "Restoring the branch of a merged pull request will not trigger a build, nor will pushing a new commit to a branch that has already been merged."

But I think merging a new PR should trigger a new build, and, since the file is already as you want it in the gh-pages repository it should get pulled in. I just merged #1548 since it was ready to see if that fixes the issue here. I'll report back.

**Comment by walshbr** [comment]
@drjwbaker @spapastamkou - I think that did it. Looks like https://programminghistorian.org/fr/nous-soutenir#donations is showing up on the main site now but ping me if it does not?

**Comment by drjwbaker** [comment]
Bingo

**Pull request merged**
