### PR TITLE
New lesson template to Author Guidelines #991

### LINKED ISSUE #991: New Lesson template
#972 update metadata block example, has made me realise we could simplify our author and editor guidelines quite a lot by just offering a template for people to use in new lessons. It could look like this:

```

title: ["YOUR TITLE HERE"]
collection: lessons
layout: lesson
slug: [LEAVE BLANK]
date: [LEAVE BLANK]
translation_date: [LEAVE BLANK]
authors:
- [FORENAME SURNAME 1]
- [FORENAME SURNAME 2, etc]
reviewers:
- [LEAVE BLANK]
editors:
- [LEAVE BLANK]
translator:
- [FORENAME SURNAME 1]
translation-editor:
- [LEAVE BLANK]
translation-reviewer:
- [LEAVE BLANK]
original: [LEAVE BLANK]
review-ticket: [LEAVE BLANK]
difficulty: [LEAVE BLANK]
activity: [LEAVE BLANK]
topics: [LEAVE BLANK]
abstract: [LEAVE BLANK]
---

# Contents

{% include toc.html %}

# First level heading

[CONTENT HERE. Please write formally, sustainably, and for a global audience.]

## Second level heading - with some examples of formatting

### Font Formatting:
*italic text*
**bold text**
`reserved words or file names` (eg "for loop", or "myData.csv")

### Links:
[a link to *Programming Historian*](http://programminghistorian.org)

### Images:
{% include figure.html filename="IMAGE-FILENAME" caption="Caption to image" %} - see https://programminghistorian.org/en/author-guidelines for more guidance on images.

### A Sample Unordered List

* Fruits
  * Apples
  * Oranges
  * Grapes
* Dairy
  * Milk
  * Cheese

### A Sample Ordered List

1. Finish tutorial
2. Go to grocery store
3. Prepare lunch

###A Sample Table:

| Heading 1 | Heading 2 | Heading 3 |
| --------- | --------- | --------- |
| Row 1, column 1 | Row 1, column 2 | Row 1, column 3|
| Row 2, column 1 | Row 2, column 2 | Row 2, column 3|
| Row 3, column 1 | Row 3, column 2 | Row 3, column 3|

### A Code Block:

```
Code block
```

### An End Note:

This is some text.[^1] 
This is some more text.[^2] 



# Endnotes
[^1] Properly formatted citation using Chicago Manual of Style
[^2] Properly formatted citation using Chicago Manual of Style

### PR DESCRIPTION
**Pull request by acrymble**
Closes #991 - New Lesson Template.

I have added the "new lesson template" markdown template to the English version of the Author Guidelines. I have also removed a few sections of that file that were redundant after the new template was inserted (how to write endnotes, how to add the metadata block). Finally, I moved a few sections around so that all sections about markdown were together, and information on writing sustainably and globally was after rather than in the middle.

I have NOT made changes to the Spanish file (which is actually different anyway because of information on translation). Can someone on the Spanish team please decide if they would like to update the Spanish guidelines as well?

### CODE REVIEW

**Comment by acrymble** [comment]
This has been waiting a few weeks for comment. I suspect that means the Spanish Team doesn't want to pursue this idea. If that's the case, can someone let me know? @mariajoafana @vgayolrs @jamotilla @jenniferisasi

**Comment by vgayolrs** [comment]
Hi @acrymble . As far as I know, there has not been a discussion about it in the Spanish team. Give me a few days and I ask to reach a consensus. At least I think it's important.

**Comment by mariajoafana** [comment]
I think is important as well. If you all agree I can take care of translating the submission form and add it to the Spanish language guidelines, for new submissions.

**Comment by jenniferisasi** [comment]
Hi! 
I agree it would help us a lot. @mariajoafana, I can take care of doing the changes on the guidelines to follow what @acrymble has done in English after you translate the form - that way we divide the work.

**Comment by vgayolrs** [comment]
Excellent @jenniferisasi ! Tell us if you need help or support at any point.

**Review by mariajoafana — DISMISSED** [review]
Will create a pull request for the Spanis translation once is ready

**Comment by mariajoafana** [comment]
[Formulario.Consulta.Lección.txt](https://github.com/programminghistorian/jekyll/files/2415615/Formulario.Consulta.Leccion.txt)
Traduje el formulario al español. @jenniferisasi Please take a look at it before adding it to the author guidelines. @acrymble Where in the author guidelines is the form to be found?

**Comment by acrymble** [comment]
@mariajoafana it replaced the "add metadata" section. You can see all the changes here (but I realise that it's difficult to see like that): https://github.com/programminghistorian/jekyll/pull/998/files

**Comment by acrymble** [comment]
@mariajoafana would it be easier if I merged this pull request so you could see the clean version of the new guidelines?

**Comment by mariajoafana** [comment]
@acrymble Yes, that'll be easier

**Comment by acrymble** [comment]
Ok. I had to make a minor update to resolve a conflict with the existing website. @mariajoafana can you re-review, and then just merge it yourself? Then we can open a new ticket for the Spanish one.

**Review by mariajoafana — APPROVED** [review]

**Pull request merged**
