### PR TITLE
Issue 2753

### LINKED ISSUE #2753: Correcting small error in The Sound of Data / Sonificação de dados
The author of _The Sound of Data_ / _Sonificação de dados_ has kindly [reached out via Twitter](https://twitter.com/electricarchaeo/status/1592263730859241473) to let us know about a small error in the following lessons:

/en/lessons/sonification
/pt/licoes/som-dados-sonificacao-historiadores

The error is in a code block at the second [Practice step](https://programminghistorian.org/en/lessons/sonification#practice-2) / [Prática](https://programminghistorian.org/pt/licoes/som-dados-sonificacao-historiadores#pr%C3%A1tica-2):

The author [explains](https://via.hypothes.is/https://programminghistorian.org/en/lessons/sonification) that: _If you uncomment out the # for the 'live_loop' command, you need a second end to finish things off. One 'end' to close live_loop, one to close off data.each:_

```
live_loop :jesuit do
  data.each do |line|
    topic1 = line[:topic1].to_f
    topic2 = line[:topic2].to_f

    use_synth :piano
    play topic1*2, attack: rand(0.5), decay: rand(1), amp: rand(0.25)
    use_synth :piano
    play topic2*2, attack: rand(0.5), decay: rand(1), amp: rand(0.25)
    sleep (0.5)

  end
end
```

Screenshot 2022-11-16 at 19 36 28

### PR DESCRIPTION
**Pull request by anisa-hawes**
I am correcting a small error in The Sound of Data / Sonificação de dados.

I'm also adding in the table of contents to the PT lesson, which I noted was missing.

Closes #2753 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] ~~if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description~~
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Hello @hawc2. A quick Lesson Maintenance fix, ready for your review.

I just have [one query](https://github.com/programminghistorian/jekyll/issues/2753#issuecomment-1318474851) about the phrase 'commenting out', which I would be grateful for your insight on. 

Thank you,
A.

**Comment by hawc2** [comment]
Sorry for delays @anisa-hawes (I thought I answered this on slack). I agree that the right way to phrase this note is "'commenting out' involves adding a hash sign".

**Comment by hawc2** [comment]
Maybe you've already made this change, does it just need final review and approval?

**Comment by anisa-hawes** [comment]
Thank you, @hawc2. I have made that adjustment to the EN lesson.

As I understand it, the way this has been phrased in Portuguese is clearer, so no change is needed there. To remove a comment, we remove the #. 

_'retirar o comentário' signfica remover o sinal #_  // _'remove the comment' means remove the # sign_

Perhaps @DanielAlvesLABDH could confirm?

If the PT lesson doesn't need updating, then all I need to merge this is a Review + Approval.

**Review by hawc2 — APPROVED** [review]

**Comment by DanielAlvesLABDH** [comment]
Hi @anisa-hawes. Yes I can confirm that is the right meaning. Thanks

**Pull request merged**
