### PR TITLE
Issue #2258

### LINKED ISSUE #2258: Portuguese version not mentioned in 'Contribute' pages in French, Spanish and English
I was reading the [/contribuciones](https://programminghistorian.org/es/contribuciones)  page of the Spanish site as part of my onboarding and noticed that it does not mention Portuguese alongside French and English.
The Portuguese version is also omitted from the [French](https://programminghistorian.org/fr/contribuer) and [English](https://programminghistorian.org/en/contribute) equivalent pages.
I'm happy  to make the changes, but wanted to check first if there might be a reason to wait or something I'm not aware of (since I'm brand-new to the PH team).

### PR DESCRIPTION
**Pull request by isag91**
Add references to Portuguese in the /contribute pages of the Spanish, French and English sites. Closes #2258 

These pages also mention that the different versions have a listing in WorldCat, but I haven't added Portuguese there since I couldn't find that it was listed in Worldcat (yet).

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [ ] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by jenniferisasi** [comment]
@isag91 I'm fixing that broken link on my PR #2251

**Comment by jenniferisasi** [comment]
~~@isag91 if you approve said PR, I can merge it.~~ Then, I can update this one to reflect or catch that the website has some new changes, and I'll approve it for you to merge.

**Comment by jenniferisasi** [comment]
ugh, looks like it didn't pick the latest update with the blogpost announcement

**Review by rivaquiroga — DISMISSED** [review]

**Comment by jenniferisasi** [comment]
@ZoeLeBlanc just confirmed with me that we need to wait a few minutes till all the GitHub magic mechanisms update and a new PR is able to catch the previous PR's changes.

**Comment by isag91** [comment]
Thanks @jenniferisasi !

**Comment by jenniferisasi** [comment]
Still didn't catch it ...

**Comment by jenniferisasi** [comment]
Ok we are going to wait on this for whenever @ZoeLeBlanc can take a look and see why an update to the build is not catching the PR we merged today with the new editors in ES in the blog. I tried the update through terminal but it tells me it is up to date.

**Comment by rivaquiroga** [comment]
@jenniferisasi, you mean in the preview of the site?

**Comment by jenniferisasi** [comment]
Yes @rivaquiroga, the deploy-preview is not getting showing the latest update on the website (the announcement blogpost) so I asked Zoe if we had to wait a few minutes in between PR merges; she said yes, but this one is still not catching that update.

**Comment by rivaquiroga** [comment]
Maybe if you re-run the build the preview will be updated.

**Comment by jenniferisasi** [comment]
Ok let me try one more time,... will be the third.

**Comment by rivaquiroga** [comment]
The file for the latest post has not been merge to this branch: https://github.com/programminghistorian/jekyll/tree/Issue-%232258/_posts. Probably that is why it can't be shown in the preview

**Comment by jenniferisasi** [comment]
Yes that is why I tried to update it through the terminal and, again, without success 😢

**Comment by rivaquiroga** [comment]
Ahí lo actualicé y ahora se ve.
Creo que me es más fácil explicarlo en español que en inglés: en el terminal dice que está up to date porque la rama `Issue-#2258` la creaste localmente a partir de la versión actualizada que tienes de `gh-pages`.  Así que cuando cuando le tratas de hacer merge desde gh-pages a la nueva rama, te dice que no hay nada que actualizar. Pero eso está actualizado solo en tu repo local. Así que si haces push, se vienen los cambio a la versión de GitHub del repo, que no tiene los archivos del último PR.

**Review by rivaquiroga — APPROVED** [review]

**Comment by isag91** [comment]
Thanks @jenniferisasi and @rivaquiroga for sorting this out! Apologies for letting you do all the work but I was sadly clueless - clearly I need to investigate the inner workings of GitHub

**Comment by jenniferisasi** [comment]
Tengo que aprender del todo a hacer lo de la terminal.

**Comment by rivaquiroga** [comment]
@isag91, esto que pasó ahora pasa siempre! Como estamos trabajando en muchos PR al mismo tiempo, sucede que la versión del repositorio con la que se inicia un PR puede quedar rápidamente obsoleta.  Además, usualmente nos encontramos con que hay enlaces rotos que hay que actualizar. Y quizás alguien justo ya lo arregló en otro PR porque se encontró con el mismo problema.  Así que no es raro tener que traer cambios nuevos de otra rama a la que una creó. 
¿Cómo sueles usar git/github? ¿Desde la terminal? ¿O con GitHub desktop, Gitkraken o una aplicación de ese tipo?

**Comment by isag91** [comment]
@rivaquiroga Sí, desde la terminal

**Pull request merged**
