### PR TITLE
Update support-us.md

### PR DESCRIPTION
**Pull request by drjwbaker**
Add CDCS to list of IPP members.

Dear ES/FR Teams: can you please help translate the following line into Spanish and French in the file `support-us.md`:

> '[Centre for Data, Culture and Society, University of Edinburgh](https://www.cdcs.ed.ac.uk/ [2020-Present]'

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Review by rivaquiroga — DISMISSED** [review]

**Comment by drjwbaker** [comment]
Thanks @rivaquiroga (especially the missing parenthesis!). Just waiting for @programminghistorian/french-team to add the line for `nous-soutenir.md` then we are ready to go!

**Comment by acrymble** [comment]
Do we need to translate this? These are names of organizations. Maybe we could consider cutting down on admin burden by agreeing to list these (in future) in the language of the organization itself?

**Comment by drjwbaker** [comment]
> Do we need to translate this? These are names of organizations. Maybe we could consider cutting down on admin burden by agreeing to list these (in future) in the language of the organization itself?

Perhaps, but not my call to decide. @programminghistorian/spanish-team @programminghistorian/french-team MEs: what do you think?

**Comment by mariechristineb** [comment]
> > Do we need to translate this? These are names of organizations. Maybe we could consider cutting down on admin burden by agreeing to list these (in future) in the language of the organization itself?
> 
> Perhaps, but not my call to decide. @programminghistorian/spanish-team @programminghistorian/french-team MEs: what do you think?

@acrymble @drjwbaker From what I could tell, the French names are only translated at the 'larger' institutional level, such as universities and faculties, but names of specific research centres were left in the original (so I did the same for this specific case)

**Comment by drjwbaker** [comment]
Thanks for your note @mariechristineb. Seen as I do these when new IPPs come in, what I'll do from now on is to raise a PR with the English text in the ES and FR pages, ask for a review, and if the ES and FR teams want to translate, you can, as it seems you are taking slightly different approaches (the ES page *has* translated the name of the Centre). This is fine with me, if it is fine with the ES and FR teams - because you are in charge of translation policy in your publications, not me :)

**Review by rivaquiroga — APPROVED** [review]

**Pull request merged**
