### PR TITLE
Issue 1938

### PR DESCRIPTION
**Pull request by ZoeLeBlanc**
This PR is a first attempt at closing #1938. It adds two fields to lessons.html and snippets.yaml, a `tested_date` and `lesson-tester` so that we can begin to record testing of lessons.

The names of lesson testers will appear next to reviewers, editors, translators, etc... whereas the lesson tested date will appear below next to published, modified, translated date, etc... 

This setup assumes that we will only record the most recent tested date, but that we will record all previous lesson testers. The rationale is that though we could include all testing dates that info is less relevant (we mostly want to know if it's stale or not) and we want to give credit to all testers. So therefore list of names, but only one date to try and minimize user entered data errors.

Prior to merging this PR, we'll need to update lesson guidelines. Also open to discussing additional fields or formats!

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [ ] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [ ] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by acrymble** [comment]
Just in terms of a timeline @ZoeLeBlanc, I'm hoping to have a placement student to test some lessons in May. Are we likely to have this live in time, or will we have to keep track on a spreadsheet or something else in the meantime?

**Comment by ZoeLeBlanc** [comment]
We should have it available pretty soon @acrymble. I think the technical team is about done on our end so going to make this PR live and request translation from various teams!

**Comment by ZoeLeBlanc** [comment]
Would members of @programminghistorian/spanish-team @programminghistorian/french-team @programminghistorian/portuguese-team be able to translate some snippets for this PR?

I'm happy to add in the data or have people merge into this branch, but I need translations of the words `tested by` and either `last tested` or `tested on` (which ever makes more sense to you) for this PR.

You can see the snippets fields below:
```
lesson-testers:
  en: tested by
  es:
  fr: 
  pt: 
tested-date:
  en: tested
  es:
  fr: 
  pt: 
```
Thanks!

**Comment by pymentha** [comment]
Hello!

For portuguese we can write:

*For lesson-testers*

pt: Testado por

*For lesson-date*

pt: ultimo teste or testado em *or* testado

Ricardo M Pimenta

Em qua., 24 de mar. de 2021 08:59, Zoe LeBlanc ***@***.***>
escreveu:

**Comment by ZoeLeBlanc** [comment]
Thanks so much @pymentha 🙏🏽 ! Just merged in your translations 🎉

**Comment by rivaquiroga** [comment]
@programminghistorian/spanish-team: Which translation do you think works best in this case? _testeado por_ y _último test_, _probado por_ y _última prueba_, ¿otra?

**Comment by ZoeLeBlanc** [comment]
@programminghistorian/spanish-team would anyone have time to add a translation to this branch so we could merge this in? Thanks 🙏🏽 !

**Comment by rivaquiroga** [comment]
@ZoeLeBlanc, done!

**Comment by ZoeLeBlanc** [comment]
Thanks so much @rivaquiroga ! Just one final issue for the @programminghistorian/spanish-team to chime in on.

There's a breaking link in the lesson `introduccion-control-versiones-github-desktop`. It looks like the link to the old Github Desktop is no longer available ([https://central.github.com/mac/latest](https://central.github.com/mac/latest) ). When I went to the web archive to find an alternative link, it redirected to a zip download [https://mac-installer.github.com/mac/GitHub%20Desktop%20222.zip](https://mac-installer.github.com/mac/GitHub%20Desktop%20222.zip) but I have no idea if that's suitable for the lesson or not. Would someone mind letting me know and I can update the broken link. Thanks again!!

**Comment by jenniferisasi** [comment]
Hi @ZoeLeBlanc. That lesson is retired, so no need to maintain it, but also makes me wonder (cos I don't remember) if it is necessary that the build runs inside the retired lessons to look for broken links?
https://programminghistorian.org/en/lesson-retirement-policy

**Pull request merged**
