### PR TITLE
blogpost connected to #499

### PR DESCRIPTION
**Pull request by acrymble**
This is the blog post from issue #499, which we can point authors to when they are trying to come up with a manageable scope for their lessons.

### CODE REVIEW

**Review by mdlincoln — CHANGES_REQUESTED** [review]
The core points are good here, but I think you might do another editing pass with an eye towards tone. Since this is supposed to be a useful post for cultivating would-be authors, I think we should avoid sounding exasperated, or like we are presenting a list of complaints (even though these are all very real challenges that you list!)

Perhaps orienting it a bit more towards the author's point of view, rather than that of an irritated editor, might help. For example, right now the post laments authors "disappearing" or needing to be chased down. You might reframe it as: we want to make sure that authors' initial hard work submitting a draft doesn't go to waste. By understanding the time commitment involved, authors can better focus on managing their scope and expectations about time commitment.

**Review by walshbr — APPROVED** [review]
I largely agree with @mdlincoln. This is all great advice, and I think just framing it in the ways he suggest might help. I'll go ahead and approve since the changes I would request are the same! Thanks for putting this together, @acrymble. Really glad it will be on the blog.

**Comment by acrymble** [comment]
Thanks, I've revised the tone. Good suggestion.

**Review by mdlincoln — COMMENTED** [review]
This looks excellent! I'll merge it now.

**Review by mdlincoln — APPROVED** [review]

**Pull request merged**
