### PR TITLE
translate snippet and about page

### PR DESCRIPTION
**Pull request by arojascastro**
Please approve this little change @mdlincoln @vgayolrs @jenniferisasi

### CODE REVIEW

**Comment by mdlincoln** [comment]
@arojascastro this PR reverses a lot of the changes that you already merged in the previous PRs. Please pull the most recent `gh-pages` branch again, and resubmit your changes.

**Comment by arojascastro** [comment]
I do not know what is going on, to be honest... :(

**Comment by acrymble** [comment]
He's asking you to amend his pull requests so that the English and Spanish
changes all go in the same pull request.

You have accepted his pull request and opened a new one for Spanish
changes. So he wants 1 pull request for everything instead of 2.

**Comment by arojascastro** [comment]
I see now. I promise to do it next time. Thanks to both @mdlincoln and @acrymble

**Pull request closed without merging**
