### PR TITLE
Publicar Contagem e mineração de dados de investigação com Unix

### PR DESCRIPTION
**Pull request by DanielAlvesLABDH**
*Publicar tradução da lição Counting and mining research data with Unix*

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by DanielAlvesLABDH** [comment]
Dear @anisa-hawes the build is failing because of a broken link in this lesson:

Found 635 internal links in the cache...
- ./_site/en/lessons/sonification.html
Ran on 386 files!
  *  External link https://rubyrogues.com/221 failed: 404 No error

HTML-Proofer found 1 failure!

I found a video that I think is similar to the one referenced on that link: https://www.youtube.com/watch?v=7sEMKXrRaAs
We are now translating this lesson, and the solution found here, can be used there: https://github.com/programminghistorian/ph-submissions/issues/429
Can you help me with this or let me know how can I fix it. Many thanks!

**Comment by anisa-hawes** [comment]
Hello @DanielAlvesLABDH. Funnily, I've actually updated that link before! In PR #2461 I found a couple of possible alternative links to the interview. This one <https://devchat.cachefly.net/rubyrogues/RR215SonicPi.mp3?rss=true> provides full audio of the podcast episode that is referenced. I have a few minutes now, so I can update /en/lessons/sonification with this new link, and @JimmyMedeiros82 can update [#429](https://github.com/programminghistorian/ph-submissions/issues/429)!

**Comment by DanielAlvesLABDH** [comment]
Great! Thanks a lot!

**Comment by JimmyMedeiros82** [comment]
Update done in https://github.com/programminghistorian/ph-submissions/issues/429 @anisa-hawes and @DanielAlvesLABDH

**Review by joanacvp — APPROVED** [review]
@DanielAlvesLABDH está pronta a publicar :)

**Pull request merged**
