### PR TITLE
Publishing use api almost without coding php

### PR DESCRIPTION
**Pull request by alsalin**
publishing lesson

### CODE REVIEW

**Comment by mdlincoln** [comment]
Hey @alsalin I noticed your "jpg" files were actually filled with HTML - but it looks like you're already replacing all of them as we speak!

**Comment by mdlincoln** [comment]
But the new ones are also wrong :(

**Comment by alsalin** [comment]
Yep! I’m not sure what happened – when uploading everything on Friday it all went awry. I just replaced the featured image and am working on the lesson images now. Thanks for checking in though!

**Comment by alsalin** [comment]
@JMParr after fixing some bizarre issues with images - i think it's ready! could you review the pub and let me know if there are any issues?

**Comment by JMParr** [comment]
Yes. Will review after lunch.

**Comment by acrymble** [comment]
@JMParr as I'm now managing editor, can you get me up to speed on this and what needs doing? Thanks.

**Comment by JMParr** [comment]
> @JMParr as I'm now managing editor, can you get me up to speed on this and what needs doing? Thanks.

@alsalin was in the midst of moving the files. This lesson should be ready for final publication, and closure of the review ticket.

**Comment by acrymble** [comment]
@mdlincoln how do we get a netlify preview of this so that we can check it over?

**Comment by mdlincoln** [comment]
https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html

**Review by acrymble — CHANGES_REQUESTED** [review]
I've had a careful look at this, and there are a number of elements that need addressing before we can publish. Some of these are from the editorial checklist, and others are matters of style.

**General:**

- [ ] The language is far too colloquial throughout. "First Go" and "Cool Stuff" are examples of phrases that need to be changed. This is a matter of writing for a global audience and avoiding colloquialisms and unnessarily informal writing. On a scale of blog post to academic journal article, the tone should be much closer to academic journal article, or at least New York Times. For example, sentences such as  “by the famous guy Tim Berners-Lee” need to be formalized. Be clear rather than cool.
- [ ] The author shifts frequently between forms of addressing the reader, including but not limited to "you", "we", and "participant". One form only should be used throughout. Likewise shifts between "I" and "the author" need to be consistent.
- [ ] In keeping with our common practice, technical terms should be linked to Wikipedia in the first instance.
- [ ] Editorializing can and should be cut. For example: "To be honest, sometimes the author is not very happy with the current practice of Open Data. There is a strong tendency that normal websites are prepared for ordinary users and APIs are for developers. He thinks this is not very FAIR.” 

**Specific:** 

- [ ] "Application Programming Interface" is a noun, but it’s being used as a verb in both the title and abstract.
- [ ] The abstract doesn’t make sense grammatically.
- [ ] Punctuation is inconsistent or incorrect in places. This needs to be fixed.
- [ ] Subheadings need to be in title case (or at least consistent)
- [ ] Figures should be numbered (Figure 1, Figure 2, etc) and should be referenced in the text.
- [ ] Figures that are simply decoration (eg Figure 1) should be removed
- [ ] Emphasis (bold) should be used very sparingly. It is overused throughout this tutorial
- [ ] Avoid "PC" as an acronym for computer.
- [ ] Don't refer to the "latest" version of something. If something needs at least version X, then be specific. Someone might read this 10 years from now, so give enough context.

**For the Editor:**

- [ ] The Gallery Image has not been shrunk to 200px square, as per the Editorial Guidelines.
- [ ] The word count is 8,500. This far exceeds the recommended maximum word count. Are you putting forth a case that the topic requires an exemption?

Please let me know if you need any clarification on any of these points.
- [ ] Given the number of new topics, I just wanted to double check that you're happy with a "1" difficulty rating.

**Comment by mdlincoln** [comment]
Hello @alsalin @acrymble which one of you is going to implement these changes?

**Comment by acrymble** [comment]
@mdlincoln I've assignmed myself to this ticket. I've also emailed @JMParr, but I know she's very busy right now. If I don't hear in a week I will push forward with this myself, but I wanted to give her a chance to reply.

**Comment by JMParr** [comment]
Hi, Adam - I have started working on editing, but did not have a chance to
finish because there's a lot of copy-editing (as you note).

**Comment by acrymble** [comment]
Thanks @JMParr I will move forward on the remaining copy edits, as we discussed.

**Comment by acrymble** [comment]
I have been in touch with the author via email. I am sending this back to him for some revision of the language and style in particular. We aim to have a resubmission (I hope) by 15 May 2019 at which point we can do a new pull request.

**Pull request closed without merging**
