### PR TITLE
Remove education manager role

### PR DESCRIPTION
**Pull request by jenniferisasi**
Per a conversation between @acrymble and @amsichani, I am removing the Education Manager role tag from two metadata files.

This role was part of the Communications Team. 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  ~~- [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description~~
- [x] Add the appropriate "Label"
- [ ] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Review by amsichani — DISMISSED** [review]

**Comment by acrymble** [comment]
I tried fixing this @jenniferisasi but our link checker has once again got in the way.

The new problem is a link to someone's github repository that they seem to now have taken down. Github repositories aren't in the internet archive. It's also been translated into Spanish:

- https://programminghistorian.org/en/lessons/intro-to-twitterbots.html
- https://programminghistorian.org/fr/lecons/intro-aux-bots-twitter

Can you please forward to the tech team how frustrating this has become. The work of fixing it overwhelmingly is falling on a handful of people who didn't cause the problems and just want to make simple changes to the website.

**Comment by drjwbaker** [comment]
Hey @acrymble. Relax. This isn't the fault of anybody on the team. We can work on this in your absence.

**Comment by drjwbaker** [comment]
The issue is this link https://stefan.glitch.me/. Resolving.

**Comment by drjwbaker** [comment]
So this is failing on broken blog links. Any reason why https://github.com/programminghistorian/jekyll/pull/2140 (which should resolve this) isn't closed? (pinging @ZoeLeBlanc)
Screenshot from 2021-08-09 17-52-04

**Comment by ZoeLeBlanc** [comment]
@drjwbaker I'll try to get #2140 merged in today so that this breaking issue can be fixed 👍🏽

**Comment by acrymble** [comment]
> Hey @acrymble. Relax. This isn't the fault of anybody on the team. We can work on this in your absence.

Sorry you're right. I'm frustrated at the tech. Not at people.

**Review by ZoeLeBlanc — APPROVED** [review]
Looks good to me! Merge away 👍🏽

**Comment by drjwbaker** [comment]
> > Hey @acrymble. Relax. This isn't the fault of anybody on the team. We can work on this in your absence.
> 
> Sorry you're right. I'm frustrated at the tech. Not at people.

It is okay Adam. Raging at tech is usually a good sign that a holiday/break is needed. I hope you enjoy yours.

**Pull request merged**
