### PR TITLE
Update introduccion-map-warper.md

### LINKED ISSUE #2344: Re-test Introducción a Map Warper
A [recent thread on Twitter ](https://twitter.com/NYPLMaps/status/1452668555992965122?s=20) indicates that the NYPL Maps Division are closing their MapWarper project. It would be good to re-test our ES tutorial https://programminghistorian.org/es/lecciones/introduccion-map-warper, and see what the implications are/check that the lesson still works. 

I can have a go at this, guided by the screenshots, but I would appreciate it if someone from the @programminghistorian/spanish-team could support this too. 

If the lesson still works now, we could consider applying an information alert box to indicate that the project is changing and set ourselves a reminder to check again in a few months' time.

### PR DESCRIPTION
**Pull request by anisa-hawes**
Adding a blue "alert information" box at the very beginning of the lesson, to let users know that some utilities have changed, plus a link to the NYPL's status update.

Adding yellow "warning alert" boxes in sections _Georrectificación_ and _Exportar_ where specific functions are not currently working.

Translation is already complete! Thanks to @nllano!

Closes #2344

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Hello @rivaquiroga. This is a Lesson Maintenance Issue, brought to our attention via a dialogue on Twitter. The NYPL have archived their Mapwarper project, and this means that certain utilities of the lesson have changed. We've added an "info" alert + two "warnings" to let readers know. I've also added a `tested_date:` into the YAML for our records as well as to reassure users. This lesson has recently been proposed for an EN translation, so I will also let their team know.

**Comment by jenniferisasi** [comment]
Sorry to intrude, but since I get all emails I have to :) 

That note reads to me as if MapWarper is created and maintained by the NYPL and like the software will be archived and ceased to exist. However,[ Map Warper its in own individual software maintained by Tim Waters](https://mapwarper.net/) and there is nothing on the official website indicating it will stop working. 

An [instance of Map Warper used by the NYPL](https://wayback.archive-it.org/13216/20210520171637/http://maps.nypl.org/warper/) is what will be archived; but our lesson doesn't use the NYPL instance. @rivaquiroga might want/need to check on this, but I believe that note is going to confuse people rather than help them.

**Comment by anisa-hawes** [comment]
Thank you for interjecting, @jenniferisasi. This is really useful. I'm sorry, I have mis-understood how archiving of the NYPL's instance of Mapwarper may effect our lesson...

**Comment by anisa-hawes** [comment]
Hello @rivaquiroga. Apologies for my confusion. When you have time, please let me know whether you think these changes are needed or not. 

Jenn @jenniferisasi has explained that our lesson doesn't directly use the NYPL's instance of Mapwarper, so the info-alert box at lines 27-30 may be unnecessary.

But Nicolás's @nllano's testing did identify some utilities of the software which aren't working anymore, so may the warning-alert boxes at lines 80-82 and 179-180 might still be useful? But we'd need to update the wording if these issues are unrelated to the NYPL.

Also tagging @hawc2 here because I'm aware he is soon to be editing an EN translation of this lesson.

**Comment by rivaquiroga** [comment]
@anisa-hawes, I'll take a look!

**Comment by anisa-hawes** [comment]
Thank you, @rivaquiroga! Much appreciated. I'm finishing up for the day now, but will check in with you again next week. Wishing you a restful weekend ✨

**Comment by rivaquiroga** [comment]
Hi, @anisa-hawes! I agree with @jenniferisasi that the alert on lines 27-30 may be unnecessary (and confusing).
The other two warnings seem like a good idea.

**Comment by anisa-hawes** [comment]
Thank you, @rivaquiroga! I'll remove the info box at lines 27-30.

Do you think the wording of the alerts at lines 80-82 and 179-180 need to be adjusted? Or are they okay to publish as they are?

**Comment by rivaquiroga** [comment]
I just updated the wording ;)

**Comment by anisa-hawes** [comment]
Thank you so much @nllano, @rivaquiroga and @jenniferisasi! 

Riva, @rivaquiroga this is ready for review now.

**Review by rivaquiroga — APPROVED** [review]

**Pull request merged**
