### PR TITLE
Date format check

### LINKED ISSUE #1654: add YAML check for proper date format
If the date is not entered as YYYY-MM-DD, liquid produces a confusing-sounding error when it tries to order all the lessons by date to generate our RSS feed:

`comparison of Array with Array failed in feed.xml`

We can catch this in the YAML checks and provide a more informative error message.

re: #1651

### PR DESCRIPTION
**Pull request by mdlincoln**
This adds checks into `validate_yaml.rb` to confirm that both `date` and `translation_date` (if present) parse as valid dates in `YYYY-MM-DD` format. It will produce informative error messages if not.

This closes #1654

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  ~- [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description~
- [x] Add the appropriate "Label"
- [ ] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
~- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)~
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by mdlincoln** [comment]
This check shows an example of what the build looks like when introduced "bad" dates: https://travis-ci.org/programminghistorian/jekyll/builds/647510577

**Review by jenniferisasi — APPROVED** [review]
Very nice!

**Comment by jenniferisasi** [comment]
> This check shows an example of what the build looks like when introduced "bad" dates: https://travis-ci.org/programminghistorian/jekyll/builds/647510577

out of curiosity, did you fake these errors or where they actually wrong?

**Comment by mdlincoln** [comment]
I faked em - gotta test that the test actually tests!

**Pull request merged**
