### PR TITLE
Issue 2381

### LINKED ISSUE #2381: Update USD IPP rate
I am updating the USD membership rate, increasing it to $1400 at the £1k level. This is to reflect the fall in the value of the dollar against the pound.

### PR DESCRIPTION
**Pull request by anisa-hawes**
I am updating the USD membership rate, increasing it to $1400 at the £1k level. This is to reflect the fall in the value of the dollar against the pound.

Closes #2381 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] ~~if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description~~
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by rivaquiroga** [comment]
@anisa-hawes, I made a small change in the Spanish version. I remove the commas used as thousands separators, because in Spanish we use commas as decimals separators.

**Comment by anisa-hawes** [comment]
Thank you for noticing this, @rivaquiroga. Apologies for not seeing it. At the moment, the live ES page does use commas as  thousands separators, so its great if we can put this right at the same time.

**Comment by rivaquiroga** [comment]
You don't need to apologize. It was published like that and none of us noticed it before.

**Comment by jenniferisasi** [comment]
I just made a quick change to the version in Spanish as well, we were missing the tilde (´) on the word "países", don't know how we didn't see that before either 🙃

**Comment by rivaquiroga** [comment]
:open_mouth:

**Review by acrymble — APPROVED** [review]

**Pull request merged**
