### PR TITLE
Adding a new translation about tabular data with R

### PR DESCRIPTION
**Pull request by arojascastro**
Translated by @jenniferisasi 

Approve pull after passing the checks please

### CODE REVIEW

**Comment by arojascastro** [comment]
all clear! :)

**Review by mdlincoln — CHANGES_REQUESTED** [review]
It looks like the author bio still needs to be translated.

Everything else looks good to me though! 👍

**Comment by jenniferisasi** [comment]
Thanks @mdlincoln for pointing that out! Will work on that as soon as I can this morning

**Review by jenniferisasi — APPROVED** [review]
Looks good!

**Review by jenniferisasi — COMMENTED** [review]
I've done the translation...but I didn't know I had to connect it with this pull request ? (I don't know how to do that)

**Comment by arojascastro** [comment]
No worries, we just need @mdlincoln to approve this :)

**Review by mdlincoln — APPROVED** [review]

**Comment by arojascastro** [comment]
Thanks!

**Pull request merged**
