### PR TITLE
Geospatial data analysis updates

### LINKED ISSUE #1181: possible bug in "using geospatial data"
[reported from twitter](https://twitter.com/Nate_Housley/status/1097272622834798598):

>There seems to be a directory missing in the data provided for "Using Geospatial Data to Inform Historical Research in R." The tutorial reads: Census_Data <- read.csv("./data/County1990_Data/nhgis0027_ts_nominal_county.csv" but there is no County1990_Data folder

I can look into it this weekend unless someone has a chance to take a look sooner.

### PR DESCRIPTION
**Pull request by svmelton**
Uploading new data files and correcting errors in lesson (closes #1181)

### CODE REVIEW

**Review by mdlincoln — CHANGES_REQUESTED** [review]
1. Why has `assets/geospatial-data-analysis/Archive.zip` been moved to `assets/Archive.zip`? Seems like this is a mistake to put a file outside of the folder for the rest of the lesson.

2. See the errors on Travis: make sure that there's an image alt text description added to the lesson yaml metadata

**Comment by svmelton** [comment]
Thanks, @mdlincoln—I've made those changes. Let me know if there's anything else you need from me!
(Also, it looks like the TEI site is currently offline—hence the error. I suspect it will come back up soon.)

**Review by mdlincoln — CHANGES_REQUESTED** [review]
Alright, I've re-tested this with the data in Archive.zip and it looks like everything is, at long last, working.

I didn't see the uncompressed files referenced in the lesson, so do you think we could remove them from the PR before finalizing this?

**Comment by svmelton** [comment]
@mdlincoln Sure thing, just removed the uncompressed files

**Review by mdlincoln — APPROVED** [review]

**Pull request merged**
