### PR TITLE
3rd Newsletter of 2020 

### PR DESCRIPTION
**Pull request by jenniferisasi**
Will check how it looks and read again everything before publishing it. 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [ ] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by jenniferisasi** [comment]
@programminghistorian/technical-team why is the preview showing these newsletters followed by the previos newsletters, and thus it omits the last two posts that happened in between? Any idea?

**Comment by spapastamkou** [comment]
@jenniferisasi 
I added Helène Huet as new FR ombuds in the New members section (only in the FR version of the letter). 
Also, I added two words in"Collaborez avec nous" to say we have two original lessons in FR in elaboration. 

Where you mention what James said on twitter about ProgHist, maybe a link should be provided? 

Thanks for your all your work on this!

**Comment by walshbr** [comment]
What were the two posts that are missing @jenniferisasi?

**Comment by spapastamkou** [comment]
@walshbr @jenniferisasi There are two blog posts that were published in September but do not appear in the preview - I just checked and their files are not in the branch, I think it is only a question of updating the branch.

**Comment by spapastamkou** [comment]
I used the PR to make some corrections on 2 pages of the FR site, no relation with the blog post.

**Review by spapastamkou — DISMISSED** [review]

**Review by spapastamkou — APPROVED** [review]

**Pull request merged**
