### PR TITLE
Added info box about new version

### PR DESCRIPTION
**Pull request by svmelton**
Closes issue #2477.

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by svmelton** [comment]
This PR is currently failing because it looks like the Zooniverse site is down, but I suspect that's only a temporary issue and the site will come back up soon.

Tagging @spapastamkou and @rivaquiroga for French and Spanish translation.

**Comment by jenniferisasi** [comment]
Hi @svmelton, here is the translation. I didn't add it to our file yet because I'd like to hear what @rivaquiroga thinks ... as the guide provided is in English. I added a note in there, but is that enough?

En 2022, Lauren Anthony sacó AntConc 4.0, una actualización importante del software AntConc. Aunque casi todas las funciones siguen siendo las mismas, algunas de las prácticas que se describen en esta lección han cambiado un poco. Si estás utilizando una versión más reciente de AntConc que la que se muestra a continuación, puedes consultar la <a href="https://www.laurenceanthony.net/software/antconc/releases/AntConc403/help.pdf">guía de ayuda</a> proporcionada por Laurence Anthony (solo disponible en inglés). Este aviso es especialmente relevante para abrir un corpus utilizando la nueva herramienta Corpus Manager (enero de 2022).

**Comment by rivaquiroga** [comment]
@jenniferisasi, ¡muchas gracias! El mensaje me parece bien :)

@svmelton, the message seems like a good solution in the short run. But do we want to keep the lesson as is? Or do we want to update it to reflect recent changes in the tool used? How useful is for the readers if we don't update it?

**Comment by spapastamkou** [comment]
Hey @programminghistorian/french-team, I proposed a translation here but it would perhaps be preferable if someone else reviews for the FR team. Thanks!

**Comment by InesSalome** [comment]
I propose to replace "mise à jour importante" by "mise à jour conséquente" and to add at the end of the last sentence "pour ouvrir des corpus grâce à la nouvelle fonctionnalité Corpus Manager". Otherwise I have nothing to say on your translation @spapastamkou  !

**Comment by spapastamkou** [comment]
@InesSalome Done. So the FR part is now ok, @svmelton

**Comment by svmelton** [comment]
Thanks, all! @rivaquiroga Heather has said that the new version has some additional options but otherwise isn't very different, and the steps for the tutorial remain the same. I'd say we're probably ok to just add the note unless anyone has concerns.

Tagging the @programminghistorian/english-team (or @anisa-hawes) for review, whoever gets to it first!

**Review by spapastamkou — APPROVED** [review]

**Comment by spapastamkou** [comment]
thanks @anisa-hawes !

**Pull request merged**
