### PR TITLE
Remove Team Dev role

### PR DESCRIPTION
**Pull request by acrymble**
Deletes the 'team development role' description from the Project Team page, as this is no longer a separate role.

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by acrymble** [comment]
@programminghistorian/technical-team I think the build errors (broken links) were fixed in a pull request that was merged yesterday. Is there an easy way I can rebase the code to the latest branch using the web interface?

**Comment by spapastamkou** [comment]
I updated the branch for you via the app (but I have no answer for the web
way)

**Comment by walshbr** [comment]
To my knowledge there is not. @ZoeLeBlanc might know otherwise though.

**Comment by acrymble** [comment]
Thanks everyone. @jenniferisasi this is ready for merging when you can review.

**Comment by ZoeLeBlanc** [comment]
Agree with Brandon! Don't think there is a way to pull from other branches in the web interface (though could see them adding that eventually!).

**Comment by acrymble** [comment]
@jenniferisasi just need a review on this please.

**Review by jenniferisasi — APPROVED** [review]

**Comment by jenniferisasi** [comment]
I usually don't merge anything I haven't opened myself but let me know if you want me to start doing that in this type of PRs

**Pull request merged**
