### PR TITLE
Issue 2531

### LINKED ISSUE #2531: Lesson 'Configurar um ambiente de desenvolvimento integrado para Python (Mac)'
Hello @anisa-hawes.
When trying to do the Portuguese version of the lesson [Configurar um ambiente de desenvolvimento integrado para Python (Mac)](https://programminghistorian.org/pt/licoes/instalacao-mac) I found some problems (that I believe can be found in the other versions of the lesson).

I am using MacOS Monterey 12.3 and I couldn't find all the steps to configure Komodo Edit in the lesson. Before creating the command "Run Python", I had to:
- Since Komodo Edit is usually blocked by MacOS, we can't immediately open the software. We have to authorise the computer to run it by going to System Preferences > Security and Privacy > General (not sure those are the names in English) and clicking in the locker in the left down corner. We can then unblock Komodo Edit.

Then, as it is (partially) explained in the Windows version of the lesson, I had to:
- Go to Komodo > Preferences > Python 3. 
- - Access the “bin” (an invisible directory) and find Python 3. The path should be like “/usr/bin/python3”.

Maybe I am doing something wrong and it can be solved out on an easier way.

Thank you for your help!

### PR DESCRIPTION
**Pull request by charlottejmc**
This lesson originally suggested to use Komodo Edit as a text editor, but it is unfortunately not compatible with MacOS Big Sur or earlier. We've made changes to the EN lesson especially to suggest readers use BBEdit or Sublime Text instead. 

Closes #2531 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Add the appropriate "Label"
- [x] If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above
- [x] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Manager @anisa-hawes 
- [x] Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines), then assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR.

### CODE REVIEW

**Comment by charlottejmc** [comment]
Hello @jenniferisasi and @ericbrasiln ,

@anisa-hawes and I have been trying to close a [Lesson Maintenance issue](https://github.com/programminghistorian/jekyll/issues/2531) which reported the incompatibility of Komodo Edit text editor with MacOS Big Sur (or earlier versions). This affected the en/mac-installation, es/instalacion-mac and pt/instalacao-mac lessons. 

In [our changes to en/mac-installation](https://github.com/programminghistorian/jekyll/pull/3151/commits/d6ca20cf9245c15b3a8942fb76b81a0be61df7e8), we removed mentions of Komodo Edit, and pointed the readers to the text editors BBEdit and Sublime Text instead. 

In all three lessons, we added a new figure image to show what running ['Hello World'](https://github.com/programminghistorian/jekyll/pull/3151/commits/a5b60d7b0aab78083b471b160a10a76deaca121f)/['Hola Mundo'](https://github.com/programminghistorian/jekyll/pull/3151/commits/19a79e0eabd6303f44a180aa6a5c76b52b5b545d)/['Ola Mundo'](https://github.com/programminghistorian/jekyll/pull/3151/commits/241134067fc49781c8c9fa905e5ded26ff619617) would look like in Sublime Text, as well as BBEdit. 

However, because we weren't able to update the text in Spanish and Portuguese, we could not make the same adjustments for es/instalacion-mac and pt/instalacao-mac as we made for [en/mac-installation](https://github.com/programminghistorian/jekyll/pull/3151/commits/d6ca20cf9245c15b3a8942fb76b81a0be61df7e8). Would you be able to review the adjustments we made (remove mention of Komodo Edit, introduce the reader to BBEdit and Sublime Text, and adapt the commands to their interfaces), and replicate them in your respective languages? 

Thank you very much for your help! ✨ Please do not hesitate to ask me if anything is still unclear.

**Review by ericbrasiln — COMMENTED** [review]
Hello @charlottejmc ,

I've revised the changes to the English version and images (they seem okay to me). 

[I've included the changes to the Portuguese version](https://github.com/programminghistorian/jekyll/pull/3151/commits/fc5a817b1ac8aa5cc985bb9ed7e75d46d7212445).

I haven't revised or changed the Spanish version, as I think it's better to wait for Jenifer

**Review by ericbrasiln — DISMISSED** [review]

**Comment by charlottejmc** [comment]
Hello @jenniferisasi,

Just a gentle nudge to see whether you might have a moment to look at this pull request? You might find it helpful to review [the commit](https://github.com/programminghistorian/jekyll/pull/3151/commits/fc5a817b1ac8aa5cc985bb9ed7e75d46d7212445) which Eric made on the Portuguese version.

I see that the Spanish version still shows an image of Komodo Edit (`{% include figure.html filename="komodo-edit-mac.png" caption="Komodo Edit en una Mac" %}` at line 83), so please feel free to delete this completely.

Thank you very much, and please let me know if you have any questions!

Charlotte ✨

**Review by anisa-hawes — APPROVED** [review]
As @jenniferisasi and @ericbrasiln have contributed here, I'm happy to approve and merge. Thanks all ✨

**Pull request merged**
