### PR TITLE
Issue 2384

### LINKED ISSUE #2384: Modify code in Python lesson sequence across EN, ES, FR and PT
An "str/bytes" error is produced at the [Saving a Local Copy of a Web Page](https://programminghistorian.org/en/lessons/working-with-web-pages#saving-a-local-copy-of-a-web-page) step of Downloading Web Pages with Python (lesson 5 of 15 in the Python lesson series).

The command `response = urllib.request.urlopen(url)` appears to return a bytes object, which Mac and Windows handle differently when writing files. 

In previous dialogues about this, people have offered the solution of opening the file as 'wb' but this doesn't appear to work on both Mac and Windows. 

Instead we could use the command `response.read().decode('UTF-8')` to decode it into a string. 

I am going to test this, and make an adjustment if necessary.

### PR DESCRIPTION
**Pull request by anisa-hawes**
I am updating lessons across the Python sequence in EN, ES, FR and PT to mitigate a "str/bytes" error encountered by users.

Replacing the command `= response.read()` with `= response.read().decode('UTF-8')` (EN and PT)
Replacing the command `= respuesta.read()` with `= respuesta.read().decode('UTF-8’)`
Replacing the command `= reponse.read()` with `= reponse.read().decode('UTF-8’)` 

I have also updated the .zip files across EN and ES, amending the commands above ^^.

Closes #2384 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] ~~if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description~~
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Thank you so much, @rivaquiroga! This is now ready for review. I've checked through each of the lessons I've updated via the Netlify preview: all good!

**Comment by rivaquiroga** [comment]
Looks great! Do you want to change the zip files of each lesson in this PR? Or do you prefer to do it in a different one?

**Comment by anisa-hawes** [comment]
Thank you, @rivaquiroga. I've now updated the .zip files in this branch too.

**Comment by anisa-hawes** [comment]
Hello @rivaquiroga. Apologies! This PR got held up by a broken link but that is now fixed! 
Let me know when you have time to review this 🙂

**Review by rivaquiroga — APPROVED** [review]

**Pull request merged**
