### PR TITLE
Issue 2351

### LINKED ISSUE #2351: Updating initial contact information on Research pages
I am updating the initial contact information on the Research pages of our website, so that our MEs are no longer listed as first point of contact for academic researchers using the project.

### PR DESCRIPTION
**Pull request by anisa-hawes**
I am updating the initial contact information on the Research pages of our website, so that our MEs are no longer listed as first point of contact for academic researchers using the project and my contact information is given instead.

research.md
investigacion.md
recherche.md
pesquisa.md

Closes #2351

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by jenniferisasi** [comment]
@DanielAlvesLABDH in Portuguese it should say "nossa asistente", right?

And @anisa-hawes call for help if you receive any of those emails in ES, FR or PT :)

**Comment by anisa-hawes** [comment]
Ah! Thank you, @jenniferisasi! 

I was thinking 'nosso' because we at PH are a mixed group, but as I am then identifying myself (female) it should be 'nossa'. 

I am learning every day!

**Comment by jenniferisasi** [comment]
I don't understand the error... 

```
- ./_site/en/research.html
  *  internally linking to anisa.hawes@icloud.com, which does not exist (line 240)
     <a href="anisa.hawes@icloud.com">Anisa Hawes</a>
```
There is no line 240 in the research page; and the link is not formatted as `<a href=` in the pages you are editing here... I'll investigate.

**Comment by anisa-hawes** [comment]
Oh dear. Thank you, @jenniferisasi. I did note that the original links to generate emails to the MEs were formatted like this, `{% include managing-editor.html lang=page.lang %}` but I thought it would be possible to replace that with a link formatted as Markdown...

**Comment by jenniferisasi** [comment]
Yes, that is a `liquid loop` (maybe that's not their tech name) that calls to [_includes/managing-editor.html](https://github.com/programminghistorian/jekyll/blob/gh-pages/_includes/managing-editor.html), that looks into snippets to find the name of the managing editor based on the language the page is in (that corresponds to the folder where the .md is in).

**Comment by anisa-hawes** [comment]
Okay. Thank you, @jenniferisasi. If this works, I can do the same for the other three pages.

**Comment by jenniferisasi** [comment]
@anisa-hawes looks like my fix on the EN page worked. So you have to change the markdown type links to html links like this: ```<a href="mailto:anisa.hawes@icloud.com">Anisa Hawes</a>. ```

**Review by DanielAlvesLABDH — APPROVED** [review]

**Comment by anisa-hawes** [comment]
Thank you, @DanielAlvesLABDH & @jenniferisasi!

**Pull request merged**
