### PR TITLE
Issue 2748

### LINKED ISSUE #2748: Adding a new menu item events / eventos / manifestations / eventos
I am opening this Issue to signal that I'm adding a new menu item to our website which provides a space for listing future and past _Programming Historian_ events.

I propose the following menu headings: en/events, es/eventos, fr/manifestations, pt/eventos
and that each page will have two sections: 

en/events/future
en/events/past

es/eventos/futuros
es/eventos/pasados

fr/manifestations/futur
fr/manifestations/passé

pt/eventos/futuros
pt/eventos/passados

- [x] I'm going to begin preparing the necessary changes in `menu.html` and `snippets.yml` alongside template versions of the four new pages in a branch so I can make sure everything works.

- [x] @GeeAlmeida and I will connect next Friday 18th November and work together to populate these pages with information about November and December's events. Gisele will maintain the pages going forwards. Our idea is to include links to EventBrite registration pages for future events, and YouTube/links to other documentation for past events.

In creating the templates, I've been thinking about how best to formulate/present the multi-lingual list. I think it's important to a) make it clear which language the event will be co-ordinated in, b) simplify maintenance/translation of the page upon each update. I very much welcome feedback on this.

- [ ] When we're happy with the formatting, we'll seek feedback on the vocabulary choices, and I will be happy to make adjustments to my (very rough) translations as needed!

### PR DESCRIPTION
**Pull request by anisa-hawes**
1. I'm adding a new menu item to our website which provides a space for listing future and past Programming Historian events.

2. I am also collapsing the Vacancies tab into the About drop-down menu, and correcting the re-direct problem [which Daniel notes here](https://github.com/programminghistorian/jekyll/issues/2748#issuecomment-1320388838).

3. I am applying a small correction [advised by Daniel](https://github.com/programminghistorian/jekyll/issues/2748#issuecomment-1320388838) to the holding statement on /pt/vagas.md 

Closes #2748

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [ ] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Hello @spapastamkou / @programminghistorian/french-team,

I would be grateful if you could glance over this, and let me know if any corrections are needed.

I'm creating a new item on our navigation menu titled Events / Eventos / Manifestations / Eventos. Each one of the landing pages includes a short paragraph of text. The ES and PT teams have reviewed their pages, but I am not 100% confident it is correct in French (I'm very much still learning!).

https://deploy-preview-2749--ph-preview.netlify.app/fr/manifestations

I would appreciate your feedback before I move this forward and merge it in.

Thank you,
Anisa

**Comment by spapastamkou** [comment]
Done @anisa-hawes. If we have further edits in FR we can make them in the future. Thanks a lot!

**Comment by anisa-hawes** [comment]
Dear @acrymble,

Do you have time to review this for me? 

Daniel, Riva and Sofia have confirmed that they are happy with the PT, ES and FR text on the Events landing pages.  

I would like to ask if you are happy with the changes I've made to our top navigation bar?

- I've added Events to our navigation bar (menu-events)
- I've collapsed the Vacancies page into the About menu (menu-about-vacancies)

This PR also includes two corrections:
1. a problem with the re-direct from the postes-vacants / vacantes / vagas pages 
2. a small update the holding statement on /pt/vagas

**Review by acrymble — APPROVED** [review]

**Comment by acrymble** [comment]
thanks for doing this @anisa-hawes

**Pull request merged**
