### PR TITLE
check that author has bio in the appropriate language

### LINKED ISSUE #1373: Check script should confirm bio is present for author in the required language
the checks didn't catch the problem in #1372

### PR DESCRIPTION
**Pull request by mdlincoln**
This PR adds a new test to the check script. It ensures that there is an author bio for the page language in all lessons.

@programminghistorian/spanish-team This identified two lessons that need to have new translations - look at the Travis results on here to see the changes needed, and please add them to this PR.

@programminghistorian/technical-team Please look at the change in `validate_yaml.rb` to get a sense of how I added this test (sorry, it's not a very elegant script 😂)

closes #1373

### CODE REVIEW

**Review by walshbr — DISMISSED** [review]

**Review by mariajoafana — DISMISSED** [review]

**Comment by mdlincoln** [comment]
Hey @mariajoafana, you can't approve this until you fix the missing bios :)

See the missing biography report at: https://travis-ci.org/programminghistorian/jekyll/builds/558542854

**Comment by mdlincoln** [comment]
@programminghistorian/spanish-team Can you please add to this PR the translations for the two author bios that are currently in error, listed here: 

```
* In /es/lecciones/crear-exposicion-con-omeka.md:
  - [ ] 'Megan R. Brett' does not have a 'es' bio in ph_authors.yml.
* In /es/lecciones/introduccion-a-powershell.md:
  - [ ] 'Ted Dawson' does not have a 'es' bio in ph_authors.yml.
```

**Comment by jenniferisasi** [comment]
Ok. New Travis errors: 

> - ./_site/en/lessons/introduction-to-ffmpeg.html
340  *  External link https://filmcolors.org/2018/03/08/vian/ failed: 404 No error
341- ./_site/fr/equipe-projet.html
342  *  External link http://jenniferisasi.com failed: 404 No error
343- ./_site/posts/Uses-Of-The-Programming-Historian.html
344  *  External link http://wp.auburn.edu/dighist/?page_id=127 failed: 404 No error
345- ./_site/posts/buletin-de-information.html
346  *  External link https://programminghistorian.org/posts%20/%20riva-quiroga-joshua-ortiz failed: 404 No error

Will change my website url (my fault) and also check the post

**Comment by jenniferisasi** [comment]
Sorry @mdlincoln but I have to bother you on this one...
1) I've checked the authors file and my current URL is correct, why is it giving us an error when the FR version loops/connects to it? 
2) I've check the post [Bulletin de information](https://programminghistorian.org/posts/buletin-de-information) for the link about [Riva and Joshua joining the team](https://programminghistorian.org/posts/riva-quiroga-joshua-ortiz) and it works, ?!? 
3) External links 340 and 344 are "404 not found". 

Now I realize it says 404 no error, what does that mean?

**Comment by mdlincoln** [comment]
I'll check on it a bit more shortly

**Comment by mdlincoln** [comment]
OK, I just needed to update it off of the gh-pages branch. When PRs go for a very long time like this, they get out of date with the links that have already been fixed on the main site.

If you can please approve this, and then go ahead and merge :)

**Review by walshbr — APPROVED** [review]

**Comment by walshbr** [comment]
Approved!

**Pull request merged**
