### PR TITLE
Update ph_authors.yml

### PR DESCRIPTION
**Pull request by DanielAlvesLABDH**
Change Daniel's role to editorial and Eric's role to managing. Eric é o novo Editor-Chefe do Programming Historian em português.

*Please summarise the reason for your Pull Request here*

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Add the appropriate "Label"
- [ ] If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above
- [x] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Manager @anisa-hawes 
- [x] Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)
- [x] Assign at least one individual or team to "Reviewers"

### CODE REVIEW

**Comment by DanielAlvesLABDH** [comment]
O update falha por erro em link (http://www.brightspiral.com/tracery) no ficheiro /fr/lecons/intro-aux-bots-twitter.html 
@marie-flesch can you verify this, please? Happy New Year!

**Comment by anisa-hawes** [comment]
Olá @DanielAlvesLABDH. Happy New Year!

We'll take care of replacing this link! I'll rebase this PR when that's done. ☺️

**Comment by DanielAlvesLABDH** [comment]
Thank you @anisa-hawes. Happy New Year

**Comment by anisa-hawes** [comment]
Feliz Ano Novo @ericbrasiln! Congratulations on this new role! ⭐ 

I'm looking forward to connecting with you next week to talk through our shared workflows and any questions you may have.

Daniel has prepared this PR to update the labels across our Project Team pages. [Reviewing the Preview](https://deploy-preview-3135--ph-preview.netlify.app/pt/equipe#programming-historian-em-portugu%C3%AAs), you will notice that your profile is now labelled **Editor-chefe**. This is achieved with a small adjustment to the `ph_authors.yml` file:

```
team_roles:
    - managing
```

or 

```
team_roles:
    - editorial
```

The various roles held by people across the Project Team are defined and translated in a separate file: [`/_data/teamroles.yml`](https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/teamroles.yml) if you are interested to learn how that works ✨ 

I'll leave it to you to review this PR when you're ready. Let me know if you have any questions.

**Review by ericbrasiln — APPROVED** [review]
All good!

**Comment by ericbrasiln** [comment]
Hello! 
What a great news. 
I'm very happy to be taking on this new role. Thanks to @DanielAlvesLABDH for the partnership and @anisa-hawes for the support.

Happy new year!

**Pull request merged**
