### PR TITLE
Adding crossref.xml to PT

### PR DESCRIPTION
**Pull request by ZoeLeBlanc**
This PR is for issue #1802 and adds a `crossref.xml` to the PT section of the site. To generate the actual XML, I had to generate the PT portion of the site so currently in this PR, PT is live and in the _config.yml I have `# - pt`. Currently the PT crossref.xml is empty since we have no lessons in the PT folder.

Tbh, I don't fully understand this process but I've emailed Tim at Sussex to hopefully get the ball rolling.

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [ ] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [ ] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by DanielAlvesLABDH** [comment]
Hi @ZoeLeBlanc hope you are well. We have a first lesson ready here: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/lessons/portuguese/propostas/preservar-os-seus-dados-de-investiga%C3%A7%C3%A3o.md Do I need to do something else, or change the location of the file? Sorry for asking but is the first one! Thanks in advance

**Comment by ZoeLeBlanc** [comment]
Hi @DanielAlvesLABDH! Lesson looks great but our current policy is that once a lesson is ready to go you actually need to move it over this repository. Instructions are under our Editor Guidelines on the site https://programminghistorian.org/en/editor-guidelines#3-move-the-files and I'm happy to help answer any questions you have or set a time to help walk you through the process.

**Comment by DanielAlvesLABDH** [comment]
Thank you @ZoeLeBlanc will do that today with the help of @joanacvp , after the meeting of my Department

**Comment by rivaquiroga** [comment]
@DanielAlvesLABDH, I'm also happy to help, in case you need it.

**Comment by ZoeLeBlanc** [comment]
@walshbr thanks for offering to help fix bugs! I think I've fixed the majority of the links but one thing I need help with is this favicon /images/favicons/pt_favicon.ico, which doesn't seem to exist? Any ideas?

~For @DanielAlvesLABDH one thing to clarify is if you want to use Privacidade or Privacidad for your privacy policy. You use both spellings and we need to be consistent. Thanks!~  Never mind, just saw it's just a file naming issue.

**Comment by walshbr** [comment]
@ZoeLeBlanc That isn't on the wiki, so I'll add it as a step and look a little more into what those are.

**Comment by ZoeLeBlanc** [comment]
We're also missing this post `/posts/compromissodePHcomadiversidade`. Is this supposed to be published somewhere?

**Comment by ZoeLeBlanc** [comment]
@DanielAlvesLABDH before you move over the lesson today, would you mind letting me know about this post `/posts/compromissodePHcomadiversidade`? I think you want to reference this post from 2016 `/posts/PH-commitment-to-diversity` so are you planning to translate this original post? If not, we can quickly update the link.

Thanks!

**Comment by walshbr** [comment]
And just because it's not clear offhand (and might be part of the confusion) - the blog posts are typically not translated. You certainly could translate it, but what you see in that folder is what exists. The Comms team has been translating some of the newsletters in recent years though.

**Comment by DanielAlvesLABDH** [comment]
@ZoeLeBlanc and @walshbr we are going to move the files now (last two days were madness with a lot of Department meetings). Just to clarify: do we need to translate that post on diversity? Isn't that statement already included in the About section?

**Comment by walshbr** [comment]
@DanielAlvesLABDH - Blog posts are typically not translated, and if you look at the French and Spanish editorial guidelines they also just link to the English post at /posts/PH-commitment-to-diversity. So I'd just go with that - link to the original English.

**Comment by walshbr** [comment]
Blog posts typically aren't translated. If you look at the French and Spanish editorial guidelines, they both just link to the English version of that same post. So I would just do that and change that link to /posts/PH-commitment-to-diversity.

**Comment by walshbr** [comment]
There are also a couple things missing in FYI (you might be aware already) - 
* In /pt/licoes/preservar-os-seus-dados-de-investigacao.md:
  - [ ] 'review-ticket' is missing.
  - [ ] 'doi' is missing.

**Comment by DanielAlvesLABDH** [comment]
Hi @walshbr the doi is missing because we can't ask for it before the lesson is live, or so I understand from the last messages from @ZoeLeBlanc . Sorry if I understand wrongly. As for the review ticket it's strange because it is there when I open the "edit file" but doesn't show on the preview file

**Comment by walshbr** [comment]
@ZoeLeBlanc, based on https://github.com/programminghistorian/jekyll/wiki/How-to-Request-a-new-DOI, it looks like you request the DOI first, which gets us the actual DOI link, paste it in the file, merge it in, then report back to Sussex. Maybe the process was just different here because it is the first lesson, so the crossref.xml didn't exist yet?

FWIW the fact that DOI is a required field for travis or the site won't build means that the lessons are not allowed to go live without a DOI. It's required that we have something for that field first.

**Comment by walshbr** [comment]
Oh I see @DanielAlvesLABDH - for the review ticket you need the whole URL, not just the number. I.e. - https://github.com/programminghistorian/ph-submissions/issues/237. It should work if you switch it to the whole URL.

**Comment by ZoeLeBlanc** [comment]
So the issue is that we didn't have the crossref.xml live so according to Tim at Sussex we couldn't ask for any DOIs, which was why I was hoping to get the PT site live before we added the lesson 😅. I might have to create a new branch just to get PT live without the lesson and then we can request the DOI 🤔

**Comment by ZoeLeBlanc** [comment]
Also this is our first time setting up a new language with DOIs so lots of bugs in the process are expected so thanks for bearing with us @DanielAlvesLABDH 🙏

**Comment by walshbr** [comment]
Yeah I think we'd need to…get PT and crossref live. Request the DOI. Push the lesson live. Confusing! haha

**Comment by ZoeLeBlanc** [comment]
Alrighty just created the new PR for crossref to go live. Once that's merged in, I'll contact Tim to get the DOI process started and once we have that we can update this lesson and merge it in.

**Comment by walshbr** [comment]
Oh that's a good catch.

**Review by DanielAlvesLABDH — DISMISSED** [review]

**Comment by DanielAlvesLABDH** [comment]
Thanks! 😊

**Review by walshbr — APPROVED** [review]

**Comment by ZoeLeBlanc** [comment]
Looks great to me! Gonna merge this in and thanks @walshbr and @jenniferisasi for tracking down this final crossref issue 👏

**Comment by DanielAlvesLABDH** [comment]
It's LIVE! It looks great! Many thanks to you all!

**Pull request merged**
