### PR TITLE
Update exploring-and-analyzing-network-data-with-python.md

### LINKED ISSUE #2867: Exploring and Analyzing Network Data with Python - new major code release
## If you are reporting a problem with a lesson, please try to provide us with the following information:  

- Exploring and Analyzing Network Data with Python by @jrladd and others.
- Using Mac & Python 3.x

The tutorial was published in 2017 and advised using Networkx version 2.4. The Networkx module's latest stable release is 3.0, and from my experience working with students in the classroom, they tend to install the latest version of software, not necessarily the version used in the tutorial.  In this case, that would cause an error because one of the functions used in the tutorial was deprecated in version 3.0.

` print(nx.info(G)) `

I've checked the Networkx notes and .info was deprecated in the move from networkx 2x to 3x. (“Remove deprecated function nx.info (#5759)”) - https://networkx.org/documentation/stable/release/release_3.0.html. I haven’t been able to find a replacement, nor details of why it was deprecated. Just that it was. This means the brief example following that line of code can’t be replicated if using 3.x or newer.

To future-proof this lesson, my recommendation is to advise downloading the latest version of networkx in the "Data Prep and NetworkX Installation" section (instead of specifying 2.4). This is in line with our sustainability practices.

Then simply removing the section: 

` Finally, you can get basic information about your newly-created network using the info function:

print(nx.info(G))

The info function gives five items as output: the name of your graph (which will be blank in our case), its type, the number of nodes, the number of edges, and the average degree[4](https://programminghistorian.org/en/lessons/exploring-and-analyzing-network-data-with-python#fn:averagedegree) in the network. The output should look like this:

Name:
Type: Graph
Number of nodes: 119
Number of edges: 174
Average degree:   2.9244 `

and the code line 

`print(nx.info(G)) # Print information about the Graph`

Everything else works fine. This is not a bug in the original tutorial, but a sustainability suggestion to move forward, and avoid confusion in users.

### PR DESCRIPTION
**Pull request by anisa-hawes**
- Integrate small tweaks to update to NetworkX 3.1

Closes #2867

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Add the appropriate "Label"
- [x] If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above
- [x] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Assistant @anisa-hawes 
- [x] Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines), then assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR.

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Olá @DanielAlvesLABDH and @ericbrasiln, 

I hope you're both well. 

John Ladd (EN team member + one of the original authors of [Exploring and Analyzing Network Data with Python](https://programminghistorian.org/en/lessons/exploring-and-analyzing-network-data-with-python)) has prepared an update to this lesson so that the code works using NetworkX 3.1. 

I'd like to ask if you might have time to help with updating the recently published Portuguese translation [Explorar e Analisar Dados de Rede com Python](https://programminghistorian.org/pt/licoes/explorar-analisar-dados-rede-python)?

The changes to the code are minimal (I've slotted these in https://github.com/programminghistorian/jekyll/pull/3008/commits/d669b197be8cb67aa85926ff865816ca2a2feb79), but there are two paragraphs of text which need adjusting too. 

In the PT Markdown it is the paragraphs at line 111 and line 185:

**111**
Recentemente, o NetworkX atualizou para a versão 2.0. Se estiver a encontrar problemas com o código abaixo e tiver trabalhado com o NetworkX antes, pode tentar atualizar o pacote acima com `pip3 install networkx==3.1 --upgrade`.

We want to update this to read:

A quick note on versioning: this tutorial uses NetworkX 3.1, but the library is in active development and is updated frequently. We recommend using the installation command above to ensure your version of NetworkX matches the code below (rather than simply installing the latest version). If you have an older version of NetworkX already installed, you should run `pip3 install networkx==3.1 --upgrade` before trying the tutorial.

**185**
A função `info` dá uma lista de cinco itens como _output_: o nome do seu grafo (que estará em branco no nosso caso), o seu tipo, o número de nós, o número de _edges_, e o grau médio[^7] na rede. 

We want to update this to read:

This tells you your network's type (in this case, it's a standard Graph object) and the number of nodes and edges in the network.

**Comment by DanielAlvesLABDH** [comment]
Hello @anisa-hawes. I think the two changes can be translated like this:
111: Uma nota curta sobre controle de versão: este tutorial usa NetworkX 3.1, mas a biblioteca está em desenvolvimento ativo e é atualizada com frequência. Recomendamos usar o comando de instalação acima para garantir que a sua versão do NetworkX corresponde ao código abaixo (em vez de simplesmente instalar a versão mais recente). Se já tiver uma versão mais antiga do NetworkX instalada, execute pip3 install networkx==3.1 --upgrade antes de tentar o tutorial.

185: A função info informa o tipo da sua rede (neste caso, é um objeto Graph padrão) e o número de nós e arestas na mesma.

Thanks for the update

**Comment by ericbrasiln** [comment]
Hi @DanielAlvesLABDH e @anisa-hawes 

On line 111, in the Portuguese translation, we decided to put a translation note on this issue of versioning.

As the original lesson has been updated, we can delete Note 5. What do you think?

And we should update line 108 from `pip3 install networkx==2.4`  to `pip3 install networkx==3.1`

**Comment by anisa-hawes** [comment]
Thank you, @ericbrasiln.

I _think_ all the instances of 2.4 have been replaced with 3.1 in this commit (including line 108): https://github.com/programminghistorian/jekyll/commit/d669b197be8cb67aa85926ff865816ca2a2feb79

I'm happy to remove the note if you don't feel it is needed. Maybe it is worth keeping? As you explain, (if my rough translation is correct) the library is under active development and is updated frequently. But I leave this decision to you.

If we opt to remove it, I can also re-number the subsequent endnotes as appropriate.

**Comment by ericbrasiln** [comment]
Sorry I missed [that commit](https://github.com/programminghistorian/jekyll/commit/d669b197be8cb67aa85926ff865816ca2a2feb79)! 

About the note: we can keep it, but I suggest this update:

>É importante lembrar que existem variações entre as diferentes versões do NetworkX que podem resultar em erros ou outputs diferentes. Tal é o caso da 2.6, com a qual obtivemos uma mensagem de erro durante a avaliação da modularidade e uma resposta diferente com a função print(nx.info(G)) daquela apresentada com a 2.4.

**Review by ericbrasiln — APPROVED** [review]
Ok!

**Pull request merged**
