### PR TITLE
updates to beautiful soup tutorial to address issues from #1347. 

### PR DESCRIPTION
**Pull request by jerielizabeth**
requires review. 

Attn @drjwbaker 

(and clearly I can no longer spell ... "embarrassing" typo.)

### CODE REVIEW

**Comment by drjwbaker** [comment]
What type of machine do you recommend that I test this on?

**Comment by jerielizabeth** [comment]
If you can confirm that it works on a Mac and with Linux that’d be great! The issue mentioned that it didn’t work well in windows but that may be a larger problem.

**Comment by drjwbaker** [comment]
@jerielizabeth Tested on Mac. Two questions.

1. The final code block produces the attached error. Is this okay? 
Screenshot 2019-08-29 at 09 26 03

2. The final code block has lots of (what looks to me as a Python novice as) commented out code. Do we need all that?

**Comment by drjwbaker** [comment]
I'll test on Linux when I'm on a Linux machine next week.

**Comment by jerielizabeth** [comment]
1. Yeah ... I think they changed their website a bit since I first created the lesson and there are a few additional strings that should be deleted for it to work as it did originally. It is not a fatal error and I can fix it - it will just require adding a few more steps to the lesson. Hitting that balance between updating and rewriting again.

2. There is a lot of commented out code, to address the concern in the issue about code being removed. Not sure which is the less confusing way when writing an executable file ... happy to change back to removing, rather than commenting out.

**Review by drjwbaker — CHANGES_REQUESTED** [review]
Confirm this works on Mac and Linux (I don't have a Windows machine for testing). On commented our text https://github.com/programminghistorian/jekyll/pull/1415#issuecomment-526931565, can I suggest a small revision that a) *briefly* explains what commented our code is (as this is an Medium difficult lesson and full explanation is not appropriate), and b) notes why keeping commented code in can be useful. Happy then to pull this to the main repo.

**Comment by jerielizabeth** [comment]
@drjwbaker Added some brief language about the commenting.

**Review by drjwbaker — DISMISSED** [review]

**Comment by drjwbaker** [comment]
@programminghistorian/technical-team sorry to be a pain, but I've run out of talent trying to understand the Travis build fail here. I'm happy to merge this PR once the build fail is resolved. Ta!

**Comment by walshbr** [comment]
```
- ./_site/en/lessons/transforming-xml-with-xsl.html
  *  External link http://www.tei-c.org/index.xml failed: 404 No error
```
Means that in the transforming-xml-with-xsl lesson there is a link to the TEI website that no longer resolves. Looking at the internet archive, it looks like that link used to go to the main index page of the TEI consortium. So I'd just update the link to direct to https://tei-c.org @drjwbaker.

**Comment by drjwbaker** [comment]
@walshbr Huh. Didn't realise that a build fail on files not included in a PR would make Travis fail. Fixed now. Can someone please merge when the Travis checks are complete.

**Comment by walshbr** [comment]
I think it was still failing because that lesson was translated, so the Spanish lesson also linked to the bad link. Let's let that run and then I'll merge if it comes through.

**Review by walshbr — APPROVED** [review]

**Comment by drjwbaker** [comment]
Ta.

**Pull request merged**
