### PR TITLE
add adapted images to Spanish from tutorial on XSL

### PR DESCRIPTION
**Pull request by arojascastro**
I just added the translation to Beal's tutorial on XSLT. These are the images required for the Spanish version -- with adaptions.

### CODE REVIEW

**Comment by mdlincoln** [comment]
Is there also supposed to be a new translation here? Right now it's just images and this new ZIP file.

**Comment by arojascastro** [comment]
Yes, this translation: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/traducciones/transformaci%C3%B3n-datos-xml-xsl.md

**Comment by mdlincoln** [comment]
Sorry, maybe I am confused. Are you ready to publish that translation? If so, then you need to add the .md file to this PR too.

**Comment by arojascastro** [comment]
No, no, it needs to be reviewed yet. But the reviewers may want to check out the file and see the images. Shoud I added them somewhere else?

**Comment by mdlincoln** [comment]
OK I see. These need to be added to the ph-submissions repo like all the files and images for lessons and translations under review, not this one.

**Comment by arojascastro** [comment]
ops, sorry!

**Pull request closed without merging**
