### PR TITLE
Twitter lesson fix

### PR DESCRIPTION
**Pull request by ZoeLeBlanc**
This commit should reopen the previous twitter lesson edits for review without erasing subsequent changes to the repository. @anisa-hawes when you get a chance could you take a look and confirm that's correct? Thanks!!

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] ~~if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines]~~(https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] ~~If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above~~

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Thank you for your support to resolve this @ZoeLeBlanc! As soon as the build is complete, I'll check it through!

**Review by anisa-hawes — APPROVED** [review]

**Comment by anisa-hawes** [comment]
Hello @svmelton, this PR is a little complicated...! 

In short, it fixes one I somehow managed to Merge without your Review... But, with Zoe's magical help, it is here, ready for you to check over. 

It relates to the updates we've been discussing in 2087 re: the "Beginner's Guide to Twitter Data" lesson.

**Comment by svmelton** [comment]
Thanks @anisa-hawes! I just updated the PR so it includes the most recent publication.

**Comment by anisa-hawes** [comment]
Perfect! Are you happy with these changes to the lesson?

**Pull request merged**
