### PR TITLE
Slowing re-adding open refine lesson as site will not compile.

### PR DESCRIPTION
**Pull request by jerielizabeth**
Attempting to identify whatever is preventing the site from compiling. 

First removing the lesson files. Leaving the update to the travis script for Project Gutenberg and my edits to my bio.

### CODE REVIEW

**Comment by jerielizabeth** [comment]
@mdlincoln Do you have any idea what might be going on here? It seems to all be passing in the final checks, but once merged in, the site is failing to build.

**Comment by mdlincoln** [comment]
@jerielizabeth did you manage to work this out? I see the request is merged, and everything looks like it's built ok.

**Comment by jerielizabeth** [comment]
Hm, I am still seeing a failure to build on from Github and the new lesson is not in the build.

**Comment by jerielizabeth** [comment]
deleting branch and will create a new one for future trials.

**Pull request merged**
