### PR TITLE
Update ph_authors.yml with François's new affiliation; closes Issue #1453

### PR DESCRIPTION
**Pull request by fdlaramee**
Update to my institutional affiliation and bio. Will need a one-sentence translation from @programminghistorian/spanish-team. Thanks!

### CODE REVIEW

**Review by spapastamkou — DISMISSED** [review]

**Comment by acrymble** [comment]
Did you want the Spanish description updated?

**Comment by fdlaramee** [comment]
@acrymble Ideally, yes.

**Comment by acrymble** [comment]
François Dominic Laramée is a postdoctoral fellow in digital history of medicine at the University of Ottawa, in Canada.

François Dominic Laramée es investigador postdoctoral de historia digital de medicina de Universidad d'Ottawa en Canada.

Confirmed by a native Spanish speaker.

**Comment by fdlaramee** [comment]
Thanks @acrymble; I have added the translation to ph_authors and removed the request for a translation/review from the Spanish team.

Sorry @spapastamkou ; can you please approve again?

**Review by acrymble — DISMISSED** [review]

**Review by jenniferisasi — CHANGES_REQUESTED** [review]
Thanks @acrymble for taking the lead in doing the Spanish translation. It needs changes: 
de Universidad --> en la Universidad  
de medicina --> de la medicina 
Universidad d'Ottawa --> Universidad de Ottawa 
Canada --> Canadá

I'm going to try to make the change myself. 

Update: Won't let me introduce the changes in the edited file that is pending approval; if I click "edit" it takes me to the original file without the changes. I think @fdlaramee has to make the changes?

**Review by spapastamkou — APPROVED** [review]

**Comment by mdlincoln** [comment]
@jenniferisasi are you sure you're unable to edit the file? You should be able to edit the version on this branch by going to the "Files changed" tab and then clicking here:

Screen Shot 2019-09-27 at 8 12 31 AM

**Comment by mdlincoln** [comment]
PS the broken links will be fixed by #1468 so just ping me when this is finally ready to go and I'll override the failing checks.

**Comment by mdlincoln** [comment]
n/m I see that @spapastamkou has put in the changes

**Review by jenniferisasi — COMMENTED** [review]
All is good now.

**Pull request merged**
