### PR TITLE
Update topics.yml

### LINKED ISSUE #2947: New topic: Creative coding
The ES team is [about to publish a lesson](https://github.com/programminghistorian/ph-submissions/issues/509) that doesn't fall under any of the topics or categories we have available at the moment, thus, we propose the creation of a new tag along the lines of "creative coding" (using [Wikipedia article](https://en.wikipedia.org/wiki/Creative_coding) as reference). 

 type: creative-coding
  displayname:
    en: "Creative coding"
    es: "Programación creativa"
    fr: "Code créatif"
    pt: "Código criativo"
  description:
    en: "Lessons for creating expressive rather than functional products with programming."
    es: "Lecciones para crear productos expresivos en vez de funcionales con programación."
    fr: "Leçons pour créer des produits expressifs plutôt que fonctionnels avec la programmation"
    pt: "Lições para criar produtos expressivos em vez de funcionais com a programação"

Do you like this definition? 

Reminder: Update _[Interactive Fiction in the Humanities Classroom](https://github.com/programminghistorian/jekyll/blob/gh-pages/en/lessons/interactive-text-games-using-twine.md)_ once this is ready.

### PR DESCRIPTION
**Pull request by anisa-hawes**
Add new topic: `- type: creative-coding`

Closes #2947 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Add the appropriate "Label"
- [x] If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above
- [x] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Assistant @anisa-hawes 
- [ ] ~~Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)~~
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines), then assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR.

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Dear @marie-flesch and @DanielAlvesLABDH,

May I ask if you could review my FR and PT translation of a new `topic:` and `description:`?

```
- type: creative-coding
  displayname:
    en: "creative coding"
    es: "programación creativa"
    fr: "code créatif"
    pt: "código criativo"
  description:
    en: "Lessons for creating expressive rather than functional products with programming."
    es: "Lecciones para crear productos expresivos en vez de funcionales con programación."
    fr: "Leçons pour créer des produits expressifs plutôt que fonctionnels avec la programmation."
    pt: "Lições para criar produtos expressivos em vez de funcionais com a programação."
```

You can add a comment here with your suggested changes, or [edit the file directly in this branch](https://github.com/programminghistorian/jekyll/pull/2947/files).

Please note: this new topic will not show in the Netlify preview or on the live lesson indexes for each journal until it is included in at least one lesson’s YAML.

-- 

Thank you for suggesting this @nllano and @jenniferisasi 🙂

**Comment by DanielAlvesLABDH** [comment]
Done @anisa-hawes

**Comment by anisa-hawes** [comment]
Obrigado, @DanielAlvesLABDH!

**Comment by marie-flesch** [comment]
Awesome new topic!
It's all good for me, no edit needed!

**Comment by anisa-hawes** [comment]
Merci beaucoup, @marie-flesch!

**Review by jenniferisasi — APPROVED** [review]

**Pull request merged**
