### PR TITLE
Change references from current GH desktop to GHD "classic"

### LINKED ISSUE #1012: Confused by instructions on getting-started-with-github-desktop.md
Hi,

I've been slowly working my way through https://github.com/programminghistorian/jekyll/blob/gh-pages/en/lessons/getting-started-with-github-desktop.md

I'm using Windows and I got as far as "Making changes remotely" and the part which says "We will see the sync button on 'GitHub Desktop'. I'm afraid I can't see a sync button like the one pictured. Is it a Windows/Mac thing maybe? It's at line 274

Cheers

Rachel

### PR DESCRIPTION
**Pull request by mdlincoln**
I've made a few substantive changes:

1. Added a warning to the top of the lesson explaining that it uses an old version
2. Updated install instructions
3. Removed references to Windows - the lesson doesn't actually show any Windows interface, anyway
4. Removed the public GitHub desktop link referenced at the end

This lesson has been translated, and so these changes will also need to be translated before merging.

Closes #1012

### CODE REVIEW

**Comment by arojascastro** [comment]
Thanks Matthew. I'll try to work on it on the weekend. You can merge if you want (if that helps to finish some tasks) and close this. I won't forget.

**Comment by mdlincoln** [comment]
Thanks @arojascastro. Let's follow the usual workflow - please add your commits to `github-desktop-classic` branch and we'll merge when it's all ready.

**Comment by arojascastro** [comment]
Done! Sorry for the delay.

Question: Most of changes were deletions of spaces, right? I did not see anything else in paragraphs places at the bottom.

**Review by arojascastro — APPROVED** [review]
Gracias

**Comment by mdlincoln** [comment]
@arojascastro ah, you're right! Sorry, I think I accidentally set my text editor to start deleting extra spaces automatically - which is bad behavior for this shared project. Thank you for translating the actual text changes, and I'm sorry that the change log was so confusing :(

**Pull request merged**
