### PR TITLE
Extracting-keywords.md

### PR DESCRIPTION
**Pull request by acrymble**
Added csv handling to auto-write output to new output.csv file @ editor’s request

### CODE REVIEW

**Comment by wcaleb** [comment]
@acrymble This Pull Request was made on the `master` branch instead of the `gh-pages` branch, which is one reason why I think it's rolling in so many unrelated commits. Is there a reason you did the edit as a pull request instead of directly editing the lesson in question?

**Comment by acrymble** [comment]
Because I was trying to follow the submission guidelines. Forking and
pulling and git in general is not something I find intuitive. I also had to
change a file in the assets folder which I can't do online.

**Comment by acrymble** [comment]
I obviously did this wrong because the files I was trying to add aren't anywhere to be seen.

**Comment by wcaleb** [comment]
I will try to improve the documentation on submitting a pull request. It *is* pretty bare bones at the moment. One of our Fellows is also working on a screencast.

If I understand correctly, [this is the lesson](https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/extracting-keywords.md) that you are trying to edit? If it's just a small tweak, then since you already have editing privileges on our repo, I think the easiest thing to do for now would be to edit directly on the file linked above.

If you'd like to send me the assets file you need to change, I can do that for you this time until our documentation is improved.

**Comment by fredgibbs** [comment]
the tutorial is now visible at
http://programminghistorian.org/lessons/extracting-keywords. it looks fine
to me with your CSV revisions--is this ready for review? i thought there
were some issues getting things in the repository, but i don't see anything
amiss.

also, if you need to make further revisions, make sure you start with this
version of the file (either git pull it into your local repo or copy and
paste the md code into your editor), as i had to make a few minor commits
(fixing a link and removing smart quotes from the an image caption
directive) to get the page to build correctly.

looking good!

On Fri, Jun 19, 2015 at 7:55 AM, W. Caleb McDaniel <notifications@github.com
> wrote:

> I will try to improve the documentation on submitting a pull request. It
> *is* pretty bare bones at the moment. One of our Fellows is also working
> on a screencast.
>
> If I understand correctly, this is the lesson
> <https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/extracting-keywords.md>
> that you are trying to edit? If it's just a small tweak, then since you
> already have editing privileges on our repo, I think the easiest thing to
> do for now would be to edit directly on the file linked above.
>
> If you'd like to send me the assets file you need to change, I can do that
> for you this time until our documentation is improved.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/programminghistorian/jekyll/pull/108#issuecomment-113521992>
> .
>



-- 
frederick w gibbs | assistant professor of history | univ. of new mexico
fredgibbs.net | @fredgibbs
<http://www.twitter.com/fredgibbs>

**Comment by acrymble** [comment]
Yes, ready for review.

Caleb helped get everything in order.

All the best, Adam

**Pull request closed without merging**
