### PR TITLE
Issue 2525

### LINKED ISSUE #2525: Update links to our most recent Zenodo deposit.
I am updating links on the following pages 

/en/about
/es/acerca-de
/fr/apropos
/pt/sobre

so that we are providing a direct click to our most recent Zenodo deposit (created November 2021).

### PR DESCRIPTION
**Pull request by anisa-hawes**
I am updating links on the following pages

/en/about 
/es/acerca-de 
/fr/apropos 
/pt/sobre

so that we are providing a direct click to [our most recent Zenodo deposit (created November 2021)](https://doi.org/10.5281/zenodo.5645020).

Closes #2525 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Hello @programminghistorian/portuguese-team. 

I noted as I updated the Zenodo links on sobre.md, that the PT page is missing a sentence about the UK Web Archive, who crawl our whole website regularly as part of their domain crawl.

May I ask if @joanacvp or anybody else has a moment to translate it? If so, I can make this addition.

> Since 2018, the [UK Web Archive](https://www.webarchive.org.uk/) has made regular crawls of the _Programming Historian_. These are archived and made publicly available [via their website](https://www.webarchive.org.uk/wayback/en/archive/*/http://programminghistorian.org/).

Thank you!

**Comment by joanacvp** [comment]
Hello @anisa-hawes. It should be like:

Desde 2018, o [UK Web Archive](https://www.webarchive.org.uk/) faz rastreamentos regulares ao Programming Historian. Estes são arquivados e disponibilizados ao público no seu [website](https://www.webarchive.org.uk/wayback/en/archive/*/http://programminghistorian.org/).

**Comment by anisa-hawes** [comment]
Thank you, @joanacvp! 🌟

**Comment by anisa-hawes** [comment]
Hello Antoine @icolab. Just to let you know, I've made the correction you noted part of this PR instead, because a large number of changes have been made to our site since your patch was created! Thank you!

**Review by acrymble — APPROVED** [review]

**Pull request merged**
