### PR TITLE
Updating contact information

### PR DESCRIPTION
**Pull request by svmelton**
Updating my contact info with new position. This will need translation of my position title in the authors file from @programminghistorian/french-team, @programminghistorian/spanish-team, and @programminghistorian/portuguese-team.  @rivaquiroga @DanielAlvesLABDH @spapastamkou  

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

### CODE REVIEW

**Comment by DanielAlvesLABDH** [comment]
Hi @svmelton, this one, although short it's not easy to translate. My best guess would be "Sarah Melton é Formadora de Programadores de Software na Sourcegraph."

**Comment by jenniferisasi** [comment]
@svmelton sorry to take over your PR :) but in the spirits of making it everything easier for everyone, I am wondering if @spapastamkou and @isag91 want to take advantage of this same PR? If I don't hear from them, I'll proceed with the Spanish translation of Sarah's update.

**Comment by spapastamkou** [comment]
@jenniferisasi I did a silent commit already but if @isag91 or someone else want to request/make directly changes I have nothing against :-)

**Comment by isag91** [comment]
Committed my changes just now ! Thanks :)

**Comment by jenniferisasi** [comment]
Oh, this PR needs to be updated with the latest gh-pages,the Netlify preview doesn't show the latest PR which made these banners:
Screen Shot 2021-12-06 at 12 25 30 PM

**Review by spapastamkou — APPROVED** [review]

**Pull request merged**
