### PR TITLE
Add avatar_alt text to lesson header images

### LINKED ISSUE #1324: alt-text descriptions for lesson galley images
re: #1315 

Technically, we can set this up to as new variables in the lesson metadata, aka

```yaml
avatar_alt: "A compass rose"
```

We will need to write all those descriptions, though! Perhaps if we can split up the work across a few volunteers so that we each write 10-20 descriptions? I'm happy to take on a set of english descriptions.

### PR DESCRIPTION
**Pull request by mdlincoln**
closes: #1324

To-do:
- [x] determine if/how to do alt-text-translations
- [x] generate to-do list of lessons that need alt text
- [x] get all translations done
- [x] update editor guidelines and YAML template with `avatar_alt` fields
- [x] add `avatar_alt` to required fields in travis checks

### CODE REVIEW

**Comment by walshbr** [comment]
- [ ] analisis-voyant-tools.png
- [ ] analyzing-documents-with-tfidf.png
- [ ] applied-archival-downloading-with-wget.png
- [ ] automated-downloading-with-wget.png
- [ ] basic-text-processing-in-r.png
- [ ] building-static-sites-with-jekyll-github-pages.png
- [ ] cleaning-data-with-openrefine.png
- [ ] cleaning-ocrd-text-with-regular-expressions.png
- [ ] code-reuse-and-modularity.png
- [ ] corpus-analysis-with-antconc.png
- [ ] corpus-paralelo-lfaligner.png
- [ ] correspondence-analysis-in-R.png
- [ ] counting-frequencies-from-zotero-items.png
- [ ] counting-frequencies.png
- [ ] creating-an-omeka-exhibit.png
- [ ] creating-and-viewing-html-files-with-python.png
- [ ] creating-apis-with-python-and-flask.png
- [ ] creating-mobile-augmented-reality-experiences-in-unity.png
- [ ] creating-network-diagrams-from-historical-sources.png
- [ ] creating-new-items-in-zotero.png
- [ ] data-mining-the-internet-archive.png
- [ ] data_wrangling_and_management_in_R.png
- [ ] dealing-with-big-data-and-network-analysis-using-neo4j.png
- [ ] downloading-multiple-records-using-query-strings.png
- [ ] editing-audio-with-audacity.png
- [ ] editor-guidelines.png
- [ ] exploring-and-analyzing-network-data-with-python.png
- [ ] extracting-illustrated-pages.png
- [ ] extracting-keywords.png
- [ ] fetch-and-parse-data-with-openrefine.png
- [ ] from-html-to-list-of-words-1.png
- [ ] from-html-to-list-of-words-2.png
- [ ] generating-an-ordered-data-set-from-an-OCR-text-file.png
- [ ] geocoding-qgis.png
- [ ] geoparsing-text-with-edinburgh.png
- [ ] georeferencing-qgis.png
- [ ] geospatial-data-analysis.png
- [ ] getting-started-with-github-desktop.png
- [ ] getting-started-with-markdown.png
- [ ] getting-started-with-mysql-using-r.png
- [ ] googlemaps-googleearth.png
- [ ] graph-databases-and-SPARQL.jpg
- [ ] graph-databases-and-SPARQL.png
- [ ] gravity-model.png
- [ ] installing-omeka.png
- [ ] installing-python-modules-pip.png
- [ ] intro-to-augmented-reality-with-unity.png
- [ ] intro-to-bash.png
- [ ] intro-to-beautiful-soup.png
- [ ] intro-to-linked-data.png
- [ ] intro-to-powershell.png
- [ ] intro-to-the-zotero-api.png
- [ ] intro-to-twitterbots.png
- [ ] introduction-and-installation.png
- [ ] introduction-to-ffmpeg.png
- [ ] introduction-to-populating-a-website-with-api-data.png
- [ ] introduction-to-stylometry-with-python.png
- [ ] json-and-jq.png
- [ ] keywords-in-context-using-n-grams.png
- [ ] linux-installation.png
- [ ] mac-installation.png
- [ ] manipulating-strings-in-python.png
- [ ] mapping-with-python-leaflet.png
- [ ] naive-bayesian.png
- [ ] normalizing-data.png
- [ ] output-data-as-html-file.png
- [ ] output-keywords-in-context-in-html-file.png
- [ ] preserving-your-research-data.png
- [ ] qgis-layers.png
- [ ] r-basics-with-tabular-data.png
- [ ] research-data-with-unix.png
- [ ] sentiment-analysis.png
- [ ] sonification.png
- [ ] sustainable-authorship-in-plain-text-using-pandoc-and-markdown.png
- [ ] temporal-network-analysis-with-r.png
- [ ] text-mining-with-extracted-features.png
- [ ] topic-modeling-and-mallet.png
- [ ] transforming-xml-with-xsl.png
- [ ] transliterating.png
- [ ] understanding-regular-expressions.png
- [ ] up-and-running-with-omeka.png
- [ ] using-javascript-to-create-maps.png
- [ ] vector-layers-qgis.png
- [ ] viewing-html-files.png
- [ ] visualizing-with-bokeh.png
- [ ] windows-installation.png
- [ ] working-with-text-files.png
- [ ] working-with-web-pages.png

**Comment by jenniferisasi** [comment]
About to add the list of lessons in Spanish to the list created by @walshbr  (will delete this comment later)

**Comment by mdlincoln** [comment]
So, in the last 90sec of our call @programminghistorian/technical-team I realized a flaw in the change we just made add multilingual lesson alt text. It's actually not necessary - here's why: although the lesson IMAGE file is shared between all versions of a lesson, the alt text lives in the actual lesson markdown. That makes it like the `title` or `abstract` of the lesson - it IS something that needs to be translated, but it's NOT something that uses the en/es/fr yaml construction. You just have a spanish title in the spanish markdown file, a french title in the french markdown file, and so on. What this means is that just having

```
avatar_alt: Alt text here
```

in the yaml header is sufficient.

Therefore, I'm going to "revert" the two changes we made to this PR during the call. I can do this manually, but it's also possible to do this on git on the command line, so that it precisely reverses the commits.

Click on the "Commits" tab above and you'll see the list of commits. The clipboard icon will copy the git commit IDs and let me paste them into the command line.

Screenshot_2019-08-30 Add avatar_alt text to lesson header images by mdlincoln · Pull Request #1357 · programminghistorian


```sh
git revert 68b3bba7c479d9476191118bd0a99a4fb58fbd70
git revert d392f3a91e013bd8f954ecb281451f00d9912f22
```

@walshbr this does mean that you'll need to collect the filenames of the *.md lessons, NOT the images 😬 that will also mean going into the es and fr directories to get them.

**Comment by mdlincoln** [comment]
Chunk 1) **Person assigned** 
- [ ] analisis-voyant-tools.md
- [ ] analyzing-documents-with-tfidf.md
- [ ] applied-archival-downloading-with-wget.md
- [ ] automated-downloading-with-wget.md
- [ ] basic-text-processing-in-r.md
- [ ] building-static-sites-with-jekyll-github-pages.md
- [ ] cleaning-data-with-openrefine.md
- [ ] cleaning-ocrd-text-with-regular-expressions.md
- [ ] code-reuse-and-modularity.md
- [ ] corpus-analysis-with-antconc.md

Chunk 2) **Person assigned** 
- [ ] corpus-paralelo-lfaligner.md
- [ ] correspondence-analysis-in-R.md
- [ ] counting-frequencies-from-zotero-items.md
- [ ] counting-frequencies.md
- [ ] creating-an-omeka-exhibit.md
- [ ] creating-and-viewing-html-files-with-python.md
- [ ] creating-apis-with-python-and-flask.md
- [ ] creating-mobile-augmented-reality-experiences-in-unity.md
- [ ] creating-network-diagrams-from-historical-sources.md
- [ ] creating-new-items-in-zotero.md

Chunk 3) **@walshbr** 
- [x] data-mining-the-internet-archive.md
- [x] data_wrangling_and_management_in_R.md
- [x] dealing-with-big-data-and-network-analysis-using-neo4j.md
- [x] downloading-multiple-records-using-query-strings.md
- [x] editing-audio-with-audacity.md
- [ ] editor-guidelines.md
- [x] exploring-and-analyzing-network-data-with-python.md
- [x] extracting-illustrated-pages.md
- [x] extracting-keywords.md
- [x] fetch-and-parse-data-with-openrefine.md

Chunk 4) **Person assigned** 
- [ ] from-html-to-list-of-words-1.md
- [ ] from-html-to-list-of-words-2.md
- [ ] generating-an-ordered-data-set-from-an-OCR-text-file.md
- [ ] geocoding-qgis.md
- [ ] geoparsing-text-with-edinburgh.md
- [ ] georeferencing-qgis.md
- [ ] geospatial-data-analysis.md
- [ ] getting-started-with-github-desktop.md
- [ ] getting-started-with-markdown.md
- [ ] getting-started-with-mysql-using-r.md

Chunk 5) **Person assigned** 
- [ ] googlemaps-googleearth.md
- [ ] graph-databases-and-SPARQL.jpg
- [ ] graph-databases-and-SPARQL.md
- [ ] gravity-model.md
- [ ] installing-omeka.md
- [ ] installing-python-modules-pip.md
- [ ] intro-to-augmented-reality-with-unity.md
- [ ] intro-to-bash.md
- [ ] intro-to-beautiful-soup.md
- [ ] intro-to-linked-data.md

Chunk 6) **Person assigned** 
- [ ] intro-to-powershell.md
- [ ] intro-to-the-zotero-api.md
- [ ] intro-to-twitterbots.md
- [ ] introduction-and-installation.md
- [ ] introduction-to-ffmpeg.md
- [ ] introduction-to-populating-a-website-with-api-data.md
- [ ] introduction-to-stylometry-with-python.md
- [ ] json-and-jq.md
- [ ] keywords-in-context-using-n-grams.md
- [ ] linux-installation.md

Chunk 7) **Person assigned** 
- [ ] mac-installation.md
- [ ] manipulating-strings-in-python.md
- [ ] mapping-with-python-leaflet.md
- [ ] naive-bayesian.md
- [ ] normalizing-data.md
- [ ] output-data-as-html-file.md
- [ ] output-keywords-in-context-in-html-file.md
- [ ] preserving-your-research-data.md
- [ ] qgis-layers.md
- [ ] r-basics-with-tabular-data.md

Chunk 8) **Person assigned** 
- [ ] research-data-with-unix.md
- [ ] sentiment-analysis.md
- [ ] sonification.md
- [ ] sustainable-authorship-in-plain-text-using-pandoc-and-markdown.md
- [ ] temporal-network-analysis-with-r.md
- [ ] text-mining-with-extracted-features.md
- [ ] topic-modeling-and-mallet.md
- [ ] transforming-xml-with-xsl.md
- [ ] transliterating.md
- [ ] understanding-regular-expressions.md

Chunk 9) **Person assigned** 
- [ ] up-and-running-with-omeka.md
- [ ] using-javascript-to-create-maps.md
- [ ] vector-layers-qgis.md
- [ ] viewing-html-files.md
- [ ] visualizing-with-bokeh.md
- [ ] windows-installation.md
- [ ] working-with-text-files.md
- [ ] working-with-web-pages.md

In Spanish: 
Chunk 1) @jenniferisasi 
- [x] administracion-de-datos-en-r.md	
- [x] analisis-de-corpus-con-antconc.md
- [x] analisis-temporal-red.md Help! I don't know what this is??
- [x] analisis-voyant-tools.md
- [x] contar-frecuencias.md
- [x] corpus-paralelo-lfaligner.md	
- [x]	creando-diagramas-de-redes-desde-fuentes-historicas.md	
- [x] crear-exposicion-con-omeka.md	

Chunk 2) @JoshuaGOB  	
- [x]	crear-y-ver-archivos-html-con-python.md	
- [x]	datos-de-investigacion-con-unix.md
- [x]	datos-tabulares-en-r.md	
- [x]	de-html-a-lista-de-palabras-1.md
- [x]	de-html-a-lista-de-palabras-2.md
- [x]	descarga-automatizada-con-wget.md
- [x]	editar-audio-con-audacity.md

Chunk 3) @arojascastro 	
- [x]	escritura-sostenible-usando-pandoc-y-markdown.md
- [x]	instalacion-linux.md
- [x]	instalacion-mac.md
- [x]	instalacion-windows.md
- [x]	instalar-modulos-python-pip.md	
- [x]	intro-a-google-maps-y-google-earth.md	
- [x]	introduccion-a-bash.md	

Chunk 4) **@jenniferisasi**
- [x]	introduccion-a-markdown.md	
- [x]	introduccion-a-powershell.md	
- [x]	introduccion-control-versiones-github-desktop.md
- [x]	introduccion-datos-abiertos-enlazados.md	
- [x]	introduccion-e-instalacion.md	
- [x]	limpieza-de-datos-con-OpenRefine.md	
- [x]	manipular-cadenas-de-caracteres-en-python.md	

Chunk 5) **@jenniferisasi**
- [ ]	mineria-de-datos-en-internet-archive.md	
- [ ]	normalizar-datos.md	
- [ ]	palabras-clave-en-contexto-n-grams.md	
- [ ]	poniendo-omeka-a-funcionar.md	
- [ ]	preservar-datos-de-investigacion.md	
- [ ]	procesamiento-basico-de-textos-en-r.md	
- [ ]	reutilizacion-de-codigo-y-modularidad.md	

Chunk 6) **@rivaquiroga**
- [ ]	salida-de-datos-como-archivo-html.md	
- [ ]	salida-palabras-clave-contexto-ngrams.md	
- [ ]	sparql-datos-abiertos-enlazados.md
- [ ]	topic-modeling-y-mallet.md
- [ ]	trabajar-con-archivos-de-texto.md	
- [ ]	trabajar-con-paginas-web.md
- [ ]	transformacion-datos-xml-xsl.md	
- [ ]	ver-archivos-html.md

**Comment by walshbr** [comment]
Sounds good! I'll grab em in a second. In the interests of sharing technical things, I'll say that the reason I could do it so quickly was I…
1) pulled up the page in the browser that had all those filenames
2) opened developer tools for the browser
3) used css to hide extra elements of the table until it gave me just a list of the files
4) just pasted that list in

I'll post the new list here in a bit.

**Comment by walshbr** [comment]
Oh you did it already @mdlincoln :)

**Comment by spapastamkou** [comment]
I thought it could be useful to add avatar_alt in all already published FR
lessons and start doing it systematically in the ones that will follow.
So if I understand correctly, it is ok to only add
avatar_alt: [FR image title] in each lesson's yaml?

On confirmation (or correction:-)) I will work through a separate ticket.

>

**Comment by mdlincoln** [comment]
@spapastamkou yes, correct, just adding `avatar_alt` will be fine! Can you please add the commits to this branch?

**Comment by spapastamkou** [comment]
only did this for the 2 FR lessons that are on the branch; could add later for the remaining 2 once the branch is updated.

**Comment by mdlincoln** [comment]
@spapastamkou I just updated this branch based on the most current `gh-pages` code

**Comment by walshbr** [comment]
@mdlincoln - I did my assigned alt text cluster. One question though - does editor-guidelines.md actually have an avatar associated with it? Or was that filename in the list just an accidental insertion? I wasn't seeing an actual image for me to give alt text for.

**Comment by arojascastro** [comment]
What is this sorcery? I do not understand what I have to do :-(

**Comment by walshbr** [comment]
@arojascastro - https://github.com/programminghistorian/jekyll/pull/1357/commits/397ffd1ff25be40b87ba8c5db2504e0753af4f3c. For the files in the chunk you sign up for, you just need to add at the top as part of the YML metadata an avatar_alt category with text describing what the image for the lesson has in it.

**Comment by jenniferisasi** [comment]
> What is this sorcery? I do not understand what I have to do :-(

No worries, @arojascastro. That is why I assigned you a batch of avatar edits, since you are probably the one who edits more lessons. So, those images we place for each lesson (the little, square, B&W ones) need to have an alt text for screen readers to describe the image and, thus, make our site more accessible.

You need to include 'avatar_alt' category in the YAML of the files I assigned you with a short description of the image. We are doing in on GitHub desktop to edit all lessons and then push them as a batch, rather than doing one by one online.

**Comment by arojascastro** [comment]
Ok thank you both @jenniferisasi @walshbr - when is the deadline for this? :-S

**Comment by walshbr** [comment]
@arojascastro I don't think we set a deadline.

**Comment by spapastamkou** [comment]
I was looking for an image for an original lesson I am editing and I thought that perhaps from now on, for the next original lessons to be published in any language, we can define something like a small convention for the avatar_alt in yaml? For example, include the original title of the image (from the notice), source (the library or archive), and identifier.
What do you think? If we agree, I can make a ticket to propose to the whole PH team. This would involve to make slight additions to the Editors guidelines, which I could take in charge.

**Comment by arojascastro** [comment]
I will try to do this task on next weekend. Sorry... Is this ok?

**Comment by arojascastro** [comment]
done my part... sorry and thanks

**Comment by mdlincoln** [comment]
I just went through and finished all the EN texts. The remaining work is listed below. (I've also rebased against our current branch so all available lessons should now be on this PR)

**Comment by mdlincoln** [comment]
@programminghistorian/french-team 👍 


* In /fr/lecons/analyse-corpus-antconc.md:

  - [x] 'avatar_alt' is missing.

* In /fr/lecons/comprendre-les-pages-web.md:

  - [x] 'avatar_alt' is missing.

* In /fr/lecons/introduction-a-la-stylometrie-avec-python.md:

  - [x] 'avatar_alt' is missing.

* In /fr/lecons/nettoyer-ses-donnees-avec-openrefine.md:

  - [x] 'avatar_alt' is missing.

* In /fr/lecons/travailler-avec-des-fichiers-texte.md:

  - [x] 'avatar_alt' is missing.

**Comment by mdlincoln** [comment]
@programminghistorian/spanish-team 

* In /es/lecciones/mineria-de-datos-en-internet-archive.md:

  - [x] 'avatar_alt' is missing.

* In /es/lecciones/normalizar-datos.md:

  - [x] 'avatar_alt' is missing.

* In /es/lecciones/palabras-clave-en-contexto-n-grams.md:

  - [x] 'avatar_alt' is missing.

* In /es/lecciones/poniendo-omeka-a-funcionar.md:

  - [x] 'avatar_alt' is missing.

* In /es/lecciones/preservar-datos-de-investigacion.md:

  - [x] 'avatar_alt' is missing.

* In /es/lecciones/procesamiento-basico-de-textos-en-r.md:

  - [x] 'avatar_alt' is missing.

* In /es/lecciones/reutilizacion-de-codigo-y-modularidad.md:

  - [x] 'avatar_alt' is missing.

* In /es/lecciones/salida-de-datos-como-archivo-html.md:

  - [x] 'avatar_alt' is missing.

* In /es/lecciones/salida-palabras-clave-contexto-ngrams.md:

  - [x] 'avatar_alt' is missing.

* In /es/lecciones/sparql-datos-abiertos-enlazados.md:

  - [x] 'avatar_alt' is missing.

* In /es/lecciones/topic-modeling-y-mallet.md:

  - [x] 'avatar_alt' is missing.

* In /es/lecciones/trabajar-con-archivos-de-texto.md:

  - [x] 'avatar_alt' is missing.

* In /es/lecciones/trabajar-con-paginas-web.md:

  - [x] 'avatar_alt' is missing.

* In /es/lecciones/transformacion-datos-xml-xsl.md:

  - [x] 'avatar_alt' is missing.


* In /es/lecciones/ver-archivos-html.md:

  - [x] 'avatar_alt' is missing.

**Comment by mdlincoln** [comment]
@programminghistorian/french-team and @programminghistorian/spanish-team We need just a few more `avatar_alt` additions on the lessons here, and then I will be ready to merge this PR!

**Comment by jenniferisasi** [comment]
> jekyll 3.8.5 | Error:  There were YAML errors.

Hmm...is it giving errors because the FR tags are missing? I don't see anything wrong with the tags I just added.

**Comment by spapastamkou** [comment]
I added the avatar_alt text in four lessons out of five. 
The remaining lesson corresponds to this original: https://programminghistorian.org/en/lessons/viewing-html-files I am not sure the avatar_alt text in the original ("A boy drawing on a tablet") corresponds to the image, am I mistaken in this? This is why I left it out and prefer to confirm here before adding a translation. 
(And the build fails bcz the text is missing in the FR lesson)

**Comment by mdlincoln** [comment]
@spapastamkou good catch! I put that into the wrong file. I'm pushing a change now.

**Comment by mdlincoln** [comment]
OK @spapastamkou I think this is ready - we just need the final French translation for comprendre-les-pages-web. I would propose a French translation, but I am not comfortable translating "ear trumpet" by myself 😂 Hopefully you have a more elegant term!

**Comment by spapastamkou** [comment]
@mdlincoln did my best:)

**Pull request merged**
