### PR TITLE
Detecting reuse with passim

### PR DESCRIPTION
**Pull request by svmelton**
*add the reason for your pull request here*

### Checklist

- [X] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [X] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by svmelton** [comment]
Just requesting someone from the @programminghistorian/technical-team to review the PR!

**Review by ZoeLeBlanc — APPROVED** [review]
Lesson looks good to me! 

One thing I noticed was these characters `>>>` in the command line prompts, which is not something we've done previously.  Don't think it's something that has to be changed but might be worth making sure that readers understand that the arrows should not be copied when typing their commands.

Otherwise looks fantastic to me 👍🏽

**Comment by walshbr** [comment]
@svmelton - just a note that this lesson needs to be added to the Twitter bot spreadsheet - https://programminghistorian.org/en/editor-guidelines#6-incorporate-your-lesson-into-our-twitter-bot. Normally the editor of the lesson does this, but I think AM is still on leave right now. Congratulations on two publications in one day!

**Comment by svmelton** [comment]
Thanks @walshbr! It's been added now.

**Comment by amsichani** [comment]
oops, sorry team, I missed this step! Many thanks for helping on this!

**Pull request merged**
