### PR TITLE
add recent support

### PR DESCRIPTION
**Pull request by drjwbaker**
Add line on Sussex support per #1301. Will require translation.

@acrymble: do you want to you add Hertfordshire copyediting support before translation starts?

### CODE REVIEW

**Comment by drjwbaker** [comment]
Thanks @acrymble.

**Review by spapastamkou — DISMISSED** [review]

**Review by acrymble — APPROVED** [review]
This should be fine now that @spapastamkou has looked at it for French.

**Comment by drjwbaker** [comment]
@acrymble I was looking for this text on our site, and I think you closed rather than merged this PR in error.

**Comment by drjwbaker** [comment]
@acrymble I was looking for this text on our site and couldn't find it, and so I think you closed rather than merged this PR in error..

**Comment by drjwbaker** [comment]
I don't think there is anything stopping us merging, I just don't like merging my own PRs until we have a policy in place on that (as discussed in the call today).

**Pull request merged**
