### PR TITLE
Homepage issue#2048

### PR DESCRIPTION
**Pull request by matgille**
This pull request adresses issue #2048. I've changed the french, portuguese and spanish translations of "Enter" , and I've dropped the article in the journal titles. 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Review by DanielAlvesLABDH — DISMISSED** [review]
Approved from the PT team

**Review by rivaquiroga — DISMISSED** [review]

**Comment by spapastamkou** [comment]
@matgille I was about to merge but then I saw the donation banner and one thing brought another:-)
Please take a look to my commits @rivaquiroga and @DanielAlvesLABDH to check if all ok with your languages. 
Also @programminghistorian/technical-team please take a look to my commits as well to be aware of the changes; and I would like prior confirmation to update also `index.md` so that we have Programming Historian on the upper left of the menu instead of The Programming Historian. Thanks!

**Comment by DanielAlvesLABDH** [comment]
I think it is fine @spapastamkou. Thanks!

**Comment by spapastamkou** [comment]
thanks @DanielAlvesLABDH ! 
@matgille I believe I forgot that Spanish is a mother language to you, am I right here? In case you prefer to check yourself.

**Review by rivaquiroga — DISMISSED** [review]

**Comment by matgille** [comment]
@spapastamkou Riva approved the changes, it's perfect. Thanks for completing my commits.

**Comment by spapastamkou** [comment]
The build fails because of a dead link problem. I normally fixed this in PR #2151; once that one merged, we should have no problem here.

**Comment by spapastamkou** [comment]
Ok, I worked a bit on this and I think that what remains to be changed is: 
- this line of code `<nav class="hide-print print-header navbar-brand">The Programming Historian </nav>` in the `menu.html` file of the ```_includes``` folder
-  in `snippets.yml` file in `_data` folder this part: 
footer:  
  license:
    en: |
      The _Programming Historian_ (ISSN: 2397-2068) is released under a [CC-BY](https://creativecommons.org/licenses/by/4.0/deed.en) license.
    es: |
      _The Programming Historian en español_ (ISSN: 2517-5769) se publica con una licencia [CC-BY](https://creativecommons.org/licenses/by/4.0/deed.es).
    fr: |
      Le _Programming Historian en français_ (ISSN: 2631-9462) est publié sous licence [CC-BY](https://creativecommons.org/licenses/by/4.0/deed.fr).
    pt: |
      _The Programming Historian em português_ (ISSN: 2753-9296) é publicado com uma licença [CC-BY](https://creativecommons.org/licenses/by/4.0/deed.pt).

I can work on this. For the footer, I may have some questions for the language teams; for all the rest, if everything ok in the preview, I will ask a final review from the @programminghistorian/technical-team because I am a bit nervous for all these changes:)

**Comment by spapastamkou** [comment]
Although the build fails, bcz of a broken link, changes in the menu seem ok. 

As for the footer: I would like to propose to the teams a slight change to make the footer text shorter and avoid redundancies (because the ISSN number for each publication follows anyway on the bottom on the left). Taking the example of the text in English, instead of having:  
**The _Programming Historian_ (ISSN: 2397-2068) is released under a [CC-BY](https://creativecommons.org/licenses/by/4.0/deed.en) license.** 
we could have: 
**All contents are licensed under a [CC-BY](https://creativecommons.org/licenses/by/4.0/deed.en) license.** (or something like this, if there are better ideas. 
What do you think @programminghistorian/english-team @programminghistorian/spanish-team @programminghistorian/portuguese-team @programminghistorian/french-team  (and if ok can you provide respective translations in ES and PT so that I can make the changes)? Thanks all.
cc @Anisa-ProgHist

**Comment by jenniferisasi** [comment]
@spapastamkou and all is this ready now? If so, I will try to do the update to get it with the latests merges so you can finish this one.

**Comment by jenniferisasi** [comment]
All, this PR is now up-to-date to make any additional changes if following Sofia's suggestions. 

I like the suggestion. In Spanish it would be: 

Todos los contenidos tienen licencia CC-BY.

**Comment by spapastamkou** [comment]
thank you very much @jenniferisasi. 
@programminghistorian/portuguese-team: Could you let me know if the following phrase is correct, please? 
"Todos os conteúdos são licenciados sob uma licença CC-BY" (to translate "All contents are licensed under a CC-BY license")
Upon confirmation I will edit myself the file for all languages (and merge this PR:)). If my Google translation is not correct, please edit this comment or comment separately. Thanks!

**Comment by DanielAlvesLABDH** [comment]
Dear @spapastamkou the translation is correct. Many thanks

**Review by ZoeLeBlanc — APPROVED** [review]
Looks good! Merge it in 👍🏽

**Pull request merged**
