### PR TITLE
Optimizing website for printing and pdfs

### PR DESCRIPTION
**Pull request by ZoeLeBlanc**
NOTICE: Are you attempting to submit a lesson to the Programming Historian? We no longer accept lesson submissions by pull request to this repository. Please consult our [guidelines for submitting a lesson](http://programminghistorian.org/new-lesson-workflow) for further instructions.

If your pull request instead concerns some issue with the formatting or functioning of our site, or some error in an existing lesson, please see our technical contribution guidelines: https://github.com/programminghistorian/jekyll/wiki/Making-technical-contributions

This PR is to begin optimizing the website for printing and pdfs. This branch is a work in progress so some of the code might be moved around and reformatted once we decide on what exactly we want for this features. 
#
Please see the discussion on #1225 for notes on how to inspect the output and ideas about how the printed version should look.

### CODE REVIEW

**Comment by ZoeLeBlanc** [comment]
@mdlincoln fyi some of these changes are artifacts of me trying to figure out how to do this, so not all of them are required. The big ones are to the `base.html` and the `styles.css`. If you find any bugs let me know but at this stage I think the big question is what do we want the optimized print version to include. It would be very easy to add a footer for example or additional information to the header.

**Comment by mdlincoln** [comment]
Nice - it looks like the header contains the things it needs to. 

Screen Shot 2019-04-05 at 8 45 57 AM


- Would it be terribly difficult to expand the width of that header metadata so that it fits more comfortably on the page?
- The body text looks like it's bolded / heavy-weight - possible to set this to a "normal" font?

**Comment by ZoeLeBlanc** [comment]
All things are possible Matt 😅 ! 

But ya I think your suggestions are 👌 and I'll make the changes. Quick question is that screenshot from you doing save to pdf or actually go to printer? The styling looks slightly different for each which is annoying. Also which browser are you using? 

Thanks for the feedback tho 👏

**Comment by mdlincoln** [comment]
Save-to-pdf, Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0

**Comment by ZoeLeBlanc** [comment]
So firefox unfortunately removed the ability to emulate print media so it's a little harder to debug what's going on in that browser. Here's screenshots of how it looks in Chrome currently:
To print:
Screen Shot 2019-04-06 at 9 42 23 AM
To pdf:
Screen Shot 2019-04-06 at 9 42 10 AM
Wondering how much time I should spend getting this to work across browsers versus us just saying if you want to print use Chrome?

I'll still make the changes you suggested but I'm just not even sure how to go about digging into how Firefox is rendering print since I can't inspect anything. I guess just keep trying and hope something sticks 😅

**Comment by acrymble** [comment]
If there isn't a cross-browser easy and sustainable solution, then I wouldn't spend too much energy on it. The "do it with chrome" option sounds reasonable to me.

**Review by mdlincoln — COMMENTED** [review]
I agree with @acrymble - I think we can call this good enough. Perhaps you could toss a little advisory into the bottom of the lesson template suggesting the use of Chrome for printing?

**Review by mdlincoln — CHANGES_REQUESTED** [review]
I agree with @acrymble - I think we can call this good enough. Perhaps you could toss a little advisory into the bottom of the lesson template suggesting the use of Chrome for printing?

**Comment by walshbr** [comment]
Going through to cull out issues. This just needs a brief note on the template to be merge-ready, yeah?

**Comment by ZoeLeBlanc** [comment]
There could be more improvements to work for other browsers but we can table that for now if you want. I won't be able to look at this until September though.

**Comment by mdlincoln** [comment]
I've tossed in a footer advisory - working on rebasing this branch so it's merge-able now :)

**Review by mdlincoln — APPROVED** [review]

**Pull request merged**
