### PR TITLE
note Europeana no longer allows SERVICE queries

### LINKED ISSUE #904: Europeana SPARQL endpoint?
I'm revising all lessons in order to get data about the resources employed and I bumped into @mdlincoln's beautiful lesson on lod. There is a note here about the Europeana endpoint: https://programminghistorian.org/en/lessons/graph-databases-and-SPARQL#linking-multiple-sparql-endpoints

I think the Endpoint now is available here: http://sparql.europeana.eu/

More info: https://pro.europeana.eu/post/europeana-sparql-endpoint

### PR DESCRIPTION
**Pull request by mdlincoln**
Closes #904 

This clarifies the text in the warning on the "Linking Multiple SPARQL Endpoints" section of the lesson.

@programminghistorian/spanish-team the spanish version of this lesson needs to be updated to include this warning.

### CODE REVIEW

**Comment by arojascastro** [comment]
Give me some days to finish this please - I have some work overload :S

**Comment by arojascastro** [comment]
Done! I have added the note using > to visualize it as a block. Sorry for the dealy. Feel free to merge once it has passed Travis.

**Comment by mdlincoln** [comment]
Thanks @arojascastro - you are right to improve the formatting. So I put the warnings inside `<div class="alert alert-warning">` which we use for warnings elsewhere on the site.

Can you please approve this PR?

**Review by arojascastro — APPROVED** [review]
THANK YOU and sorry for the late response, it was simpler than I had assumed.

**Pull request merged**
