### PR TITLE
adding my bio to ph_authors.yml

### PR DESCRIPTION
**Pull request by hawc2**
*adding my bio to ph_authors*

Can I also request help translating my bio and institution into French, Spanish, and Portuguese? Thank you!

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by acrymble** [comment]
@hawc2 unfortunately we have 5 people trying to update this file at the same time. To prevent conflicts, we'll have to wait until the others have finished their pull requests.

**Comment by acrymble** [comment]
In the meantime, can you please put your avatar in this same pull request instead of in 2 separate ones. Please:

- close your other pull request (#1897)
- use these instructions to go to the branch for THIS pull request (hawc2-patch-1) and then add the avatar to this pull request (https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions)
- Request a review from either the English team or Technical team.

**Comment by hawc2** [comment]
ok should be all set now

**Comment by acrymble** [comment]
Thanks @hawc2 the preview looks ok. There are two other things you have to do though (and since this is about practicing good habits, we might as well do it right the first time).

Firstly, the checklist in the opening comment is something you're actively meant to tick off. This tells your reviewers you've done your part of the pull request by checking over everything. This is an important time saver for everyone. Were you able to check the preview to see what the finished change will look like? If not we can walk you through that process.

Secondly, I see you haven't translated your bio. It's up to you as the pull requester to ask for these translations. To make it easy for our colleagues, we have some brief guidelines on how to do that in a helpful way (https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines). You don't really need a review until you've got those translations in place.

**Comment by hawc2** [comment]
Thanks Adam, for all your help walking me through this! Slowly but surely
I'm getting the hang of it

Just checked off the items on the list. The preview looks all set to me.

For the bio translations, I had tried to put in the pull request what the
translation request guidelines ask for, and I @'d the relevant project
teams. Is there more I should do for that?

**Comment by acrymble** [comment]
@hawc2 it's probably easier for our translators to put the actual sentence in the comment. Otherwise you're asking the translators to go looking for (and maybe not finding) what you want translated.

Something like:

Can @programminghistorian/french-team @programminghistorian/spanish-team please help me translate the following: 

>  Alex Wermer-Colan is the Digital Humanities Postdoctoral Fellow at Temple University Libraries' Loretta C. Duckworth Scholars Studio.

If they want the information in a different format, they can let us know. The goal is to do as much of the work for them as possible, as they get a lot of these little requests.

**Comment by hawc2** [comment]
oh ok! great, that makes sense, will do

**Comment by hawc2** [comment]
@programminghistorian/french-team @programminghistorian/spanish-team @programminghistorian/portuguese-team please help me translate my bio fpr ph_authors.yml:

Alex Wermer-Colan is the Digital Humanities Postdoctoral Fellow at Temple University Libraries' Loretta C. Duckworth Scholars Studio.

**Comment by DanielAlvesLABDH** [comment]
Hi @hawc2 . Here are the Portuguese translation: "Alex Wermer-Colan é bolseiro de pós-doutorado em Humanidades Digitais no Loretta C. Duckworth Scholars Studio da biblioteca da Temple University."

**Review by DanielAlvesLABDH — DISMISSED** [review]
In the affiliation for pt use "Temple University, Estados Unidos."

**Comment by jenniferisasi** [comment]
Adding it here to avoid another pull since it seems to still be running something: 

Alex Wermer-Colan es becario postdoctoral en Humanidades Digitales en el Loretta C. Duckworth Scholars Studio de la Biblioteca de la Universidad de Temple.

**Comment by spapastamkou** [comment]
FR: Alex Wermer-Colan est chercheur postdoctoral en humanités numériques au Loretta C. Duckworth Scholars Studio des bibliothèques de l'Université Temple.

**Comment by hawc2** [comment]
@acrymble @programminghistorian/english-team I think my pull request to add me as author to the English editorial team is now ready to go. Thanks to all for your help

**Review by acrymble — DISMISSED** [review]
Looks good. Well done. All you have to do now is merge the pull request and delete the branch.

**Comment by acrymble** [comment]
Could someone with @programminghistorian/technical-team help us with the branch conflicts please?

**Comment by walshbr** [comment]
That should do it @acrymble

**Review by acrymble — APPROVED** [review]

**Comment by acrymble** [comment]
@hawc2 can you please merge this pull request ASAP? We have a number of other people trying to edit this file and we need to close this first.

**Pull request merged**
