### PR TITLE
Bug fix for Static website with Jekyll & GitHub - Closes #1669

### LINKED ISSUE #1669: Additional step suggested for Mac users of "Building Static Sites with Jekyll"
In the installing Ruby Gems and Jekyll phase, my Mac users have received an error that they don't have write permissions to the ruby gems directory. 

This is the suggested fix in the instructions:
> If you get a permissions error at this point, entering usr/local/bin/gem install rubygems-update instead of the command above may help.

That did not working for us, but the following did:

Typing this command:
`echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> ~/.bash_profile`
Then this command:
`source ~/.bash_profile`

That fix derived from here:https://stackoverflow.com/questions/51126403/you-dont-have-write-permissions-for-the-library-ruby-gems-2-3-0-directory-ma

### PR DESCRIPTION
**Pull request by mariechristineb**
Following a bug testing report, I made the following changes to this lesson: 

- Note about zsh on Catalina and the possibility of reverting to bash
- Bug fix for permissions error during Mac install of Ruby Gems, as reported in #1669 
- Credit to PH user for pointing to bug fix

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by drjwbaker** [comment]
@mariechristineb If this is an example of a 'minor' change that isn't covered at https://github.com/programminghistorian/jekyll/wiki/The-Programming-Historian-Digital-Object-Identifier-Policy-%28April-2020%29 please consider adding to the list. This policy is new (and required because of DOIs), so it is useful to have more examples to refer to for future work.

**Comment by mariechristineb** [comment]
@drjwbaker for the most part, I'd say it falls under 'Changes to code that are approximately at the same level as correcting a matter of spelling or fact in the text itself.' Although I guess the added information about Catalina might deserve its own category.

**Comment by drjwbaker** [comment]
@mariechristineb I think you are right. I guess even a link back to this ticket from the wiki would help a future editor judge whether or not what they are dealing with matches a past 'minor' case.

**Comment by walshbr** [comment]
Thanks for this! 

Removing the technical team from this as we decided perviously that bug testing lessons would be the purview of the particular project teams (unless I'm mistaken).

**Comment by walshbr** [comment]
@ZoeLeBlanc do you have any comment on the fix? It looks fine to me, but path issues are sort of where my developer knowledge checks out.

**Review by svmelton — APPROVED** [review]

**Review by ZoeLeBlanc — APPROVED** [review]
This looks good to me! Merge away 👍

**Pull request merged**
