### PR TITLE
Spanish journal review

### PR DESCRIPTION
**Pull request by acrymble**
As noted by @arojascastro the project has been reviewed in a Spanish digital humanities journal. I've added this to our 'Reviews' section of our research page (both EN/ES). I haven't added it to the French pages.

### CODE REVIEW

**Review by drjwbaker — APPROVED** [review]

**Review by drjwbaker — DISMISSED** [review]

**Review by arojascastro — APPROVED** [review]
muchas gracias

**Comment by mdlincoln** [comment]
why not add it to the french pages @acrymble ?

**Comment by acrymble** [comment]
Just because those files aren't on the live branch. I wasn't sure how @mdlincoln

**Comment by mdlincoln** [comment]
use the `french-staging` branch

**Pull request merged**
