### PR TITLE
add machine learning topic

### PR DESCRIPTION
**Pull request by davanstrien**
Add a topic for machine learning. I have made an attempt at the translations but they should definitely be checked by a native speaker. 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by DanielAlvesLABDH** [comment]
I would translate as "Aprendizagem automática" and "Lições focadas em aprendizagem automática"

**Comment by davanstrien** [comment]
> I would translate as "Aprendizagem automática" and "Lições focadas em aprendizagem automática"

Thanks for providing a sensible translation!

**Comment by davanstrien** [comment]
I've just pushed an improved Spanish version (thanks to @mcollardanuy)

**Review by kmcdono2 — COMMENTED** [review]
in French, propose "Leçons" rather than "Cours".

**Comment by anisa-hawes** [comment]
I have resolved the build-check failure here, but note that the Netlify preview doesn't include the new topic 'Machine Learning' on the Lesson Index pages. I think this is because (at the moment) no lessons are labelled with this topic, but when the new lessons are published the topic will display. 

Is that correct, @jenniferisasi? I have had a look back at your recent [PR 2524](https://github.com/programminghistorian/jekyll/pull/2524) and I think that the changes made in this patch are ready to merge in.

**Comment by davanstrien** [comment]
> I have resolved the build-check failure here, but note that the Netlify preview doesn't include the new topic 'Machine Learning' on the Lesson Index pages. I think this is because (at the moment) no lessons are labelled with this topic, but when the new lessons are published the topic will display.
> 
> Is that correct, @jenniferisasi? I have had a look back at your recent [PR 2524](https://github.com/programminghistorian/jekyll/pull/2524) and I think that the changes made in this patch are ready to merge in.

I think the other step is updating the `/js/lessonfilter.js` file to include the new topic (taken from https://programminghistorian.org/en/editor-guidelines#3-add-yaml-metadata-to-the-lesson-file). I'm happy to add that to this PR but otherwise, it could maybe be added alongside the CV lesson this topic will first be used for?

**Comment by davanstrien** [comment]
> > I have resolved the build-check failure here, but note that the Netlify preview doesn't include the new topic 'Machine Learning' on the Lesson Index pages. I think this is because (at the moment) no lessons are labelled with this topic, but when the new lessons are published the topic will display.
> > Is that correct, @jenniferisasi? I have had a look back at your recent [PR 2524](https://github.com/programminghistorian/jekyll/pull/2524) and I think that the changes made in this patch are ready to merge in.
> 
> I think the other step is updating the `/js/lessonfilter.js` file to include the new topic (taken from [programminghistorian.org/en/editor-guidelines#3-add-yaml-metadata-to-the-lesson-file](https://programminghistorian.org/en/editor-guidelines#3-add-yaml-metadata-to-the-lesson-file)). I'm happy to add that to this PR but otherwise, it could maybe be added alongside the CV lesson this topic will first be used for?

Having just looked at that file (https://github.com/programminghistorian/jekyll/blob/gh-pages/js/lessonfilter.js), I think the filter function has changed from the description provided in the editor guidelines (https://programminghistorian.org/en/editor-guidelines#3-add-yaml-metadata-to-the-lesson-file)

**Comment by anisa-hawes** [comment]
That's right, @davanstrien. I'm working on a revision of the Editorial Guidelines at the moment, because there are several sections (including the one you cite above) which are now out-of-date.

**Comment by jenniferisasi** [comment]
> Is that correct, @jenniferisasi? I have had a look back at your recent [PR 2524](https://github.com/programminghistorian/jekyll/pull/2524) and I think that the changes made in this patch are ready to merge in.

Yes! That should be the case. I am guessing just because the number of tags differ in the 4 languages and it is because of a lack of lessons with whatever tag is not displaying :)

**Review by jenniferisasi — CHANGES_REQUESTED** [review]
I would like to propose a reversal to "Lecciones sobre métodos de aprendizaje automático." for the es version

**Comment by anisa-hawes** [comment]
Thank you @jenniferisasi, @DanielAlvesLABDH and @spapastamkou for contributing adjustments to the translations ✨

**Review by jenniferisasi — APPROVED** [review]

**Pull request merged**
