### PR TITLE
Update consignes-auteurs.md

### LINKED ISSUE #2826: Investigating if it is possible to fix multiple broken links on fr/consignes-auteurs
I note that ~10 links to a sub-domain of the Canadian government's website <https://www.quebec.ca/> which are included in fr/consignes-auteurs have broken...

<http://bdl.oqlf.gouv.qc.ca> is now redirecting to <https://vitrinelinguistique.oqlf.gouv.qc.ca/>

Our FR author guidelines currently link to multiple pages across that website. I'm going to take a look now, but I may need some support from the @programminghistorian/french-team to identify which replacement links will be suitable...

### PR DESCRIPTION
**Pull request by anisa-hawes**
I am replacing all links to http://bdl.oqlf.gouv.qc.ca/ with alternatives pages on the site https://vitrinelinguistique.oqlf.gouv.qc.ca/.

(I've removed the first link at l.148, as I think it makes sense to use the second one only).

Closes #2826 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by anisa-hawes** [comment]
I need to combine this PR with the edit I prepared on #2825, or neither of them will build successfully!

So, noting here that I am also going to fix a broken link on our research / investigacion / recherche / pesquisa pages.

http://researchprofiles.herts.ac.uk/portal/files/10476604/Blip_2016_Autumn_2016_Final_Autumn_2016.pdf is broken and I am replacing it with https://www.herts.ac.uk/__data/assets/pdf_file/0016/138013/Blip-2016-Autumn-2016-Final-Autumn-2016.pdf.

**Comment by anisa-hawes** [comment]
Dear @marie-flesch and @spapastamkou,

I think I have found the relevant alternative pages within https://vitrinelinguistique.oqlf.gouv.qc.ca/ (it wasn't too difficult). 

If you have time to check the links / make any changes that would be good.

Thank you,
Anisa

**Comment by anisa-hawes** [comment]
> I need to combine this PR with the edit I prepared on #2825, or neither of them will build successfully!
> 
> So, noting here that I am also going to fix a broken link on our research / investigacion / recherche / pesquisa pages.
> 
> http://researchprofiles.herts.ac.uk/portal/files/10476604/Blip_2016_Autumn_2016_Final_Autumn_2016.pdf is broken and I am replacing it with https://www.herts.ac.uk/__data/assets/pdf_file/0016/138013/Blip-2016-Autumn-2016-Final-Autumn-2016.pdf.

Oh.... Maybe not necessary... 🤔

**Comment by spapastamkou** [comment]
@anisa-hawes I'll be able to do this later today

**Comment by spapastamkou** [comment]
I modified two links to be in accordance with the text and englobe the general categories the text is about - @marie-flesch you can review if you want, so that I do not approve my own changes:-)

**Comment by anisa-hawes** [comment]
Merci beaucoup, @spapastamkou!

**Review by marie-flesch — APPROVED** [review]
C'est tout bon pour moi :)

**Comment by spapastamkou** [comment]
Thanks @marie-flesch ! Looks good, I merge for you @anisa-hawes so that you are able to work with the rest - out of precaution however I won't delete the current branch for you, please consider this later.

**Comment by spapastamkou** [comment]
@anisa-hawes I receive by email a report for a deployment problem here: https://github.com/programminghistorian/jekyll/actions/runs/3959726526/jobs/6783095016 
It concerns the two links I changed. I had tested them however before and if I insert them in the navigator bar, they work; but when I click from the guidelines page, I receive an error. I will be able to check this later this evening.

**Comment by anisa-hawes** [comment]
Dear @spapastamkou,

Thank you for letting me know. I have re-run the build and it has now deployed successfully 🙂 

Best, Anisa

**Pull request merged**
