### PR TITLE
Turn PR template into a checklist for editors

### LINKED ISSUE #1600: New PR template to help out editors?
Right now we have a [PR template](https://github.com/programminghistorian/jekyll/blob/gh-pages/.github/PULL_REQUEST_TEMPLATE.md) that is addressed to external users who occasionally try to submit PRs directly for our lessons. It's the text that is automatically put into any new pull request.

I'm wondering if it would be more useful to rewrite this template so that it's useful for _us team members_, and provides a checklist that every PR (whether for a new lesson or a blog post or a small content change) should pass before it's ready to submit. 

The template could include a spot at the top to describe the change, and then include a footer section with a generic checklist that could include reminders:

- on how to open up the Travis check results
- to check how the page looks on the Netlify preview
- to assign at least one reviewer (either individual or team)
    - if changing a page with translations, reminder to add all appropriate language teams as reivewers
- to assign self as "assignee" responsible for the PR
- to add an appropriate label

Do we think this makes sense? Are there any other tasks we need?

### PR DESCRIPTION
**Pull request by mdlincoln**
Closes #1600 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully. Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by drjwbaker** [comment]
This is great @mdlincoln. One thing, on..

> [ ] Assign at least one individual or team to "Reviewers

.. do we have a list of 'teams' that people can chose from? From memory, there is some inconsistency regarding which teams listed at https://github.com/programminghistorian/jekyll/wiki#project-structure can be `@`ed as a team.

**Comment by mdlincoln** [comment]
@drjwbaker these are all the sub-teams that can be @-ed : https://github.com/orgs/programminghistorian/teams/project-team/teams

I can set up global & comms teams now

**Comment by mdlincoln** [comment]
Added @programminghistorian/global-team and @programminghistorian/communication-team ✅

**Comment by mdlincoln** [comment]
If we're happy with this, can I get a review @programminghistorian/technical-team ?

**Comment by drjwbaker** [comment]
> @drjwbaker these are all the sub-teams that can be @-ed : https://github.com/orgs/programminghistorian/teams/project-team/teams
> 
> I can set up global & comms teams now

Thanks @mdlincoln. That view is really useful. I've added a link to the wiki.

**Review by walshbr — APPROVED** [review]

**Pull request merged**
