### PR TITLE
Issue 2481

### LINKED ISSUE #2481: Onboarding tasks: new editors joining our English team
I am updating our Authors (ph_authors.yml) _ Avatars (avatars) file because a group of new editors are joining our English team.

### PR DESCRIPTION
**Pull request by anisa-hawes**
I am updating our Authors (ph_authors.yml) _ Avatars (avatars) file because a group of new editors are joining our English team.

Hello @programminghistorian/spanish-team @programminghistorian/french-team @programminghistorian/portuguese-team   Please could you help us with translations of Author bios for our new EN team members?

Closes #2481 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by rivaquiroga** [comment]
@anisa-hawes, I just added the Spanish translations. New editors: please add your data at the end of the document to make translators life easier :grimacing:. I moved the one that was in the middle to the end of the file.

**Comment by anisa-hawes** [comment]
Thank you, @rivaquiroga. Apologies. John was previously an author and has now joined us as an editor – that's why his bio was further up in the document.

@ZoeLeBlanc thinks this combination of two roles might what it causing the build error here....

**Comment by jenniferisasi** [comment]
The issue was a missing middle name initial in the new version of John's profile. Same with the avatar, it is looking for it with an R in it. 

The build is technically not looking for that R. in particular; it looks for names in the "author:" in the YAML box in each lesson; it was not finding John R. Ladd so it was breaking. 

Will try to fix the issue with the image

**Comment by anisa-hawes** [comment]
You are magic, @jenniferisasi ! Thank you !

**Comment by jenniferisasi** [comment]
Ok, @anisa-hawes pretty sure now the error is by the indentation on the first line of Giulia's profile.

**Comment by anisa-hawes** [comment]
Super! All the build checks have passed, so we're almost ready to merge.

@programminghistorian/french-team and @programminghistorian/portuguese-team, the sentences which require translation are:

1. Liz Fischer is a PhD student at the University of Texas at Austin.

2. Rolando is a MSIS candidate at University of North Carolina at Chapel Hill.
 
3. Yann is a postdoctoral researcher working with the COMHIS computational history group at the University of Helsinki.

5. Scott Kleinman is Professor of English and Director of the Center for Digital Humanities at California State University, Northridge.

6. John Ladd is Visiting Assistant Professor in Data Analytics at Denison University, where he uses humanities approaches to data and network analysis to think about the long, interwoven histories of media and technology, especially in early modern literature.

7. Giulia Taurino is a Postdoctoral Researcher at The Institute for Experiential AI (Northeastern University, Khoury College of Computer Science / Roux Institute), where she works on the development of AI toolkits for media research in collaboration with the NULab for Texts, Maps, and Networks and MIT Data + Feminism Lab.

If you'd prefer to post the translations here, I can slot them into the ph_authors file.

Thank you!

**Comment by DanielAlvesLABDH** [comment]
Portuguese:
1. Liz Fischer é estudante de doutoramento na Universidade do Texas em Austin. 
2. Rolando é estudante de Mestrado em Sistemas de Informação na Universidade da Carolina do Norte em Chapel Hill.
3. Yann é um pesquisador de pós-doutoramento que trabalha com o grupo de história computacional COMHIS na Universidade de Helsínquia.
4. Scott Kleinman é Professor de Inglês e diretor do Center for Digital Humanities da Universidade do Estado da Califórnia, Northridge. 
5. John Ladd é Professor Assistente Visitante em Análise de Dados na Universidade de Denison, onde usa abordagens de humanidades para dados e análise de rede para pensar sobre as longas e entrelaçadas histórias de media e tecnologia, especialmente na literatura da época moderna. 
6. Giulia Taurino é pesquisadora de pós-doutoramento no The Institute for Experiential AI (Universidade de Northeastern, Khoury College of Computer Science / Roux Institute), onde trabalha no desenvolvimento de kits de ferramentas de IA para pesquisa de media em colaboração com o NULab for Texts, Maps, and Networks e o MIT Data + Feminism Lab. 

Hope this helps @anisa-hawes

**Comment by anisa-hawes** [comment]
Hello @spapastamkou / @programminghistorian/french-team. Might anyone have a moment to help with translating our new EN team members' bios? Thank you, Anisa

**Comment by spapastamkou** [comment]
I am on a train with intermittent connection - if someone from the FR team can help, this would be great. Thank you!

Envoyé de mon iPhone

**Comment by spapastamkou** [comment]
I let you take a look and let me know if you need something @anisa-hawes

**Comment by acrymble** [comment]
@anisa-hawes a note for future, the bios aren't needed anymore unless someone is an author. It used to be that we shared bios, but in order to reduce the need for translations we stopped doing this for editors. It also meant bios didn't risk going out of date quite so often.

**Comment by anisa-hawes** [comment]
Understood. This will make the task simpler in the future. Thank you, Adam.

**Review by svmelton — COMMENTED** [review]
Looks great @anisa-hawes! The only thing that needs changing is that John now has 2 avatars—I'd suggest we use the john-r-ladd one for consistency.

**Comment by anisa-hawes** [comment]
Thank you, @svmelton. I've deleted the duplicate avatar.

*The build was failing due to a link in geocoding-qgis.md which was pointing to geoparser-lesson.md in ph-submissions. I've corrected this!

Ready for your review now.

**Review by svmelton — APPROVED** [review]

**Pull request merged**
