### PR TITLE
Issue 2671 - adding to the research / investigacion / recherche / pesquisa pages

### LINKED ISSUE #2671: Collating activities to add to the research / investigacion / recherche / pesquisa pages
Hi everyone

Does anyone have any research activities to add to PH's research / investigacion / recherche / pesquisa pages?

I'll add the roundtable discussion on 8/Sept. If you have anything, please let me know below!

### PR DESCRIPTION
**Pull request by GeeAlmeida**
adding to the research / investigacion / recherche / pesquisa pages

Closes #2671 

### Checklist

- [X ] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  ~- [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines]~(https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description~
- [X ] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Review by anisa-hawes — COMMENTED** [review]
Thank you for preparing this @GeeAlmeida! Formatting looks generally good, but the author's/authors' name(s) are missing for the report _Incllewsion and the Programming Historian, ‘Initial Accessibility Testing: Summary of Findings’, (2021)_?

**Comment by GeeAlmeida** [comment]
> Incllewsion

The author is this company, Incllewsion.

**Review by anisa-hawes — APPROVED** [review]
Excellent @GeeAlmeida ✨

**Comment by anisa-hawes** [comment]
Hello @GeeAlmeida. You can go ahead and merge this in! 

Unless you'd prefer to add [the Japanese edition Adam mentions](https://github.com/programminghistorian/jekyll/issues/2699) into this branch?

If you choose to do so, I can rebase this PR when you've made the changes – because by now the branch you created is several commits behind gh-pages.

**Pull request merged**
