### PR TITLE
Sponsor08 2020

### LINKED ISSUE #1879: Add new IPP partner to /sponsor page
Need to add Western University to our list of sponsoring institution. Need to wait to hear from @programminghistorian/portuguese-team on the #1818 progress as pages are frozen while being translated.

### PR DESCRIPTION
**Pull request by acrymble**
Closes #1879 adding Western University to the support us page in EN/ES/FR

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by acrymble** [comment]
Thank you @spapastamkou and @rivaquiroga for translating!

**Comment by drjwbaker** [comment]
Given the pause on page updates, @acrymble are you happy for me add two new $15 patrons to this PR? If so, I'll make the changes to the relevant EN/ES/FR files.

**Comment by acrymble** [comment]
Ya go ahead @drjwbaker

**Comment by drjwbaker** [comment]
@acrymble Ta. Done.

**Comment by acrymble** [comment]
@jenniferisasi this is waiting for a review please.

**Review by jenniferisasi — APPROVED** [review]

**Pull request merged**
