### PR TITLE
Archive Directory

### LINKED ISSUE #1482: Offline archive of bids et al
As discussed at https://github.com/programminghistorian/jekyll/issues/1449 and following on from https://github.com/programminghistorian/jekyll/issues/1426, as project Archivist I’ve been thinking of ways to store in a private, offline manner, documents we want to have team access to but don’t want to put on GitHub: so, things like bids, internal surveys, et cetera.

You've now started sending me things to add to this (thank you!). The next step is to create a mechanism for sharing. My proposal is to have a list of directories and files (so the output of `ls -R` in the base directory) that I put on here periodically. You can then consult the list and ask me for the file.

The question is where to put the .txt file with the list of documents. @programminghistorian/technical-team: I don't see the point of adding a new repo, so do you have any objections to me adding a new directory at https://github.com/programminghistorian/jekyll in wich I put these .txt files? It isn't exactly the right place, but presuming it won't be anything to disrupt the jekyll build, it seems the most simple option.

### PR DESCRIPTION
**Pull request by drjwbaker**
Add directory with initial archive listing and readme explaining the purpose and function of the directory. I'll also add something to the Service Integrations Wiki.

Closes https://github.com/programminghistorian/jekyll/issues/1482

### CODE REVIEW

**Review by walshbr — DISMISSED** [review]

**Review by mdlincoln — CHANGES_REQUESTED** [review]
inside the _config.yml file, there's a heading for `exclude` where we list any directories in the repo that shouldn't be rendered onto programminghistorian.org. Please add this folder to that list

**Comment by drjwbaker** [comment]
Thanks @mdlincoln. Good to know that feature. Have I done it right?

**Review by mdlincoln — APPROVED** [review]

**Comment by drjwbaker** [comment]
Now. Per our team call. Am I responsible for merging?

**Comment by mdlincoln** [comment]
yes

**Comment by drjwbaker** [comment]
Such power! (I'll be good, promise..)

**Pull request merged**
