### PR TITLE
Publish /en/lessons/designing-a-timeline-tabletop-simulator

### LINKED ISSUE #3208: Preparing to publish new EN lesson designing-a-timeline-tabletop-simulator
I am opening this Issue to prepare designing-a-timeline-tabletop-simulator for publication.

### PR DESCRIPTION
**Pull request by anisa-hawes**
Preparing files for publication.

Closes #3208 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Add the appropriate "Label"
- [x] If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above
- [x] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Manager @anisa-hawes 
- [x] Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)
- [x] Assign at least one individual or team to "Reviewers"
  - ~~[ ] if the text needs to be translated, please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines), then assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR.~~

### CODE REVIEW

**Comment by anisa-hawes** [comment]
Hello Alex, @hawc2.

I’ve staged designing-a-timeline-tabletop-simulator for publication. You can [read it through in Preview](https://deploy-preview-3209--ph-preview.netlify.app/) and let me know if you note anything which you'd like to adjust.

If you're happy, we can publish this lesson next week when our colleagues at Sussex will be around to activate our DOI, and then we can launch the promotions on social media.

(I will adjust the `date:` depending on which day you prefer I publish it next week).

--

Thank you,
A.

**Comment by hawc2** [comment]
@anisa-hawes looks good! One minor thing, in the title "deck," "cards," and "tabletops" should each have their first letter capitalized

**Comment by anisa-hawes** [comment]
Thank you, @hawc2. I've corrected the title case!

This is ready for your review (again) 🙂

**Comment by hawc2** [comment]
Thanks @anisa-hawes. One other minor edit is in the lesson abstract, I find the second sentence a little awkward. Could it be changed to say: "This lesson will also highlight best practices for handling digitized historical objects."

I've looked through the lesson as a whole and everything else looks good to me. So once we revise the abstract I'll approve the pull request

**Review by hawc2 — APPROVED** [review]

**Comment by anisa-hawes** [comment]
Thank you, @hawc2. 

I will update you as soon as the DOI is live, then launch our social media announcements.

**Pull request merged**
