### PR TITLE
Remove the broken link and add information to the metadata of lesson "Sustainable Authorship using Pandoc..."

### PR DESCRIPTION
**Pull request by pao-chuan**
The broken link "Penflip" is removed because it would cause security risks, and also the lesson-tester and tested date are added to the metadata.

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Review by acrymble — APPROVED** [review]

**Comment by acrymble** [comment]
@programminghistorian/technical-team this branch has fallen behind and the error has been corrected in another pull request. Could someone please help get it back up to date so we can merge?

**Comment by walshbr** [comment]
Ah @ZoeLeBlanc I went to do this, but it looks like @pao-chuan made the branch on her own form, not on our repository. So when I merged our branch into it the changes took place on a new branch on our repo and not the actual repo where the PR was originating from. I don't think I know the easiest way to get the gh-pages changes from our repo to the branch she is creating the PR from on her repo. Can you advise and help resolve this?

**Comment by acrymble** [comment]
Sorry @walshbr I didn't notice that. Should we just re-do the branch on our repo?

**Comment by acrymble** [comment]
This has been superceded by #2157

**Pull request closed without merging**
