### PR TITLE
Store datasets for Creating Network Diagrams lesson

### LINKED ISSUE #961: Creating network diagrams - Move Sample Datasets
The sample data of the tutorial on Data extraction and network visualization is in the author's Google drive, and in the Spanish version is on my Google drive. For sustainability we should move this elsewhere. How do we move them to our repository?

This is the tutorial:
https://programminghistorian.org/en/lessons/creating-network-diagrams-from-historical-sources

These are the links for the sample data:
EN https://docs.google.com/spreadsheets/d/1LzbWsG73m74t3p6xE7lutfVWuOdzOIfN55FbhCCRZvk/edit#gid=77820913
ES https://docs.google.com/spreadsheets/d/1_RzqvgUs-q9fpnyc9MEH4FFYXmuGa2xOmzyEUax6kFk/edit#gid=0

### PR DESCRIPTION
**Pull request by acrymble**
As per #961 we noticed that the datasets were on google docs and not our website. This pull request will move them to our /assets folder.

Closes #961

This work was started some time ago so the branch is out of date and needs rebasing before merging.

### CODE REVIEW

**Review by mariajoafana — DISMISSED** [review]

**Comment by acrymble** [comment]
Sorry @mariajoafana I had a typo in the url to one of the csv files. Can you re-review now that it's fixed?

**Comment by acrymble** [comment]
@mdlincoln or @walshbr can you advise on how to get the branch up to date with the live site before this is merged?

**Comment by mdlincoln** [comment]
I don't believe anything special needs to happen, since your changes don't conflict with any of the changes that have been made to the `gh-pages` branch. You can just merge it when ready.

**Review by mariajoafana — APPROVED** [review]
Looks goods

**Pull request merged**
