### PR TITLE
Update snippets.yml to include PT ISSN

### LINKED ISSUE #2012: Add ISSN to PT version
Add the ISSN number to the Portuguese pages

### PR DESCRIPTION
**Pull request by DanielAlvesLABDH**
Add the ISSN number to the Portuguese version. @programminghistorian/technical-team please let me know if there is any other file I need to edit for this? Thanks Closes #2012 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
- [x] Add the appropriate "Label"
- [x] [Ensure the GitHub Acrions pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

### CODE REVIEW

**Comment by walshbr** [comment]
I checked it out and looks good.

**Review by walshbr — DISMISSED** [review]

**Comment by DanielAlvesLABDH** [comment]
@walshbr I notice those fails in the Travis CI but couldn't figure out what was the problem

**Comment by walshbr** [comment]
https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions - if you scroll down to "check travis for errors" you can see some guidance on these errors and how to address them @DanielAlvesLABDH. They're all just broken links that have rotted. Those often happen due to circumstances out of our control, so it's often the case that when they happen they affect files that you didn't actually touch on the pull request (that's the case here). We usually have a policy of "if it's your PR you try to fix the links" by poking around on the site where the link originally pointed towards to see if you can find the new link. If that doesn't work, you can try the Wayback Machine - https://archive.org/web/ - to see if you can get an archived version of the link. I'll post a list of them when travis finally finishes running.

**Comment by DanielAlvesLABDH** [comment]
Thank you @walshbr

**Comment by walshbr** [comment]
Checking into this @DanielAlvesLABDH - i'll report back!

**Review by ZoeLeBlanc — APPROVED** [review]
This looks good to me! Sorry for all my commits being included. I guess that's bound to happen since I moved gh-pages so far ahead (right @walshbr ?). I would say go ahead and merge it in, and I'll send an email to Sussex so we can get the DOIs registered!

**Comment by DanielAlvesLABDH** [comment]
Thanks @ZoeLeBlanc ! Great work with those changes from Travis to GitHub Actions!

**Pull request merged**
