### PR TITLE
Update FR team roles in relevant pages

### LINKED ISSUE #1193: French ombudsperson
I just noticed that Amanda Visconti is being listed as the Ombudsperson on the French submission tickets. Really it would be better for someone on the French team to take on this role for French submissions so that everyone can operate in French.

This role is not a lot of work. We have only ever ONCE called upon the ombudsperson. But it's important to have them in place.

### PR DESCRIPTION
**Pull request by spapastamkou**
I create this PR to update pages with the new FR team roles.
 
I updated ph-authors for all FR members. 

I added the FR Managing Editor where necessary. For this, I updated also the EN project-team page and ES equipo-de-proyecto which is why I ask reviews from @JMParr  the @programminghistorian/spanish-team (please check if you can).
 
 @mpuren and @fdlaramee could you please update the FR guidelines pages (consignes-auteurs, consignes-redacteurs, consignes-relecteurs) by adding your names and e-mail address where the ombudsperson is mentionned? This way we can close #1193.

I don't seem to find the form the authors use to propose a lesson to add the FR Managing Editor. Could you help me @mdlincoln ? It is not urgent though, we can perhaps add this later.

### CODE REVIEW

**Comment by mdlincoln** [comment]
@spapastamkou the french submission form is at `assets/forms/Formulaire.Tutoriel.txt`

**Comment by spapastamkou** [comment]
@mdlincoln thanks! Also for the label

**Comment by fdlaramee** [comment]
@spapastamkou Hi Sofia; the current setup in English and French includes the name of the ombudsperson but links to the project team page, where there is an email button for each individual that appears to be protected against spam harvesters, instead of publishing the ombudsperson's address in clear. This seems like a good setup that we may not want to change. What do you think?

**Comment by spapastamkou** [comment]
Yes @fdlaramee, sorry, I guess I talked about e-mail address bcz it was everywhere for the Managing Editor:) What I had in mind was parts like these in the FR Editor Guidelines, for example: 
https://programminghistorian.org/fr/consignes-evaluateurs#transparence
https://programminghistorian.org/fr/consignes-evaluateurs#ouverture-et-inclusion
https://programminghistorian.org/fr/consignes-evaluateurs#soumettre-votre-%C3%A9valuation

Amanda Visconti's name is mentioned 3 times there and links of course to the project team page, as you said (not e-mail). In that page (project team), you and Marie will appear as ombudspersons bcz I updated the roles. But in the guidelines, there will still be Amanda and not the dedicated FR persons.

**Comment by fdlaramee** [comment]
@spapastamkou @mpuren I have inserted both Marie's and my name everywhere Amanda was mentioned and adjusted the surrounded language accordingly. @mpuren could you please verify that the way I did it is satisfactory? Thanks!

**Review by fdlaramee — DISMISSED** [review]

**Comment by mpuren** [comment]
I will, thks @fdlaramee

**Review by mdlincoln — APPROVED** [review]
Just fixed one 404 link. @spapastamkou you may merge whenever you're ready.

**Pull request merged**
