### PR TITLE
update-affiliation-sofia #1169

### PR DESCRIPTION
**Pull request by spapastamkou**
Hey @programminghistorian/spanish-team, I am not sure whether an article might be needed before my affiliation. If you can just take a quick look, thanks a lot.

### CODE REVIEW

**Comment by drjwbaker** [comment]
(I totally missed that we could alert project teams using something like @programminghistorian/spanish-team! I learn something new every day..)

**Review by mdlincoln — DISMISSED** [review]
Looks fine to me but still needs @programminghistorian/spanish-team to double check I think?

**Comment by arojascastro** [comment]
Thank you whoever made the change in the Spanish page!

**Review by arojascastro — APPROVED** [review]
Merci beaucoup!

**Comment by spapastamkou** [comment]
thank you!

**Pull request merged**
